import { Check } from "lucide-react";
import { Section } from "@/app/_landing/components/section";

const BENEFITS = ["Masa başına QR, tara-ve-sipariş, uygulama yok", "Gerçek zamanlı siparişler mutfak veya yönetici tabletinde", "Veya restoran WhatsApp'ına yönlendirme — seçim sizin", "Modifikatörler, varyantlar ve alerjenler fişe yansır", "Her siparişte misafirden serbest yorum", "Mutfak için günlük numaralandırma", "35 dil çok dilli checkout, misafir telefonundan otomatik", "Sipariş başına sıfır komisyon — sabit aylık abonelik"];
const HOW_STEPS = [
  { title: "Restoranda siparişleri aktive et", desc: "Restoran ayarlarını açın, Siparişler anahtarını açın ve toplayacağınız misafir alanlarını (ad, telefon, adres) seçin." },
  { title: "Teslimat kanalını seçin", desc: "Dahili mod yeni siparişleri Mutfak sekmesine gönderir. WhatsApp modu mesaj olarak restoran WhatsApp'ına gönderir. Veya ikisi paralel." },
  { title: "QR'ları yazdır ve yerleştir", desc: "QR'ı (masa başına bir tane veya tüm mekan için) PDF veya PNG olarak indirin ve masalara yapıştırın. Misafirler doğal kamerayla tarar — App Store yok, sürtünme yok." },
  { title: "Servisi yönet", desc: "Siparişler Mutfak sekmesinde masa numarası, yemekler, varyantlar, alerjenler, yorum ve gün numarasıyla görünür. yeni → işleniyor → tamamlandı arasında hareket edin. Misafirin tarayıcısı gerçek zamanlı güncellenir." },
];
const COMPARISON_ROWS = [["Sipariş başına komisyon","%20–30","%0","%0 (€6,90/ay sabit)"],["Sipariş hedefi","Agregatör uygulaması","Kendi kasanız","Mutfak tabletiniz veya WhatsApp"],["Fişte masa numarası","Yok","Manuel","Var, otomatik"],["Modifikatör / varyant","Sınırlı","Var","Var, alerjenli"],["Çok dilli checkout","Uygulamalarının dili","Yok","35 dil, otomatik"],["Gerekli donanım","Agregatör tableti","POS terminali","Tarayıcılı herhangi bir tablet"],["Kurulum süresi","Onboarding araması","Günler-haftalar","5 dakika"]];

export function SeoContent() {
  return (<>
    <Section dataSection="seo-intro"><div className="max-w-4xl mx-auto"><p className="text-xs font-medium uppercase tracking-widest text-primary mb-3 text-center">Detayda</p><h2 className="text-3xl sm:text-4xl lg:text-5xl font-medium tracking-tight mb-3 text-center">Restoran online sipariş sistemi <span className="text-muted-foreground">gerçekte nedir</span></h2><p className="text-base sm:text-lg text-muted-foreground mb-10 text-center">Pazaryeri değil. Teslimat agregatörü değil. Masanızdaki misafirin telefonundan mutfak tabletinize — veya WhatsApp'ınıza doğrudan hat.</p><div className="space-y-4 text-base sm:text-lg text-foreground/90 leading-relaxed"><p>IQ Rest anlamında <strong>restoran online sipariş sistemi</strong>, masanızdaki misafire menüyü telefonunda açmasına, sepet kurmasına ve siparişi mutfağınıza göndermesine olanak tanıyan yazılımdır — Yemeksepeti, Uber Eats, Wolt veya başka bir pazaryeri olmadan. Misafir QR menünüzden ayrılmaz, sipariş başına komisyon ödemezsiniz ve fişte gerçek masa numarası yazar.</p><p>IQ Rest iki teslimat kanalı etrafında inşa edildi. Varsayılan <em>dahili mod</em>: her yeni sipariş geçişte tuttuğunuz tablet, telefon veya dizüstüde panelin Mutfak sekmesine geliyor — masa numarası, varyantlı ve alerjenli yemekler, misafirin serbest yorumu ve mutfak için gün numarasıyla. Alternatif <em>WhatsApp modu</em>: aynı sipariş biçimlendirilmiş mesaj olarak restoranın WhatsApp numarasına gönderiliyor — küçük ekipler, ağırlıklı paket servis veya yöneticinin sahada olmadığı durumlar için yararlı. İki mod paralel çalışabilir.</p></div></div></Section>
    <Section dataSection="seo-benefits"><div className="max-w-4xl mx-auto"><h3 className="text-2xl sm:text-3xl font-medium tracking-tight mb-6 text-center">Gerçekten ne alıyorsunuz</h3><div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-3 sm:gap-4">{BENEFITS.map((b) => (<div key={b} className="bg-muted/20 border border-border rounded-2xl p-4 sm:p-5 flex flex-row items-center gap-3"><div className="h-8 w-8 rounded-lg bg-primary/10 text-primary flex items-center justify-center shrink-0"><Check className="h-4 w-4" strokeWidth={2.5} /></div><p className="text-sm sm:text-base text-foreground/90 leading-snug">{b}</p></div>))}</div></div></Section>
    <Section dataSection="seo-how"><div className="max-w-4xl mx-auto"><h3 className="text-2xl sm:text-3xl font-medium tracking-tight mb-6 text-center">IQ Rest sipariş akışı nasıl çalışır</h3><p className="text-base sm:text-lg text-foreground/90 leading-relaxed mb-6 text-center">Panelde dört anahtar ve siz canlısınız. Kurucu yok, POS donanımı yok, entegrasyon projesi yok.</p><div className="grid grid-cols-1 sm:grid-cols-2 gap-3 sm:gap-4">{HOW_STEPS.map((s, i) => (<div key={s.title} className="bg-muted/20 border border-border rounded-2xl p-5 flex flex-row items-start gap-4"><div className="h-10 w-10 rounded-lg bg-primary text-primary-foreground flex items-center justify-center shrink-0 font-semibold text-base">{i + 1}</div><div className="flex-1 min-w-0"><div className="text-base sm:text-lg font-semibold tracking-tight mb-1">{s.title}</div><p className="text-sm text-muted-foreground leading-relaxed">{s.desc}</p></div></div>))}</div></div></Section>
    <Section dataSection="seo-table"><div className="max-w-4xl mx-auto"><h3 className="text-2xl sm:text-3xl font-medium tracking-tight mb-6 text-center">Agregatör, klasik POS veya sipariş sistemi</h3><div className="bg-muted/20 border border-border rounded-2xl p-4 sm:p-6 overflow-x-auto"><table className="w-full text-sm sm:text-base border-collapse"><thead><tr className="border-b border-border"><th className="text-left font-semibold py-3 pr-3 text-foreground">Özellik</th><th className="text-left font-semibold py-3 pr-3 text-muted-foreground">Teslimat agregatörü</th><th className="text-left font-semibold py-3 pr-3 text-muted-foreground">Klasik POS</th><th className="text-left font-semibold py-3 text-primary">IQ Rest siparişleri</th></tr></thead><tbody className="text-foreground/90">{COMPARISON_ROWS.map((row, i) => (<tr key={row[0]} className={i < COMPARISON_ROWS.length - 1 ? "border-b border-border/50" : ""}><td className="py-3 pr-3 font-medium">{row[0]}</td><td className="py-3 pr-3 text-muted-foreground">{row[1]}</td><td className="py-3 pr-3 text-muted-foreground">{row[2]}</td><td className="py-3 text-foreground">{row[3]}</td></tr>))}</tbody></table></div><p className="text-sm text-muted-foreground leading-relaxed mt-6 text-center">Restoranın gerçekten sahibi olduğu sipariş sistemi ilk hafta sonunda kendini öder — misafirin mekanınızda harcadığı her euro mekanınızda kalır, geçişteki fiş her zaman gerçek masa numarasını taşır.</p></div></Section>
  </>);
}
