import { QrCode, MessageCircle, ChefHat, Settings2, Languages, BarChart3 } from "lucide-react";
import type { LandingTexts } from "@/app/_landing/types";

export const TEXTS: LandingTexts = {
  htmlLang: "tr",
  htmlDir: "ltr",
  meta: {
    title: "Restoran Online Sipariş Sistemi — QR ve WhatsApp | IQ Rest",
    description: "Restoranınız için online sipariş sistemi: müşteri QR'ı okur, sipariş veriyor, sipariş doğrudan mutfak tabletinize veya WhatsApp'ınıza geliyor. Komisyon yok, masa numarası dahil. 14 gün ücretsiz.",
    canonical: "https://iq-rest.com/tr/restoran-online-siparis-sistemi",
    ogLocale: "tr_TR",
    ogTitle: "Restoran Online Sipariş Sistemi — Doğrudan Mutfağa",
    ogDescription: "Müşteri masada QR'ı okuyor, siparişi hazırlıyor, doğrudan tabletinize veya WhatsApp'ınıza geliyor — aracı yok, komisyon yok, her fişte masa numarası.",
  },
  ctaText: "Siparişlerimi aktive et",
  demoText: "Canlı demo izle",
  microcopy: "Aylık €6,90'dan · 14 gün ücretsiz · İstediğin zaman iptal",
  header: { navFeatures: "Özellikler", navHow: "Nasıl çalışır", navPricing: "Fiyatlar", navFaq: "SSS", signIn: "Giriş", cta: "Ücretsiz dene" },
  hero: {
    verticals: ["Restoranlar", "Kafeler", "Bistrolar", "Pizzacılar", "Barlar", "Bira Evleri"],
    headline: "Restoran Online Sipariş Sistemi.",
    sub: "Müşteri masasının QR'ını okuyor, siparişi telefonunda hazırlıyor ve fiş doğrudan mutfak tabletinize veya restoranın WhatsApp'ına geliyor. Aracı yok, komisyon yok, her fişte masa numarası.",
    dynamicHeadlines: ["Masada sipariş.", "Doğrudan mutfak tabletine.", "Veya doğrudan WhatsApp'a.", "Sıfır komisyon.", "Masa numarası dahil."],
    painBullets: [
      "Restoranın gerçekten sahibi olduğu online sipariş sistemi — aracı yok, komisyon yok.",
      "Siparişler mutfak veya yönetici tabletine masa numarası, modifikatörler, alerjenler ve notlarla geliyor.",
      "Veya doğrudan restoranın WhatsApp'ına yönlendiriliyor — paket servis ve küçük ekipler için ideal.",
      "Her masaya bir QR (veya tüm mekana bir tane) otomatik oluşturuluyor.",
    ],
    rating: "30+ ülkede 500+ restoran",
  },
  features: {
    heading: "Masa için tasarlanmış",
    headingAccent: "sipariş sistemi.",
    sub: "Gerçek işlevsellik — teslimat agregatörü klonu değil.",
    items: [
      { Icon: QrCode, title: "Her masada sepetli QR menü", desc: "Müşteri masanın QR'ını okuyor, kendi dilinde menüye göz atıyor, modifikatörlerle yemek ekliyor, mutfağa not bırakıyor ve gönderiyor. Uygulama yüklemeden.", tag: "QR sipariş" },
      { Icon: ChefHat, title: "Mutfak tabletinde siparişler", desc: "Her yeni sipariş panelin Mutfak sekmesinde — geçişte tuttuğunuz tablette — masa numarası, yemekler, varyantlar, alerjenler ve müşteri yorumuyla görünür. Tek dokunuşla yapılıyor → tamamlandı.", tag: "Mutfak görünümü" },
      { Icon: MessageCircle, title: "Veya siparişleri WhatsApp'a gönder", desc: "Restoranı WhatsApp moduna alın (veya ikisini birden) ve her sipariş restoranın WhatsApp numarasına biçimlendirilmiş mesaj olarak gelsin — paket servis veya küçük ekipler için ideal.", tag: "WhatsApp modu" },
      { Icon: Settings2, title: "Modifikatörler, varyantlar, alerjenler", desc: "Her yemek kendi varyant gruplarını (boy, pişme, eklemeler) fiyat farkı, alerjen etiketleri ve serbest açıklamayla taşır. Sepet hepsine uyar — tabletteki fiş net.", tag: "Gerçek sepet" },
      { Icon: Languages, title: "Çok dilli checkout", desc: "Tüm sipariş akışı — sepet, modifikatörler, yorum, onay — 35 dile çevrildi ve misafirin telefon diline otomatik uyar.", tag: "35 dil" },
      { Icon: BarChart3, title: "Günlük numaralandırma ve günlük", desc: "Her sipariş mutfak için günlük numara alır, toplamlar ve zaman damgalarıyla bir günlüğe gider, analitiği besler. İptaller soft-delete — raporlar temiz kalır.", tag: "Sipariş günlüğü" },
    ],
  },
  founder: {
    eyebrow: "Kafe sahibi tarafından, teslimat startup'ı değil",
    quoteStart: "Eşim ve ben bir kafe açtık ve masadan sipariş alacak, %30'u agregatöre vermeyecek ve €1500'luk POS gerektirmeyecek bir yol haftalarca aradık. Denediğimiz her şey ağır, pahalı veya temel özelliklerden yoksundu —",
    quoteAccent: "bu yüzden istediğimiz sipariş sistemini biz yaptık.",
    sign: "Bogdan Sokolov · kurucu, eski kafe sahibi",
    photoAlt: "Bogdan, IQ Rest kurucusu",
  },
  how: {
    heading: "Sipariş sisteminizi aktive edin",
    headingAccent: "4 adımda",
    sub: "Kurulum yok, entegratör yok, IT araması yok. Sadece telefonunuz ve 5 dakika.",
    steps: [
      { n: "1", t: "Restoran oluştur", d: "E-posta veya Google ile kayıt — 30 saniye." },
      { n: "2", t: "Menü ekle", d: "Sürükle-bırak veya kağıt menüyü AI ile tara." },
      { n: "3", t: "Kanal seç", d: "Mutfak tableti, WhatsApp veya ikisi birden." },
      { n: "4", t: "QR'ı yazdır", d: "Masa başına bir QR — misafirler hemen sipariş veriyor." },
    ],
  },
  pricing: {
    badge: "Sınırsız sipariş · Sıfır komisyon",
    heading: "Tek plan.",
    headingAccent: "Sipariş başına ücret yok.",
    sub: "Online sipariş, QR menü, WhatsApp modu, çok dilli checkout ve analitik — hepsi tek abonelikte. İşlem başına yüzde yok.",
    monthlyLabel: "Aylık",
    yearlyLabel: "Yıllık",
    saveBadge: "%25 tasarruf",
    perMonth: "ayda",
    billedAnnually: "Yıllık faturalandırıldı {total}",
    youSave: "Tasarruf {amount}",
    trust: { secure: "Stripe ile abonelik", noCommitment: "Bağlayıcılık yok", quick: "Dakikalar içinde aktif", restaurants: "+500 restoran" },
  },
  faq: {
    eyebrow: "Sipariş sistemi — sık sorulanlar",
    heading: "Sipariş",
    headingAccent: "sistemi hakkında.",
    sub: "Sahiplerin IQ Rest ile online sipariş aktive etmeden önce sorduğu sorular. Sorunuz yok mu? WhatsApp'tan yazın — gerçek insanlar cevaplar.",
    whatsappCta: "WhatsApp'tan sor",
    whatsappPrefill: "Merhaba, IQ Rest siparişleri hakkında bir sorum var",
    items: [
      { q: "Bu Yemeksepeti veya Uber Eats gibi bir teslimat platformu mu?", a: "Hayır, asıl mesele bu. IQ Rest restoranın kendi sipariş kanalı — misafir sizin QR'ınızdan sipariş veriyor, fiş tabletinize veya WhatsApp'a geliyor, siz servis ediyorsunuz. Pazaryeri yok, agregatör kataloğu yok — ve hesabın bir kısmını asla almıyoruz." },
      { q: "Siparişler tam olarak nerede görünüyor?", a: "IQ Rest panelinin Mutfak sekmesinde — geçişte veya barda tuttuğunuz herhangi bir tablet/telefonda. Her sipariş masa numarasını, varyantlı ve alerjenli yemekleri, misafir yorumunu ve günlük sipariş numarasını gösterir. Tek dokunuşla yeni → işleniyor → tamamlandı." },
      { q: "Siparişleri WhatsApp'tan alabilir miyim?", a: "Evet. Her restoranda üç mod var: dahili (sadece mutfak tableti), WhatsApp (sipariş restoranın WhatsApp numarasına biçimlendirilmiş mesaj olarak gelir) veya ikisi birden. Mod panelin tek anahtarı — istediğiniz zaman değiştirin." },
      { q: "Sipariş ne içeriyor?", a: "Varyantları ve eklemeleri olan yemekler (fiyat farkı dahil), alerjenler, masa numarası, misafirin serbest yorumu ve — alanları açarsanız — misafirin adı, telefonu ve adresi. Paket servis sürücüsü göndermek veya alerjen için masayı geri aramak için yeterli." },
      { q: "Misafirler menüden online ödeyebilir mi?", a: "Varsayılan olarak hayır. IQ Rest masada ödeme etrafında kuruludur — misafir sipariş veriyor, hesabı getiriyorsunuz, her zamanki gibi ödüyor. Online kart ödemesi (paket servis için tipik) gerekirse Stripe Connect entegrasyonu istek üzerine yapılabilir — WhatsApp'tan yazın." },
      { q: "Özel tablet, yazıcı veya POS donanımı gerekiyor mu?", a: "Hayır. Tarayıcılı herhangi bir tablet, dizüstü veya telefon çalışır — paneli açın, giriş yapın, Mutfak sekmesini açık bırakın. POS'unuz varsa IQ Rest yanında yaşar; kasanızı değiştirmez." },
      { q: "14 ücretsiz günden sonra ne oluyor?", a: "Ödeme yöntemi eklemezseniz hesap duraklar — asla otomatik tahsil etmeyiz. Menü, siparişler ve ayarlar kayıtlı kalır; yeniden etkinleştirmek için ne zaman isterseniz kart ekleyin. Tek tıkla iptal, bağlayıcılık yok." },
    ],
  },
  finalCta: {
    heading: "Sipariş sisteminizi aktive edin.",
    headingAccent: "5 dakikada hazır.",
    sub: "14 gün ücretsiz, kartsız. İstediğiniz zaman iptal. IQ Rest ile kendi online siparişlerini yöneten 500+ restorana katılın.",
  },
  scan: {
    heading: "Kağıt menüden sipariş sistemine",
    headingAccent: "60 saniyede",
    sub: "Menü fotoğrafı yükleyin — AI kategorileri, yemekleri ve fiyatları doğrudan editöre çekiyor. Buradan sepet ve QR bir tık ötede.",
    cta: "Menümü tara →",
  },
  footer: {
    featureLinks: [
      { href: "/tr/ai-translation", label: "AI çeviri" },
      { href: "/tr/reservations", label: "Rezervasyonlar" },
      { href: "/tr/mobile-management", label: "Mobil yönetim" },
      { href: "/tr/easy-menu", label: "Menü editörü" },
      { href: "/tr/custom-design", label: "Video ve fotoğraf arka planları" },
      { href: "/tr/color-scheme", label: "Marka renkleri" },
      { href: "/tr/multilingual", label: "Çok dilli menü" },
      { href: "/tr/ai-images", label: "AI fotoğraf optimizasyonu" },
      { href: "/tr/analytics", label: "Analitik" },
      { href: "/tr/instant-setup", label: "Anında kurulum" },
      { href: "/tr/personal-support", label: "Kişisel destek" },
    ],
    navLinks: [
      { href: "#pricing", label: "Fiyatlar" },
      { href: "#faq", label: "Sorular" },
      { href: "/tr/changelog", label: "Yenilikler" },
      { href: "/tr/languages", label: "Dil değiştir" },
    ],
    copyrightTemplate: "© {year} IQ Rest. Tüm hakları saklıdır.",
  },
};
