import { Check } from "lucide-react";
import { Section } from "@/app/_landing/components/section";

const BENEFITS = ["QR på varje bord, skanna-och-beställ, utan app", "Beställningar i realtid på köks- eller chefsplatta", "Eller på restaurangens WhatsApp — du väljer", "Modifierare, varianter och allergener kommer med på kvittot", "Fri kommentar från gäst på varje beställning", "Daglig numrering för köket", "Flerspråkig checkout på 35 språk, efter gästens telefon", "Noll provision per beställning — fast månadsprenumeration"];
const HOW_STEPS = [
  { title: "Aktivera beställningar för restaurangen", desc: "Öppna restaurangens inställningar, aktivera knappen Beställningar och välj vilka gästfält (namn, telefon, adress) som ska samlas in." },
  { title: "Välj leveranskanal", desc: "Internt läge skickar nya beställningar till fliken Kök. WhatsApp-läge formaterar beställningen som meddelande till restaurangens WhatsApp. Eller båda parallellt." },
  { title: "Skriv ut och fäst QR", desc: "Ladda ner QR (en per bord eller en per restaurang) i PDF eller PNG och fäst på borden. Gästerna skannar med egen kamera — utan App Store, utan friktion." },
  { title: "Kör passet", desc: "Beställningar dyker upp i fliken Kök med bordsnummer, rätter, varianter, allergener, kommentar och dagligt nummer. Övergång ny → pågår → klar. Gästens webbläsare uppdateras i realtid." },
];
const COMPARISON_ROWS = [["Provision per beställning","20–30%","0%","0% (€6,90/mån fast)"],["Vart beställningen hamnar","Aggregator-app","Din kassa","Din köksplatta eller WhatsApp"],["Bordsnummer på kvitto","Nej","Manuellt","Ja, automatiskt"],["Modifierare / varianter","Begränsade","Ja","Ja, med allergener"],["Flerspråkig checkout","Deras app-språk","Nej","35 språk, automatiskt"],["Nödvändig hårdvara","Aggregator-platta","POS-terminal","Vilken platta som helst med webbläsare"],["Tid för uppstart","Onboarding-samtal","Dagar-veckor","5 minuter"]];

export function SeoContent() {
  return (<>
    <Section dataSection="seo-intro"><div className="max-w-4xl mx-auto"><p className="text-xs font-medium uppercase tracking-widest text-primary mb-3 text-center">På djupet</p><h2 className="text-3xl sm:text-4xl lg:text-5xl font-medium tracking-tight mb-3 text-center">Vad ett online beställningssystem för restaurang <span className="text-muted-foreground">faktiskt är</span></h2><p className="text-base sm:text-lg text-muted-foreground mb-10 text-center">Ingen marketplace. Ingen leveransaggregator. En direkt linje från gästens telefon vid ditt bord till köksplattan — eller WhatsApp.</p><div className="space-y-4 text-base sm:text-lg text-foreground/90 leading-relaxed"><p><strong>Online beställningssystem för restaurang</strong> i IQ Rests mening är mjukvara som låter gästen vid ditt bord öppna menyn i telefonen, skapa en kundvagn och skicka beställningen till köket — utan Foodora, Wolt, Bolt Food eller någon annan marketplace. Gästen lämnar aldrig din QR-meny, du betalar ingen provision per beställning, och kvittot kommer med det riktiga bordsnumret.</p><p>IQ Rest är byggt kring två kanaler. Som standard är <em>internt läge</em>: varje ny beställning hamnar i fliken Kök på panelen på en platta, telefon eller laptop vid passet — med bordsnummer, rätter med varianter och allergener, fri kommentar från gäst och dagligt beställningsnummer. Alternativet är <em>WhatsApp-läge</em>: samma beställning formateras som meddelande till restaurangens WhatsApp. Användbart för små team, främst hämtning eller när chefen är borta från salen. Båda lägen kan köras samtidigt.</p></div></div></Section>
    <Section dataSection="seo-benefits"><div className="max-w-4xl mx-auto"><h3 className="text-2xl sm:text-3xl font-medium tracking-tight mb-6 text-center">Vad du faktiskt får</h3><div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-3 sm:gap-4">{BENEFITS.map((b) => (<div key={b} className="bg-muted/20 border border-border rounded-2xl p-4 sm:p-5 flex flex-row items-center gap-3"><div className="h-8 w-8 rounded-lg bg-primary/10 text-primary flex items-center justify-center shrink-0"><Check className="h-4 w-4" strokeWidth={2.5} /></div><p className="text-sm sm:text-base text-foreground/90 leading-snug">{b}</p></div>))}</div></div></Section>
    <Section dataSection="seo-how"><div className="max-w-4xl mx-auto"><h3 className="text-2xl sm:text-3xl font-medium tracking-tight mb-6 text-center">Så funkar IQ Rests beställningsflöde</h3><p className="text-base sm:text-lg text-foreground/90 leading-relaxed mb-6 text-center">Fyra knappar i panelen — och du är live. Ingen installatör, ingen POS-hårdvara, inget integrationsprojekt.</p><div className="grid grid-cols-1 sm:grid-cols-2 gap-3 sm:gap-4">{HOW_STEPS.map((s, i) => (<div key={s.title} className="bg-muted/20 border border-border rounded-2xl p-5 flex flex-row items-start gap-4"><div className="h-10 w-10 rounded-lg bg-primary text-primary-foreground flex items-center justify-center shrink-0 font-semibold text-base">{i + 1}</div><div className="flex-1 min-w-0"><div className="text-base sm:text-lg font-semibold tracking-tight mb-1">{s.title}</div><p className="text-sm text-muted-foreground leading-relaxed">{s.desc}</p></div></div>))}</div></div></Section>
    <Section dataSection="seo-table"><div className="max-w-4xl mx-auto"><h3 className="text-2xl sm:text-3xl font-medium tracking-tight mb-6 text-center">Aggregator, klassisk POS eller beställningssystem</h3><div className="bg-muted/20 border border-border rounded-2xl p-4 sm:p-6 overflow-x-auto"><table className="w-full text-sm sm:text-base border-collapse"><thead><tr className="border-b border-border"><th className="text-left font-semibold py-3 pr-3 text-foreground">Egenskap</th><th className="text-left font-semibold py-3 pr-3 text-muted-foreground">Leveransaggregator</th><th className="text-left font-semibold py-3 pr-3 text-muted-foreground">Klassisk POS</th><th className="text-left font-semibold py-3 text-primary">IQ Rest-beställningar</th></tr></thead><tbody className="text-foreground/90">{COMPARISON_ROWS.map((row, i) => (<tr key={row[0]} className={i < COMPARISON_ROWS.length - 1 ? "border-b border-border/50" : ""}><td className="py-3 pr-3 font-medium">{row[0]}</td><td className="py-3 pr-3 text-muted-foreground">{row[1]}</td><td className="py-3 pr-3 text-muted-foreground">{row[2]}</td><td className="py-3 text-foreground">{row[3]}</td></tr>))}</tbody></table></div><p className="text-sm text-muted-foreground leading-relaxed mt-6 text-center">Ett online beställningssystem som restaurangen själv äger tjänar in sig första helgen — varje krona gästen spenderar i din sal stannar i din sal, och kvittot vid passet är alltid med riktigt bordsnummer.</p></div></Section>
  </>);
}
