import { QrCode, MessageCircle, ChefHat, Settings2, Languages, BarChart3 } from "lucide-react";
import type { LandingTexts } from "@/app/_landing/types";

export const TEXTS: LandingTexts = {
  htmlLang: "sv",
  htmlDir: "ltr",
  meta: {
    title: "Online beställningssystem för restaurang — QR och WhatsApp | IQ Rest",
    description: "Online beställningssystem för restaurang: gästen skannar QR vid bordet, skapar beställning och den hamnar direkt på köksplattan eller WhatsApp. Noll provision, med bordsnummer. 14 dagar gratis.",
    canonical: "https://iq-rest.com/sv/online-bestallningssystem-restaurang",
    ogLocale: "sv_SE",
    ogTitle: "Online beställningssystem för restaurang — Direkt till köket",
    ogDescription: "Gästen skannar QR vid bordet, skapar beställning och den hamnar på plattan eller WhatsApp — ingen mellanhand, ingen provision, med bordsnummer på varje kvitto.",
  },
  ctaText: "Aktivera beställningar",
  demoText: "Live demo",
  microcopy: "Från €6,90/mån · 14 dagar gratis · Avsluta när du vill",
  header: { navFeatures: "Funktioner", navHow: "Så funkar det", navPricing: "Priser", navFaq: "FAQ", signIn: "Logga in", cta: "Testa" },
  hero: {
    verticals: ["Restauranger", "Caféer", "Bistroer", "Pizzerior", "Barer", "Ölbarer"],
    headline: "Online beställningssystem för restaurang.",
    sub: "Gästen skannar QR-koden vid sitt bord, skapar beställning i telefonen — och kvittot hamnar direkt på köksplattan eller restaurangens WhatsApp. Ingen mellanhand, ingen provision, med bordsnummer på varje kvitto.",
    dynamicHeadlines: ["Beställning vid bordet.", "Direkt till köksplattan.", "Eller direkt till WhatsApp.", "Noll provision.", "Med bordsnummer."],
    painBullets: [
      "Online beställningssystem som restaurangen själv äger — inga mellanhänder, ingen provision.",
      "Beställningar hamnar på köket eller chefens platta med bordsnummer, modifierare, allergener och anteckningar.",
      "Eller skickas direkt till restaurangens WhatsApp — perfekt för hämtning och små team.",
      "QR för varje bord (eller en för hela restaurangen) genereras automatiskt.",
    ],
    rating: "500+ restauranger i 30+ länder",
  },
  features: {
    heading: "Beställningssystem,",
    headingAccent: "byggt för bordet.",
    sub: "Verklig funktionalitet — inte en klon av leveransaggregatorer.",
    items: [
      { Icon: QrCode, title: "QR-meny med kundvagn för varje bord", desc: "Gästen skannar QR, bläddrar i menyn på sitt eget språk, lägger till rätter med modifierare, lämnar en anteckning till köket och skickar. Utan app.", tag: "QR-beställning" },
      { Icon: ChefHat, title: "Beställningar på köksplattan", desc: "Varje ny beställning dyker upp i fliken Kök — på en platta vid passet — med bordsnummer, rätter, varianter, allergener och kommentar. Ett tryck från „pågår“ till „klar“.", tag: "Köksvy" },
      { Icon: MessageCircle, title: "Eller till WhatsApp", desc: "Sätt restaurangen i WhatsApp-läge (eller båda samtidigt) — varje beställning hamnar på WhatsApp som formaterat meddelande. Perfekt för hämtning eller små team.", tag: "WhatsApp-läge" },
      { Icon: Settings2, title: "Modifierare, varianter och allergener", desc: "Varje rätt har variantgrupper (storlek, stekning, extra) med prisskillnad, allergen-taggar och fri beskrivning. Kundvagnen räknar allt — kvittot på plattan utan tvivel.", tag: "Riktig kundvagn" },
      { Icon: Languages, title: "Flerspråkig checkout", desc: "Hela beställningsflödet — kundvagn, modifierare, kommentar, bekräftelse — är översatt till 35 språk och anpassas automatiskt till gästens telefonspråk.", tag: "35 språk" },
      { Icon: BarChart3, title: "Daglig numrering och logg", desc: "Varje beställning får ett dagligt nummer för köket, går i loggen med belopp och tidsstämplar, matar analyser. Avbokningar är soft-delete, rapporter förblir rena.", tag: "Beställningslogg" },
    ],
  },
  founder: {
    eyebrow: "Gjord av en caféägare, inte en leverans-startup",
    quoteStart: "Min fru och jag öppnade ett café och tillbringade veckor med att leta efter ett sätt att ta emot bordsbeställningar som inte gav 30 % till en aggregator eller krävde en kassa för 1500 €. Allt vi testade var klumpigt, dyrt eller saknade grunderna —",
    quoteAccent: "så vi byggde beställningssystemet vi själva ville ha.",
    sign: "Bogdan Sokolov · grundare, f.d. caféägare",
    photoAlt: "Bogdan, grundare av IQ Rest",
  },
  how: {
    heading: "Aktivera beställningssystemet",
    headingAccent: "på 4 steg",
    sub: "Ingen installation, ingen integrator, inget IT-samtal. Bara en telefon och 5 minuter.",
    steps: [
      { n: "1", t: "Skapa restaurang", d: "Registrering med e-post eller Google — 30 sekunder." },
      { n: "2", t: "Lägg till meny", d: "Drag-and-drop eller AI-skanning av pappersmeny." },
      { n: "3", t: "Välj kanal", d: "Köksplatta, WhatsApp eller båda." },
      { n: "4", t: "Skriv ut QR", d: "En QR per bord — gäster beställer direkt." },
    ],
  },
  pricing: {
    badge: "Obegränsade beställningar · Noll provision",
    heading: "En plan.",
    headingAccent: "Ingen avgift per beställning.",
    sub: "Online beställning, QR-meny, WhatsApp-läge, flerspråkig checkout och analyser — allt i en prenumeration. Ingen procentsats av transaktionen.",
    monthlyLabel: "Månadsvis",
    yearlyLabel: "Årsvis",
    saveBadge: "Spara 25%",
    perMonth: "per månad",
    billedAnnually: "Faktureras en gång om året {total}",
    youSave: "Du sparar {amount}",
    trust: { secure: "Prenumeration via Stripe", noCommitment: "Ingen bindning", quick: "Aktivt på minuter", restaurants: "+500 restauranger" },
  },
  faq: {
    eyebrow: "Beställningssystem — vanliga frågor",
    heading: "Om beställnings-",
    headingAccent: "systemet.",
    sub: "Det restaurangägare frågar om innan de aktiverar onlinebeställningar i IQ Rest. Saknar du din fråga? Skriv på WhatsApp — riktiga människor svarar.",
    whatsappCta: "Fråga på WhatsApp",
    whatsappPrefill: "Hej, jag har en fråga om IQ Rest-beställningar",
    items: [
      { q: "Är det en leveransplattform som Foodora eller Wolt?", a: "Nej, det är hela poängen. IQ Rest är restaurangens egen beställningskanal: gästen beställer från din QR, beställningen hamnar på din platta eller WhatsApp, du serverar. Ingen marketplace, ingen aggregator-katalog — och vi tar aldrig en del av notan." },
      { q: "Var dyker beställningarna upp exakt?", a: "I fliken Kök i IQ Rest-panelen på vilken platta eller telefon som helst vid passet eller baren. Varje beställning visar bordsnummer, rätter med varianter och allergener, gästens kommentar och dagligt nummer. Övergång „ny → pågår → klar“ med ett tryck." },
      { q: "Kan beställningar komma till WhatsApp istället?", a: "Ja. Varje restaurang har tre lägen: internt (bara köksplatta), WhatsApp (beställningen kommer som meddelande till restaurangens WhatsApp) eller båda samtidigt. Läget är en knapp i panelen, ändras när du vill." },
      { q: "Vad finns i beställningen?", a: "Rätter med varianter och extra (med prisskillnad), allergener, bordsnummer, fri kommentar från gäst och — om du aktiverar fälten — namn, telefon och adress. Räcker för att skicka bud eller ringa tillbaka till bordet om en allergen." },
      { q: "Kan gästerna betala online i menyn?", a: "Som standard — nej. IQ Rest är inställt för betalning vid bordet: gästen beställer, du tar fram notan, det betalas som vanligt. Om du behöver online-kortbetalning (typiskt för hämtning) är Stripe Connect-integration möjlig på begäran — skriv på WhatsApp." },
      { q: "Behöver jag en speciell platta, skrivare eller POS-hårdvara?", a: "Nej. Vilken platta, laptop eller telefon med webbläsare som helst — öppna panelen, logga in, lämna fliken Kök öppen. Om du redan har ett POS — IQ Rest kör vid sidan, ersätter inte kassan." },
      { q: "Vad händer efter 14 gratisdagar?", a: "Utan betalmetod pausas kontot — vi drar aldrig automatiskt. Meny, beställningar och inställningar bevaras; lägg till kort när du vill för att aktivera. Avsluta med ett klick, ingen bindning." },
    ],
  },
  finalCta: {
    heading: "Aktivera beställningssystemet.",
    headingAccent: "Klart på 5 minuter.",
    sub: "14 dagar gratis, inget kort. Avsluta när du vill. Anslut dig till 500+ restauranger som hanterar sina beställningar via IQ Rest.",
  },
  scan: {
    heading: "Från pappersmeny till beställningssystem",
    headingAccent: "på 60 sekunder",
    sub: "Ladda upp en bild på menyn — AI hämtar kategorier, rätter och priser direkt in i redigeraren. Sedan kundvagn och QR — med ett klick.",
    cta: "Skanna menyn →",
  },
  footer: {
    featureLinks: [
      { href: "/sv/ai-translation", label: "AI-översättning" },
      { href: "/sv/reservations", label: "Bokningar" },
      { href: "/sv/mobile-management", label: "Mobil hantering" },
      { href: "/sv/easy-menu", label: "Meny-editor" },
      { href: "/sv/custom-design", label: "Video- och fotobakgrunder" },
      { href: "/sv/color-scheme", label: "Varumärkesfärger" },
      { href: "/sv/multilingual", label: "Flerspråkig meny" },
      { href: "/sv/ai-images", label: "AI-bildoptimering" },
      { href: "/sv/analytics", label: "Analyser" },
      { href: "/sv/instant-setup", label: "Direktstart" },
      { href: "/sv/personal-support", label: "Personlig support" },
    ],
    navLinks: [
      { href: "#pricing", label: "Priser" },
      { href: "#faq", label: "Frågor" },
      { href: "/sv/changelog", label: "Nyheter" },
      { href: "/sv/languages", label: "Byt språk" },
    ],
    copyrightTemplate: "© {year} IQ Rest. Med ensamrätt.",
  },
};
