import { Check } from "lucide-react";
import { Section } from "@/app/_landing/components/section";

const BENEFITS = ["QR на кожному столі, скануй-і-замовляй, без застосунку", "Замовлення в реальному часі на планшет кухні або менеджера", "Або в WhatsApp ресторану — обираєте ви", "Модифікатори, варіанти та алергени надходять у тикет", "Вільний коментар гостя в кожному замовленні", "Денна нумерація для кухні", "Багатомовний checkout у 35 мовах, за телефоном гостя", "Нуль комісій із замовлення — фіксована місячна підписка"];
const HOW_STEPS = [
  { title: "Увімкніть замовлення для ресторану", desc: "Відкрийте налаштування ресторану, активуйте перемикач Замовлення й оберіть, які поля гостя (ім'я, телефон, адресу) збирати." },
  { title: "Виберіть канал доставки", desc: "Внутрішній режим надсилає нові замовлення у вкладку Кухня. WhatsApp-режим форматує замовлення як повідомлення у WhatsApp ресторану. Або обидва паралельно." },
  { title: "Роздрукуйте та наклейте QR", desc: "Завантажте QR (один на стіл або один на ресторан) у PDF чи PNG і наклейте на столи. Гості сканують рідною камерою — без App Store, без тертя." },
  { title: "Працюйте зміну", desc: "Замовлення з'являються у вкладці Кухня з номером столу, стравами, варіантами, алергенами, коментарем і номером дня. Перехід між нове → в роботі → готово. Браузер гостя оновлюється в реальному часі." },
];
const COMPARISON_ROWS = [["Комісія із замовлення","20–30%","0%","0% (€6,90/міс фікс)"],["Куди йде замовлення","Застосунок агрегатора","Ваша каса","Ваш планшет кухні або WhatsApp"],["Номер столу на тикеті","Немає","Вручну","Так, автоматом"],["Модифікатори / варіанти","Обмежено","Так","Так, з алергенами"],["Багатомовний checkout","Мова їх застосунку","Немає","35 мов, автоматом"],["Потрібне залізо","Планшет агрегатора","POS-термінал","Будь-який планшет з браузером"],["Час налаштування","Onboarding-дзвінок","Дні-тижні","5 хвилин"]];

export function SeoContent() {
  return (<>
    <Section dataSection="seo-intro"><div className="max-w-4xl mx-auto"><p className="text-xs font-medium uppercase tracking-widest text-primary mb-3 text-center">Детально</p><h2 className="text-3xl sm:text-4xl lg:text-5xl font-medium tracking-tight mb-3 text-center">Що таке онлайн система замовлень для ресторану <span className="text-muted-foreground">насправді</span></h2><p className="text-base sm:text-lg text-muted-foreground mb-10 text-center">Не marketplace. Не агрегатор доставки. Пряма лінія від телефону гостя за вашим столом до планшета кухні — або в WhatsApp.</p><div className="space-y-4 text-base sm:text-lg text-foreground/90 leading-relaxed"><p><strong>Онлайн система замовлень для ресторану</strong> в сенсі IQ Rest — це софт, який дає гостю за вашим столом відкрити меню в телефоні, зібрати кошик і надіслати замовлення на кухню — без Uber Eats, Glovo, Bolt Food або будь-якого іншого marketplace. Гість не залишає ваше QR-меню, ви не платите комісію з замовлення, і тикет надходить з реальним номером столу.</p><p>IQ Rest побудовано навколо двох каналів. За замовчуванням <em>внутрішній режим</em>: кожне нове замовлення надходить у вкладку Кухня панелі на планшеті, телефоні чи ноутбуці біля видачі — з номером столу, стравами з варіантами і алергенами, вільним коментарем гостя й денним номером замовлення. Альтернатива — <em>WhatsApp-режим</em>: те саме замовлення форматується як повідомлення у WhatsApp ресторану. Корисно для малих команд, переважно самовивозу або коли менеджер поза залом. Обидва режими можуть працювати одночасно.</p></div></div></Section>
    <Section dataSection="seo-benefits"><div className="max-w-4xl mx-auto"><h3 className="text-2xl sm:text-3xl font-medium tracking-tight mb-6 text-center">Що ви реально отримуєте</h3><div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-3 sm:gap-4">{BENEFITS.map((b) => (<div key={b} className="bg-muted/20 border border-border rounded-2xl p-4 sm:p-5 flex flex-row items-center gap-3"><div className="h-8 w-8 rounded-lg bg-primary/10 text-primary flex items-center justify-center shrink-0"><Check className="h-4 w-4" strokeWidth={2.5} /></div><p className="text-sm sm:text-base text-foreground/90 leading-snug">{b}</p></div>))}</div></div></Section>
    <Section dataSection="seo-how"><div className="max-w-4xl mx-auto"><h3 className="text-2xl sm:text-3xl font-medium tracking-tight mb-6 text-center">Як працює потік замовлень IQ Rest</h3><p className="text-base sm:text-lg text-foreground/90 leading-relaxed mb-6 text-center">Чотири перемикачі в панелі — і ви в ефірі. Без установника, без POS-заліза, без проєкту інтеграції.</p><div className="grid grid-cols-1 sm:grid-cols-2 gap-3 sm:gap-4">{HOW_STEPS.map((s, i) => (<div key={s.title} className="bg-muted/20 border border-border rounded-2xl p-5 flex flex-row items-start gap-4"><div className="h-10 w-10 rounded-lg bg-primary text-primary-foreground flex items-center justify-center shrink-0 font-semibold text-base">{i + 1}</div><div className="flex-1 min-w-0"><div className="text-base sm:text-lg font-semibold tracking-tight mb-1">{s.title}</div><p className="text-sm text-muted-foreground leading-relaxed">{s.desc}</p></div></div>))}</div></div></Section>
    <Section dataSection="seo-table"><div className="max-w-4xl mx-auto"><h3 className="text-2xl sm:text-3xl font-medium tracking-tight mb-6 text-center">Агрегатор, класичний POS чи система замовлень</h3><div className="bg-muted/20 border border-border rounded-2xl p-4 sm:p-6 overflow-x-auto"><table className="w-full text-sm sm:text-base border-collapse"><thead><tr className="border-b border-border"><th className="text-left font-semibold py-3 pr-3 text-foreground">Характеристика</th><th className="text-left font-semibold py-3 pr-3 text-muted-foreground">Агрегатор доставки</th><th className="text-left font-semibold py-3 pr-3 text-muted-foreground">Класичний POS</th><th className="text-left font-semibold py-3 text-primary">Замовлення IQ Rest</th></tr></thead><tbody className="text-foreground/90">{COMPARISON_ROWS.map((row, i) => (<tr key={row[0]} className={i < COMPARISON_ROWS.length - 1 ? "border-b border-border/50" : ""}><td className="py-3 pr-3 font-medium">{row[0]}</td><td className="py-3 pr-3 text-muted-foreground">{row[1]}</td><td className="py-3 pr-3 text-muted-foreground">{row[2]}</td><td className="py-3 text-foreground">{row[3]}</td></tr>))}</tbody></table></div><p className="text-sm text-muted-foreground leading-relaxed mt-6 text-center">Онлайн система замовлень, якою володіє сам ресторан, окупається за перший вікенд — кожна гривня, яку гість витрачає у вашому залі, залишається у вашому залі, а тикет біля видачі завжди з реальним номером столу.</p></div></Section>
  </>);
}
