import { Check } from "lucide-react";
import { Section } from "@/app/_landing/components/section";

const BENEFITS = ["QR igal laual, skanni-ja-telli, ilma rakenduseta", "Tellimused reaalajas köögi või halduri tahvelarvutis", "Või restorani WhatsAppi — sina valid", "Modifikaatorid, valikud ja allergeenid lähevad tšekile", "Külalise vaba kommentaar igal tellimusel", "Päevane nummerdamine köögile", "Mitmekeelne checkout 35 keeles, külalise telefoni järgi", "Null vahendustasu tellimuselt — fikseeritud kuumakse"];
const HOW_STEPS = [
  { title: "Lülita restoranile tellimused sisse", desc: "Ava restorani seaded, aktiveeri lüliti Tellimused ja vali, milliseid külalise välju (nimi, telefon, aadress) koguda." },
  { title: "Vali kohaletoimetuskanal", desc: "Sisemine režiim saadab uued tellimused vahekaardile Köök. WhatsAppi režiim vormindab tellimuse sõnumina restorani WhatsAppi. Või mõlemad paralleelselt." },
  { title: "Prindi ja kleebi QR", desc: "Laadi alla QR (üks laua kohta või üks restorani kohta) PDF-is või PNG-s ja kleebi laudadele. Külalised skannivad oma kaameraga — ilma App Store'ita, ilma takistusteta." },
  { title: "Tee vahetust", desc: "Tellimused ilmuvad vahekaardil Köök koos lauanumbri, roogade, valikute, allergeenide, kommentaari ja päevase numbriga. Üleminek uus → töös → valmis. Külalise brauser uueneb reaalajas." },
];
const COMPARISON_ROWS = [["Vahendustasu tellimuselt","20–30%","0%","0% (€6,90/kuus fikseeritud)"],["Kuhu tellimus läheb","Vahendaja rakendus","Sinu kassa","Sinu köögi tahvelarvuti või WhatsApp"],["Lauanumber tšekil","Ei","Käsitsi","Jah, automaatselt"],["Modifikaatorid / valikud","Piiratud","Jah","Jah, koos allergeenidega"],["Mitmekeelne checkout","Nende rakenduse keel","Ei","35 keelt, automaatselt"],["Vajalik riistvara","Vahendaja tahvelarvuti","POS terminal","Iga tahvelarvuti brauseriga"],["Seadistamisaeg","Onboarding kõne","Päevad-nädalad","5 minutit"]];

export function SeoContent() {
  return (<>
    <Section dataSection="seo-intro"><div className="max-w-4xl mx-auto"><p className="text-xs font-medium uppercase tracking-widest text-primary mb-3 text-center">Põhjalikult</p><h2 className="text-3xl sm:text-4xl lg:text-5xl font-medium tracking-tight mb-3 text-center">Mis on online tellimissüsteem restoranile <span className="text-muted-foreground">tegelikult</span></h2><p className="text-base sm:text-lg text-muted-foreground mb-10 text-center">Mitte marketplace. Mitte kullerirakendus. Otseliin külalise telefonist sinu lauas köögi tahvelarvutisse — või WhatsAppi.</p><div className="space-y-4 text-base sm:text-lg text-foreground/90 leading-relaxed"><p><strong>Online tellimissüsteem restoranile</strong> IQ Resti mõttes on tarkvara, mis võimaldab külalisel sinu laual avada menüü telefonis, koostada ostukorv ja saata tellimus kööki — ilma Wolt, Bolt Food või muu marketplace'ita. Külaline ei lahku sinu QR-menüüst, sa ei maksa vahendustasu tellimuselt ja tšekk tuleb päris lauanumbriga.</p><p>IQ Rest on ehitatud ümber kahe kanali. Vaikimisi on <em>sisemine režiim</em>: iga uus tellimus jõuab paneeli vahekaardile Köök tahvelarvutis, telefonis või sülearvutis väljastusala juures — koos lauanumbri, roogade valikute ja allergeenidega, külalise vaba kommentaari ja tellimuse päevase numbriga. Alternatiiv on <em>WhatsAppi režiim</em>: sama tellimus vormindatakse sõnumina restorani WhatsAppi. Kasulik väikestele meeskondadele, peamiselt kaasaostule või kui haldur on saalist väljas. Mõlemad režiimid võivad korraga töötada.</p></div></div></Section>
    <Section dataSection="seo-benefits"><div className="max-w-4xl mx-auto"><h3 className="text-2xl sm:text-3xl font-medium tracking-tight mb-6 text-center">Mida tegelikult saad</h3><div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-3 sm:gap-4">{BENEFITS.map((b) => (<div key={b} className="bg-muted/20 border border-border rounded-2xl p-4 sm:p-5 flex flex-row items-center gap-3"><div className="h-8 w-8 rounded-lg bg-primary/10 text-primary flex items-center justify-center shrink-0"><Check className="h-4 w-4" strokeWidth={2.5} /></div><p className="text-sm sm:text-base text-foreground/90 leading-snug">{b}</p></div>))}</div></div></Section>
    <Section dataSection="seo-how"><div className="max-w-4xl mx-auto"><h3 className="text-2xl sm:text-3xl font-medium tracking-tight mb-6 text-center">Kuidas IQ Resti tellimuste voog töötab</h3><p className="text-base sm:text-lg text-foreground/90 leading-relaxed mb-6 text-center">Neli lülitit paneelis — ja oled eetris. Ilma paigaldajata, ilma POS riistvarata, ilma integratsiooniprojektita.</p><div className="grid grid-cols-1 sm:grid-cols-2 gap-3 sm:gap-4">{HOW_STEPS.map((s, i) => (<div key={s.title} className="bg-muted/20 border border-border rounded-2xl p-5 flex flex-row items-start gap-4"><div className="h-10 w-10 rounded-lg bg-primary text-primary-foreground flex items-center justify-center shrink-0 font-semibold text-base">{i + 1}</div><div className="flex-1 min-w-0"><div className="text-base sm:text-lg font-semibold tracking-tight mb-1">{s.title}</div><p className="text-sm text-muted-foreground leading-relaxed">{s.desc}</p></div></div>))}</div></div></Section>
    <Section dataSection="seo-table"><div className="max-w-4xl mx-auto"><h3 className="text-2xl sm:text-3xl font-medium tracking-tight mb-6 text-center">Vahendaja, klassikaline POS või tellimissüsteem</h3><div className="bg-muted/20 border border-border rounded-2xl p-4 sm:p-6 overflow-x-auto"><table className="w-full text-sm sm:text-base border-collapse"><thead><tr className="border-b border-border"><th className="text-left font-semibold py-3 pr-3 text-foreground">Omadus</th><th className="text-left font-semibold py-3 pr-3 text-muted-foreground">Kullerirakendus</th><th className="text-left font-semibold py-3 pr-3 text-muted-foreground">Klassikaline POS</th><th className="text-left font-semibold py-3 text-primary">IQ Resti tellimused</th></tr></thead><tbody className="text-foreground/90">{COMPARISON_ROWS.map((row, i) => (<tr key={row[0]} className={i < COMPARISON_ROWS.length - 1 ? "border-b border-border/50" : ""}><td className="py-3 pr-3 font-medium">{row[0]}</td><td className="py-3 pr-3 text-muted-foreground">{row[1]}</td><td className="py-3 pr-3 text-muted-foreground">{row[2]}</td><td className="py-3 text-foreground">{row[3]}</td></tr>))}</tbody></table></div><p className="text-sm text-muted-foreground leading-relaxed mt-6 text-center">Online tellimissüsteem, mida restoran ise omab, tasub end ära esimese nädalavahetusega — iga euro, mida külaline sinu saalis kulutab, jääb sinu saali, ja tšekk väljastusala juures on alati päris lauanumbriga.</p></div></Section>
  </>);
}
