import { QrCode, MessageCircle, ChefHat, Settings2, Languages, BarChart3 } from "lucide-react";
import type { LandingTexts } from "@/app/_landing/types";

export const TEXTS: LandingTexts = {
  htmlLang: "et",
  htmlDir: "ltr",
  meta: {
    title: "Online tellimissüsteem restoranile — QR ja WhatsApp | IQ Rest",
    description: "Online tellimissüsteem restoranile: külaline skannib QR-koodi laual, koostab tellimuse ja see jõuab otse köögi tahvelarvutisse või WhatsAppi. Null vahendustasu, lauanumbriga. 14 päeva tasuta.",
    canonical: "https://iq-rest.com/et/online-tellimissusteem-restoranile",
    ogLocale: "et_EE",
    ogTitle: "Online tellimissüsteem restoranile — Otse kööki",
    ogDescription: "Külaline skannib QR-i laual, koostab tellimuse ja see jõuab teie tahvelarvutisse või WhatsAppi — ilma vahendajata, ilma vahendustasuta, lauanumbriga igal tšekil.",
  },
  ctaText: "Lülita tellimused sisse",
  demoText: "Live demo",
  microcopy: "Alates €6,90/kuus · 14 päeva tasuta · Tühista millal soovid",
  header: { navFeatures: "Funktsioonid", navHow: "Kuidas töötab", navPricing: "Hinnad", navFaq: "FAQ", signIn: "Logi sisse", cta: "Proovi" },
  hero: {
    verticals: ["Restoranid", "Kohvikud", "Bistrood", "Pitsabaarid", "Baarid", "Õllepoed"],
    headline: "Online tellimissüsteem restoranile.",
    sub: "Külaline skannib oma laua QR-i, koostab tellimuse telefonis — ja tšekk jõuab otse köögi tahvelarvutisse või restorani WhatsAppi. Ilma vahendajata, ilma vahendustasuta, lauanumbriga igal tšekil.",
    dynamicHeadlines: ["Tellimus lauas.", "Otse köögi tahvelarvutisse.", "Või otse WhatsAppi.", "Null vahendustasu.", "Lauanumbriga."],
    painBullets: [
      "Online tellimissüsteem, mida restoran ise omab — ilma vahendajate, ilma vahendustasudeta.",
      "Tellimused jõuavad köögi või halduri tahvelarvutisse koos lauanumbri, modifikaatorite, allergeenide ja märkmetega.",
      "Või saadetakse otse restorani WhatsAppi — ideaalne kaasaostule ja väikestele meeskondadele.",
      "QR igale lauale (või üks kogu saalile) genereeritakse automaatselt.",
    ],
    rating: "500+ restorani 30+ riigis",
  },
  features: {
    heading: "Tellimissüsteem,",
    headingAccent: "tehtud laua jaoks.",
    sub: "Reaalne funktsionaalsus — mitte kullerirakenduste kloon.",
    items: [
      { Icon: QrCode, title: "QR-menüü ostukorviga igale lauale", desc: "Külaline skannib QR-i, sirvib menüüd oma keeles, lisab roogasid modifikaatoritega, jätab köögile märkme ja saadab. Ilma rakenduseta.", tag: "QR-tellimused" },
      { Icon: ChefHat, title: "Tellimused köögi tahvelarvutis", desc: "Iga uus tellimus ilmub vahekaardile Köök — väljastusala kõrval olevas tahvelarvutis — koos lauanumbri, roogade, valikute, allergeenide ja kommentaariga. Üks puudutus „töös“ → „valmis“.", tag: "Köögivaade" },
      { Icon: MessageCircle, title: "Või WhatsAppi", desc: "Pane restoran WhatsAppi režiimi (või mõlemad korraga) — iga tellimus tuleb WhatsAppi vormindatud sõnumina. Ideaalne kaasaostule või väikestele meeskondadele.", tag: "WhatsAppi režiim" },
      { Icon: Settings2, title: "Modifikaatorid, valikud ja allergeenid", desc: "Igal roal on valikurühmad (suurus, küpsus, lisad) hinnaerinevusega, allergeenisildid ja vaba kirjeldus. Ostukorv arvestab kõike — tšekk tahvelarvutis on ilma kahtlusteta.", tag: "Päris ostukorv" },
      { Icon: Languages, title: "Mitmekeelne checkout", desc: "Kogu tellimisvoog — ostukorv, modifikaatorid, kommentaar, kinnitus — on tõlgitud 35 keelde ja kohandub automaatselt külalise telefoni keelega.", tag: "35 keelt" },
      { Icon: BarChart3, title: "Päevane nummerdamine ja päevik", desc: "Iga tellimus saab köögi jaoks päevase numbri, läheb päevikusse koos summade ja ajatemplitega, toidab analüütikat. Tühistused on soft-delete, aruanded jäävad puhtaks.", tag: "Tellimuste päevik" },
    ],
  },
  founder: {
    eyebrow: "Tehtud kohviku omaniku poolt, mitte kulleri startupi poolt",
    quoteStart: "Mu naine ja mina avasime kohviku ja otsisime nädalaid viisi võtta vastu tellimusi lauast, mis ei annaks 30% vahendajale ega nõuaks 1500 € kassat. Kõik, mida proovisime, oli kohmakas, kallis või puudusid põhiasjad —",
    quoteAccent: "nii et ehitasime tellimissüsteemi, mida ise oleksime tahtnud.",
    sign: "Bogdan Sokolov · asutaja, endine kohviku omanik",
    photoAlt: "Bogdan, IQ Resti asutaja",
  },
  how: {
    heading: "Lülita tellimissüsteem sisse",
    headingAccent: "4 sammuga",
    sub: "Ilma paigalduseta, ilma integraatorita, ilma IT-le helistamata. Ainult telefon ja 5 minutit.",
    steps: [
      { n: "1", t: "Loo restoran", d: "Registreerumine e-posti või Google'iga — 30 sekundit." },
      { n: "2", t: "Lisa menüü", d: "Drag-and-drop või AI-skannimine paber-menüüst." },
      { n: "3", t: "Vali kanal", d: "Köögi tahvelarvuti, WhatsApp või mõlemad." },
      { n: "4", t: "Prindi QR", d: "Üks QR laua kohta — külalised tellivad kohe." },
    ],
  },
  pricing: {
    badge: "Piiramatud tellimused · Null vahendustasu",
    heading: "Üks pakett.",
    headingAccent: "Ilma tellimusetasuta.",
    sub: "Online tellimused, QR-menüü, WhatsAppi režiim, mitmekeelne checkout ja analüütika — kõik ühes tellimuses. Ilma protsendita tehingust.",
    monthlyLabel: "Kuus",
    yearlyLabel: "Aastas",
    saveBadge: "Säästa 25%",
    perMonth: "kuus",
    billedAnnually: "Arveldatakse kord aastas {total}",
    youSave: "Säästad {amount}",
    trust: { secure: "Tellimus Stripe'i kaudu", noCommitment: "Ilma kohustuseta", quick: "Aktiivne minutitega", restaurants: "+500 restorani" },
  },
  faq: {
    eyebrow: "Tellimissüsteem — korduma kippuvad küsimused",
    heading: "Tellimissüsteemi",
    headingAccent: "kohta.",
    sub: "Mida restoranipidajad küsivad enne online tellimuste sisselülitamist IQ Restis. Ei näe oma küsimust? Kirjuta WhatsAppis — vastavad päris inimesed.",
    whatsappCta: "Küsi WhatsAppist",
    whatsappPrefill: "Tere, mul on küsimus IQ Resti tellimuste kohta",
    items: [
      { q: "Kas see on kullerteenuse platvorm nagu Wolt või Bolt Food?", a: "Ei, see ongi mõte. IQ Rest on restorani oma tellimuskanal: külaline tellib teie QR-ist, tellimus jõuab teie tahvelarvutisse või WhatsAppi, teie serveerite. Mitte marketplace, mitte vahendaja kataloog — ja me ei võta kunagi osa arvest." },
      { q: "Kus täpselt tellimused ilmuvad?", a: "IQ Resti paneeli vahekaardil Köök igas tahvelarvutis või telefonis väljastusala või baari juures. Iga tellimus näitab lauanumbrit, roogasid valikute ja allergeenidega, külalise kommentaari ja päevast numbrit. Üleminek „uus → töös → valmis“ ühe puudutusega." },
      { q: "Kas tellimused saavad selle asemel tulla WhatsAppi?", a: "Jah. Igal restoranil on kolm režiimi: sisemine (ainult köögi tahvelarvuti), WhatsApp (tellimus tuleb sõnumina restorani WhatsAppi) või mõlemad korraga. Režiim on üks lüliti paneelis, muutub millal soovid." },
      { q: "Mis sisaldub tellimuses?", a: "Road valikutega ja lisadega (hinnaerinevusega), allergeenid, lauanumber, külalise vaba kommentaar ja — kui lülitad väljad sisse — nimi, telefon ja aadress. Piisab kulleri saatmiseks või lauale tagasi helistamiseks allergeeni asjus." },
      { q: "Kas külalised saavad menüüs online maksta?", a: "Vaikimisi — ei. IQ Rest on seadistatud lauas maksmiseks: külaline tellib, teie toote arve, makstakse nagu tavaliselt. Kui vajate online kaardimakset (tüüpiline kaasaostule), Stripe Connecti integratsioon on võimalik soovi korral — kirjuta WhatsAppis." },
      { q: "Kas vajan spetsiaalset tahvelarvutit, printerit või POS riistvara?", a: "Ei. Iga tahvelarvuti, sülearvuti või telefon brauseriga — ava paneel, logi sisse, jäta vahekaart Köök avatuks. Kui sul on juba POS — IQ Rest töötab kõrval, ei asenda kassat." },
      { q: "Mis juhtub pärast 14 tasuta päeva?", a: "Ilma makseviisita konto peatub — me ei võta kunagi automaatselt. Menüü, tellimused ja seaded säilivad; lisa kaart millal soovid, et taasaktiveerida. Tühista ühe klõpsuga, ilma kohustuseta." },
    ],
  },
  finalCta: {
    heading: "Lülita tellimissüsteem sisse.",
    headingAccent: "Valmis 5 minutiga.",
    sub: "14 päeva tasuta, kaardita. Tühista millal soovid. Liitu 500+ restoraniga, kes haldavad oma tellimusi IQ Resti kaudu.",
  },
  scan: {
    heading: "Paber-menüüst tellimissüsteemi",
    headingAccent: "60 sekundiga",
    sub: "Lae üles menüü foto — AI eraldab kategooriad, road ja hinnad otse redaktorisse. Seejärel ostukorv ja QR — ühe klõpsuga.",
    cta: "Skanni menüü →",
  },
  footer: {
    featureLinks: [
      { href: "/et/ai-translation", label: "AI tõlge" },
      { href: "/et/reservations", label: "Broneeringud" },
      { href: "/et/mobile-management", label: "Mobiilihaldus" },
      { href: "/et/easy-menu", label: "Menüü redaktor" },
      { href: "/et/custom-design", label: "Video- ja fototaustad" },
      { href: "/et/color-scheme", label: "Brändivärvid" },
      { href: "/et/multilingual", label: "Mitmekeelne menüü" },
      { href: "/et/ai-images", label: "AI fotooptimeerimine" },
      { href: "/et/analytics", label: "Analüütika" },
      { href: "/et/instant-setup", label: "Kohene seadistus" },
      { href: "/et/personal-support", label: "Isiklik tugi" },
    ],
    navLinks: [
      { href: "#pricing", label: "Hinnad" },
      { href: "#faq", label: "Küsimused" },
      { href: "/et/changelog", label: "Uudised" },
      { href: "/et/languages", label: "Vaheta keelt" },
    ],
    copyrightTemplate: "© {year} IQ Rest. Kõik õigused kaitstud.",
  },
};
