import { Check } from "lucide-react";
import { Section } from "@/app/_landing/components/section";

const BENEFITS = ["QR na svakom stolu, skeniraj-i-naruči, bez aplikacije", "Narudžbe u stvarnom vremenu na tabletu kuhinje ili voditelja", "Ili na WhatsAppu restorana — vi birate", "Modifikatori, varijante i alergeni idu na račun", "Slobodan komentar gosta na svakoj narudžbi", "Dnevno numeriranje za kuhinju", "Višejezični checkout na 35 jezika, prema mobitelu gosta", "Nula provizije po narudžbi — fiksna mjesečna pretplata"];
const HOW_STEPS = [
  { title: "Uključi narudžbe za restoran", desc: "Otvori postavke restorana, aktiviraj prekidač Narudžbe i odaberi koja polja gosta (ime, telefon, adresu) prikupljati." },
  { title: "Odaberi kanal isporuke", desc: "Interni način šalje nove narudžbe u karticu Kuhinja. WhatsApp način formatira narudžbu kao poruku na WhatsAppu restorana. Ili oba paralelno." },
  { title: "Otisni i zalijepi QR", desc: "Preuzmi QR (jedan po stolu ili jedan po restoranu) u PDF ili PNG i zalijepi na stolove. Gosti skeniraju vlastitom kamerom — bez App Storea, bez trenja." },
  { title: "Odradi smjenu", desc: "Narudžbe se pojavljuju u kartici Kuhinja s brojem stola, jelima, varijantama, alergenima, komentarom i dnevnim brojem. Prijelaz nova → u tijeku → gotova. Preglednik gosta osvježava se u stvarnom vremenu." },
];
const COMPARISON_ROWS = [["Provizija po narudžbi","20–30%","0%","0% (€6,90/mj fiksno)"],["Kamo narudžba ide","Aplikacija agregatora","Vaša blagajna","Vaš kuhinjski tablet ili WhatsApp"],["Broj stola na računu","Nema","Ručno","Da, automatski"],["Modifikatori / varijante","Ograničeno","Da","Da, s alergenima"],["Višejezični checkout","Jezik njihove aplikacije","Nema","35 jezika, automatski"],["Potreban hardver","Tablet agregatora","POS terminal","Bilo koji tablet s preglednikom"],["Vrijeme postavljanja","Onboarding poziv","Dani-tjedni","5 minuta"]];

export function SeoContent() {
  return (<>
    <Section dataSection="seo-intro"><div className="max-w-4xl mx-auto"><p className="text-xs font-medium uppercase tracking-widest text-primary mb-3 text-center">Detaljno</p><h2 className="text-3xl sm:text-4xl lg:text-5xl font-medium tracking-tight mb-3 text-center">Što je online sustav narudžbi za restoran <span className="text-muted-foreground">zaista</span></h2><p className="text-base sm:text-lg text-muted-foreground mb-10 text-center">Nije marketplace. Nije agregator dostave. Izravna linija od mobitela gosta na vašem stolu do kuhinjskog tableta — ili WhatsAppa.</p><div className="space-y-4 text-base sm:text-lg text-foreground/90 leading-relaxed"><p><strong>Online sustav narudžbi za restoran</strong> u smislu IQ Resta softver je koji omogućuje gostu na vašem stolu da otvori jelovnik u mobitelu, sastavi košaricu i pošalje narudžbu u kuhinju — bez Wolta, Glova, Bolt Fooda ili bilo kojeg drugog marketplacea. Gost ne napušta vaš QR jelovnik, vi ne plaćate proviziju po narudžbi, a račun stiže s pravim brojem stola.</p><p>IQ Rest je izgrađen oko dva kanala. Zadano je <em>interni način</em>: svaka nova narudžba stiže u karticu Kuhinja u panelu na tabletu, mobitelu ili laptopu uz pas — s brojem stola, jelima s varijantama i alergenima, slobodnim komentarom gosta i dnevnim brojem narudžbe. Alternativa je <em>WhatsApp način</em>: ista narudžba formatira se kao poruka na WhatsAppu restorana. Korisno za male timove, uglavnom preuzimanje ili kada je voditelj izvan sale. Oba načina mogu raditi istovremeno.</p></div></div></Section>
    <Section dataSection="seo-benefits"><div className="max-w-4xl mx-auto"><h3 className="text-2xl sm:text-3xl font-medium tracking-tight mb-6 text-center">Što stvarno dobivate</h3><div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-3 sm:gap-4">{BENEFITS.map((b) => (<div key={b} className="bg-muted/20 border border-border rounded-2xl p-4 sm:p-5 flex flex-row items-center gap-3"><div className="h-8 w-8 rounded-lg bg-primary/10 text-primary flex items-center justify-center shrink-0"><Check className="h-4 w-4" strokeWidth={2.5} /></div><p className="text-sm sm:text-base text-foreground/90 leading-snug">{b}</p></div>))}</div></div></Section>
    <Section dataSection="seo-how"><div className="max-w-4xl mx-auto"><h3 className="text-2xl sm:text-3xl font-medium tracking-tight mb-6 text-center">Kako radi tijek narudžbi IQ Resta</h3><p className="text-base sm:text-lg text-foreground/90 leading-relaxed mb-6 text-center">Četiri prekidača u panelu — i u eteru ste. Bez instalatera, bez POS hardvera, bez integracijskog projekta.</p><div className="grid grid-cols-1 sm:grid-cols-2 gap-3 sm:gap-4">{HOW_STEPS.map((s, i) => (<div key={s.title} className="bg-muted/20 border border-border rounded-2xl p-5 flex flex-row items-start gap-4"><div className="h-10 w-10 rounded-lg bg-primary text-primary-foreground flex items-center justify-center shrink-0 font-semibold text-base">{i + 1}</div><div className="flex-1 min-w-0"><div className="text-base sm:text-lg font-semibold tracking-tight mb-1">{s.title}</div><p className="text-sm text-muted-foreground leading-relaxed">{s.desc}</p></div></div>))}</div></div></Section>
    <Section dataSection="seo-table"><div className="max-w-4xl mx-auto"><h3 className="text-2xl sm:text-3xl font-medium tracking-tight mb-6 text-center">Agregator, klasični POS ili sustav narudžbi</h3><div className="bg-muted/20 border border-border rounded-2xl p-4 sm:p-6 overflow-x-auto"><table className="w-full text-sm sm:text-base border-collapse"><thead><tr className="border-b border-border"><th className="text-left font-semibold py-3 pr-3 text-foreground">Značajka</th><th className="text-left font-semibold py-3 pr-3 text-muted-foreground">Agregator dostave</th><th className="text-left font-semibold py-3 pr-3 text-muted-foreground">Klasični POS</th><th className="text-left font-semibold py-3 text-primary">Narudžbe IQ Rest</th></tr></thead><tbody className="text-foreground/90">{COMPARISON_ROWS.map((row, i) => (<tr key={row[0]} className={i < COMPARISON_ROWS.length - 1 ? "border-b border-border/50" : ""}><td className="py-3 pr-3 font-medium">{row[0]}</td><td className="py-3 pr-3 text-muted-foreground">{row[1]}</td><td className="py-3 pr-3 text-muted-foreground">{row[2]}</td><td className="py-3 text-foreground">{row[3]}</td></tr>))}</tbody></table></div><p className="text-sm text-muted-foreground leading-relaxed mt-6 text-center">Online sustav narudžbi koji restoran posjeduje sam isplati se već prvi vikend — svaka kuna koju gost potroši u vašoj sali ostaje u vašoj sali, a račun uz pas uvijek je s pravim brojem stola.</p></div></Section>
  </>);
}
