import { QrCode, MessageCircle, ChefHat, Settings2, Languages, BarChart3 } from "lucide-react";
import type { LandingTexts } from "@/app/_landing/types";

export const TEXTS: LandingTexts = {
  htmlLang: "hr",
  htmlDir: "ltr",
  meta: {
    title: "Online sustav narudžbi za restoran — QR i WhatsApp | IQ Rest",
    description: "Online sustav narudžbi za restoran: gost skenira QR za stolom, slaže narudžbu i ona dolazi izravno na kuhinjski tablet ili WhatsApp. Nula provizije, s brojem stola. 14 dana besplatno.",
    canonical: "https://iq-rest.com/hr/online-sustav-narudzbi-restoran",
    ogLocale: "hr_HR",
    ogTitle: "Online sustav narudžbi za restoran — Izravno u kuhinju",
    ogDescription: "Gost skenira QR za stolom, slaže narudžbu i ona dolazi na vaš tablet ili WhatsApp — bez agregatora, bez provizije, s brojem stola na svakom računu.",
  },
  ctaText: "Uključi narudžbe",
  demoText: "Demo uživo",
  microcopy: "Od €6,90/mj · 14 dana besplatno · Otkaži kada želiš",
  header: { navFeatures: "Značajke", navHow: "Kako radi", navPricing: "Cijene", navFaq: "FAQ", signIn: "Prijava", cta: "Isprobaj" },
  hero: {
    verticals: ["Restorani", "Kafići", "Bistroi", "Pizzerije", "Barovi", "Pivnice"],
    headline: "Online sustav narudžbi za restoran.",
    sub: "Gost skenira QR svog stola, slaže narudžbu u mobitelu — i račun stiže izravno na vaš kuhinjski tablet ili WhatsApp restorana. Bez agregatora, bez provizije, s brojem stola na svakom računu.",
    dynamicHeadlines: ["Narudžba za stolom.", "Izravno na kuhinjski tablet.", "Ili izravno na WhatsApp.", "Nula provizije.", "S brojem stola."],
    painBullets: [
      "Online sustav narudžbi koji restoran posjeduje sam — bez posrednika, bez provizije.",
      "Narudžbe stižu na tablet kuhinje ili voditelja s brojem stola, modifikatorima, alergenima i bilješkama.",
      "Ili se šalju izravno na WhatsApp restorana — idealno za preuzimanje i male timove.",
      "QR za svaki stol (ili jedan za cijelu salu) generira se automatski.",
    ],
    rating: "500+ restorana u 30+ zemalja",
  },
  features: {
    heading: "Sustav narudžbi,",
    headingAccent: "napravljen za stol.",
    sub: "Stvarna funkcionalnost — nije klon agregatora za dostavu.",
    items: [
      { Icon: QrCode, title: "QR jelovnik s košaricom za svaki stol", desc: "Gost skenira QR, pregledava jelovnik na svom jeziku, dodaje jela s modifikatorima, ostavlja bilješku za kuhinju i šalje. Bez aplikacije.", tag: "QR narudžbe" },
      { Icon: ChefHat, title: "Narudžbe na kuhinjskom tabletu", desc: "Svaka nova narudžba pojavljuje se u kartici Kuhinja — na tabletu uz pas — s brojem stola, jelima, varijantama, alergenima i komentarom. Jedan dodir od „u tijeku“ do „gotovo“.", tag: "Pogled kuhinje" },
      { Icon: MessageCircle, title: "Ili na WhatsApp", desc: "Postavi restoran u WhatsApp način (ili oba istovremeno) — svaka narudžba stiže na WhatsApp kao formatirana poruka. Idealno za preuzimanje ili male timove.", tag: "WhatsApp način" },
      { Icon: Settings2, title: "Modifikatori, varijante i alergeni", desc: "Svako jelo ima grupe varijanti (veličina, pečenost, dodaci) s razlikom u cijeni, oznake alergena i slobodan opis. Košarica obračunava sve — račun na tabletu je bez nejasnoća.", tag: "Prava košarica" },
      { Icon: Languages, title: "Višejezični checkout", desc: "Cijeli tijek narudžbe — košarica, modifikatori, komentar, potvrda — preveden je na 35 jezika i automatski se prilagođava jeziku gostovog mobitela.", tag: "35 jezika" },
      { Icon: BarChart3, title: "Dnevno numeriranje i dnevnik", desc: "Svaka narudžba dobiva dnevni broj za kuhinju, ide u dnevnik sa svotama i vremenskim oznakama, hrani analitiku. Otkazi su soft-delete, izvještaji ostaju čisti.", tag: "Dnevnik narudžbi" },
    ],
  },
  founder: {
    eyebrow: "Napravio vlasnik kafića, ne dostavni startup",
    quoteStart: "Žena i ja otvorili smo kafić i tjednima tražili način da primamo narudžbe za stolom koji ne bi dao 30% agregatoru i ne bi tražio kasu od 1500 €. Sve što smo isprobali bilo je trapavo, skupo ili bez osnovnih stvari —",
    quoteAccent: "pa smo izgradili sustav narudžbi koji smo sami htjeli imati.",
    sign: "Bogdan Sokolov · osnivač, bivši vlasnik kafića",
    photoAlt: "Bogdan, osnivač IQ Rest",
  },
  how: {
    heading: "Uključi sustav narudžbi",
    headingAccent: "u 4 koraka",
    sub: "Bez instalacije, bez integratora, bez poziva IT-u. Samo mobitel i 5 minuta.",
    steps: [
      { n: "1", t: "Stvori restoran", d: "Registracija emailom ili Googleom — 30 sekundi." },
      { n: "2", t: "Dodaj jelovnik", d: "Drag-and-drop ili AI skeniranje papirnatog jelovnika." },
      { n: "3", t: "Odaberi kanal", d: "Kuhinjski tablet, WhatsApp ili oba." },
      { n: "4", t: "Otisni QR", d: "Jedan QR po stolu — gosti naručuju odmah." },
    ],
  },
  pricing: {
    badge: "Neograničene narudžbe · Nula provizije",
    heading: "Jedan plan.",
    headingAccent: "Bez naknade po narudžbi.",
    sub: "Online narudžbe, QR jelovnik, WhatsApp način, višejezični checkout i analitika — sve u jednoj pretplati. Bez postotka od transakcije.",
    monthlyLabel: "Mjesečno",
    yearlyLabel: "Godišnje",
    saveBadge: "Ušteda 25%",
    perMonth: "mjesečno",
    billedAnnually: "Naplata jednom godišnje {total}",
    youSave: "Štediš {amount}",
    trust: { secure: "Pretplata putem Stripea", noCommitment: "Bez obveze", quick: "Aktivno u minutama", restaurants: "+500 restorana" },
  },
  faq: {
    eyebrow: "Sustav narudžbi — često postavljana pitanja",
    heading: "O sustavu",
    headingAccent: "narudžbi.",
    sub: "Što vlasnici restorana pitaju prije uključivanja online narudžbi u IQ Restu. Ne vidiš svoje pitanje? Piši na WhatsApp — odgovaraju pravi ljudi.",
    whatsappCta: "Pitaj na WhatsApp",
    whatsappPrefill: "Bok, imam pitanje o narudžbama IQ Rest",
    items: [
      { q: "Je li ovo dostavna platforma poput Wolta ili Glovoa?", a: "Ne, upravo u tome je poanta. IQ Rest je vlastiti kanal narudžbi restorana: gost naručuje s vašeg QR-a, narudžba stiže na vaš tablet ili WhatsApp, vi poslužujete. Bez marketplacea, bez kataloga agregatora — i nikada ne uzimamo dio računa." },
      { q: "Gdje točno pojavljuju se narudžbe?", a: "U kartici Kuhinja panela IQ Rest na bilo kojem tabletu ili mobitelu uz pas ili šank. Svaka narudžba prikazuje broj stola, jela s varijantama i alergenima, komentar gosta i dnevni broj. Prijelaz „nova → u tijeku → gotova“ jednim dodirom." },
      { q: "Mogu li narudžbe dolaziti na WhatsApp umjesto toga?", a: "Da. Svaki restoran ima tri načina: interni (samo kuhinjski tablet), WhatsApp (narudžba dolazi kao poruka na WhatsApp restorana) ili oba istovremeno. Način je jedan prekidač u panelu, mijenja se kada želiš." },
      { q: "Što sadrži narudžba?", a: "Jela s varijantama i dodacima (s razlikom u cijeni), alergeni, broj stola, slobodan komentar gosta i — ako uključiš polja — ime, telefon i adresu. Dovoljno za slanje dostavljača ili pozivanje stola natrag radi alergena." },
      { q: "Mogu li gosti platiti online u jelovniku?", a: "Prema zadanim postavkama — ne. IQ Rest je postavljen za plaćanje za stolom: gost naručuje, vi donosite račun, plaća se kao i obično. Ako trebate online plaćanje karticom (tipično za preuzimanje), Stripe Connect integracija je moguća na zahtjev — piši na WhatsApp." },
      { q: "Trebam li poseban tablet, printer ili POS hardver?", a: "Ne. Bilo koji tablet, laptop ili mobitel s preglednikom — otvori panel, prijavi se, ostavi karticu Kuhinja otvorenu. Ako već imaš POS — IQ Rest radi uz njega, ne zamjenjuje blagajnu." },
      { q: "Što se događa nakon 14 besplatnih dana?", a: "Bez načina plaćanja račun se pauzira — nikad ne naplaćujemo automatski. Jelovnik, narudžbe i postavke se čuvaju; dodaj karticu kada želiš za reaktivaciju. Otkaz jednim klikom, bez obveze." },
    ],
  },
  finalCta: {
    heading: "Uključi sustav narudžbi.",
    headingAccent: "Spremno u 5 minuta.",
    sub: "14 dana besplatno, bez kartice. Otkaži kada želiš. Pridruži se 500+ restorana koji upravljaju svojim narudžbama preko IQ Resta.",
  },
  scan: {
    heading: "Od papirnatog jelovnika do sustava narudžbi",
    headingAccent: "u 60 sekundi",
    sub: "Učitaj fotografiju jelovnika — AI izvlači kategorije, jela i cijene izravno u urednik. Zatim košarica i QR — jednim klikom.",
    cta: "Skeniraj jelovnik →",
  },
  footer: {
    featureLinks: [
      { href: "/hr/ai-translation", label: "AI prijevod" },
      { href: "/hr/reservations", label: "Rezervacije" },
      { href: "/hr/mobile-management", label: "Mobilno upravljanje" },
      { href: "/hr/easy-menu", label: "Editor jelovnika" },
      { href: "/hr/custom-design", label: "Video i foto pozadine" },
      { href: "/hr/color-scheme", label: "Boje brenda" },
      { href: "/hr/multilingual", label: "Višejezični jelovnik" },
      { href: "/hr/ai-images", label: "AI optimizacija fotografija" },
      { href: "/hr/analytics", label: "Analitika" },
      { href: "/hr/instant-setup", label: "Trenutna postava" },
      { href: "/hr/personal-support", label: "Osobna podrška" },
    ],
    navLinks: [
      { href: "#pricing", label: "Cijene" },
      { href: "#faq", label: "Pitanja" },
      { href: "/hr/changelog", label: "Novosti" },
      { href: "/hr/languages", label: "Promijeni jezik" },
    ],
    copyrightTemplate: "© {year} IQ Rest. Sva prava pridržana.",
  },
};
