import { QrCode, MessageCircle, ChefHat, Settings2, Languages, BarChart3 } from "lucide-react";
import type { LandingTexts } from "@/app/_landing/types";

export const TEXTS: LandingTexts = {
  htmlLang: "ja",
  htmlDir: "ltr",
  meta: {
    title: "飲食店向け QR オーダーシステム — WhatsApp 連携 | IQ Rest",
    description: "飲食店向けオンライン注文システム。お客様が QR を読み取り、注文はそのままキッチンのタブレットや店舗の WhatsApp に届きます。手数料ゼロ、テーブル番号付き。14日間無料。",
    canonical: "https://iq-rest.com/ja/qr-order-system-restaurant",
    ogLocale: "ja_JP",
    ogTitle: "飲食店向け QR オーダーシステム — そのままキッチンへ",
    ogDescription: "お客様がテーブルの QR を読み取って注文、内容はあなたのタブレットや WhatsApp に直行。集約プラットフォーム不要、手数料ゼロ、テーブル番号付き。",
  },
  ctaText: "注文を有効化",
  demoText: "ライブデモ",
  microcopy: "月額 6.90€ から · 14日間無料 · いつでも解約可能",
  header: { navFeatures: "機能", navHow: "仕組み", navPricing: "料金", navFaq: "FAQ", signIn: "ログイン", cta: "無料体験" },
  hero: {
    verticals: ["レストラン", "カフェ", "ビストロ", "ピザ屋", "バー", "居酒屋"],
    headline: "飲食店向け QR オーダーシステム",
    sub: "お客様がテーブルの QR を読み取り、スマホで注文を作成、その内容はあなたのキッチンタブレットや店舗の WhatsApp に直接届きます。集約プラットフォーム不要、手数料ゼロ、すべての伝票にテーブル番号。",
    dynamicHeadlines: ["テーブルから注文。", "そのままキッチンタブレットへ。", "WhatsApp にも対応。", "手数料ゼロ。", "テーブル番号付き。"],
    painBullets: [
      "飲食店が本当に所有するオーダーシステム — 中間業者なし、手数料なし。",
      "注文はテーブル番号・モディファイア・アレルゲン・メモ付きでキッチン／マネージャーのタブレットに届く。",
      "もしくは店舗の WhatsApp に直送 — テイクアウトや少人数チームに最適。",
      "テーブルごと（または店舗共通）の QR コードを自動生成。",
    ],
    rating: "30以上の国の 500+ レストラン",
  },
  features: {
    heading: "テーブルのために",
    headingAccent: "作られたオーダーシステム",
    sub: "本物の機能 — 配達アグリゲーターのクローンではありません。",
    items: [
      { Icon: QrCode, title: "全テーブルでカート付き QR メニュー", desc: "お客様がテーブルの QR を読み取り、自分の言語でメニューを閲覧、モディファイア付きで商品を追加、キッチンへのメモを残して送信。アプリ不要。", tag: "QR 注文" },
      { Icon: ChefHat, title: "キッチンタブレットに注文", desc: "新しい注文が管理画面の「キッチン」タブに表示。テーブル番号・商品・バリエーション・アレルゲン・お客様のコメント付き。ワンタップで「対応中」→「完了」に変更。", tag: "キッチンビュー" },
      { Icon: MessageCircle, title: "あるいは WhatsApp に送信", desc: "店舗を WhatsApp モード（または両方）に切替え、各注文がフォーマット済メッセージとして店舗の WhatsApp に届きます。テイクアウトや小規模チームに最適。", tag: "WhatsApp モード" },
      { Icon: Settings2, title: "モディファイア・バリエーション・アレルゲン", desc: "各商品にバリエーショングループ（サイズ、焼き加減、トッピング）、価格差、アレルゲンタグ、自由記述あり。カートが全てを反映し、タブレットの伝票に曖昧さなし。", tag: "本格カート" },
      { Icon: Languages, title: "多言語チェックアウト", desc: "注文フロー全体（カート、モディファイア、コメント、確認）が 35 言語に翻訳済。お客様の端末言語に自動対応。", tag: "35 言語" },
      { Icon: BarChart3, title: "日次番号付けと注文ログ", desc: "各注文にキッチン用の日次番号が付与され、合計・タイムスタンプ付きのログに記録、分析にも反映。キャンセルはソフト削除でレポートを汚しません。", tag: "注文ログ" },
    ],
  },
  founder: {
    eyebrow: "配達系スタートアップではなく、カフェオーナーが構築",
    quoteStart: "妻と私はカフェを開業し、テーブルからの注文を受ける方法を何週間も探しました。30%をアグリゲーターに渡したくないし、1500€の POS は要らない。試したものは重い、高い、基本機能が無い —",
    quoteAccent: "だから自分たちが欲しかったオーダーシステムを作りました。",
    sign: "Bogdan Sokolov · 創業者、元カフェオーナー",
    photoAlt: "Bogdan, IQ Rest 創業者",
  },
  how: {
    heading: "オーダーシステムを有効化",
    headingAccent: "4ステップ",
    sub: "インストール不要、インテグレーター不要、IT 電話不要。スマホと 5 分だけ。",
    steps: [
      { n: "1", t: "店舗を作成", d: "メール or Google で登録 — 30秒。" },
      { n: "2", t: "メニュー追加", d: "ドラッグ&ドロップ、または紙メニューを AI スキャン。" },
      { n: "3", t: "チャネル選択", d: "キッチンタブレット、WhatsApp、または両方。" },
      { n: "4", t: "QR 印刷", d: "テーブルごとに 1 枚 — お客様はすぐに注文可能。" },
    ],
  },
  pricing: {
    badge: "注文無制限 · 手数料ゼロ",
    heading: "1 プラン。",
    headingAccent: "注文ごとの追加料金なし。",
    sub: "オンライン注文、QR メニュー、WhatsApp モード、多言語チェックアウト、分析 — すべて 1 サブスクに。トランザクション手数料なし。",
    monthlyLabel: "月額",
    yearlyLabel: "年額",
    saveBadge: "25% 節約",
    perMonth: "／月",
    billedAnnually: "年額一括 {total}",
    youSave: "節約額 {amount}",
    trust: { secure: "Stripe で課金", noCommitment: "縛りなし", quick: "数分で稼働", restaurants: "+500 レストラン" },
  },
  faq: {
    eyebrow: "オーダーシステム — よくある質問",
    heading: "オーダー",
    headingAccent: "システムについて",
    sub: "IQ Rest でオンライン注文を始める前に、オーナーからよく聞かれる質問。質問がない？ WhatsApp で連絡を — 実際の人が答えます。",
    whatsappCta: "WhatsApp で質問",
    whatsappPrefill: "こんにちは、IQ Rest の注文について質問があります",
    items: [
      { q: "Uber Eats や 出前館 のような配達プラットフォームですか？", a: "いいえ、それが要点です。IQ Rest は飲食店自身の注文チャネル — お客様があなたの QR から注文し、あなたのタブレットや WhatsApp に届く、あなたが提供する。マーケットプレイスもアグリゲーターカタログもなし、勘定の一部を取ることもありません。" },
      { q: "注文はどこに表示されますか？", a: "IQ Rest 管理画面の「キッチン」タブ — どのタブレット／スマホでも、レジ前やバーに置いたデバイスで開けます。各注文にテーブル番号、商品とバリエーションとアレルゲン、お客様のコメント、日次番号が表示。ワンタップで 新規 → 対応中 → 完了。" },
      { q: "代わりに WhatsApp で注文を受け取れますか？", a: "はい。各店舗に 3 モード：内部（キッチンタブレットのみ）、WhatsApp（注文を整形メッセージで店舗 WhatsApp に送信）、または同時に両方。管理画面のスイッチ 1 つで切替可能。" },
      { q: "注文には何が含まれますか？", a: "商品とバリエーション・トッピング（価格差含む）、アレルゲン、テーブル番号、お客様の自由コメント、フィールドを有効化すれば氏名・電話・住所も。テイクアウト配達やアレルゲン確認の電話に十分な情報。" },
      { q: "お客様はメニューからオンライン決済できますか？", a: "デフォルトではできません。IQ Rest はテーブル決済前提 — お客様が注文、伝票を持っていく、いつも通り支払い。オンラインカード決済（テイクアウト用に典型的）が必要な場合、Stripe Connect 連携をご相談ください — WhatsApp でメッセージを。" },
      { q: "専用タブレット、プリンタ、POS ハードウェアが必要ですか？", a: "不要。ブラウザがあるタブレット、ノート PC、スマホで OK — 管理画面を開き、ログインし、「キッチン」タブを開いたままに。POS をお持ちなら IQ Rest は並行稼働、レジを置き換えません。" },
      { q: "14日間無料の後はどうなりますか？", a: "支払方法がなければアカウントは一時停止 — 自動課金は決してしません。メニュー、注文、設定はすべて保存される。再開したい時にカード追加。ワンクリックで解約、縛りなし。" },
    ],
  },
  finalCta: {
    heading: "オーダーシステムを有効化",
    headingAccent: "5 分で稼働",
    sub: "14日間無料、カード不要。いつでも解約可能。IQ Rest で自店のオンライン注文を運用している 500+ レストランに加わりましょう。",
  },
  scan: {
    heading: "紙メニューからオーダーシステムへ",
    headingAccent: "60 秒で",
    sub: "メニューの写真をアップロード — AI がカテゴリ・商品・価格をエディタに抽出。そこからカートと QR は 1 クリック。",
    cta: "メニューをスキャン →",
  },
  footer: {
    featureLinks: [
      { href: "/ja/ai-translation", label: "AI 翻訳" },
      { href: "/ja/reservations", label: "予約" },
      { href: "/ja/mobile-management", label: "モバイル管理" },
      { href: "/ja/easy-menu", label: "メニューエディタ" },
      { href: "/ja/custom-design", label: "動画・写真背景" },
      { href: "/ja/color-scheme", label: "ブランドカラー" },
      { href: "/ja/multilingual", label: "多言語メニュー" },
      { href: "/ja/ai-images", label: "AI 画像最適化" },
      { href: "/ja/analytics", label: "分析" },
      { href: "/ja/instant-setup", label: "即時セットアップ" },
      { href: "/ja/personal-support", label: "個別サポート" },
    ],
    navLinks: [
      { href: "#pricing", label: "料金" },
      { href: "#faq", label: "FAQ" },
      { href: "/ja/changelog", label: "更新情報" },
      { href: "/ja/languages", label: "言語切替" },
    ],
    copyrightTemplate: "© {year} IQ Rest. All rights reserved.",
  },
};
