import { QrCode, MessageCircle, ChefHat, Settings2, Languages, BarChart3 } from "lucide-react";
import type { LandingTexts } from "@/app/_landing/types";

export const TEXTS: LandingTexts = {
  htmlLang: "pl",
  htmlDir: "ltr",
  meta: {
    title: "System Zamówień Online dla Restauracji — QR i WhatsApp | IQ Rest",
    description: "System zamówień online dla restauracji: gość skanuje QR przy stoliku, zamawia, zamówienie ląduje wprost na Twoim tablecie w kuchni lub WhatsApp. Bez prowizji, z numerem stolika. 14 dni za darmo.",
    canonical: "https://iq-rest.com/pl/system-zamowien-online-dla-restauracji",
    ogLocale: "pl_PL",
    ogTitle: "System Zamówień Online dla Restauracji — Wprost do Kuchni",
    ogDescription: "Gość skanuje QR przy stoliku, składa zamówienie, trafia na Twój tablet lub WhatsApp — bez agregatora, bez prowizji, z numerem stolika na każdym bonie.",
  },
  ctaText: "Włącz zamówienia",
  demoText: "Zobacz demo na żywo",
  microcopy: "Od €6,90/mies. · 14 dni za darmo · Anuluj kiedy chcesz",
  header: { navFeatures: "Funkcje", navHow: "Jak to działa", navPricing: "Cennik", navFaq: "FAQ", signIn: "Zaloguj", cta: "Wypróbuj" },
  hero: {
    verticals: ["Restauracje", "Kawiarnie", "Bistra", "Pizzerie", "Bary", "Browary"],
    headline: "System Zamówień Online dla Restauracji.",
    sub: "Gość skanuje QR swojego stolika, składa zamówienie w telefonie, a bon ląduje wprost na tablecie w kuchni lub WhatsApp restauracji. Bez agregatora, bez prowizji, z numerem stolika na każdym bonie.",
    dynamicHeadlines: ["Zamówienia przy stoliku.", "Wprost na tablet kuchni.", "Lub wprost na WhatsApp.", "Zero prowizji.", "Z numerem stolika."],
    painBullets: [
      "System zamówień online, który należy do restauracji — bez pośrednika, bez prowizji.",
      "Zamówienia trafiają na tablet kuchni lub menedżera z numerem stolika, modyfikatorami, alergenami i notatkami.",
      "Lub wysyłane prosto na WhatsApp restauracji — idealne dla na wynos i małych zespołów.",
      "QR na każdy stolik (lub jeden na całą salę) generowany automatycznie.",
    ],
    rating: "+500 restauracji w 30+ krajach",
  },
  features: {
    heading: "System zamówień",
    headingAccent: "stworzony dla stolika.",
    sub: "Prawdziwa funkcjonalność — nie klon agregatora dostaw.",
    items: [
      { Icon: QrCode, title: "Menu QR z koszykiem przy każdym stoliku", desc: "Gość skanuje QR stolika, przegląda menu w swoim języku, dodaje dania z modyfikatorami, zostawia notatkę dla kuchni i wysyła. Bez aplikacji do instalacji.", tag: "Zamówienia QR" },
      { Icon: ChefHat, title: "Bony na tablecie w kuchni", desc: "Każde nowe zamówienie pojawia się w zakładce Kuchnia panelu — na tablecie przy wydawce — z numerem stolika, daniami, wariantami, alergenami i komentarzem gościa. Z w trakcie na gotowe jednym tapnięciem.", tag: "Widok kuchni" },
      { Icon: MessageCircle, title: "Lub wyślij na WhatsApp", desc: "Przełącz restaurację w tryb WhatsApp (lub oba naraz) — każde zamówienie trafia na WhatsApp lokalu jako sformatowana wiadomość. Idealne dla na wynos lub małych zespołów.", tag: "Tryb WhatsApp" },
      { Icon: Settings2, title: "Modyfikatory, warianty i alergeny", desc: "Każde danie ma grupy wariantów (rozmiar, wysmażenie, dodatki) z różnicą cen, tagi alergenów i opis. Koszyk respektuje wszystko — bon na tablecie jest jednoznaczny.", tag: "Prawdziwy koszyk" },
      { Icon: Languages, title: "Wielojęzyczny checkout", desc: "Cały przepływ zamówienia — koszyk, modyfikatory, komentarz, potwierdzenie — przetłumaczony na 35 języków, automatycznie wykrywa język telefonu gościa.", tag: "35 języków" },
      { Icon: BarChart3, title: "Dzienna numeracja i rejestr", desc: "Każde zamówienie dostaje dzienny numer dla kuchni, trafia do rejestru z sumami i znacznikami czasu, zasila analitykę. Anulacje to soft-delete — raporty pozostają czyste.", tag: "Rejestr zamówień" },
    ],
  },
  founder: {
    eyebrow: "Zbudowane przez właściciela kawiarni, nie startup dostawczy",
    quoteStart: "Z żoną otworzyliśmy kawiarnię i tygodniami szukaliśmy sposobu na przyjmowanie zamówień przy stoliku, który nie oddawałby 30% agregatorowi ani nie wymagał kasy za €1500. Wszystko było ciężkie, drogie albo bez podstaw —",
    quoteAccent: "więc zbudowaliśmy system zamówień, który chcielibyśmy mieć.",
    sign: "Bogdan Sokolov · założyciel, były właściciel kawiarni",
    photoAlt: "Bogdan, założyciel IQ Rest",
  },
  how: {
    heading: "Włącz swój system zamówień",
    headingAccent: "w 4 krokach",
    sub: "Bez instalacji, bez integratora, bez telefonu do informatyka. Tylko telefon i 5 minut.",
    steps: [
      { n: "1", t: "Stwórz restaurację", d: "Rejestracja email lub Google — 30 sekund." },
      { n: "2", t: "Dodaj menu", d: "Drag-and-drop lub AI-skan papierowego menu." },
      { n: "3", t: "Wybierz kanał", d: "Tablet kuchni, WhatsApp lub oba." },
      { n: "4", t: "Wydrukuj QR", d: "Jeden QR na stolik — goście zamawiają od razu." },
    ],
  },
  pricing: {
    badge: "Nieograniczone zamówienia · Zero prowizji",
    heading: "Jeden plan.",
    headingAccent: "Bez opłaty za zamówienie.",
    sub: "Zamówienia online, menu QR, tryb WhatsApp, wielojęzyczny checkout i analityka — wszystko w jednej subskrypcji. Bez procentu od transakcji.",
    monthlyLabel: "Miesięcznie",
    yearlyLabel: "Rocznie",
    saveBadge: "Oszczędzasz 25%",
    perMonth: "miesięcznie",
    billedAnnually: "Rozliczane rocznie {total}",
    youSave: "Oszczędzasz {amount}",
    trust: { secure: "Subskrypcja przez Stripe", noCommitment: "Bez zobowiązań", quick: "Aktywne w minuty", restaurants: "+500 restauracji" },
  },
  faq: {
    eyebrow: "System zamówień — częste pytania",
    heading: "O systemie",
    headingAccent: "zamówień.",
    sub: "O co pytają właściciele przed włączeniem zamówień online z IQ Rest. Nie ma Twojego pytania? Napisz na WhatsApp — odpowiadają żywi ludzie.",
    whatsappCta: "Zapytaj na WhatsApp",
    whatsappPrefill: "Cześć, mam pytanie o zamówienia IQ Rest",
    items: [
      { q: "Czy to platforma dostaw jak Uber Eats lub Glovo?", a: "Nie, w tym rzecz. IQ Rest to własny kanał zamówień restauracji — gość zamawia z Twojego QR, bon ląduje na Twoim tablecie lub WhatsApp, Ty serwujesz. Bez marketplace, bez katalogu agregatora — i nigdy nie bierzemy części rachunku." },
      { q: "Gdzie dokładnie pojawiają się zamówienia?", a: "W zakładce Kuchnia panelu IQ Rest, na każdym tablecie lub telefonie przy wydawce lub barze. Każde zamówienie pokazuje numer stolika, dania z wariantami i alergenami, komentarz gościa i dzienny numer. Z nowe → w trakcie → gotowe jednym tapnięciem." },
      { q: "Czy mogę odbierać zamówienia na WhatsApp?", a: "Tak. Każda restauracja ma trzy tryby: wewnętrzny (tylko tablet kuchni), WhatsApp (zamówienie jako sformatowana wiadomość na numer WhatsApp lokalu) lub oba naraz. Tryb to jeden przełącznik w panelu — zmieniasz kiedy chcesz." },
      { q: "Co zawiera zamówienie?", a: "Dania z wariantami i dodatkami (z różnicą cen), alergeny, numer stolika, swobodny komentarz gościa i — jeśli włączysz pola — imię, telefon i adres. Wystarczy, by wysłać kierowcę po wynos lub oddzwonić do stolika w sprawie alergenu." },
      { q: "Czy goście mogą płacić online w menu?", a: "Domyślnie nie. IQ Rest został zaprojektowany do płatności przy stoliku — gość zamawia, przynosisz rachunek, płaci jak zwykle. Płatność kartą online (typowe dla na wynos) można zintegrować przez Stripe Connect na żądanie — napisz na WhatsApp." },
      { q: "Czy potrzebny jest specjalny tablet, drukarka lub sprzęt POS?", a: "Nie. Każdy tablet, laptop lub telefon z przeglądarką działa — otwórz panel, zaloguj się, zostaw otwartą zakładkę Kuchnia. Jeśli masz już POS, IQ Rest współistnieje — nie zastępuje kasy." },
      { q: "Co się dzieje po 14 dniach darmowych?", a: "Bez metody płatności konto wstrzymuje się — nigdy nie pobieramy automatycznie. Menu, zamówienia i ustawienia pozostają zapisane; dodajesz kartę, kiedy chcesz reaktywować. Anulujesz jednym kliknięciem, bez zobowiązań." },
    ],
  },
  finalCta: {
    heading: "Włącz swój system zamówień.",
    headingAccent: "Gotowe w 5 minut.",
    sub: "14 dni za darmo, bez karty. Anuluj kiedy chcesz. Dołącz do 500+ restauracji, które prowadzą swoje zamówienia z IQ Rest.",
  },
  scan: {
    heading: "Od papierowego menu do systemu zamówień",
    headingAccent: "w 60 sekund",
    sub: "Wgraj zdjęcie menu — AI wyciąga kategorie, dania i ceny prosto do edytora. Dalej koszyk i QR są o jedno kliknięcie.",
    cta: "Zeskanuj menu →",
  },
  footer: {
    featureLinks: [
      { href: "/pl/ai-translation", label: "Tłumaczenie AI" },
      { href: "/pl/reservations", label: "Rezerwacje" },
      { href: "/pl/mobile-management", label: "Zarządzanie z telefonu" },
      { href: "/pl/easy-menu", label: "Edytor menu" },
      { href: "/pl/custom-design", label: "Tła wideo i foto" },
      { href: "/pl/color-scheme", label: "Kolory marki" },
      { href: "/pl/multilingual", label: "Wielojęzyczne menu" },
      { href: "/pl/ai-images", label: "Optymalizacja zdjęć AI" },
      { href: "/pl/analytics", label: "Analityka" },
      { href: "/pl/instant-setup", label: "Natychmiastowa konfiguracja" },
      { href: "/pl/personal-support", label: "Osobiste wsparcie" },
    ],
    navLinks: [
      { href: "#pricing", label: "Cennik" },
      { href: "#faq", label: "Pytania" },
      { href: "/pl/changelog", label: "Co nowego" },
      { href: "/pl/languages", label: "Zmień język" },
    ],
    copyrightTemplate: "© {year} IQ Rest. Wszelkie prawa zastrzeżone.",
  },
};
