import type { CookieBannerTexts } from "@/components/cookie-consent/banner";

// Banner UI strings only — the legal documents (Cookie Policy + Terms) inside the secondary
// modals are English-only on purpose (binding version, no per-locale lawyer review needed).
// Locales not listed fall back to English via the helper below.

export const COOKIE_TEXTS: Record<string, CookieBannerTexts> = {
  en: {
    title: "Cookies",
    message: "We use cookies to keep the site working and to measure how it's used. Choose what's OK with you.",
    accept: "Accept",
    reject: "Reject",
    cookiePolicyLink: "Cookie policy",
    privacyPolicyLink: "Privacy policy",
    termsLink: "Terms of service",
    cookieSettings: "Cookie settings",
  },
  es: {
    title: "Cookies",
    message: "Usamos cookies para que el sitio funcione y para medir cómo se utiliza. Elige lo que prefieras.",
    accept: "Aceptar",
    reject: "Rechazar",
    cookiePolicyLink: "Política de cookies",
    privacyPolicyLink: "Política de privacidad",
    termsLink: "Términos del servicio",
    cookieSettings: "Configuración de cookies",
  },
  de: {
    title: "Cookies",
    message: "Wir verwenden Cookies, damit die Seite funktioniert und um zu messen, wie sie genutzt wird. Wähle, was für dich in Ordnung ist.",
    accept: "Akzeptieren",
    reject: "Ablehnen",
    cookiePolicyLink: "Cookie-Richtlinie",
    privacyPolicyLink: "Datenschutzerklärung",
    termsLink: "Nutzungsbedingungen",
    cookieSettings: "Cookie-Einstellungen",
  },
  fr: {
    title: "Cookies",
    message: "Nous utilisons des cookies pour faire fonctionner le site et mesurer son utilisation. Choisis ce qui te convient.",
    accept: "Accepter",
    reject: "Refuser",
    cookiePolicyLink: "Politique de cookies",
    privacyPolicyLink: "Politique de confidentialité",
    termsLink: "Conditions d'utilisation",
    cookieSettings: "Paramètres de cookies",
  },
  it: {
    title: "Cookie",
    message: "Usiamo i cookie per far funzionare il sito e per misurare come viene utilizzato. Scegli ciò che preferisci.",
    accept: "Accetta",
    reject: "Rifiuta",
    cookiePolicyLink: "Politica sui cookie",
    privacyPolicyLink: "Politica sulla privacy",
    termsLink: "Termini di servizio",
    cookieSettings: "Impostazioni cookie",
  },
  pt: {
    title: "Cookies",
    message: "Usamos cookies para o site funcionar e para medir como é utilizado. Escolhe o que preferires.",
    accept: "Aceitar",
    reject: "Rejeitar",
    cookiePolicyLink: "Política de cookies",
    privacyPolicyLink: "Política de privacidade",
    termsLink: "Termos de serviço",
    cookieSettings: "Definições de cookies",
  },
  nl: {
    title: "Cookies",
    message: "We gebruiken cookies om de site te laten werken en om te meten hoe hij wordt gebruikt. Kies wat voor jou OK is.",
    accept: "Accepteren",
    reject: "Weigeren",
    cookiePolicyLink: "Cookiebeleid",
    privacyPolicyLink: "Privacybeleid",
    termsLink: "Servicevoorwaarden",
    cookieSettings: "Cookie-instellingen",
  },
  pl: {
    title: "Pliki cookie",
    message: "Używamy plików cookie, aby strona działała i aby mierzyć, jak jest używana. Wybierz to, co Ci pasuje.",
    accept: "Akceptuj",
    reject: "Odrzuć",
    cookiePolicyLink: "Polityka cookies",
    privacyPolicyLink: "Polityka prywatności",
    termsLink: "Warunki świadczenia usług",
    cookieSettings: "Ustawienia cookies",
  },
  ru: {
    title: "Куки",
    message: "Мы используем куки, чтобы сайт работал и чтобы измерять, как им пользуются. Выбери, что подходит тебе.",
    accept: "Принять",
    reject: "Отклонить",
    cookiePolicyLink: "Политика cookies",
    privacyPolicyLink: "Политика конфиденциальности",
    termsLink: "Условия использования",
    cookieSettings: "Настройки cookies",
  },
  uk: {
    title: "Куки",
    message: "Ми використовуємо куки, щоб сайт працював і щоб вимірювати, як ним користуються. Обери те, що тобі підходить.",
    accept: "Прийняти",
    reject: "Відхилити",
    cookiePolicyLink: "Політика cookies",
    privacyPolicyLink: "Політика конфіденційності",
    termsLink: "Умови використання",
    cookieSettings: "Налаштування cookies",
  },
  sv: {
    title: "Cookies",
    message: "Vi använder cookies för att webbplatsen ska fungera och för att mäta hur den används. Välj det som passar dig.",
    accept: "Acceptera",
    reject: "Avvisa",
    cookiePolicyLink: "Cookiepolicy",
    privacyPolicyLink: "Integritetspolicy",
    termsLink: "Användarvillkor",
    cookieSettings: "Cookie-inställningar",
  },
  da: {
    title: "Cookies",
    message: "Vi bruger cookies for at sitet fungerer og for at måle, hvordan det bruges. Vælg det, der passer dig.",
    accept: "Accepter",
    reject: "Afvis",
    cookiePolicyLink: "Cookiepolitik",
    privacyPolicyLink: "Privatlivspolitik",
    termsLink: "Servicevilkår",
    cookieSettings: "Cookie-indstillinger",
  },
  no: {
    title: "Informasjonskapsler",
    message: "Vi bruker informasjonskapsler for at siden skal fungere og for å måle hvordan den brukes. Velg det som passer deg.",
    accept: "Godta",
    reject: "Avvis",
    cookiePolicyLink: "Cookies-policy",
    privacyPolicyLink: "Personvernerklæring",
    termsLink: "Tjenestevilkår",
    cookieSettings: "Cookie-innstillinger",
  },
  fi: {
    title: "Evästeet",
    message: "Käytämme evästeitä, jotta sivusto toimii ja jotta voimme mitata, miten sitä käytetään. Valitse, mikä sopii sinulle.",
    accept: "Hyväksy",
    reject: "Hylkää",
    cookiePolicyLink: "Evästekäytäntö",
    privacyPolicyLink: "Tietosuojakäytäntö",
    termsLink: "Käyttöehdot",
    cookieSettings: "Eväste-asetukset",
  },
  cs: {
    title: "Soubory cookie",
    message: "Používáme soubory cookie, aby web fungoval a abychom mohli měřit, jak se používá. Vyber, co ti vyhovuje.",
    accept: "Přijmout",
    reject: "Odmítnout",
    cookiePolicyLink: "Zásady cookies",
    privacyPolicyLink: "Zásady ochrany osobních údajů",
    termsLink: "Podmínky služby",
    cookieSettings: "Nastavení cookies",
  },
  el: {
    title: "Cookies",
    message: "Χρησιμοποιούμε cookies για να λειτουργεί ο ιστότοπος και για να μετράμε πώς χρησιμοποιείται. Διάλεξε αυτό που σε βολεύει.",
    accept: "Αποδοχή",
    reject: "Απόρριψη",
    cookiePolicyLink: "Πολιτική cookies",
    privacyPolicyLink: "Πολιτική απορρήτου",
    termsLink: "Όροι υπηρεσίας",
    cookieSettings: "Ρυθμίσεις cookies",
  },
  tr: {
    title: "Çerezler",
    message: "Sitenin çalışması ve nasıl kullanıldığını ölçmek için çerez kullanıyoruz. Sana uyanı seç.",
    accept: "Kabul et",
    reject: "Reddet",
    cookiePolicyLink: "Çerez politikası",
    privacyPolicyLink: "Gizlilik politikası",
    termsLink: "Hizmet şartları",
    cookieSettings: "Çerez ayarları",
  },
  ro: {
    title: "Cookie-uri",
    message: "Folosim cookie-uri pentru ca site-ul să funcționeze și pentru a măsura cum este utilizat. Alege ce-ți convine.",
    accept: "Accept",
    reject: "Refuz",
    cookiePolicyLink: "Politica de cookie-uri",
    privacyPolicyLink: "Politica de confidențialitate",
    termsLink: "Termeni de utilizare",
    cookieSettings: "Setări cookies",
  },
  hu: {
    title: "Sütik",
    message: "Sütiket használunk, hogy az oldal működjön és hogy mérjük a használatát. Válaszd ki, ami neked megfelel.",
    accept: "Elfogadom",
    reject: "Elutasítom",
    cookiePolicyLink: "Süti szabályzat",
    privacyPolicyLink: "Adatvédelmi szabályzat",
    termsLink: "Szolgáltatási feltételek",
    cookieSettings: "Süti beállítások",
  },
  bg: {
    title: "Бисквитки",
    message: "Използваме бисквитки, за да работи сайтът и за да измерваме как се използва. Избери това, което ти подхожда.",
    accept: "Приемам",
    reject: "Отказвам",
    cookiePolicyLink: "Политика за бисквитки",
    privacyPolicyLink: "Политика за поверителност",
    termsLink: "Условия за ползване",
    cookieSettings: "Настройки за бисквитки",
  },
  hr: {
    title: "Kolačići",
    message: "Koristimo kolačiće kako bi stranica radila i kako bismo mjerili njezinu upotrebu. Odaberi što ti odgovara.",
    accept: "Prihvati",
    reject: "Odbij",
    cookiePolicyLink: "Politika kolačića",
    privacyPolicyLink: "Pravila privatnosti",
    termsLink: "Uvjeti korištenja",
    cookieSettings: "Postavke kolačića",
  },
  sk: {
    title: "Súbory cookie",
    message: "Používame súbory cookie, aby web fungoval a aby sme merali, ako sa používa. Vyber, čo ti vyhovuje.",
    accept: "Prijať",
    reject: "Odmietnuť",
    cookiePolicyLink: "Zásady cookies",
    privacyPolicyLink: "Zásady ochrany osobných údajov",
    termsLink: "Podmienky služby",
    cookieSettings: "Nastavenia cookies",
  },
  sl: {
    title: "Piškotki",
    message: "Uporabljamo piškotke, da spletna stran deluje in da merimo, kako se uporablja. Izberi, kar ti ustreza.",
    accept: "Sprejmi",
    reject: "Zavrni",
    cookiePolicyLink: "Pravilnik o piškotkih",
    privacyPolicyLink: "Pravilnik o zasebnosti",
    termsLink: "Pogoji uporabe",
    cookieSettings: "Nastavitve piškotkov",
  },
  et: {
    title: "Küpsised",
    message: "Kasutame küpsiseid, et sait töötaks ja et mõõta, kuidas seda kasutatakse. Vali, mis sulle sobib.",
    accept: "Nõustun",
    reject: "Keeldun",
    cookiePolicyLink: "Küpsiste poliitika",
    privacyPolicyLink: "Privaatsuspoliitika",
    termsLink: "Teenusetingimused",
    cookieSettings: "Küpsiste seaded",
  },
  lv: {
    title: "Sīkdatnes",
    message: "Mēs izmantojam sīkdatnes, lai vietne darbotos un lai mērītu, kā tā tiek izmantota. Izvēlies to, kas tev der.",
    accept: "Pieņemt",
    reject: "Noraidīt",
    cookiePolicyLink: "Sīkdatņu politika",
    privacyPolicyLink: "Privātuma politika",
    termsLink: "Pakalpojuma noteikumi",
    cookieSettings: "Sīkdatņu iestatījumi",
  },
  lt: {
    title: "Slapukai",
    message: "Naudojame slapukus, kad svetainė veiktų ir kad galėtume matuoti, kaip ji naudojama. Pasirink, kas tau tinka.",
    accept: "Sutinku",
    reject: "Atmesti",
    cookiePolicyLink: "Slapukų politika",
    privacyPolicyLink: "Privatumo politika",
    termsLink: "Paslaugos sąlygos",
    cookieSettings: "Slapukų nustatymai",
  },
  sr: {
    title: "Kolačići",
    message: "Koristimo kolačiće da sajt radi i da merimo kako se koristi. Izaberi šta ti odgovara.",
    accept: "Prihvati",
    reject: "Odbaci",
    cookiePolicyLink: "Politika kolačića",
    privacyPolicyLink: "Politika privatnosti",
    termsLink: "Uslovi korišćenja",
    cookieSettings: "Podešavanja kolačića",
  },
  ca: {
    title: "Cookies",
    message: "Fem servir cookies perquè el lloc funcioni i per mesurar-ne l'ús. Tria el que vulguis.",
    accept: "Accepta",
    reject: "Rebutja",
    cookiePolicyLink: "Política de cookies",
    privacyPolicyLink: "Política de privacitat",
    termsLink: "Termes del servei",
    cookieSettings: "Configuració de cookies",
  },
  ga: {
    title: "Fianáin",
    message: "Úsáidimid fianáin chun an suíomh a oibriú agus chun a thomhas conas a úsáidtear é. Roghnaigh a oireann duit.",
    accept: "Glac leis",
    reject: "Diúltaigh",
    cookiePolicyLink: "Polasaí fianán",
    privacyPolicyLink: "Polasaí príobháideachta",
    termsLink: "Téarmaí seirbhíse",
    cookieSettings: "Socruithe fianán",
  },
  is: {
    title: "Vafrakökur",
    message: "Við notum vafrakökur til að síðan virki og til að mæla hvernig hún er notuð. Veldu það sem hentar þér.",
    accept: "Samþykkja",
    reject: "Hafna",
    cookiePolicyLink: "Vafrakökustefna",
    privacyPolicyLink: "Persónuverndarstefna",
    termsLink: "Þjónustuskilmálar",
    cookieSettings: "Vafrakökustillingar",
  },
  fa: {
    title: "کوکی‌ها",
    message: "ما از کوکی‌ها برای کارکرد سایت و سنجش نحوه استفاده از آن استفاده می‌کنیم. آنچه را که برایتان مناسب است انتخاب کنید.",
    accept: "پذیرفتن",
    reject: "رد کردن",
    cookiePolicyLink: "سیاست کوکی",
    privacyPolicyLink: "سیاست حفظ حریم خصوصی",
    termsLink: "شرایط خدمات",
    cookieSettings: "تنظیمات کوکی",
  },
  ar: {
    title: "ملفات تعريف الارتباط",
    message: "نستخدم ملفات تعريف الارتباط لتشغيل الموقع وقياس كيفية استخدامه. اختر ما يناسبك.",
    accept: "قبول",
    reject: "رفض",
    cookiePolicyLink: "سياسة ملفات تعريف الارتباط",
    privacyPolicyLink: "سياسة الخصوصية",
    termsLink: "شروط الخدمة",
    cookieSettings: "إعدادات ملفات تعريف الارتباط",
  },
  ja: {
    title: "Cookie",
    message: "サイトの動作と利用状況の計測のために Cookie を使用しています。お好みの選択をしてください。",
    accept: "同意する",
    reject: "拒否する",
    cookiePolicyLink: "Cookie ポリシー",
    privacyPolicyLink: "プライバシーポリシー",
    termsLink: "利用規約",
    cookieSettings: "Cookie 設定",
  },
  ko: {
    title: "쿠키",
    message: "사이트 운영과 사용 측정을 위해 쿠키를 사용합니다. 원하시는 것을 선택해 주세요.",
    accept: "동의",
    reject: "거부",
    cookiePolicyLink: "쿠키 정책",
    privacyPolicyLink: "개인정보 보호정책",
    termsLink: "서비스 약관",
    cookieSettings: "쿠키 설정",
  },
  zh: {
    title: "Cookie",
    message: "我们使用 Cookie 让网站正常运行并衡量使用情况。请选择你想要的方式。",
    accept: "接受",
    reject: "拒绝",
    cookiePolicyLink: "Cookie 政策",
    privacyPolicyLink: "隐私政策",
    termsLink: "服务条款",
    cookieSettings: "Cookie 设置",
  },
};

export function getCookieTexts(locale: string): CookieBannerTexts {
  return COOKIE_TEXTS[locale] ?? COOKIE_TEXTS.en;
}
