import { Check } from "lucide-react";
import { Section } from "@/app/_landing/components/section";

const BENEFITS = ["QR jokaisessa pöydässä, skannaa-ja-tilaa, ilman sovellusta", "Tilaukset reaaliajassa keittiön tai esimiehen tabletissa", "Tai ravintolan WhatsAppiin — sinä valitset", "Modifierit, vaihtoehdot ja allergeenit menevät kuittiin", "Asiakkaan vapaa kommentti jokaisessa tilauksessa", "Päivittäinen numerointi keittiölle", "Monikielinen checkout 35 kielellä, asiakkaan puhelimen mukaan", "Nolla välityspalkkiota tilausta kohti — kiinteä kuukausitilaus"];
const HOW_STEPS = [
  { title: "Käynnistä ravintolan tilaukset", desc: "Avaa ravintolan asetukset, ota Tilaukset-kytkin käyttöön ja valitse, mitkä asiakaskentät (nimi, puhelin, osoite) kerätään." },
  { title: "Valitse toimituskanava", desc: "Sisäinen tila lähettää uudet tilaukset Keittiö-välilehdelle. WhatsApp-tila muotoilee tilauksen viestiksi ravintolan WhatsAppiin. Tai molemmat rinnakkain." },
  { title: "Tulosta ja kiinnitä QR", desc: "Lataa QR (yksi pöytää kohti tai yksi ravintolaa kohti) PDF- tai PNG-muodossa ja kiinnitä pöytiin. Asiakkaat skannaavat omalla kameralla — ilman App Storea, ilman kitkaa." },
  { title: "Aja vuoro", desc: "Tilaukset ilmestyvät Keittiö-välilehdelle pöytänumerolla, ruoilla, vaihtoehdoilla, allergeeneilla, kommentilla ja päivän numerolla. Siirtymä uusi → työn alla → valmis. Asiakkaan selain päivittyy reaaliajassa." },
];
const COMPARISON_ROWS = [["Välityspalkkio tilausta kohti","20–30 %","0 %","0 % (6,90 €/kk kiinteä)"],["Minne tilaus menee","Välittäjän sovellus","Sinun kassa","Sinun keittiön tabletti tai WhatsApp"],["Pöytänumero kuitissa","Ei","Käsin","Kyllä, automaattisesti"],["Modifierit / vaihtoehdot","Rajoitetut","Kyllä","Kyllä, allergeenien kanssa"],["Monikielinen checkout","Heidän sovelluksensa kieli","Ei","35 kieltä, automaattisesti"],["Tarvittava laitteisto","Välittäjän tabletti","POS-pääte","Mikä tahansa tabletti selaimella"],["Käyttöönottoaika","Onboarding-puhelu","Päiviä-viikkoja","5 minuuttia"]];

export function SeoContent() {
  return (<>
    <Section noContainer dataSection="seo-intro"><div className="w-full"><p className="text-xs font-medium uppercase tracking-widest text-primary mb-3 text-start">Syvällisesti</p><h2 className="text-3xl sm:text-4xl lg:text-5xl font-medium tracking-tight mb-3 text-start">Mikä online-tilausjärjestelmä ravintolalle <span className="text-muted-foreground">oikeasti on</span></h2><p className="text-base sm:text-lg text-muted-foreground mb-10 text-start">Ei marketplace. Ei kuljetusvälittäjä. Suora linja asiakkaan puhelimesta pöydässäsi keittiön tablettiin — tai WhatsAppiin.</p><div className="space-y-4 text-base sm:text-lg text-foreground/90 leading-relaxed"><p><strong>Online-tilausjärjestelmä ravintolalle</strong> IQ Restin tarkoittamassa mielessä on ohjelmisto, jonka avulla asiakas pöydässäsi avaa menun puhelimessa, kokoaa ostoskorin ja lähettää tilauksen keittiöön — ilman Woltia, Foodoraa, Bolt Foodia tai mitään muuta marketplacea. Asiakas ei poistu QR-menustasi, et maksa välityspalkkiota tilauksesta, ja kuitti tulee oikealla pöytänumerolla.</p><p>IQ Rest on rakennettu kahden kanavan ympärille. Oletuksena <em>sisäinen tila</em>: jokainen uusi tilaus saapuu Keittiö-välilehdelle paneelissa tabletilla, puhelimella tai läppärillä passin vieressä — pöytänumerolla, ruoilla vaihtoehdoilla ja allergeeneilla, asiakkaan vapaalla kommentilla ja päivittäisellä tilausnumerolla. Vaihtoehto on <em>WhatsApp-tila</em>: sama tilaus muotoillaan viestiksi ravintolan WhatsAppiin. Hyödyllinen pienille tiimeille, pääasiassa noutoon tai kun esimies on poissa salista. Molemmat tilat voivat olla päällä yhtä aikaa.</p></div></div></Section>
    <Section noContainer dataSection="seo-benefits"><div className="w-full"><h3 className="text-2xl sm:text-3xl font-medium tracking-tight mb-6 text-start">Mitä todella saat</h3><div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-3 sm:gap-4">{BENEFITS.map((b) => (<div key={b} className="bg-muted/20 border border-border rounded-2xl p-4 sm:p-5 flex flex-row items-center gap-3"><div className="h-8 w-8 rounded-lg bg-primary/10 text-primary flex items-center justify-center shrink-0"><Check className="h-4 w-4" strokeWidth={2.5} /></div><p className="text-sm sm:text-base text-foreground/90 leading-snug">{b}</p></div>))}</div></div></Section>
    <Section noContainer dataSection="seo-how"><div className="w-full"><h3 className="text-2xl sm:text-3xl font-medium tracking-tight mb-6 text-start">Miten IQ Restin tilausvirta toimii</h3><p className="text-base sm:text-lg text-foreground/90 leading-relaxed mb-6 text-start">Neljä kytkintä paneelissa — ja olet ilmassa. Ei asentajaa, ei POS-laitteistoa, ei integrointiprojektia.</p><div className="grid grid-cols-1 sm:grid-cols-2 gap-3 sm:gap-4">{HOW_STEPS.map((s, i) => (<div key={s.title} className="bg-muted/20 border border-border rounded-2xl p-5 flex flex-row items-start gap-4"><div className="h-10 w-10 rounded-lg bg-primary text-primary-foreground flex items-center justify-center shrink-0 font-semibold text-base">{i + 1}</div><div className="flex-1 min-w-0"><div className="text-base sm:text-lg font-semibold tracking-tight mb-1">{s.title}</div><p className="text-sm text-muted-foreground leading-relaxed">{s.desc}</p></div></div>))}</div></div></Section>
    <Section noContainer dataSection="seo-table"><div className="w-full"><h3 className="text-2xl sm:text-3xl font-medium tracking-tight mb-6 text-start">Välittäjä, klassinen POS vai tilausjärjestelmä</h3><div className="bg-muted/20 border border-border rounded-2xl p-4 sm:p-6 overflow-x-auto"><table className="w-full text-sm sm:text-base border-collapse"><thead><tr className="border-b border-border"><th className="text-left font-semibold py-3 pr-3 text-foreground">Ominaisuus</th><th className="text-left font-semibold py-3 pr-3 text-muted-foreground">Kuljetusvälittäjä</th><th className="text-left font-semibold py-3 pr-3 text-muted-foreground">Klassinen POS</th><th className="text-left font-semibold py-3 text-primary">IQ Rest -tilaukset</th></tr></thead><tbody className="text-foreground/90">{COMPARISON_ROWS.map((row, i) => (<tr key={row[0]} className={i < COMPARISON_ROWS.length - 1 ? "border-b border-border/50" : ""}><td className="py-3 pr-3 font-medium">{row[0]}</td><td className="py-3 pr-3 text-muted-foreground">{row[1]}</td><td className="py-3 pr-3 text-muted-foreground">{row[2]}</td><td className="py-3 text-foreground">{row[3]}</td></tr>))}</tbody></table></div><p className="text-sm text-muted-foreground leading-relaxed mt-6 text-start">Online-tilausjärjestelmä, jonka ravintola omistaa itse, maksaa itsensä takaisin ensimmäisenä viikonloppuna — jokainen euro, jonka asiakas käyttää salissasi, jää saliisi, ja kuitti passin vieressä on aina oikealla pöytänumerolla.</p></div></Section>
  </>);
}
