import { QrCode, MessageCircle, ChefHat, Settings2, Languages, BarChart3 } from "lucide-react";
import type { LandingTexts } from "@/app/_landing/types";

export const TEXTS: LandingTexts = {
  htmlLang: "fi",
  htmlDir: "ltr",
  meta: {
    title: "Online-tilausjärjestelmä ravintolalle — QR ja WhatsApp | IQ Rest",
    description: "Online-tilausjärjestelmä ravintolalle: asiakas skannaa pöydän QR-koodin, kokoaa tilauksen ja se ilmestyy suoraan keittiön tablettiin tai WhatsAppiin. Nolla välityspalkkiota, pöytänumerolla. 14 päivää ilmaiseksi.",
    canonical: "https://iq-rest.com/fi/online-tilausjarjestelma-ravintolalle",
    ogLocale: "fi_FI",
    ogTitle: "Online-tilausjärjestelmä ravintolalle — Suoraan keittiöön",
    ogDescription: "Asiakas skannaa pöydän QR-koodin, kokoaa tilauksen ja se päätyy tablettiisi tai WhatsAppiin — ei välittäjää, ei välityspalkkiota, pöytänumero joka kuitissa.",
  },
  ctaText: "Käynnistä tilaukset",
  demoText: "Live-demo",
  microcopy: "Alkaen 6,90 €/kk · 14 päivää ilmaiseksi · Peru milloin haluat",
  header: { navFeatures: "Ominaisuudet", navHow: "Miten toimii", navPricing: "Hinnat", navFaq: "FAQ", signIn: "Kirjaudu", cta: "Kokeile" },
  hero: {
    verticals: ["Ravintolat", "Kahvilat", "Bistrot", "Pizzeriat", "Baarit", "Olutbaarit"],
    headline: "Online-tilausjärjestelmä ravintolalle.",
    sub: "Asiakas skannaa pöytänsä QR-koodin, kokoaa tilauksen puhelimessa — ja kuitti ilmestyy suoraan keittiön tablettiin tai ravintolan WhatsAppiin. Ei välittäjää, ei välityspalkkiota, pöytänumero joka kuitissa.",
    dynamicHeadlines: ["Tilaus pöydässä.", "Suoraan keittiön tablettiin.", "Tai suoraan WhatsAppiin.", "Nolla välityspalkkiota.", "Pöytänumerolla."],
    painBullets: [
      "Online-tilausjärjestelmä, jonka ravintola omistaa itse — ei välikäsiä, ei välityspalkkioita.",
      "Tilaukset saapuvat keittiön tai esimiehen tablettiin pöytänumerolla, modifiereilla, allergeeneilla ja muistiinpanoilla.",
      "Tai lähetetään suoraan ravintolan WhatsAppiin — ihanteellinen noutoon ja pienille tiimeille.",
      "QR-koodi jokaiseen pöytään (tai yksi koko saliin) luodaan automaattisesti.",
    ],
    rating: "500+ ravintolaa 30+ maassa",
  },
  features: {
    heading: "Tilausjärjestelmä,",
    headingAccent: "tehty pöytään.",
    sub: "Aitoa toiminnallisuutta — ei kuljetusvälittäjien klooni.",
    items: [
      { Icon: QrCode, title: "QR-menu ostoskorilla joka pöytään", desc: "Asiakas skannaa QR-koodin, selaa menua omalla kielellään, lisää ruokia modifiereilla, jättää viestin keittiölle ja lähettää. Ilman sovellusta.", tag: "QR-tilaaminen" },
      { Icon: ChefHat, title: "Tilaukset keittiön tabletissa", desc: "Jokainen uusi tilaus ilmestyy Keittiö-välilehdellä — passin vieressä olevassa tabletissa — pöytänumerolla, ruoilla, vaihtoehdoilla, allergeeneilla ja kommentilla. Yksi napsautus „työn alla“ → „valmis“.", tag: "Keittiönäkymä" },
      { Icon: MessageCircle, title: "Tai WhatsAppiin", desc: "Aseta ravintola WhatsApp-tilaan (tai molempiin yhtä aikaa) — jokainen tilaus tulee WhatsAppiin muotoiltuna viestinä. Ihanteellinen noutoon tai pienille tiimeille.", tag: "WhatsApp-tila" },
      { Icon: Settings2, title: "Modifierit, vaihtoehdot ja allergeenit", desc: "Jokaisella ruoalla on vaihtoehtoryhmiä (koko, paistoaste, lisukkeet) hintaerolla, allergeenitunnisteet ja vapaa kuvaus. Ostoskori laskee kaiken — kuitti tabletissa on ilman epäselvyyksiä.", tag: "Oikea ostoskori" },
      { Icon: Languages, title: "Monikielinen checkout", desc: "Koko tilausvirta — ostoskori, modifierit, kommentti, vahvistus — on käännetty 35 kielelle ja mukautuu automaattisesti asiakkaan puhelimen kieleen.", tag: "35 kieltä" },
      { Icon: BarChart3, title: "Päivittäinen numerointi ja loki", desc: "Jokainen tilaus saa keittiötä varten päivänumeron, menee lokiin summineen ja aikaleimoineen, syöttää analytiikkaa. Peruutukset ovat soft-delete, raportit pysyvät puhtaina.", tag: "Tilausloki" },
    ],
  },
  founder: {
    eyebrow: "Kahvilan omistajan tekemä, ei kuljetus-startup",
    quoteStart: "Vaimoni ja minä avasimme kahvilan ja etsimme viikkoja tapaa ottaa pöytätilauksia, joka ei antaisi 30 % välittäjälle eikä vaatisi 1500 € kassaa. Kaikki mitä kokeilimme oli kömpelöä, kallista tai siitä puuttui perusasiat —",
    quoteAccent: "joten rakensimme tilausjärjestelmän, jonka itse halusimme.",
    sign: "Bogdan Sokolov · perustaja, ex-kahvilanomistaja",
    photoAlt: "Bogdan, IQ Restin perustaja",
  },
  how: {
    heading: "Käynnistä tilausjärjestelmä",
    headingAccent: "4 askeleessa",
    sub: "Ei asennusta, ei integraattoria, ei IT:lle soittoa. Vain puhelin ja 5 minuuttia.",
    steps: [
      { n: "1", t: "Luo ravintola", d: "Rekisteröinti sähköpostilla tai Googlella — 30 sekuntia." },
      { n: "2", t: "Lisää menu", d: "Drag-and-drop tai AI-skannaus paperisesta menusta." },
      { n: "3", t: "Valitse kanava", d: "Keittiön tabletti, WhatsApp tai molemmat." },
      { n: "4", t: "Tulosta QR", d: "Yksi QR pöytää kohti — asiakkaat tilaavat heti." },
    ],
  },
  pricing: {
    badge: "Rajaton tilausmäärä · Nolla välityspalkkiota",
    heading: "Yksi paketti.",
    headingAccent: "Ei maksua tilausta kohti.",
    sub: "Online-tilaaminen, QR-menu, WhatsApp-tila, monikielinen checkout ja analytiikka — kaikki yhdessä tilauksessa. Ei prosenttiosuutta tapahtumasta.",
    monthlyLabel: "Kuukausi",
    yearlyLabel: "Vuosi",
    saveBadge: "Säästä 25 %",
    perMonth: "kuukaudessa",
    billedAnnually: "Veloitus kerran vuodessa {total}",
    youSave: "Säästät {amount}",
    trust: { secure: "Tilaus Stripe-palvelun kautta", noCommitment: "Ei sitoumusta", quick: "Aktiivinen minuuteissa", restaurants: "+500 ravintolaa" },
  },
  faq: {
    eyebrow: "Tilausjärjestelmä — usein kysytyt kysymykset",
    heading: "Tilausjärjestelmästä",
    headingAccent: "tarkemmin.",
    sub: "Mitä ravintoloitsijat kysyvät ennen kuin käynnistävät online-tilaukset IQ Restissä. Et näe omaa kysymystä? Kirjoita WhatsAppissa — vastaavat oikeat ihmiset.",
    whatsappCta: "Kysy WhatsAppissa",
    whatsappPrefill: "Hei, minulla on kysymys IQ Restin tilauksista",
    items: [
      { q: "Onko tämä kuljetusalusta kuten Wolt tai Foodora?", a: "Ei, tämä onkin pointti. IQ Rest on ravintolan oma tilauskanava: asiakas tilaa QR-koodistasi, tilaus ilmestyy tablettiisi tai WhatsAppiin, sinä tarjoilet. Ei marketplacea, ei välittäjän katalogia — emmekä koskaan ota osaa laskusta." },
      { q: "Missä tilaukset tarkalleen näkyvät?", a: "Keittiö-välilehdellä IQ Rest -paneelissa millä tahansa tabletilla tai puhelimella passin tai baarin vieressä. Jokainen tilaus näyttää pöytänumeron, ruoat vaihtoehdoilla ja allergeeneilla, asiakkaan kommentin ja päivittäisen numeron. Siirtymä „uusi → työn alla → valmis“ yhdellä napsautuksella." },
      { q: "Voivatko tilaukset tulla WhatsAppiin sen sijaan?", a: "Kyllä. Jokaisella ravintolalla on kolme tilaa: sisäinen (vain keittiön tabletti), WhatsApp (tilaus tulee viestinä ravintolan WhatsAppiin) tai molemmat yhtä aikaa. Tila on yksi kytkin paneelissa, vaihtuu milloin haluat." },
      { q: "Mitä tilauksessa on?", a: "Ruoat vaihtoehdoilla ja lisukkeilla (hintaerolla), allergeenit, pöytänumero, asiakkaan vapaa kommentti ja — jos otat kentät käyttöön — nimi, puhelin ja osoite. Riittävästi lähetin lähettämiseen tai pöytään takaisin soittamiseen allergeenin vuoksi." },
      { q: "Voivatko asiakkaat maksaa verkossa menussa?", a: "Oletuksena — ei. IQ Rest on rakennettu pöytään maksamiseen: asiakas tilaa, sinä tuot laskun, maksetaan kuten tavallisesti. Jos tarvitset online-korttimaksua (tyypillistä noutoon), Stripe Connect -integraatio on mahdollinen pyynnöstä — kirjoita WhatsAppissa." },
      { q: "Tarvitsenko erityisen tabletin, tulostimen tai POS-laitteiston?", a: "En. Mikä tahansa tabletti, läppäri tai puhelin selaimella — avaa paneeli, kirjaudu sisään, jätä Keittiö-välilehti auki. Jos sinulla on jo POS — IQ Rest toimii rinnalla, ei korvaa kassaa." },
      { q: "Mitä tapahtuu 14 ilmaisen päivän jälkeen?", a: "Ilman maksutapaa tili keskeytetään — emme koskaan veloita automaattisesti. Menu, tilaukset ja asetukset säilyvät; lisää kortti milloin haluat aktivoidaksesi uudelleen. Peruutus yhdellä napsautuksella, ei sitoumusta." },
    ],
  },
  finalCta: {
    heading: "Käynnistä tilausjärjestelmä.",
    headingAccent: "Valmis 5 minuutissa.",
    sub: "14 päivää ilmaiseksi, ei korttia. Peru milloin haluat. Liity 500+ ravintolaan, jotka hallitsevat tilauksiaan IQ Restin kautta.",
  },
  scan: {
    heading: "Paperimenusta tilausjärjestelmään",
    headingAccent: "60 sekunnissa",
    sub: "Lataa kuva menusta — AI poimii kategoriat, ruoat ja hinnat suoraan editoriin. Sitten ostoskori ja QR — yhdellä napsautuksella.",
    cta: "Skannaa menu →",
  },
  footer: {
    featureLinks: [
      { href: "/fi/ai-translation", label: "AI-käännös" },
      { href: "/fi/reservations", label: "Varaukset" },
      { href: "/fi/mobile-management", label: "Hallinta puhelimesta" },
      { href: "/fi/easy-menu", label: "Menueditori" },
      { href: "/fi/custom-design", label: "Video- ja kuvataustat" },
      { href: "/fi/color-scheme", label: "Brändivärit" },
      { href: "/fi/multilingual", label: "Monikielinen menu" },
      { href: "/fi/ai-images", label: "AI-kuvaoptimointi" },
      { href: "/fi/analytics", label: "Analytiikka" },
      { href: "/fi/instant-setup", label: "Välitön käyttöönotto" },
      { href: "/fi/personal-support", label: "Henkilökohtainen tuki" },
    ],
    navLinks: [
      { href: "#pricing", label: "Hinnat" },
      { href: "#faq", label: "Kysymykset" },
      { href: "/fi/changelog", label: "Uutta" },
      { href: "/fi/languages", label: "Vaihda kieli" },
    ],
    copyrightTemplate: "© {year} IQ Rest. Kaikki oikeudet pidätetään.",
  },
};
