import { Check } from "lucide-react";
import { Section } from "@/app/_landing/components/section";

const BENEFITS = ["QR na každom stole, naskenuj-a-objednaj, bez aplikácie", "Objednávky v reálnom čase na tablete kuchyne alebo manažéra", "Alebo do WhatsAppu reštaurácie — vy si vyberáte", "Modifikátory, varianty a alergény idú do tiketu", "Voľný komentár hosťa v každej objednávke", "Denné číslovanie pre kuchyňu", "Viacjazyčný checkout v 35 jazykoch, podľa telefónu hosťa", "Žiadna provízia z objednávky — fixné mesačné predplatné"];
const HOW_STEPS = [
  { title: "Zapni objednávky pre reštauráciu", desc: "Otvor nastavenia reštaurácie, aktivuj prepínač Objednávky a vyber, ktoré polia hosťa (meno, telefón, adresa) zbierať." },
  { title: "Vyber doručovací kanál", desc: "Interný režim posiela nové objednávky do karty Kuchyňa. Režim WhatsApp formátuje objednávku ako správu do WhatsAppu reštaurácie. Alebo oba paralelne." },
  { title: "Vytlač a nalep QR", desc: "Stiahni QR (jeden na stôl alebo jeden na reštauráciu) v PDF alebo PNG a nalep na stoly. Hostia skenujú vlastnou kamerou — bez App Store, bez trenia." },
  { title: "Odjazdi zmenu", desc: "Objednávky sa objavujú v karte Kuchyňa s číslom stola, jedlami, variantami, alergénmi, komentárom a denným číslom. Prechod nová → v práci → hotová. Prehliadač hosťa sa aktualizuje v reálnom čase." },
];
const COMPARISON_ROWS = [["Provízia z objednávky","20–30%","0%","0% (€6,90/mes fix)"],["Kam ide objednávka","Aplikácia agregátora","Vaša pokladňa","Váš kuchynský tablet alebo WhatsApp"],["Číslo stola na tikete","Nie je","Ručne","Áno, automaticky"],["Modifikátory / varianty","Obmedzené","Áno","Áno, s alergénmi"],["Viacjazyčný checkout","Jazyk ich aplikácie","Nie je","35 jazykov, automaticky"],["Potrebný hardvér","Tablet agregátora","POS terminál","Akýkoľvek tablet s prehliadačom"],["Čas nastavenia","Onboarding hovor","Dni-týždne","5 minút"]];

export function SeoContent() {
  return (<>
    <Section dataSection="seo-intro"><div className="max-w-4xl mx-auto"><p className="text-xs font-medium uppercase tracking-widest text-primary mb-3 text-center">Podrobne</p><h2 className="text-3xl sm:text-4xl lg:text-5xl font-medium tracking-tight mb-3 text-center">Čo je online objednávkový systém pre reštauráciu <span className="text-muted-foreground">naozaj</span></h2><p className="text-base sm:text-lg text-muted-foreground mb-10 text-center">Žiadny marketplace. Žiadny rozvozový agregátor. Priama linka z telefónu hosťa pri vašom stole na kuchynský tablet — alebo do WhatsAppu.</p><div className="space-y-4 text-base sm:text-lg text-foreground/90 leading-relaxed"><p><strong>Online objednávkový systém pre reštauráciu</strong> v zmysle IQ Rest je softvér, ktorý umožňuje hosťovi pri vašom stole otvoriť menu v telefóne, zostaviť košík a poslať objednávku do kuchyne — bez Wolt, Bolt Food alebo iného marketplace. Hosť nikdy neopúšťa vaše QR menu, vy neplatíte províziu z objednávky a tiket príde so skutočným číslom stola.</p><p>IQ Rest stojí na dvoch kanáloch. Predvolený je <em>interný režim</em>: každá nová objednávka príde do karty Kuchyňa panela na tablete, telefóne alebo notebooku pri výdaji — s číslom stola, jedlami s variantami a alergénmi, voľným komentárom hosťa a denným číslom objednávky. Alternatíva je <em>režim WhatsApp</em>: rovnaká objednávka sa naformátuje ako správa do WhatsAppu reštaurácie. Užitočné pre malé tímy, prevažne vyzdvihnutie alebo keď je manažér mimo sály. Oba režimy môžu bežať súčasne.</p></div></div></Section>
    <Section dataSection="seo-benefits"><div className="max-w-4xl mx-auto"><h3 className="text-2xl sm:text-3xl font-medium tracking-tight mb-6 text-center">Čo reálne dostanete</h3><div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-3 sm:gap-4">{BENEFITS.map((b) => (<div key={b} className="bg-muted/20 border border-border rounded-2xl p-4 sm:p-5 flex flex-row items-center gap-3"><div className="h-8 w-8 rounded-lg bg-primary/10 text-primary flex items-center justify-center shrink-0"><Check className="h-4 w-4" strokeWidth={2.5} /></div><p className="text-sm sm:text-base text-foreground/90 leading-snug">{b}</p></div>))}</div></div></Section>
    <Section dataSection="seo-how"><div className="max-w-4xl mx-auto"><h3 className="text-2xl sm:text-3xl font-medium tracking-tight mb-6 text-center">Ako funguje objednávkový tok IQ Rest</h3><p className="text-base sm:text-lg text-foreground/90 leading-relaxed mb-6 text-center">Štyri prepínače v paneli — a ste v prevádzke. Bez inštalátora, bez POS hardvéru, bez integračného projektu.</p><div className="grid grid-cols-1 sm:grid-cols-2 gap-3 sm:gap-4">{HOW_STEPS.map((s, i) => (<div key={s.title} className="bg-muted/20 border border-border rounded-2xl p-5 flex flex-row items-start gap-4"><div className="h-10 w-10 rounded-lg bg-primary text-primary-foreground flex items-center justify-center shrink-0 font-semibold text-base">{i + 1}</div><div className="flex-1 min-w-0"><div className="text-base sm:text-lg font-semibold tracking-tight mb-1">{s.title}</div><p className="text-sm text-muted-foreground leading-relaxed">{s.desc}</p></div></div>))}</div></div></Section>
    <Section dataSection="seo-table"><div className="max-w-4xl mx-auto"><h3 className="text-2xl sm:text-3xl font-medium tracking-tight mb-6 text-center">Agregátor, klasický POS alebo objednávkový systém</h3><div className="bg-muted/20 border border-border rounded-2xl p-4 sm:p-6 overflow-x-auto"><table className="w-full text-sm sm:text-base border-collapse"><thead><tr className="border-b border-border"><th className="text-left font-semibold py-3 pr-3 text-foreground">Vlastnosť</th><th className="text-left font-semibold py-3 pr-3 text-muted-foreground">Rozvozový agregátor</th><th className="text-left font-semibold py-3 pr-3 text-muted-foreground">Klasický POS</th><th className="text-left font-semibold py-3 text-primary">Objednávky IQ Rest</th></tr></thead><tbody className="text-foreground/90">{COMPARISON_ROWS.map((row, i) => (<tr key={row[0]} className={i < COMPARISON_ROWS.length - 1 ? "border-b border-border/50" : ""}><td className="py-3 pr-3 font-medium">{row[0]}</td><td className="py-3 pr-3 text-muted-foreground">{row[1]}</td><td className="py-3 pr-3 text-muted-foreground">{row[2]}</td><td className="py-3 text-foreground">{row[3]}</td></tr>))}</tbody></table></div><p className="text-sm text-muted-foreground leading-relaxed mt-6 text-center">Online objednávkový systém, ktorý vlastní samotná reštaurácia, sa zaplatí za prvý víkend — každé euro, ktoré hosť minie vo vašej sále, zostáva vo vašej sále, a tiket pri výdaji je vždy so skutočným číslom stola.</p></div></Section>
  </>);
}
