import { QrCode, MessageCircle, ChefHat, Settings2, Languages, BarChart3 } from "lucide-react";
import type { LandingTexts } from "@/app/_landing/types";

export const TEXTS: LandingTexts = {
  htmlLang: "sk",
  htmlDir: "ltr",
  meta: {
    title: "Online objednávkový systém pre reštauráciu — QR a WhatsApp | IQ Rest",
    description: "Online objednávkový systém pre reštauráciu: hosť naskenuje QR pri stole, zostaví objednávku a tá prichádza priamo na kuchynský tablet alebo WhatsApp. Žiadna provízia, s číslom stola. 14 dní zadarmo.",
    canonical: "https://iq-rest.com/sk/online-objednavkovy-system-restauracia",
    ogLocale: "sk_SK",
    ogTitle: "Online objednávkový systém pre reštauráciu — Priamo do kuchyne",
    ogDescription: "Hosť naskenuje QR pri stole, zostaví objednávku a tá prichádza na tablet alebo WhatsApp — bez sprostredkovateľa, bez provízie, s číslom stola na každom tikete.",
  },
  ctaText: "Zapnúť objednávky",
  demoText: "Live demo",
  microcopy: "Od €6,90/mes · 14 dní zadarmo · Zruš kedykoľvek",
  header: { navFeatures: "Funkcie", navHow: "Ako to funguje", navPricing: "Ceny", navFaq: "FAQ", signIn: "Prihlásiť", cta: "Vyskúšaj" },
  hero: {
    verticals: ["Reštaurácie", "Kaviarne", "Bistrá", "Pizzerie", "Bary", "Pivárne"],
    headline: "Online objednávkový systém pre reštauráciu.",
    sub: "Hosť naskenuje QR svojho stola, zostaví objednávku v telefóne — a tiket prichádza priamo na kuchynský tablet alebo WhatsApp reštaurácie. Bez sprostredkovateľa, bez provízie, s číslom stola na každom tikete.",
    dynamicHeadlines: ["Objednávka pri stole.", "Priamo na kuchynský tablet.", "Alebo priamo do WhatsAppu.", "Žiadna provízia.", "S číslom stola."],
    painBullets: [
      "Online objednávkový systém, ktorý vlastní samotná reštaurácia — bez sprostredkovateľov, bez provízie.",
      "Objednávky chodia na tablet kuchyne alebo manažéra s číslom stola, modifikátormi, alergénmi a poznámkami.",
      "Alebo sa posielajú priamo do WhatsAppu reštaurácie — ideálne pre vyzdvihnutie a malé tímy.",
      "QR na každý stôl (alebo jeden pre celú sálu) sa generuje automaticky.",
    ],
    rating: "500+ reštaurácií v 30+ krajinách",
  },
  features: {
    heading: "Objednávkový systém,",
    headingAccent: "vyrobený pre stôl.",
    sub: "Reálna funkcionalita — nie klon rozvozových agregátorov.",
    items: [
      { Icon: QrCode, title: "QR menu s košíkom pre každý stôl", desc: "Hosť naskenuje QR, prezerá menu vo svojom jazyku, pridáva jedlá s modifikátormi, nechá poznámku pre kuchyňu a odošle. Bez aplikácie.", tag: "QR objednávanie" },
      { Icon: ChefHat, title: "Objednávky na kuchynskom tablete", desc: "Každá nová objednávka sa objaví v karte Kuchyňa — na tablete pri výdaji — s číslom stola, jedlami, variantami, alergénmi a komentárom. Jedným klepnutím z „v práci“ na „hotovo“.", tag: "Pohľad kuchyne" },
      { Icon: MessageCircle, title: "Alebo do WhatsAppu", desc: "Prepni reštauráciu do režimu WhatsApp (alebo oba súčasne) — každá objednávka prichádza do WhatsAppu ako formátovaná správa. Ideálne pre vyzdvihnutie alebo malé tímy.", tag: "Režim WhatsApp" },
      { Icon: Settings2, title: "Modifikátory, varianty a alergény", desc: "Každé jedlo má skupiny variantov (veľkosť, prepečenie, prílohy) s rozdielom v cene, štítky alergénov a voľný popis. Košík všetko zaúčtuje — tiket na tablete je bez nejasností.", tag: "Skutočný košík" },
      { Icon: Languages, title: "Viacjazyčný checkout", desc: "Celý priebeh objednávky — košík, modifikátory, komentár, potvrdenie — je preložený do 35 jazykov a automaticky sa prispôsobuje jazyku telefónu hosťa.", tag: "35 jazykov" },
      { Icon: BarChart3, title: "Denné číslovanie a denník", desc: "Každá objednávka dostane denné číslo pre kuchyňu, ide do denníka so sumami a časovými značkami, kŕmi analytiku. Storná sú soft-delete, reporty zostávajú čisté.", tag: "Denník objednávok" },
    ],
  },
  founder: {
    eyebrow: "Vyrobené majiteľom kaviarne, nie rozvozovým startupom",
    quoteStart: "S manželkou sme otvorili kaviareň a týždne hľadali spôsob, ako prijímať objednávky pri stole, ktorý by nedával 30 % agregátoru a nevyžadoval pokladňu za 1500 €. Všetko, čo sme skúsili, bolo neohrabané, drahé alebo bez základných vecí —",
    quoteAccent: "tak sme postavili objednávkový systém, ktorý sme sami chceli mať.",
    sign: "Bogdan Sokolov · zakladateľ, ex-majiteľ kaviarne",
    photoAlt: "Bogdan, zakladateľ IQ Rest",
  },
  how: {
    heading: "Zapni objednávkový systém",
    headingAccent: "v 4 krokoch",
    sub: "Bez inštalácie, bez integrátora, bez volania ITčkárovi. Iba telefón a 5 minút.",
    steps: [
      { n: "1", t: "Vytvor reštauráciu", d: "Registrácia e-mailom alebo Google — 30 sekúnd." },
      { n: "2", t: "Pridaj menu", d: "Drag-and-drop alebo AI skenovanie papierového menu." },
      { n: "3", t: "Vyber kanál", d: "Tablet kuchyne, WhatsApp alebo oba." },
      { n: "4", t: "Vytlač QR", d: "Jeden QR na stôl — hostia objednávajú hneď." },
    ],
  },
  pricing: {
    badge: "Neobmedzené objednávky · Žiadna provízia",
    heading: "Jeden tarif.",
    headingAccent: "Bez poplatku za objednávku.",
    sub: "Online objednávky, QR menu, režim WhatsApp, viacjazyčný checkout a analytika — všetko v jednom predplatnom. Bez percenta z transakcie.",
    monthlyLabel: "Mesačne",
    yearlyLabel: "Ročne",
    saveBadge: "Zľava 25%",
    perMonth: "mesačne",
    billedAnnually: "Účtované raz ročne {total}",
    youSave: "Ušetríš {amount}",
    trust: { secure: "Predplatné cez Stripe", noCommitment: "Bez záväzkov", quick: "Aktívne za minúty", restaurants: "+500 reštaurácií" },
  },
  faq: {
    eyebrow: "Objednávkový systém — časté otázky",
    heading: "O objednávkovom",
    headingAccent: "systéme.",
    sub: "Čo sa majitelia reštaurácií pýtajú pred zapnutím online objednávok v IQ Rest. Nevidíš svoju otázku? Napíš na WhatsApp — odpovedajú skutoční ľudia.",
    whatsappCta: "Spýtaj sa na WhatsApp",
    whatsappPrefill: "Dobrý deň, mám otázku k objednávkam IQ Rest",
    items: [
      { q: "Je to rozvozová platforma ako Wolt alebo Bolt Food?", a: "Nie, to je celá pointa. IQ Rest je vlastný objednávkový kanál reštaurácie: hosť objedná z vášho QR, objednávka príde na váš tablet alebo WhatsApp, vy servírujete. Žiadny marketplace, žiadny katalóg agregátora — a my si nikdy neberieme časť účtu." },
      { q: "Kde presne sa objednávky objavujú?", a: "V karte Kuchyňa panela IQ Rest na ľubovoľnom tablete alebo telefóne pri výdaji či bare. Každá objednávka ukazuje číslo stola, jedlá s variantami a alergénmi, komentár hosťa a denné číslo. Prechod „nová → v práci → hotová“ jedným klepnutím." },
      { q: "Môžu objednávky chodiť do WhatsAppu namiesto toho?", a: "Áno. Každá reštaurácia má tri režimy: interný (iba kuchynský tablet), WhatsApp (objednávka príde ako správa do WhatsAppu reštaurácie) alebo oba súčasne. Režim je jeden prepínač v paneli, mení sa kedykoľvek." },
      { q: "Čo je v objednávke?", a: "Jedlá s variantami a prílohami (s rozdielom ceny), alergény, číslo stola, voľný komentár hosťa a — ak zapneš polia — meno, telefón a adresa. Stačí to na odoslanie kuriéra alebo zavolanie ku stolu kvôli alergénu." },
      { q: "Môžu hostia platiť online v menu?", a: "V predvolenom nastavení — nie. IQ Rest je nastavený na platbu pri stole: hosť objedná, vy prinesiete účet, platí sa ako obvykle. Ak potrebujete online platbu kartou (typické pre vyzdvihnutie), integrácia Stripe Connect je možná na vyžiadanie — napíš na WhatsApp." },
      { q: "Potrebujem špeciálny tablet, tlačiareň alebo POS hardvér?", a: "Nie. Akýkoľvek tablet, notebook alebo telefón s prehliadačom — otvor panel, prihlás sa, nechaj kartu Kuchyňa otvorenú. Ak už máš POS — IQ Rest beží vedľa, nenahrádza pokladňu." },
      { q: "Čo po 14 dňoch zadarmo?", a: "Bez platobnej metódy sa účet pozastaví — nikdy nestrhávame automaticky. Menu, objednávky a nastavenia zostávajú; pridáš kartu, kedykoľvek chceš, na reaktiváciu. Zrušenie jedným klepnutím, bez záväzkov." },
    ],
  },
  finalCta: {
    heading: "Zapni objednávkový systém.",
    headingAccent: "Hotové za 5 minút.",
    sub: "14 dní zadarmo, bez karty. Zruš kedykoľvek. Pridaj sa k 500+ reštauráciám, ktoré spravujú svoje objednávky cez IQ Rest.",
  },
  scan: {
    heading: "Z papierového menu na objednávkový systém",
    headingAccent: "za 60 sekúnd",
    sub: "Nahraj foto menu — AI vytiahne kategórie, jedlá a ceny priamo do editora. Potom košík a QR — jedným klepnutím.",
    cta: "Naskenovať menu →",
  },
  footer: {
    featureLinks: [
      { href: "/sk/ai-translation", label: "AI preklad" },
      { href: "/sk/reservations", label: "Rezervácie" },
      { href: "/sk/mobile-management", label: "Správa z telefónu" },
      { href: "/sk/easy-menu", label: "Editor menu" },
      { href: "/sk/custom-design", label: "Video a foto pozadia" },
      { href: "/sk/color-scheme", label: "Farby značky" },
      { href: "/sk/multilingual", label: "Viacjazyčné menu" },
      { href: "/sk/ai-images", label: "AI optimalizácia foto" },
      { href: "/sk/analytics", label: "Analytika" },
      { href: "/sk/instant-setup", label: "Okamžité spustenie" },
      { href: "/sk/personal-support", label: "Osobná podpora" },
    ],
    navLinks: [
      { href: "#pricing", label: "Ceny" },
      { href: "#faq", label: "Otázky" },
      { href: "/sk/changelog", label: "Novinky" },
      { href: "/sk/languages", label: "Zmeniť jazyk" },
    ],
    copyrightTemplate: "© {year} IQ Rest. Všetky práva vyhradené.",
  },
};
