import { Check } from "lucide-react";
import { Section } from "@/app/_landing/components/section";

const BENEFITS = ["QR pe fiecare masă, scanează-și-comandă, fără aplicație", "Comenzi în timp real pe tableta bucătăriei sau a managerului", "Sau pe WhatsApp-ul restaurantului — tu alegi", "Modificatori, variante și alergeni intră pe bon", "Comentariu liber al clientului pe fiecare comandă", "Numerotare zilnică pentru bucătărie", "Checkout multilingv în 35 de limbi, după telefonul clientului", "Zero comision pe comandă — abonament lunar fix"];
const HOW_STEPS = [
  { title: "Activează comenzile pentru restaurant", desc: "Deschide setările restaurantului, activează comutatorul Comenzi și alege ce câmpuri ale clientului (nume, telefon, adresă) să colectezi." },
  { title: "Alege canalul de livrare", desc: "Modul intern trimite comenzile noi în tab-ul Bucătărie. Modul WhatsApp formatează comanda ca mesaj pe WhatsApp-ul restaurantului. Sau ambele în paralel." },
  { title: "Tipărește și lipește QR", desc: "Descarcă QR (unul pe masă sau unul pe restaurant) în PDF sau PNG și lipește-l pe mese. Clienții scanează cu propria cameră — fără App Store, fără frecare." },
  { title: "Rulează tura", desc: "Comenzile apar în tab-ul Bucătărie cu număr de masă, preparate, variante, alergeni, comentariu și număr zilnic. Trecere nouă → în lucru → gata. Browserul clientului se actualizează în timp real." },
];
const COMPARISON_ROWS = [["Comision pe comandă","20–30%","0%","0% (€6,90/lună fix)"],["Unde ajunge comanda","Aplicația agregatorului","Casa ta","Tableta ta de bucătărie sau WhatsApp"],["Număr masă pe bon","Nu","Manual","Da, automat"],["Modificatori / variante","Limitate","Da","Da, cu alergeni"],["Checkout multilingv","Limba aplicației lor","Nu","35 de limbi, automat"],["Hardware necesar","Tableta agregatorului","Terminal POS","Orice tabletă cu browser"],["Timp de configurare","Apel onboarding","Zile-săptămâni","5 minute"]];

export function SeoContent() {
  return (<>
    <Section dataSection="seo-intro"><div className="max-w-4xl mx-auto"><p className="text-xs font-medium uppercase tracking-widest text-primary mb-3 text-center">În detaliu</p><h2 className="text-3xl sm:text-4xl lg:text-5xl font-medium tracking-tight mb-3 text-center">Ce este un sistem comenzi online pentru restaurant <span className="text-muted-foreground">de fapt</span></h2><p className="text-base sm:text-lg text-muted-foreground mb-10 text-center">Nu este marketplace. Nu este agregator de livrare. O linie directă de la telefonul clientului de la masa ta până la tableta de bucătărie — sau WhatsApp.</p><div className="space-y-4 text-base sm:text-lg text-foreground/90 leading-relaxed"><p><strong>Sistem comenzi online pentru restaurant</strong> în sensul IQ Rest este software care permite clientului de la masa ta să deschidă meniul pe telefon, să formeze un coș și să trimită comanda în bucătărie — fără Glovo, Tazz, Bolt Food sau alt marketplace. Clientul nu părăsește niciodată meniul tău QR, nu plătești comision pe comandă, iar bonul ajunge cu numărul real al mesei.</p><p>IQ Rest este construit în jurul a două canale. Implicit este <em>modul intern</em>: fiecare comandă nouă ajunge în tab-ul Bucătărie din panou pe o tabletă, telefon sau laptop lângă pas — cu număr de masă, preparate cu variante și alergeni, comentariu liber al clientului și numărul zilnic al comenzii. Alternativa este <em>modul WhatsApp</em>: aceeași comandă este formatată ca mesaj pe WhatsApp-ul restaurantului. Util pentru echipe mici, preponderent ridicare sau când managerul este în afara sălii. Ambele moduri pot rula simultan.</p></div></div></Section>
    <Section dataSection="seo-benefits"><div className="max-w-4xl mx-auto"><h3 className="text-2xl sm:text-3xl font-medium tracking-tight mb-6 text-center">Ce primești de fapt</h3><div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-3 sm:gap-4">{BENEFITS.map((b) => (<div key={b} className="bg-muted/20 border border-border rounded-2xl p-4 sm:p-5 flex flex-row items-center gap-3"><div className="h-8 w-8 rounded-lg bg-primary/10 text-primary flex items-center justify-center shrink-0"><Check className="h-4 w-4" strokeWidth={2.5} /></div><p className="text-sm sm:text-base text-foreground/90 leading-snug">{b}</p></div>))}</div></div></Section>
    <Section dataSection="seo-how"><div className="max-w-4xl mx-auto"><h3 className="text-2xl sm:text-3xl font-medium tracking-tight mb-6 text-center">Cum funcționează fluxul de comenzi IQ Rest</h3><p className="text-base sm:text-lg text-foreground/90 leading-relaxed mb-6 text-center">Patru comutatoare în panou — și ești live. Fără instalator, fără hardware POS, fără proiect de integrare.</p><div className="grid grid-cols-1 sm:grid-cols-2 gap-3 sm:gap-4">{HOW_STEPS.map((s, i) => (<div key={s.title} className="bg-muted/20 border border-border rounded-2xl p-5 flex flex-row items-start gap-4"><div className="h-10 w-10 rounded-lg bg-primary text-primary-foreground flex items-center justify-center shrink-0 font-semibold text-base">{i + 1}</div><div className="flex-1 min-w-0"><div className="text-base sm:text-lg font-semibold tracking-tight mb-1">{s.title}</div><p className="text-sm text-muted-foreground leading-relaxed">{s.desc}</p></div></div>))}</div></div></Section>
    <Section dataSection="seo-table"><div className="max-w-4xl mx-auto"><h3 className="text-2xl sm:text-3xl font-medium tracking-tight mb-6 text-center">Agregator, POS clasic sau sistem de comenzi</h3><div className="bg-muted/20 border border-border rounded-2xl p-4 sm:p-6 overflow-x-auto"><table className="w-full text-sm sm:text-base border-collapse"><thead><tr className="border-b border-border"><th className="text-left font-semibold py-3 pr-3 text-foreground">Caracteristică</th><th className="text-left font-semibold py-3 pr-3 text-muted-foreground">Agregator de livrare</th><th className="text-left font-semibold py-3 pr-3 text-muted-foreground">POS clasic</th><th className="text-left font-semibold py-3 text-primary">Comenzi IQ Rest</th></tr></thead><tbody className="text-foreground/90">{COMPARISON_ROWS.map((row, i) => (<tr key={row[0]} className={i < COMPARISON_ROWS.length - 1 ? "border-b border-border/50" : ""}><td className="py-3 pr-3 font-medium">{row[0]}</td><td className="py-3 pr-3 text-muted-foreground">{row[1]}</td><td className="py-3 pr-3 text-muted-foreground">{row[2]}</td><td className="py-3 text-foreground">{row[3]}</td></tr>))}</tbody></table></div><p className="text-sm text-muted-foreground leading-relaxed mt-6 text-center">Un sistem comenzi online deținut chiar de restaurant se amortizează în primul weekend — fiecare leu pe care clientul îl cheltuie în sala ta rămâne în sala ta, iar bonul lângă pas vine întotdeauna cu numărul real al mesei.</p></div></Section>
  </>);
}
