import { QrCode, MessageCircle, ChefHat, Settings2, Languages, BarChart3 } from "lucide-react";
import type { LandingTexts } from "@/app/_landing/types";

export const TEXTS: LandingTexts = {
  htmlLang: "ro",
  htmlDir: "ltr",
  meta: {
    title: "Sistem comenzi online pentru restaurant — QR și WhatsApp | IQ Rest",
    description: "Sistem comenzi online pentru restaurant: clientul scanează QR-ul de la masă, face comanda și ajunge direct pe tableta de bucătărie sau WhatsApp. Zero comision, cu număr de masă. 14 zile gratis.",
    canonical: "https://iq-rest.com/ro/sistem-comenzi-online-restaurant",
    ogLocale: "ro_RO",
    ogTitle: "Sistem comenzi online pentru restaurant — Direct în bucătărie",
    ogDescription: "Clientul scanează QR-ul de la masă, face comanda și ajunge pe tabletă sau WhatsApp — fără intermediar, fără comision, cu număr de masă pe fiecare bon.",
  },
  ctaText: "Activează comenzile",
  demoText: "Demo live",
  microcopy: "De la €6,90/lună · 14 zile gratis · Anulezi când vrei",
  header: { navFeatures: "Funcții", navHow: "Cum funcționează", navPricing: "Prețuri", navFaq: "Întrebări", signIn: "Conectare", cta: "Încearcă" },
  hero: {
    verticals: ["Restaurante", "Cafenele", "Bistrouri", "Pizzerii", "Baruri", "Berării"],
    headline: "Sistem comenzi online pentru restaurant.",
    sub: "Clientul scanează QR-ul mesei lui, face comanda pe telefon — și bonul ajunge direct pe tableta de bucătărie sau WhatsApp-ul restaurantului. Fără intermediar, fără comision, cu număr de masă pe fiecare bon.",
    dynamicHeadlines: ["Comandă la masă.", "Direct pe tableta de bucătărie.", "Sau direct pe WhatsApp.", "Zero comision.", "Cu număr de masă."],
    painBullets: [
      "Sistem comenzi online deținut chiar de restaurant — fără intermediari, fără comision.",
      "Comenzile ajung pe tableta de bucătărie sau a managerului cu număr de masă, modificatori, alergeni și note.",
      "Sau sunt trimise direct pe WhatsApp-ul restaurantului — ideal pentru ridicare și echipe mici.",
      "QR pentru fiecare masă (sau unul pentru toată sala) se generează automat.",
    ],
    rating: "500+ restaurante în 30+ țări",
  },
  features: {
    heading: "Sistem de comenzi,",
    headingAccent: "făcut pentru masă.",
    sub: "Funcționalitate reală — nu o clonă a agregatorilor de livrare.",
    items: [
      { Icon: QrCode, title: "Meniu QR cu coș pentru fiecare masă", desc: "Clientul scanează QR, răsfoiește meniul în limba lui, adaugă preparate cu modificatori, lasă o notă pentru bucătărie și trimite. Fără aplicație.", tag: "Comenzi QR" },
      { Icon: ChefHat, title: "Comenzi pe tableta de bucătărie", desc: "Fiecare comandă nouă apare în tab-ul Bucătărie — pe o tabletă lângă pas — cu număr de masă, preparate, variante, alergeni și comentariu. Un tap din „în lucru“ în „gata“.", tag: "Vizualizare bucătărie" },
      { Icon: MessageCircle, title: "Sau pe WhatsApp", desc: "Pune restaurantul în mod WhatsApp (sau ambele simultan) — fiecare comandă ajunge pe WhatsApp ca mesaj formatat. Ideal pentru ridicare sau echipe mici.", tag: "Mod WhatsApp" },
      { Icon: Settings2, title: "Modificatori, variante și alergeni", desc: "Fiecare preparat are grupuri de variante (mărime, gătit, extra) cu diferență de preț, etichete de alergeni și descriere liberă. Coșul calculează tot — bonul pe tabletă fără ambiguități.", tag: "Coș real" },
      { Icon: Languages, title: "Checkout multilingv", desc: "Tot fluxul comenzii — coș, modificatori, comentariu, confirmare — este tradus în 35 de limbi și se adaptează automat la limba telefonului clientului.", tag: "35 de limbi" },
      { Icon: BarChart3, title: "Numerotare zilnică și jurnal", desc: "Fiecare comandă primește un număr zilnic pentru bucătărie, intră în jurnal cu sume și marcaje de timp, alimentează analitica. Anulările sunt soft-delete, rapoartele rămân curate.", tag: "Jurnal comenzi" },
    ],
  },
  founder: {
    eyebrow: "Făcut de un proprietar de cafenea, nu de un startup de livrare",
    quoteStart: "Eu și soția mea am deschis o cafenea și am căutat săptămâni un mod de a primi comenzi la masă care să nu dea 30% unui agregator și să nu ceară o casă de 1500 €. Tot ce am încercat era greoi, scump sau lipseau lucrurile de bază —",
    quoteAccent: "așa că am construit sistemul de comenzi pe care îl voiam noi înșine.",
    sign: "Bogdan Sokolov · fondator, fost proprietar de cafenea",
    photoAlt: "Bogdan, fondatorul IQ Rest",
  },
  how: {
    heading: "Activează sistemul de comenzi",
    headingAccent: "în 4 pași",
    sub: "Fără instalare, fără integrator, fără apel către IT. Doar telefon și 5 minute.",
    steps: [
      { n: "1", t: "Creează restaurantul", d: "Înregistrare cu email sau Google — 30 secunde." },
      { n: "2", t: "Adaugă meniul", d: "Drag-and-drop sau scanare AI dintr-un meniu pe hârtie." },
      { n: "3", t: "Alege canalul", d: "Tabletă de bucătărie, WhatsApp sau ambele." },
      { n: "4", t: "Tipărește QR", d: "Un QR pe masă — clienții comandă imediat." },
    ],
  },
  pricing: {
    badge: "Comenzi nelimitate · Zero comision",
    heading: "Un singur plan.",
    headingAccent: "Fără taxă pe comandă.",
    sub: "Comenzi online, meniu QR, mod WhatsApp, checkout multilingv și analitică — totul într-un singur abonament. Fără procent din tranzacție.",
    monthlyLabel: "Lunar",
    yearlyLabel: "Anual",
    saveBadge: "Reducere 25%",
    perMonth: "pe lună",
    billedAnnually: "Facturat o dată pe an {total}",
    youSave: "Economisești {amount}",
    trust: { secure: "Abonament prin Stripe", noCommitment: "Fără angajamente", quick: "Activ în câteva minute", restaurants: "+500 restaurante" },
  },
  faq: {
    eyebrow: "Sistem de comenzi — întrebări frecvente",
    heading: "Despre sistemul",
    headingAccent: "de comenzi.",
    sub: "Ce întreabă proprietarii de restaurante înainte să activeze comenzi online pe IQ Rest. Nu vezi întrebarea ta? Scrie-ne pe WhatsApp — răspund oameni reali.",
    whatsappCta: "Întreabă pe WhatsApp",
    whatsappPrefill: "Salut, am o întrebare despre comenzile IQ Rest",
    items: [
      { q: "Este o platformă de livrare ca Glovo sau Tazz?", a: "Nu, exact asta e ideea. IQ Rest este canalul propriu de comenzi al restaurantului: clientul comandă din QR-ul tău, comanda ajunge pe tableta ta sau WhatsApp, tu servești. Fără marketplace, fără catalog de agregator — și nu luăm niciodată o parte din notă." },
      { q: "Unde apar comenzile exact?", a: "În tab-ul Bucătărie din panoul IQ Rest pe orice tabletă sau telefon de lângă pas sau bar. Fiecare comandă arată numărul mesei, preparatele cu variante și alergeni, comentariul clientului și numărul zilnic. Trecerea „nouă → în lucru → gata“ cu un tap." },
      { q: "Pot ajunge comenzile pe WhatsApp în loc?", a: "Da. Fiecare restaurant are trei moduri: intern (doar tableta de bucătărie), WhatsApp (comanda vine ca mesaj pe WhatsApp-ul restaurantului) sau ambele simultan. Modul este un comutator în panou, se schimbă oricând." },
      { q: "Ce conține comanda?", a: "Preparate cu variante și extra (cu diferență de preț), alergeni, număr de masă, comentariu liber al clientului și — dacă activezi câmpurile — nume, telefon și adresă. Suficient pentru a trimite un curier sau a suna la masă pentru un alergen." },
      { q: "Pot clienții să plătească online în meniu?", a: "În mod implicit — nu. IQ Rest este configurat pentru plată la masă: clientul comandă, tu aduci nota, se plătește ca de obicei. Dacă ai nevoie de plată online cu card (tipic pentru ridicare), integrarea Stripe Connect este posibilă la cerere — scrie pe WhatsApp." },
      { q: "Am nevoie de tabletă, imprimantă sau hardware POS special?", a: "Nu. Orice tabletă, laptop sau telefon cu browser — deschide panoul, autentifică-te, lasă tab-ul Bucătărie deschis. Dacă ai deja POS — IQ Rest rulează alături, nu înlocuiește casa." },
      { q: "Ce se întâmplă după 14 zile gratis?", a: "Fără metodă de plată contul se pune pe pauză — nu retragem niciodată automat. Meniul, comenzile și setările se păstrează; adaugi card oricând pentru reactivare. Anulezi cu un click, fără angajament." },
    ],
  },
  finalCta: {
    heading: "Activează sistemul de comenzi.",
    headingAccent: "Gata în 5 minute.",
    sub: "14 zile gratis, fără card. Anulezi când vrei. Alătură-te celor 500+ restaurante care își gestionează comenzile prin IQ Rest.",
  },
  scan: {
    heading: "De la meniu pe hârtie la sistem de comenzi",
    headingAccent: "în 60 de secunde",
    sub: "Încarcă o poză a meniului — AI extrage categorii, preparate și prețuri direct în editor. Apoi coș și QR — cu un click.",
    cta: "Scanează meniul →",
  },
  footer: {
    featureLinks: [
      { href: "/ro/ai-translation", label: "Traducere AI" },
      { href: "/ro/reservations", label: "Rezervări" },
      { href: "/ro/mobile-management", label: "Gestiune mobilă" },
      { href: "/ro/easy-menu", label: "Editor de meniu" },
      { href: "/ro/custom-design", label: "Fundal video și foto" },
      { href: "/ro/color-scheme", label: "Culori brand" },
      { href: "/ro/multilingual", label: "Meniu multilingv" },
      { href: "/ro/ai-images", label: "Optimizare foto AI" },
      { href: "/ro/analytics", label: "Analitică" },
      { href: "/ro/instant-setup", label: "Configurare instant" },
      { href: "/ro/personal-support", label: "Suport personal" },
    ],
    navLinks: [
      { href: "#pricing", label: "Prețuri" },
      { href: "#faq", label: "Întrebări" },
      { href: "/ro/changelog", label: "Noutăți" },
      { href: "/ro/languages", label: "Schimbă limba" },
    ],
    copyrightTemplate: "© {year} IQ Rest. Toate drepturile rezervate.",
  },
};
