import { Check } from "lucide-react";
import { Section } from "@/app/_landing/components/section";

const BENEFITS = ["QR ant kiekvieno stalo, nuskaityk-ir-užsakyk, be programėlės", "Užsakymai realiu laiku virtuvės ar vadovo planšetėje", "Arba į restorano WhatsApp — tu renkis", "Modifikacijos, variantai ir alergenai patenka į čekį", "Laisvas svečio komentaras kiekviename užsakyme", "Dienos numeravimas virtuvei", "Daugiakalbis checkout 35 kalbomis, pagal svečio telefoną", "Nulis komisinių už užsakymą — fiksuota mėnesinė prenumerata"];
const HOW_STEPS = [
  { title: "Įjunk restorano užsakymus", desc: "Atidaryk restorano nustatymus, aktyvuok jungiklį Užsakymai ir pasirink, kuriuos svečio laukus (vardas, telefonas, adresas) rinkti." },
  { title: "Pasirink pristatymo kanalą", desc: "Vidinis režimas siunčia naujus užsakymus į skiltį Virtuvė. WhatsApp režimas formatuoja užsakymą kaip pranešimą į restorano WhatsApp. Arba abu lygiagrečiai." },
  { title: "Atspausdink ir priklijuok QR", desc: "Atsisiųsk QR (vieną stalui arba vieną restoranui) PDF arba PNG formatu ir priklijuok prie stalų. Svečiai nuskaito sava kamera — be App Store, be trinties." },
  { title: "Pravesk pamainą", desc: "Užsakymai pasirodo skiltyje Virtuvė su stalo numeriu, patiekalais, variantais, alergenais, komentaru ir dienos numeriu. Perėjimas naujas → vykdoma → paruošta. Svečio naršyklė atsinaujina realiu laiku." },
];
const COMPARISON_ROWS = [["Komisinis už užsakymą","20–30%","0%","0% (€6,90/mėn fiksuotai)"],["Kur patenka užsakymas","Agregatoriaus programėlė","Tavo kasa","Tavo virtuvės planšetė arba WhatsApp"],["Stalo numeris ant čekio","Nėra","Rankiniu būdu","Taip, automatiškai"],["Modifikacijos / variantai","Riboti","Taip","Taip, su alergenais"],["Daugiakalbis checkout","Jų programėlės kalba","Nėra","35 kalbos, automatiškai"],["Reikalinga įranga","Agregatoriaus planšetė","POS terminalas","Bet kokia planšetė su naršykle"],["Nustatymo laikas","Onboarding skambutis","Dienos-savaitės","5 minutės"]];

export function SeoContent() {
  return (<>
    <Section dataSection="seo-intro"><div className="max-w-4xl mx-auto"><p className="text-xs font-medium uppercase tracking-widest text-primary mb-3 text-center">Išsamiai</p><h2 className="text-3xl sm:text-4xl lg:text-5xl font-medium tracking-tight mb-3 text-center">Kas yra internetinė užsakymų sistema restoranui <span className="text-muted-foreground">iš tikrųjų</span></h2><p className="text-base sm:text-lg text-muted-foreground mb-10 text-center">Ne marketplace. Ne pristatymo agregatorius. Tiesi linija nuo svečio telefono prie tavo stalo iki virtuvės planšetės — arba WhatsApp.</p><div className="space-y-4 text-base sm:text-lg text-foreground/90 leading-relaxed"><p><strong>Internetinė užsakymų sistema restoranui</strong> IQ Rest prasme yra programinė įranga, leidžianti svečiui prie tavo stalo atidaryti meniu telefone, sudaryti krepšelį ir siųsti užsakymą į virtuvę — be Wolt, Bolt Food ar kito marketplace. Svečias niekada nepalieka tavo QR meniu, tu nemoki komisinių už užsakymą, ir čekis ateina su tikru stalo numeriu.</p><p>IQ Rest pastatytas aplink du kanalus. Pagal numatytuosius yra <em>vidinis režimas</em>: kiekvienas naujas užsakymas patenka į skiltį Virtuvė pulte planšetėje, telefone ar nešiojamame kompiuteryje šalia paso — su stalo numeriu, patiekalais su variantais ir alergenais, laisvu svečio komentaru ir dienos užsakymo numeriu. Alternatyva yra <em>WhatsApp režimas</em>: tas pats užsakymas formatuojamas kaip pranešimas į restorano WhatsApp. Naudinga mažoms komandoms, daugiausia atsiimti arba kai vadovas ne salėje. Abu režimai gali veikti vienu metu.</p></div></div></Section>
    <Section dataSection="seo-benefits"><div className="max-w-4xl mx-auto"><h3 className="text-2xl sm:text-3xl font-medium tracking-tight mb-6 text-center">Ką iš tikrųjų gauni</h3><div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-3 sm:gap-4">{BENEFITS.map((b) => (<div key={b} className="bg-muted/20 border border-border rounded-2xl p-4 sm:p-5 flex flex-row items-center gap-3"><div className="h-8 w-8 rounded-lg bg-primary/10 text-primary flex items-center justify-center shrink-0"><Check className="h-4 w-4" strokeWidth={2.5} /></div><p className="text-sm sm:text-base text-foreground/90 leading-snug">{b}</p></div>))}</div></div></Section>
    <Section dataSection="seo-how"><div className="max-w-4xl mx-auto"><h3 className="text-2xl sm:text-3xl font-medium tracking-tight mb-6 text-center">Kaip veikia IQ Rest užsakymų srautas</h3><p className="text-base sm:text-lg text-foreground/90 leading-relaxed mb-6 text-center">Keturi jungikliai pulte — ir tu eteryje. Be diegimo specialisto, be POS įrangos, be integracijos projekto.</p><div className="grid grid-cols-1 sm:grid-cols-2 gap-3 sm:gap-4">{HOW_STEPS.map((s, i) => (<div key={s.title} className="bg-muted/20 border border-border rounded-2xl p-5 flex flex-row items-start gap-4"><div className="h-10 w-10 rounded-lg bg-primary text-primary-foreground flex items-center justify-center shrink-0 font-semibold text-base">{i + 1}</div><div className="flex-1 min-w-0"><div className="text-base sm:text-lg font-semibold tracking-tight mb-1">{s.title}</div><p className="text-sm text-muted-foreground leading-relaxed">{s.desc}</p></div></div>))}</div></div></Section>
    <Section dataSection="seo-table"><div className="max-w-4xl mx-auto"><h3 className="text-2xl sm:text-3xl font-medium tracking-tight mb-6 text-center">Agregatorius, klasikinis POS ar užsakymų sistema</h3><div className="bg-muted/20 border border-border rounded-2xl p-4 sm:p-6 overflow-x-auto"><table className="w-full text-sm sm:text-base border-collapse"><thead><tr className="border-b border-border"><th className="text-left font-semibold py-3 pr-3 text-foreground">Savybė</th><th className="text-left font-semibold py-3 pr-3 text-muted-foreground">Pristatymo agregatorius</th><th className="text-left font-semibold py-3 pr-3 text-muted-foreground">Klasikinis POS</th><th className="text-left font-semibold py-3 text-primary">IQ Rest užsakymai</th></tr></thead><tbody className="text-foreground/90">{COMPARISON_ROWS.map((row, i) => (<tr key={row[0]} className={i < COMPARISON_ROWS.length - 1 ? "border-b border-border/50" : ""}><td className="py-3 pr-3 font-medium">{row[0]}</td><td className="py-3 pr-3 text-muted-foreground">{row[1]}</td><td className="py-3 pr-3 text-muted-foreground">{row[2]}</td><td className="py-3 text-foreground">{row[3]}</td></tr>))}</tbody></table></div><p className="text-sm text-muted-foreground leading-relaxed mt-6 text-center">Internetinė užsakymų sistema, kurią restoranas valdo pats, atsiperka per pirmąjį savaitgalį — kiekvienas euras, kurį svečias išleidžia tavo salėje, lieka tavo salėje, o čekis šalia paso visada su tikru stalo numeriu.</p></div></Section>
  </>);
}
