import { QrCode, MessageCircle, ChefHat, Settings2, Languages, BarChart3 } from "lucide-react";
import type { LandingTexts } from "@/app/_landing/types";

export const TEXTS: LandingTexts = {
  htmlLang: "lt",
  htmlDir: "ltr",
  meta: {
    title: "Internetinė užsakymų sistema restoranui — QR ir WhatsApp | IQ Rest",
    description: "Internetinė užsakymų sistema restoranui: svečias nuskaito QR prie stalo, sudaro užsakymą ir jis tiesiai patenka į virtuvės planšetę arba WhatsApp. Nulis komisinių, su stalo numeriu. 14 dienų nemokamai.",
    canonical: "https://iq-rest.com/lt/internetine-uzsakymu-sistema-restoranui",
    ogLocale: "lt_LT",
    ogTitle: "Internetinė užsakymų sistema restoranui — Tiesiai į virtuvę",
    ogDescription: "Svečias nuskaito QR prie stalo, sudaro užsakymą ir jis patenka į planšetę arba WhatsApp — be tarpininko, be komisinių, su stalo numeriu kiekviename čekyje.",
  },
  ctaText: "Įjungti užsakymus",
  demoText: "Tiesioginė demo",
  microcopy: "Nuo €6,90/mėn · 14 dienų nemokamai · Atšauk bet kada",
  header: { navFeatures: "Funkcijos", navHow: "Kaip veikia", navPricing: "Kainos", navFaq: "FAQ", signIn: "Prisijungti", cta: "Išbandyk" },
  hero: {
    verticals: ["Restoranai", "Kavinės", "Bistro", "Picerijos", "Barai", "Aludės"],
    headline: "Internetinė užsakymų sistema restoranui.",
    sub: "Svečias nuskaito savo stalo QR, sudaro užsakymą telefone — ir čekis patenka tiesiai į virtuvės planšetę arba restorano WhatsApp. Be tarpininko, be komisinių, su stalo numeriu kiekviename čekyje.",
    dynamicHeadlines: ["Užsakymas prie stalo.", "Tiesiai į virtuvės planšetę.", "Arba tiesiai į WhatsApp.", "Nulis komisinių.", "Su stalo numeriu."],
    painBullets: [
      "Internetinė užsakymų sistema, kurią restoranas valdo pats — be tarpininkų, be komisinių.",
      "Užsakymai patenka į virtuvės ar vadovo planšetę su stalo numeriu, modifikacijomis, alergenais ir pastabomis.",
      "Arba siunčiami tiesiai į restorano WhatsApp — idealu atsiimti ir mažoms komandoms.",
      "QR kiekvienam stalui (arba vienas visai salei) generuojamas automatiškai.",
    ],
    rating: "500+ restoranų 30+ šalyse",
  },
  features: {
    heading: "Užsakymų sistema,",
    headingAccent: "sukurta stalui.",
    sub: "Tikras funkcionalumas — ne pristatymo agregatorių klonas.",
    items: [
      { Icon: QrCode, title: "QR meniu su krepšeliu kiekvienam stalui", desc: "Svečias nuskaito QR, naršo meniu sava kalba, prideda patiekalų su modifikacijomis, palieka pastabą virtuvei ir siunčia. Be programėlės.", tag: "QR užsakymai" },
      { Icon: ChefHat, title: "Užsakymai virtuvės planšetėje", desc: "Kiekvienas naujas užsakymas pasirodo skiltyje Virtuvė — planšetėje šalia paso — su stalo numeriu, patiekalais, variantais, alergenais ir komentaru. Vienu palietimu nuo „vykdoma“ iki „paruošta“.", tag: "Virtuvės vaizdas" },
      { Icon: MessageCircle, title: "Arba į WhatsApp", desc: "Įjunk restoraną WhatsApp režime (arba abu vienu metu) — kiekvienas užsakymas ateina į WhatsApp kaip suformatuotas pranešimas. Idealu atsiimti arba mažoms komandoms.", tag: "WhatsApp režimas" },
      { Icon: Settings2, title: "Modifikacijos, variantai ir alergenai", desc: "Kiekvienas patiekalas turi variantų grupes (dydis, kepimas, priedai) su kainos skirtumu, alergenų žymas ir laisvą aprašymą. Krepšelis viską suskaičiuoja — čekis planšetėje be dviprasmiškumo.", tag: "Tikras krepšelis" },
      { Icon: Languages, title: "Daugiakalbis checkout", desc: "Visas užsakymo srautas — krepšelis, modifikacijos, komentaras, patvirtinimas — išverstas į 35 kalbas ir automatiškai prisitaiko prie svečio telefono kalbos.", tag: "35 kalbos" },
      { Icon: BarChart3, title: "Dienos numeravimas ir žurnalas", desc: "Kiekvienas užsakymas gauna dienos numerį virtuvei, patenka į žurnalą su sumomis ir laiko žymėmis, maitina analitiką. Atšaukimai yra soft-delete, ataskaitos lieka švarios.", tag: "Užsakymų žurnalas" },
    ],
  },
  founder: {
    eyebrow: "Sukurta kavinės savininko, ne pristatymo startuolio",
    quoteStart: "Su žmona atidarėme kavinę ir savaites ieškojome būdo priimti užsakymus prie stalo, kuris neduotų 30% agregatui ir nereikalautų 1500 € kasos. Viskas, ką bandėme, buvo gremėzdiška, brangu arba trūko pagrindinių dalykų —",
    quoteAccent: "todėl pasistatėme užsakymų sistemą, kurios patys norėjome.",
    sign: "Bogdan Sokolov · įkūrėjas, buvęs kavinės savininkas",
    photoAlt: "Bogdan, IQ Rest įkūrėjas",
  },
  how: {
    heading: "Įjunk užsakymų sistemą",
    headingAccent: "per 4 žingsnius",
    sub: "Be diegimo, be integratoriaus, be skambučio IT. Tik telefonas ir 5 minutės.",
    steps: [
      { n: "1", t: "Sukurk restoraną", d: "Registracija el. paštu arba Google — 30 sekundžių." },
      { n: "2", t: "Pridėk meniu", d: "Drag-and-drop arba AI skenavimas iš popierinio meniu." },
      { n: "3", t: "Pasirink kanalą", d: "Virtuvės planšetė, WhatsApp arba abu." },
      { n: "4", t: "Atspausdink QR", d: "Vienas QR stalui — svečiai užsako iškart." },
    ],
  },
  pricing: {
    badge: "Neriboti užsakymai · Nulis komisinių",
    heading: "Vienas planas.",
    headingAccent: "Be mokesčio už užsakymą.",
    sub: "Internetiniai užsakymai, QR meniu, WhatsApp režimas, daugiakalbis checkout ir analitika — viskas vienoje prenumeratoje. Be procento nuo sandorio.",
    monthlyLabel: "Mėnesinis",
    yearlyLabel: "Metinis",
    saveBadge: "Sutaupyk 25%",
    perMonth: "per mėnesį",
    billedAnnually: "Sąskaita kartą per metus {total}",
    youSave: "Sutaupai {amount}",
    trust: { secure: "Prenumerata per Stripe", noCommitment: "Be įsipareigojimų", quick: "Aktyvi per minutes", restaurants: "+500 restoranų" },
  },
  faq: {
    eyebrow: "Užsakymų sistema — dažni klausimai",
    heading: "Apie užsakymų",
    headingAccent: "sistemą.",
    sub: "Ką restoranų savininkai klausia prieš įjungdami internetinius užsakymus IQ Rest. Nematai savo klausimo? Rašyk WhatsApp — atsako tikri žmonės.",
    whatsappCta: "Klausk WhatsApp",
    whatsappPrefill: "Sveiki, turiu klausimą apie IQ Rest užsakymus",
    items: [
      { q: "Ar tai pristatymo platforma kaip Wolt ar Bolt Food?", a: "Ne, kaip tik tai esmė. IQ Rest yra restorano nuosavas užsakymų kanalas: svečias užsako iš tavo QR, užsakymas patenka į tavo planšetę arba WhatsApp, tu patiekai. Be marketplace, be agregatoriaus katalogo — ir niekada neimame dalies sąskaitos." },
      { q: "Kur tiksliai atsiranda užsakymai?", a: "Skiltyje Virtuvė IQ Rest pulte bet kurioje planšetėje arba telefone šalia paso ar baro. Kiekvienas užsakymas rodo stalo numerį, patiekalus su variantais ir alergenais, svečio komentarą ir dienos numerį. Perėjimas „naujas → vykdoma → paruošta“ vienu palietimu." },
      { q: "Ar užsakymai gali ateiti į WhatsApp vietoj to?", a: "Taip. Kiekvienas restoranas turi tris režimus: vidinis (tik virtuvės planšetė), WhatsApp (užsakymas ateina kaip pranešimas į restorano WhatsApp) arba abu vienu metu. Režimas yra vienas jungiklis pulte, keičiasi bet kada." },
      { q: "Ką sudaro užsakymas?", a: "Patiekalai su variantais ir priedais (su kainos skirtumu), alergenai, stalo numeris, laisvas svečio komentaras ir — jei įjungsi laukus — vardas, telefonas ir adresas. Pakanka kurjeriui išsiųsti arba atgal skambinti į stalą dėl alergeno." },
      { q: "Ar svečiai gali mokėti internetu meniu?", a: "Pagal numatytuosius nustatymus — ne. IQ Rest sukurtas mokėjimui prie stalo: svečias užsako, tu atneši sąskaitą, mokama kaip įprasta. Jei reikia internetinio mokėjimo kortele (tipinis atsiėmimui), Stripe Connect integracija galima pagal pageidavimą — rašyk WhatsApp." },
      { q: "Ar reikia specialios planšetės, spausdintuvo ar POS įrangos?", a: "Ne. Bet kokia planšetė, nešiojamas kompiuteris ar telefonas su naršykle — atidarysk pultą, prisijunk, palik atvirą skiltį Virtuvė. Jei jau turi POS — IQ Rest veikia greta, nepakeičia kasos." },
      { q: "Kas po 14 nemokamų dienų?", a: "Be mokėjimo būdo paskyra sustabdoma — niekada nesinuskaitome automatiškai. Meniu, užsakymai ir nustatymai išsaugomi; pridedi kortelę kada nori atnaujinti. Atšaukimas vienu paspaudimu, be įsipareigojimų." },
    ],
  },
  finalCta: {
    heading: "Įjunk užsakymų sistemą.",
    headingAccent: "Paruošta per 5 minutes.",
    sub: "14 dienų nemokamai, be kortelės. Atšauk bet kada. Prisijunk prie 500+ restoranų, kurie valdo savo užsakymus per IQ Rest.",
  },
  scan: {
    heading: "Iš popierinio meniu į užsakymų sistemą",
    headingAccent: "per 60 sekundžių",
    sub: "Įkelk meniu nuotrauką — AI ištraukia kategorijas, patiekalus ir kainas tiesiai į redaktorių. Tada krepšelis ir QR — vienu paspaudimu.",
    cta: "Skenuoti meniu →",
  },
  footer: {
    featureLinks: [
      { href: "/lt/ai-translation", label: "AI vertimas" },
      { href: "/lt/reservations", label: "Rezervacijos" },
      { href: "/lt/mobile-management", label: "Mobilus valdymas" },
      { href: "/lt/easy-menu", label: "Meniu redaktorius" },
      { href: "/lt/custom-design", label: "Video ir foto fonai" },
      { href: "/lt/color-scheme", label: "Prekės ženklo spalvos" },
      { href: "/lt/multilingual", label: "Daugiakalbis meniu" },
      { href: "/lt/ai-images", label: "AI nuotraukų optimizavimas" },
      { href: "/lt/analytics", label: "Analitika" },
      { href: "/lt/instant-setup", label: "Akimirksnio nustatymas" },
      { href: "/lt/personal-support", label: "Asmeninė pagalba" },
    ],
    navLinks: [
      { href: "#pricing", label: "Kainos" },
      { href: "#faq", label: "Klausimai" },
      { href: "/lt/changelog", label: "Naujienos" },
      { href: "/lt/languages", label: "Pakeisti kalbą" },
    ],
    copyrightTemplate: "© {year} IQ Rest. Visos teisės saugomos.",
  },
};
