import { Check } from "lucide-react";
import { Section } from "@/app/_landing/components/section";

const BENEFITS = ["QR на всяка маса, сканирай-и-поръчвай, без приложение", "Поръчки в реално време на таблет на кухнята или мениджъра", "Или в WhatsApp на ресторанта — вие избирате", "Модификатори, варианти и алергени влизат в тикета", "Свободен коментар на госта във всяка поръчка", "Дневна номерация за кухнята", "Многоезичен checkout на 35 езика, спрямо телефона на госта", "Нула комисиона от поръчка — фиксиран месечен абонамент"];
const HOW_STEPS = [
  { title: "Активирайте поръчките за ресторанта", desc: "Отворете настройките на ресторанта, активирайте превключвателя Поръчки и изберете кои полета на госта (име, телефон, адрес) да се събират." },
  { title: "Изберете канал за доставка", desc: "Вътрешният режим изпраща новите поръчки в таб Кухня. Режим WhatsApp форматира поръчката като съобщение в WhatsApp на ресторанта. Или двата паралелно." },
  { title: "Отпечатайте и залепете QR", desc: "Изтеглете QR (един на маса или един на ресторант) в PDF или PNG и залепете на масите. Гостите сканират със собствената камера — без App Store, без триене." },
  { title: "Работете смяна", desc: "Поръчките се появяват в таб Кухня с номер на маса, ястия, варианти, алергени, коментар и дневен номер. Преход нова → в работа → готово. Браузърът на госта се обновява в реално време." },
];
const COMPARISON_ROWS = [["Комисиона от поръчка","20–30%","0%","0% (€6,90/мес фикс)"],["Къде отива поръчката","Приложение на агрегатора","Вашата каса","Вашият кухненски таблет или WhatsApp"],["Номер на маса в тикета","Няма","Ръчно","Да, автоматично"],["Модификатори / варианти","Ограничено","Да","Да, с алергени"],["Многоезичен checkout","Език на тяхното приложение","Няма","35 езика, автоматично"],["Необходим хардуер","Таблет на агрегатора","POS терминал","Всеки таблет с браузър"],["Време за настройка","Onboarding обаждане","Дни-седмици","5 минути"]];

export function SeoContent() {
  return (<>
    <Section dataSection="seo-intro"><div className="max-w-4xl mx-auto"><p className="text-xs font-medium uppercase tracking-widest text-primary mb-3 text-center">Подробно</p><h2 className="text-3xl sm:text-4xl lg:text-5xl font-medium tracking-tight mb-3 text-center">Какво е система за онлайн поръчки за ресторант <span className="text-muted-foreground">наистина</span></h2><p className="text-base sm:text-lg text-muted-foreground mb-10 text-center">Не marketplace. Не агрегатор за доставка. Директна линия от телефона на госта на вашата маса до кухненския таблет — или в WhatsApp.</p><div className="space-y-4 text-base sm:text-lg text-foreground/90 leading-relaxed"><p><strong>Система за онлайн поръчки за ресторант</strong> в смисъла на IQ Rest е софтуер, който позволява на госта на вашата маса да отвори менюто на телефона си, да събере кошница и да изпрати поръчка в кухнята — без Uber Eats, Foodpanda, Wolt или какъвто и да е друг marketplace. Гостът не напуска вашето QR меню, вие не плащате комисиона от поръчка и тикетът пристига с истинския номер на маса.</p><p>IQ Rest е изграден около два канала. По подразбиране <em>вътрешен режим</em>: всяка нова поръчка пристига в таб Кухня на панела на таблет, телефон или лаптоп до пас-а — с номер на маса, ястия с варианти и алергени, свободен коментар на госта и дневен номер на поръчката. Алтернативата е <em>режим WhatsApp</em>: същата поръчка се форматира като съобщение в WhatsApp на ресторанта. Полезно за малки екипи, основно вземане или когато мениджърът е извън залата. Двата режима могат да работят едновременно.</p></div></div></Section>
    <Section dataSection="seo-benefits"><div className="max-w-4xl mx-auto"><h3 className="text-2xl sm:text-3xl font-medium tracking-tight mb-6 text-center">Какво реално получавате</h3><div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-3 sm:gap-4">{BENEFITS.map((b) => (<div key={b} className="bg-muted/20 border border-border rounded-2xl p-4 sm:p-5 flex flex-row items-center gap-3"><div className="h-8 w-8 rounded-lg bg-primary/10 text-primary flex items-center justify-center shrink-0"><Check className="h-4 w-4" strokeWidth={2.5} /></div><p className="text-sm sm:text-base text-foreground/90 leading-snug">{b}</p></div>))}</div></div></Section>
    <Section dataSection="seo-how"><div className="max-w-4xl mx-auto"><h3 className="text-2xl sm:text-3xl font-medium tracking-tight mb-6 text-center">Как работи потокът на поръчките в IQ Rest</h3><p className="text-base sm:text-lg text-foreground/90 leading-relaxed mb-6 text-center">Четири превключвателя в панела — и сте в ефир. Без инсталатор, без POS хардуер, без проект за интеграция.</p><div className="grid grid-cols-1 sm:grid-cols-2 gap-3 sm:gap-4">{HOW_STEPS.map((s, i) => (<div key={s.title} className="bg-muted/20 border border-border rounded-2xl p-5 flex flex-row items-start gap-4"><div className="h-10 w-10 rounded-lg bg-primary text-primary-foreground flex items-center justify-center shrink-0 font-semibold text-base">{i + 1}</div><div className="flex-1 min-w-0"><div className="text-base sm:text-lg font-semibold tracking-tight mb-1">{s.title}</div><p className="text-sm text-muted-foreground leading-relaxed">{s.desc}</p></div></div>))}</div></div></Section>
    <Section dataSection="seo-table"><div className="max-w-4xl mx-auto"><h3 className="text-2xl sm:text-3xl font-medium tracking-tight mb-6 text-center">Агрегатор, класически POS или система за поръчки</h3><div className="bg-muted/20 border border-border rounded-2xl p-4 sm:p-6 overflow-x-auto"><table className="w-full text-sm sm:text-base border-collapse"><thead><tr className="border-b border-border"><th className="text-left font-semibold py-3 pr-3 text-foreground">Характеристика</th><th className="text-left font-semibold py-3 pr-3 text-muted-foreground">Агрегатор за доставка</th><th className="text-left font-semibold py-3 pr-3 text-muted-foreground">Класически POS</th><th className="text-left font-semibold py-3 text-primary">Поръчки на IQ Rest</th></tr></thead><tbody className="text-foreground/90">{COMPARISON_ROWS.map((row, i) => (<tr key={row[0]} className={i < COMPARISON_ROWS.length - 1 ? "border-b border-border/50" : ""}><td className="py-3 pr-3 font-medium">{row[0]}</td><td className="py-3 pr-3 text-muted-foreground">{row[1]}</td><td className="py-3 pr-3 text-muted-foreground">{row[2]}</td><td className="py-3 text-foreground">{row[3]}</td></tr>))}</tbody></table></div><p className="text-sm text-muted-foreground leading-relaxed mt-6 text-center">Система за онлайн поръчки, която ресторантът притежава сам, се изплаща за първия уикенд — всеки лев, който гостът харчи във вашата зала, остава във вашата зала, а тикетът до пас-а винаги е с истински номер на маса.</p></div></Section>
  </>);
}
