import { Check } from "lucide-react";
import { Section } from "@/app/_landing/components/section";

const BENEFITS = ["QR uz katra galdiņa, skenē-un-pasūti, bez aplikācijas", "Pasūtījumi reāllaikā uz virtuves vai vadītāja planšetes", "Vai uz restorāna WhatsApp — tu izvēlies", "Modifikatori, varianti un alergēni nonāk čekā", "Brīvs viesa komentārs katrā pasūtījumā", "Dienas numerācija virtuvei", "Daudzvalodu checkout 35 valodās, pēc viesa telefona", "Nulle komisijas par pasūtījumu — fiksēts mēneša abonements"];
const HOW_STEPS = [
  { title: "Ieslēdz restorāna pasūtījumus", desc: "Atver restorāna iestatījumus, aktivizē slēdzi Pasūtījumi un izvēlies, kurus viesa laukus (vārds, telefons, adrese) vākt." },
  { title: "Izvēlies piegādes kanālu", desc: "Iekšējais režīms sūta jaunus pasūtījumus uz cilni Virtuve. WhatsApp režīms formatē pasūtījumu kā ziņojumu restorāna WhatsApp. Vai abus paralēli." },
  { title: "Izdrukā un pielīmē QR", desc: "Lejupielādē QR (vienu uz galdiņu vai vienu uz restorānu) PDF vai PNG un pielīmē pie galdiņiem. Viesi skenē ar savu kameru — bez App Store, bez berzes." },
  { title: "Strādā maiņu", desc: "Pasūtījumi parādās cilnē Virtuve ar galdiņa numuru, ēdieniem, variantiem, alergēniem, komentāru un dienas numuru. Pāreja jauns → procesā → gatavs. Viesa pārlūks atjaunojas reāllaikā." },
];
const COMPARISON_ROWS = [["Komisija par pasūtījumu","20–30%","0%","0% (€6,90/mēn fiksēts)"],["Kur pasūtījums nonāk","Agregatora aplikācija","Tava kase","Tava virtuves planšete vai WhatsApp"],["Galdiņa numurs uz čeka","Nav","Manuāli","Jā, automātiski"],["Modifikatori / varianti","Ierobežoti","Jā","Jā, ar alergēniem"],["Daudzvalodu checkout","Viņu aplikācijas valoda","Nav","35 valodas, automātiski"],["Nepieciešama aparatūra","Agregatora planšete","POS terminālis","Jebkura planšete ar pārlūku"],["Iestatīšanas laiks","Onboarding zvans","Dienas-nedēļas","5 minūtes"]];

export function SeoContent() {
  return (<>
    <Section noContainer dataSection="seo-intro"><div className="w-full"><p className="text-xs font-medium uppercase tracking-widest text-primary mb-3 text-start">Detalizēti</p><h2 className="text-3xl sm:text-4xl lg:text-5xl font-medium tracking-tight mb-3 text-start">Kas ir tiešsaistes pasūtījumu sistēma restorānam <span className="text-muted-foreground">patiesībā</span></h2><p className="text-base sm:text-lg text-muted-foreground mb-10 text-start">Nav marketplace. Nav piegādes agregators. Tieša līnija no viesa telefona pie tava galdiņa līdz virtuves planšetei — vai WhatsApp.</p><div className="space-y-4 text-base sm:text-lg text-foreground/90 leading-relaxed"><p><strong>Tiešsaistes pasūtījumu sistēma restorānam</strong> IQ Rest izpratnē ir programmatūra, kas ļauj viesim pie tava galdiņa atvērt ēdienkarti telefonā, izveidot grozu un nosūtīt pasūtījumu uz virtuvi — bez Wolt, Bolt Food vai cita marketplace. Viesis nekad nepamet tavu QR ēdienkarti, tu nemaksā komisiju par pasūtījumu, un čeks nāk ar īstu galdiņa numuru.</p><p>IQ Rest ir uzbūvēts ap diviem kanāliem. Pēc noklusējuma ir <em>iekšējais režīms</em>: katrs jauns pasūtījums nonāk cilnē Virtuve panelī uz planšetes, telefona vai klēpjdatora pie pasa — ar galdiņa numuru, ēdieniem ar variantiem un alergēniem, brīvu viesa komentāru un dienas pasūtījuma numuru. Alternatīva ir <em>WhatsApp režīms</em>: tas pats pasūtījums tiek formatēts kā ziņojums restorāna WhatsApp. Noderīgs mazām komandām, galvenokārt paņemšanai vai kad vadītājs nav zālē. Abi režīmi var darboties vienlaicīgi.</p></div></div></Section>
    <Section noContainer dataSection="seo-benefits"><div className="w-full"><h3 className="text-2xl sm:text-3xl font-medium tracking-tight mb-6 text-start">Ko tu reāli iegūsti</h3><div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-3 sm:gap-4">{BENEFITS.map((b) => (<div key={b} className="bg-muted/20 border border-border rounded-2xl p-4 sm:p-5 flex flex-row items-center gap-3"><div className="h-8 w-8 rounded-lg bg-primary/10 text-primary flex items-center justify-center shrink-0"><Check className="h-4 w-4" strokeWidth={2.5} /></div><p className="text-sm sm:text-base text-foreground/90 leading-snug">{b}</p></div>))}</div></div></Section>
    <Section noContainer dataSection="seo-how"><div className="w-full"><h3 className="text-2xl sm:text-3xl font-medium tracking-tight mb-6 text-start">Kā darbojas IQ Rest pasūtījumu plūsma</h3><p className="text-base sm:text-lg text-foreground/90 leading-relaxed mb-6 text-start">Četri slēdži panelī — un tu ēterā. Bez uzstādītāja, bez POS aparatūras, bez integrācijas projekta.</p><div className="grid grid-cols-1 sm:grid-cols-2 gap-3 sm:gap-4">{HOW_STEPS.map((s, i) => (<div key={s.title} className="bg-muted/20 border border-border rounded-2xl p-5 flex flex-row items-start gap-4"><div className="h-10 w-10 rounded-lg bg-primary text-primary-foreground flex items-center justify-center shrink-0 font-semibold text-base">{i + 1}</div><div className="flex-1 min-w-0"><div className="text-base sm:text-lg font-semibold tracking-tight mb-1">{s.title}</div><p className="text-sm text-muted-foreground leading-relaxed">{s.desc}</p></div></div>))}</div></div></Section>
    <Section noContainer dataSection="seo-table"><div className="w-full"><h3 className="text-2xl sm:text-3xl font-medium tracking-tight mb-6 text-start">Agregators, klasiskais POS vai pasūtījumu sistēma</h3><div className="bg-muted/20 border border-border rounded-2xl p-4 sm:p-6 overflow-x-auto"><table className="w-full text-sm sm:text-base border-collapse"><thead><tr className="border-b border-border"><th className="text-left font-semibold py-3 pr-3 text-foreground">Īpašība</th><th className="text-left font-semibold py-3 pr-3 text-muted-foreground">Piegādes agregators</th><th className="text-left font-semibold py-3 pr-3 text-muted-foreground">Klasiskais POS</th><th className="text-left font-semibold py-3 text-primary">IQ Rest pasūtījumi</th></tr></thead><tbody className="text-foreground/90">{COMPARISON_ROWS.map((row, i) => (<tr key={row[0]} className={i < COMPARISON_ROWS.length - 1 ? "border-b border-border/50" : ""}><td className="py-3 pr-3 font-medium">{row[0]}</td><td className="py-3 pr-3 text-muted-foreground">{row[1]}</td><td className="py-3 pr-3 text-muted-foreground">{row[2]}</td><td className="py-3 text-foreground">{row[3]}</td></tr>))}</tbody></table></div><p className="text-sm text-muted-foreground leading-relaxed mt-6 text-start">Tiešsaistes pasūtījumu sistēma, kas pieder pašam restorānam, atmaksājas pirmajā nedēļas nogalē — katrs eiro, ko viesis tērē tavā zālē, paliek tavā zālē, un čeks pie pasa vienmēr ar īstu galdiņa numuru.</p></div></Section>
  </>);
}
