import { QrCode, MessageCircle, ChefHat, Settings2, Languages, BarChart3 } from "lucide-react";
import type { LandingTexts } from "@/app/_landing/types";

export const TEXTS: LandingTexts = {
  htmlLang: "lv",
  htmlDir: "ltr",
  meta: {
    title: "Tiešsaistes pasūtījumu sistēma restorānam — QR un WhatsApp | IQ Rest",
    description: "Tiešsaistes pasūtījumu sistēma restorānam: viesis skenē QR pie galdiņa, izveido pasūtījumu un tas nonāk tieši uz virtuves planšeti vai WhatsApp. Nulle komisijas, ar galdiņa numuru. 14 dienas bez maksas.",
    canonical: "https://iq-rest.com/lv/tiessaistes-pasutijumu-sistema-restoranam",
    ogLocale: "lv_LV",
    ogTitle: "Tiešsaistes pasūtījumu sistēma restorānam — Tieši uz virtuvi",
    ogDescription: "Viesis skenē QR pie galdiņa, izveido pasūtījumu un tas nonāk uz planšeti vai WhatsApp — bez starpnieka, bez komisijas, ar galdiņa numuru uz katra čeka.",
  },
  ctaText: "Ieslēgt pasūtījumus",
  demoText: "Demo tiešraidē",
  microcopy: "No €6,90/mēn · 14 dienas bez maksas · Atceltu jebkurā brīdī",
  header: { navFeatures: "Funkcijas", navHow: "Kā darbojas", navPricing: "Cenas", navFaq: "FAQ", signIn: "Pieslēgties", cta: "Pamēģini" },
  hero: {
    verticals: ["Restorāni", "Kafejnīcas", "Bistro", "Picērijas", "Bāri", "Alus bāri"],
    headline: "Tiešsaistes pasūtījumu sistēma restorānam.",
    sub: "Viesis skenē sava galdiņa QR, izveido pasūtījumu telefonā — un čeks nonāk tieši uz virtuves planšeti vai restorāna WhatsApp. Bez starpnieka, bez komisijas, ar galdiņa numuru uz katra čeka.",
    dynamicHeadlines: ["Pasūtījums pie galdiņa.", "Tieši uz virtuves planšeti.", "Vai tieši WhatsApp.", "Nulle komisijas.", "Ar galdiņa numuru."],
    painBullets: [
      "Tiešsaistes pasūtījumu sistēma, kas pieder pašam restorānam — bez starpniekiem, bez komisijas.",
      "Pasūtījumi nonāk uz virtuves vai vadītāja planšeti ar galdiņa numuru, modifikatoriem, alergēniem un piezīmēm.",
      "Vai tiek nosūtīti tieši uz restorāna WhatsApp — ideāli pasūtījumu paņemšanai un mazām komandām.",
      "QR katram galdiņam (vai viens visai zālei) tiek ģenerēts automātiski.",
    ],
    rating: "500+ restorāni 30+ valstīs",
  },
  features: {
    heading: "Pasūtījumu sistēma,",
    headingAccent: "veidota galdiņam.",
    sub: "Reāla funkcionalitāte — nevis piegādes agregatoru klons.",
    items: [
      { Icon: QrCode, title: "QR ēdienkarte ar grozu katram galdiņam", desc: "Viesis skenē QR, pārlūko ēdienkarti savā valodā, pievieno ēdienus ar modifikatoriem, atstāj piezīmi virtuvei un nosūta. Bez aplikācijas.", tag: "QR pasūtījumi" },
      { Icon: ChefHat, title: "Pasūtījumi uz virtuves planšetes", desc: "Katrs jauns pasūtījums parādās cilnē Virtuve — uz planšetes pie pasa — ar galdiņa numuru, ēdieniem, variantiem, alergēniem un komentāru. Viens pieskāriens no „procesā“ uz „gatavs“.", tag: "Virtuves skats" },
      { Icon: MessageCircle, title: "Vai uz WhatsApp", desc: "Pārslēdz restorānu WhatsApp režīmā (vai abos vienlaikus) — katrs pasūtījums nonāk WhatsApp kā formatēts ziņojums. Ideāli paņemšanai vai mazām komandām.", tag: "WhatsApp režīms" },
      { Icon: Settings2, title: "Modifikatori, varianti un alergēni", desc: "Katram ēdienam ir variantu grupas (izmērs, gatavība, papildinājumi) ar cenas atšķirību, alergēnu birkām un brīvu aprakstu. Grozs visu uzskaita — čeks uz planšetes bez neskaidrības.", tag: "Īsts grozs" },
      { Icon: Languages, title: "Daudzvalodu checkout", desc: "Viss pasūtījuma plūsma — grozs, modifikatori, komentārs, apstiprinājums — ir tulkots 35 valodās un automātiski pielāgojas viesa telefona valodai.", tag: "35 valodas" },
      { Icon: BarChart3, title: "Dienas numerācija un žurnāls", desc: "Katrs pasūtījums saņem dienas numuru virtuvei, nonāk žurnālā ar summām un laika zīmogiem, baro analītiku. Atcelšanas ir soft-delete, atskaites paliek tīras.", tag: "Pasūtījumu žurnāls" },
    ],
  },
  founder: {
    eyebrow: "Veidoja kafejnīcas īpašnieks, nevis piegādes startups",
    quoteStart: "Mēs ar sievu atvērām kafejnīcu un nedēļām meklējām veidu, kā pieņemt pasūtījumus pie galdiņa, kas neatdotu 30% agregatoram un neprasītu 1500 € kasi. Viss, ko izmēģinājām, bija neveikls, dārgs vai pietrūka pamatlietu —",
    quoteAccent: "tāpēc uzbūvējām pasūtījumu sistēmu, kuru paši būtu vēlējušies.",
    sign: "Bogdans Sokolovs · dibinātājs, bijušais kafejnīcas īpašnieks",
    photoAlt: "Bogdans, IQ Rest dibinātājs",
  },
  how: {
    heading: "Ieslēdz pasūtījumu sistēmu",
    headingAccent: "4 soļos",
    sub: "Bez instalēšanas, bez integratora, bez zvana IT. Tikai telefons un 5 minūtes.",
    steps: [
      { n: "1", t: "Izveido restorānu", d: "Reģistrācija ar e-pastu vai Google — 30 sekundes." },
      { n: "2", t: "Pievieno ēdienkarti", d: "Drag-and-drop vai AI skenēšana no papīra ēdienkartes." },
      { n: "3", t: "Izvēlies kanālu", d: "Virtuves planšete, WhatsApp vai abi." },
      { n: "4", t: "Izdrukā QR", d: "Viens QR uz galdiņu — viesi pasūta uzreiz." },
    ],
  },
  pricing: {
    badge: "Neierobežoti pasūtījumi · Nulle komisijas",
    heading: "Viens plāns.",
    headingAccent: "Bez maksas par pasūtījumu.",
    sub: "Tiešsaistes pasūtījumi, QR ēdienkarte, WhatsApp režīms, daudzvalodu checkout un analītika — viss vienā abonementā. Bez procentiem no darījuma.",
    monthlyLabel: "Mēnesī",
    yearlyLabel: "Gadā",
    saveBadge: "Ietaupi 25%",
    perMonth: "mēnesī",
    billedAnnually: "Rēķins reizi gadā {total}",
    youSave: "Tu ietaupi {amount}",
    trust: { secure: "Abonements caur Stripe", noCommitment: "Bez saistībām", quick: "Aktīvs minūtēs", restaurants: "+500 restorāni" },
  },
  faq: {
    eyebrow: "Pasūtījumu sistēma — bieži uzdotie jautājumi",
    heading: "Par pasūtījumu",
    headingAccent: "sistēmu.",
    sub: "Ko restorānu īpašnieki jautā pirms tiešsaistes pasūtījumu ieslēgšanas IQ Rest. Neredzi savu jautājumu? Raksti WhatsApp — atbild īsti cilvēki.",
    whatsappCta: "Jautā WhatsApp",
    whatsappPrefill: "Sveiki, man ir jautājums par IQ Rest pasūtījumiem",
    items: [
      { q: "Vai šī ir piegādes platforma kā Wolt vai Bolt Food?", a: "Nē, tieši tā ir doma. IQ Rest ir paša restorāna pasūtījumu kanāls: viesis pasūta no tava QR, pasūtījums nonāk uz tavu planšeti vai WhatsApp, tu pasniedz. Bez marketplace, bez agregatora kataloga — un mēs nekad neņemam daļu no rēķina." },
      { q: "Kur tieši parādās pasūtījumi?", a: "Cilnē Virtuve IQ Rest panelī uz jebkuras planšetes vai telefona pie pasa vai bāra. Katrs pasūtījums rāda galdiņa numuru, ēdienus ar variantiem un alergēniem, viesa komentāru un dienas numuru. Pāreja „jauns → procesā → gatavs“ ar vienu pieskārienu." },
      { q: "Vai pasūtījumi var nākt WhatsApp tā vietā?", a: "Jā. Katram restorānam ir trīs režīmi: iekšējais (tikai virtuves planšete), WhatsApp (pasūtījums nāk kā ziņojums uz restorāna WhatsApp) vai abi vienlaikus. Režīms ir viens slēdzis panelī, mainās jebkurā brīdī." },
      { q: "Kas ir pasūtījumā?", a: "Ēdieni ar variantiem un papildinājumiem (ar cenas atšķirību), alergēni, galdiņa numurs, viesa brīvs komentārs un — ja ieslēdz laukus — vārds, telefons un adrese. Pietiek, lai nosūtītu kurjeru vai atzvanītu galdiņam par alergēnu." },
      { q: "Vai viesi var maksāt tiešsaistē ēdienkartē?", a: "Pēc noklusējuma — nē. IQ Rest ir iestatīts maksāšanai pie galdiņa: viesis pasūta, tu atnes rēķinu, maksā kā parasti. Ja vajag tiešsaistes karšu maksu (tipiski paņemšanai), Stripe Connect integrācija iespējama pēc pieprasījuma — raksti WhatsApp." },
      { q: "Vai vajadzīga īpaša planšete, printeris vai POS aparatūra?", a: "Nē. Jebkura planšete, klēpjdators vai telefons ar pārlūku — atver paneli, pieslēdzies, atstāj cilni Virtuve atvērtu. Ja jau ir POS — IQ Rest darbojas blakus, neaizvieto kasi." },
      { q: "Kas pēc 14 bezmaksas dienām?", a: "Bez maksājuma metodes konts pauzē — nekad neapmaksājam automātiski. Ēdienkarte, pasūtījumi un iestatījumi saglabājas; pievieno karti jebkurā brīdī, lai atjauninātu. Atcelšana ar vienu klikšķi, bez saistībām." },
    ],
  },
  finalCta: {
    heading: "Ieslēdz pasūtījumu sistēmu.",
    headingAccent: "Gatavs 5 minūtēs.",
    sub: "14 dienas bez maksas, bez kartes. Atceltu jebkurā brīdī. Pievienojies 500+ restorāniem, kas pārvalda savus pasūtījumus caur IQ Rest.",
  },
  scan: {
    heading: "No papīra ēdienkartes uz pasūtījumu sistēmu",
    headingAccent: "60 sekundēs",
    sub: "Augšupielādē ēdienkartes foto — AI iegūst kategorijas, ēdienus un cenas tieši redaktorā. Tad grozs un QR — ar vienu klikšķi.",
    cta: "Skenēt ēdienkarti →",
  },
  footer: {
    featureLinks: [
      { href: "/lv/ai-translation", label: "AI tulkojums" },
      { href: "/lv/reservations", label: "Rezervācijas" },
      { href: "/lv/mobile-management", label: "Mobilā pārvaldība" },
      { href: "/lv/easy-menu", label: "Ēdienkartes redaktors" },
      { href: "/lv/custom-design", label: "Video un foto foni" },
      { href: "/lv/color-scheme", label: "Zīmola krāsas" },
      { href: "/lv/multilingual", label: "Daudzvalodu ēdienkarte" },
      { href: "/lv/ai-images", label: "AI foto optimizācija" },
      { href: "/lv/analytics", label: "Analītika" },
      { href: "/lv/instant-setup", label: "Tūlītēja iestatīšana" },
      { href: "/lv/personal-support", label: "Personīgs atbalsts" },
    ],
    navLinks: [
      { href: "#pricing", label: "Cenas" },
      { href: "#faq", label: "Jautājumi" },
      { href: "/lv/changelog", label: "Jaunumi" },
      { href: "/lv/languages", label: "Mainīt valodu" },
    ],
    copyrightTemplate: "© {year} IQ Rest. Visas tiesības rezervētas.",
  },
};
