#!/usr/bin/env python3
"""Generate per-locale ad folders on the Desktop: 4 creatives + description.txt.

Reuses make_ad.build(). Run from ad-assets/. Output: ~/Desktop/iq-rest-ads/<LOC>/.
"""
import os
from make_ad import build, build_story

HERE = os.path.dirname(os.path.abspath(__file__))
OUT_ROOT = os.path.expanduser("~/Desktop/iq-rest-ads")

PHOTO = {
    "web": "hero-cafe.webp",
    "orders": "feature-orders.webp",
    "reservations": "feature-reservation.webp",
    "kitchen": "feature-kitchen.webp",
}

# Per locale: web/orders/reservations/kitchen = (headline, sub) with "|" line breaks; primary = FB text.
DATA = {
 "es": {"web":("Web propia y|carta digital|para tu restaurante","Tu sitio completo, no solo el menú.|14 días gratis, sin tarjeta."),"orders":("Más pedidos,|menos espera","Tus clientes piden desde el móvil.|14 días gratis, sin tarjeta."),"reservations":("Llena tu sala|con reservas|online","Reservas 24/7 sin llamadas ni libretas.|Pruébalo gratis 14 días."),"kitchen":("Adiós a los|tickets de|papel","Comandas directas a cocina, menos errores.|Empieza gratis, sin tarjeta."),"primary":"Web, carta digital, pedidos QR, reservas y pantalla de cocina para tu restaurante. 14 días gratis, sin tarjeta."},
 "en": {"web":("A full website|+ digital menu|for your restaurant","Your own site, not just a menu.|14 days free, no card."),"orders":("More orders,|less waiting","Guests order from their phone.|14 days free, no card."),"reservations":("Fill your tables|with online|bookings","24/7 bookings, no phone calls.|Try free for 14 days."),"kitchen":("Ditch the|paper|tickets","Orders straight to the kitchen, fewer errors.|Start free, no card."),"primary":"Website, digital menu, QR ordering, bookings and kitchen display for your restaurant. 14 days free, no card."},
 "it": {"web":("Sito completo|e menù digitale|per il ristorante","Un vero sito, non solo il menù.|14 giorni gratis, senza carta."),"orders":("Più ordini,|meno attese","I clienti ordinano dal telefono.|14 giorni gratis, senza carta."),"reservations":("Riempi la sala|con prenotazioni|online","Prenotazioni 24/7 senza telefonate.|Provalo gratis 14 giorni."),"kitchen":("Addio alle|comande di|carta","Ordini diretti in cucina, meno errori.|Inizia gratis, senza carta."),"primary":"Sito web, menù digitale, ordini QR, prenotazioni e display di cucina per il tuo ristorante. 14 giorni gratis."},
 "fr": {"web":("Site complet|et carte digitale|pour votre resto","Un vrai site, pas juste la carte.|14 jours gratuits, sans carte."),"orders":("Plus de commandes,|moins d'attente","Vos clients commandent depuis leur mobile.|14 jours gratuits, sans carte."),"reservations":("Remplissez votre|salle avec des|réservations","Réservations 24/7 sans appels.|Essai gratuit 14 jours."),"kitchen":("Fini les|tickets|papier","Commandes directes en cuisine, moins d'erreurs.|Commencez gratuitement, sans carte."),"primary":"Site web, carte digitale, commande QR, réservations et écran cuisine pour votre restaurant. 14 jours gratuits."},
 "de": {"web":("Komplette Website|+ digitale Karte|fürs Restaurant","Eine echte Website, nicht nur die Karte.|14 Tage gratis, ohne Karte."),"orders":("Mehr Bestellungen,|weniger Warten","Gäste bestellen per Handy.|14 Tage gratis, ohne Karte."),"reservations":("Füll deinen Saal|mit Online-|Reservierungen","Reservierungen rund um die Uhr, ohne Anrufe.|14 Tage gratis testen."),"kitchen":("Schluss mit|Papier-|Bons","Bestellungen direkt in die Küche, weniger Fehler.|Gratis starten, ohne Karte."),"primary":"Website, digitale Karte, QR-Bestellung, Reservierungen und Küchendisplay für dein Restaurant. 14 Tage gratis."},
 "pt": {"web":("Site completo|e menu digital|para o teu restaurante","Um site a sério, não só o menu.|14 dias grátis, sem cartão."),"orders":("Mais pedidos,|menos espera","Os clientes pedem pelo telemóvel.|14 dias grátis, sem cartão."),"reservations":("Enche a sala|com reservas|online","Reservas 24/7 sem telefonemas.|Experimenta grátis 14 dias."),"kitchen":("Adeus aos|talões de|papel","Pedidos direto à cozinha, menos erros.|Começa grátis, sem cartão."),"primary":"Site, menu digital, pedidos QR, reservas e ecrã de cozinha para o teu restaurante. 14 dias grátis, sem cartão."},
 "pl": {"web":("Pełna strona|i menu cyfrowe|dla restauracji","Prawdziwa strona, nie tylko menu.|14 dni gratis, bez karty."),"orders":("Więcej zamówień,|mniej czekania","Goście zamawiają z telefonu.|14 dni gratis, bez karty."),"reservations":("Zapełnij salę|rezerwacjami|online","Rezerwacje 24/7 bez telefonów.|Wypróbuj za darmo 14 dni."),"kitchen":("Koniec z|papierowymi|bonami","Zamówienia prosto do kuchni, mniej błędów.|Zacznij za darmo, bez karty."),"primary":"Strona, menu cyfrowe, zamówienia QR, rezerwacje i ekran kuchenny dla restauracji. 14 dni gratis, bez karty."},
 "hu": {"web":("Teljes weboldal|és digitális étlap|az éttermednek","Igazi weboldal, nem csak az étlap.|14 nap ingyen, kártya nélkül."),"orders":("Több rendelés,|kevesebb várakozás","A vendégek telefonról rendelnek.|14 nap ingyen, kártya nélkül."),"reservations":("Töltsd meg a|termet online|foglalásokkal","Foglalások a nap 24 órájában, hívások nélkül.|Próbáld 14 napig ingyen."),"kitchen":("Búcsú a papír|rendelési|cetliknek","Rendelések egyenesen a konyhába, kevesebb hiba.|Kezdd ingyen, kártya nélkül."),"primary":"Weboldal, digitális étlap, QR-rendelés, foglalások és konyhai kijelző az éttermednek. 14 nap ingyen."},
 "sr": {"web":("Комплетан сајт|и дигитални мени|за ваш ресторан","Прави сајт, не само мени.|14 дана бесплатно, без картице."),"orders":("Више поруџбина,|мање чекања","Гости поручују са телефона.|14 дана бесплатно, без картице."),"reservations":("Напуните салу|онлајн|резервацијама","Резервације 0–24 без позива.|Пробајте бесплатно 14 дана."),"kitchen":("Крај папирним|поруџбеницама","Поруџбине право у кухињу, мање грешака.|Почните бесплатно, без картице."),"primary":"Сајт, дигитални мени, QR поруџбине, резервације и кухињски екран за ваш ресторан. 14 дана бесплатно."},
 "ro": {"web":("Site complet|și meniu digital|pentru restaurant","Un site adevărat, nu doar meniul.|14 zile gratis, fără card."),"orders":("Mai multe comenzi,|mai puțină așteptare","Clienții comandă de pe telefon.|14 zile gratis, fără card."),"reservations":("Umple sala cu|rezervări|online","Rezervări 24/7 fără telefoane.|Încearcă gratis 14 zile."),"kitchen":("Gata cu|bonurile de|hârtie","Comenzi direct la bucătărie, mai puține erori.|Începe gratis, fără card."),"primary":"Site, meniu digital, comenzi QR, rezervări și ecran de bucătărie pentru restaurant. 14 zile gratis, fără card."},
 "nl": {"web":("Een complete|site + digitale|menukaart","Een echte website, niet alleen het menu.|14 dagen gratis, zonder kaart."),"orders":("Meer bestellingen,|minder wachten","Gasten bestellen via hun telefoon.|14 dagen gratis, zonder kaart."),"reservations":("Vul je zaal met|online|reserveringen","Reserveren 24/7 zonder telefoontjes.|Probeer 14 dagen gratis."),"kitchen":("Weg met|papieren|bonnen","Bestellingen direct naar de keuken, minder fouten.|Start gratis, zonder kaart."),"primary":"Website, digitale menukaart, QR-bestellen, reserveringen en keukenscherm voor je restaurant. 14 dagen gratis."},
 "cs": {"web":("Kompletní web|a digitální menu|pro restauraci","Opravdový web, nejen menu.|14 dní zdarma, bez karty."),"orders":("Více objednávek,|méně čekání","Hosté objednávají z telefonu.|14 dní zdarma, bez karty."),"reservations":("Naplňte sál|online|rezervacemi","Rezervace 24/7 bez telefonování.|Vyzkoušejte 14 dní zdarma."),"kitchen":("Konec papírovým|účtenkám","Objednávky rovnou do kuchyně, méně chyb.|Začněte zdarma, bez karty."),"primary":"Web, digitální menu, QR objednávky, rezervace a kuchyňský displej pro restauraci. 14 dní zdarma, bez karty."},
 "sk": {"web":("Kompletný web|a digitálne menu|pre reštauráciu","Skutočný web, nielen menu.|14 dní zadarmo, bez karty."),"orders":("Viac objednávok,|menej čakania","Hostia objednávajú z telefónu.|14 dní zadarmo, bez karty."),"reservations":("Naplňte sálu|online|rezerváciami","Rezervácie 24/7 bez telefonovania.|Vyskúšajte 14 dní zadarmo."),"kitchen":("Koniec papierovým|účtenkám","Objednávky rovno do kuchyne, menej chýb.|Začnite zadarmo, bez karty."),"primary":"Web, digitálne menu, QR objednávky, rezervácie a kuchynský displej pre reštauráciu. 14 dní zadarmo."},
 "el": {"web":("Πλήρης ιστότοπος|και ψηφιακό μενού|για το εστιατόριο","Ένας πραγματικός ιστότοπος, όχι μόνο μενού.|14 ημέρες δωρεάν, χωρίς κάρτα."),"orders":("Περισσότερες|παραγγελίες, λιγότερη|αναμονή","Οι πελάτες παραγγέλνουν από το κινητό.|14 ημέρες δωρεάν, χωρίς κάρτα."),"reservations":("Γεμίστε τη σάλα|με online|κρατήσεις","Κρατήσεις 24/7 χωρίς τηλεφωνήματα.|Δοκιμάστε δωρεάν 14 ημέρες."),"kitchen":("Τέλος στα|χάρτινα|δελτία","Παραγγελίες κατευθείαν στην κουζίνα, λιγότερα λάθη.|Ξεκινήστε δωρεάν, χωρίς κάρτα."),"primary":"Ιστότοπος, ψηφιακό μενού, παραγγελίες QR, κρατήσεις και οθόνη κουζίνας για το εστιατόριό σας. 14 ημέρες δωρεάν."},
 "tr": {"web":("Restoranın için|tam web sitesi|ve dijital menü","Gerçek bir site, sadece menü değil.|14 gün ücretsiz, kartsız."),"orders":("Daha çok sipariş,|daha az bekleme","Müşteriler telefondan sipariş verir.|14 gün ücretsiz, kartsız."),"reservations":("Salonu online|rezervasyonlarla|doldur","7/24 rezervasyon, telefonsuz.|14 gün ücretsiz dene."),"kitchen":("Kâğıt|fişlere|son","Siparişler doğrudan mutfağa, daha az hata.|Ücretsiz başla, kartsız."),"primary":"Web sitesi, dijital menü, QR sipariş, rezervasyon ve mutfak ekranı restoranın için. 14 gün ücretsiz, kartsız."},
 "uk": {"web":("Повноцінний сайт|і цифрове меню|для ресторану","Справжній сайт, не лише меню.|14 днів безкоштовно, без картки."),"orders":("Більше замовлень,|менше очікування","Гості замовляють з телефону.|14 днів безкоштовно, без картки."),"reservations":("Заповніть зал|онлайн-|бронюваннями","Бронювання 24/7 без дзвінків.|Спробуйте безкоштовно 14 днів."),"kitchen":("Кінець паперовим|чекам","Замовлення одразу на кухню, менше помилок.|Почніть безкоштовно, без картки."),"primary":"Сайт, цифрове меню, QR-замовлення, бронювання та кухонний дисплей для ресторану. 14 днів безкоштовно."},
 "ru": {"web":("Полноценный сайт|и цифровое меню|для ресторана","Настоящий сайт, а не только меню.|14 дней бесплатно, без карты."),"orders":("Больше заказов,|меньше ожидания","Гости заказывают с телефона.|14 дней бесплатно, без карты."),"reservations":("Заполните зал|онлайн-|бронированиями","Брони 24/7 без звонков.|Попробуйте бесплатно 14 дней."),"kitchen":("Конец бумажным|чекам","Заказы сразу на кухню, меньше ошибок.|Начните бесплатно, без карты."),"primary":"Сайт, цифровое меню, QR-заказы, бронирования и кухонный дисплей для ресторана. 14 дней бесплатно, без карты."},
 "bg": {"web":("Пълноценен сайт|и дигитално меню|за ресторанта","Истински сайт, не само меню.|14 дни безплатно, без карта."),"orders":("Повече поръчки,|по-малко чакане","Клиентите поръчват от телефона.|14 дни безплатно, без карта."),"reservations":("Напълнете залата|с онлайн|резервации","Резервации 24/7 без обаждания.|Пробвайте безплатно 14 дни."),"kitchen":("Край на|хартиените|бонове","Поръчки право в кухнята, по-малко грешки.|Започнете безплатно, без карта."),"primary":"Сайт, дигитално меню, QR поръчки, резервации и кухненски дисплей за ресторанта. 14 дни безплатно."},
 "hr": {"web":("Potpuna web|stranica i digitalni|jelovnik","Prava web stranica, ne samo jelovnik.|14 dana besplatno, bez kartice."),"orders":("Više narudžbi,|manje čekanja","Gosti naručuju s mobitela.|14 dana besplatno, bez kartice."),"reservations":("Napunite salu|online|rezervacijama","Rezervacije 24/7 bez poziva.|Isprobajte besplatno 14 dana."),"kitchen":("Kraj papirnatim|narudžbama","Narudžbe ravno u kuhinju, manje grešaka.|Počnite besplatno, bez kartice."),"primary":"Web stranica, digitalni jelovnik, QR narudžbe, rezervacije i kuhinjski zaslon za restoran. 14 dana besplatno."},
 "sl": {"web":("Popolna spletna|stran in digitalni|meni","Prava spletna stran, ne le meni.|14 dni brezplačno, brez kartice."),"orders":("Več naročil,|manj čakanja","Gostje naročajo s telefona.|14 dni brezplačno, brez kartice."),"reservations":("Napolnite dvorano|s spletnimi|rezervacijami","Rezervacije 24/7 brez klicev.|Preizkusite 14 dni brezplačno."),"kitchen":("Konec papirnatim|listkom","Naročila naravnost v kuhinjo, manj napak.|Začnite brezplačno, brez kartice."),"primary":"Spletna stran, digitalni meni, QR naročila, rezervacije in kuhinjski zaslon za restavracijo. 14 dni brezplačno."},
 "sv": {"web":("En komplett|webbplats + digital|meny","En riktig webbplats, inte bara menyn.|14 dagar gratis, utan kort."),"orders":("Fler beställningar,|mindre väntan","Gästerna beställer från mobilen.|14 dagar gratis, utan kort."),"reservations":("Fyll lokalen med|bokningar|online","Bokningar dygnet runt utan samtal.|Testa gratis i 14 dagar."),"kitchen":("Slut på|papperslappar|i köket","Beställningar direkt till köket, färre fel.|Börja gratis, utan kort."),"primary":"Webbplats, digital meny, QR-beställning, bokningar och köksskärm för din restaurang. 14 dagar gratis."},
 "da": {"web":("En komplet|hjemmeside + digitalt|menukort","En rigtig hjemmeside, ikke kun menuen.|14 dage gratis, uden kort."),"orders":("Flere ordrer,|mindre ventetid","Gæster bestiller fra mobilen.|14 dage gratis, uden kort."),"reservations":("Fyld lokalet med|online|reservationer","Reservationer døgnet rundt uden opkald.|Prøv gratis i 14 dage."),"kitchen":("Slut med|papir-|sedler","Ordrer direkte til køkkenet, færre fejl.|Start gratis, uden kort."),"primary":"Hjemmeside, digitalt menukort, QR-bestilling, reservationer og køkkenskærm til din restaurant. 14 dage gratis."},
 "no": {"web":("En komplett|nettside + digital|meny","En ekte nettside, ikke bare menyen.|14 dager gratis, uten kort."),"orders":("Flere bestillinger,|mindre venting","Gjestene bestiller fra mobilen.|14 dager gratis, uten kort."),"reservations":("Fyll lokalet med|bestillinger|på nett","Bordbestilling døgnet rundt uten telefoner.|Prøv gratis i 14 dager."),"kitchen":("Slutt på|papir-|lapper","Bestillinger rett til kjøkkenet, færre feil.|Start gratis, uten kort."),"primary":"Nettside, digital meny, QR-bestilling, bordbestilling og kjøkkenskjerm for restauranten. 14 dager gratis."},
 "fi": {"web":("Täysi verkkosivu|ja digitaalinen|ruokalista","Oikea verkkosivu, ei pelkkä lista.|14 päivää ilmaiseksi, ilman korttia."),"orders":("Enemmän tilauksia,|vähemmän odotusta","Asiakkaat tilaavat puhelimella.|14 päivää ilmaiseksi, ilman korttia."),"reservations":("Täytä sali|verkko-|varauksilla","Varaukset 24/7 ilman puheluita.|Kokeile 14 päivää ilmaiseksi."),"kitchen":("Eroon paperisista|tilauslapuista","Tilaukset suoraan keittiöön, vähemmän virheitä.|Aloita ilmaiseksi, ilman korttia."),"primary":"Verkkosivu, digitaalinen ruokalista, QR-tilaus, pöytävaraukset ja keittiönäyttö ravintolallesi. 14 päivää ilmaiseksi."},
 "et": {"web":("Täielik veebisait|ja digitaalne|menüü","Päris veebisait, mitte ainult menüü.|14 päeva tasuta, kaardita."),"orders":("Rohkem tellimusi,|vähem ootamist","Külalised tellivad telefonist.|14 päeva tasuta, kaardita."),"reservations":("Täida saal|online-|broneeringutega","Broneeringud ööpäev läbi ilma kõnedeta.|Proovi 14 päeva tasuta."),"kitchen":("Lõpp paberist|tellimus-|sedelitele","Tellimused otse kööki, vähem vigu.|Alusta tasuta, kaardita."),"primary":"Veebisait, digitaalne menüü, QR-tellimused, broneeringud ja köögiekraan restoranile. 14 päeva tasuta."},
 "lv": {"web":("Pilnvērtīga vietne|un digitālā|ēdienkarte","Īsta vietne, ne tikai ēdienkarte.|14 dienas bez maksas, bez kartes."),"orders":("Vairāk pasūtījumu,|mazāk gaidīšanas","Viesi pasūta no telefona.|14 dienas bez maksas, bez kartes."),"reservations":("Piepildi zāli ar|rezervācijām|tiešsaistē","Rezervācijas 24/7 bez zvaniem.|Izmēģini 14 dienas bez maksas."),"kitchen":("Beigas papīra|pasūtījumu|čekiem","Pasūtījumi tieši uz virtuvi, mazāk kļūdu.|Sāc bez maksas, bez kartes."),"primary":"Vietne, digitālā ēdienkarte, QR pasūtījumi, rezervācijas un virtuves ekrāns restorānam. 14 dienas bez maksas."},
 "lt": {"web":("Visavertė svetainė|ir skaitmeninis|meniu","Tikra svetainė, ne tik meniu.|14 dienų nemokamai, be kortelės."),"orders":("Daugiau užsakymų,|mažiau laukimo","Svečiai užsako iš telefono.|14 dienų nemokamai, be kortelės."),"reservations":("Užpildyk salę|internetinėmis|rezervacijomis","Rezervacijos 24/7 be skambučių.|Išbandyk 14 dienų nemokamai."),"kitchen":("Atsisveikink su|popieriniais|čekiais","Užsakymai tiesiai į virtuvę, mažiau klaidų.|Pradėk nemokamai, be kortelės."),"primary":"Svetainė, skaitmeninis meniu, QR užsakymai, rezervacijos ir virtuvės ekranas restoranui. 14 dienų nemokamai."},
 "is": {"web":("Heil heimasíða|og stafrænn|matseðill","Alvöru heimasíða, ekki bara matseðill.|14 dagar frítt, án korts."),"orders":("Fleiri pantanir,|minni bið","Gestir panta úr símanum.|14 dagar frítt, án korts."),"reservations":("Fylltu salinn af|bókunum|á netinu","Bókanir allan sólarhringinn án símtala.|Prófaðu frítt í 14 daga."),"kitchen":("Bless við|pappírs-|miða","Pantanir beint í eldhúsið, færri mistök.|Byrjaðu frítt, án korts."),"primary":"Heimasíða, stafrænn matseðill, QR-pantanir, borðabókanir og eldhússkjár fyrir veitingastaðinn. 14 dagar frítt."},
 "ga": {"web":("Suíomh iomlán|agus biachlár|digiteach","Fíor-shuíomh, ní hé an biachlár amháin.|14 lá saor in aisce, gan chárta."),"orders":("Níos mó orduithe,|níos lú feithimh","Ordaíonn aíonna óna bhfón.|14 lá saor in aisce, gan chárta."),"reservations":("Líon do halla le|háirithintí|ar líne","Áirithintí 24/7 gan ghlaonna.|Bain triail as saor in aisce 14 lá."),"kitchen":("Slán le|ticéid|pháipéir","Orduithe díreach chuig an gcistin, níos lú botún.|Tosaigh saor in aisce, gan chárta."),"primary":"Suíomh, biachlár digiteach, orduithe QR, áirithintí agus scáileán cistine do bhialann. 14 lá saor in aisce."},
 "ca": {"web":("Web complet|i carta digital|per al restaurant","Un web de veritat, no només la carta.|14 dies gratis, sense targeta."),"orders":("Més comandes,|menys espera","Els clients demanen des del mòbil.|14 dies gratis, sense targeta."),"reservations":("Omple la sala|amb reserves|en línia","Reserves 24/7 sense trucades.|Prova-ho gratis 14 dies."),"kitchen":("Adéu als|tiquets de|paper","Comandes directes a la cuina, menys errors.|Comença gratis, sense targeta."),"primary":"Web, carta digital, comandes QR, reserves i pantalla de cuina per al restaurant. 14 dies gratis, sense targeta."},
}

LABELS = {
    "web": "Website + digital menu",
    "orders": "Order taking",
    "reservations": "Reservations",
    "kitchen": "Kitchen display",
}
ORDER = ["web", "orders", "reservations", "kitchen"]
FILE = {"web": "1-website.jpg", "orders": "2-order-taking.jpg",
        "reservations": "3-reservations.jpg", "kitchen": "4-kitchen-display.jpg"}
FILE_STORY = {"web": "1-website-9x16.jpg", "orders": "2-order-taking-9x16.jpg",
              "reservations": "3-reservations-9x16.jpg", "kitchen": "4-kitchen-display-9x16.jpg"}
# Horizontal crop bias (0=left, 0.5=center, 1=right). Only the menu photo is
# shifted right to show the phone/menu side; the rest stay centered.
CROP_X = {"web": 0.7}


def main():
    os.makedirs(OUT_ROOT, exist_ok=True)
    total = 0
    for loc, d in DATA.items():
        folder = os.path.join(OUT_ROOT, loc.upper())
        os.makedirs(folder, exist_ok=True)
        for key in ORDER:
            headline, sub = d[key]
            hl = [s for s in headline.split("|") if s]
            sl = [s for s in sub.split("|") if s]
            cx = CROP_X.get(key, 0.5)
            build(os.path.join(HERE, PHOTO[key]), os.path.join(folder, FILE[key]), hl, sl, cx)
            build_story(os.path.join(HERE, PHOTO[key]), os.path.join(folder, FILE_STORY[key]), hl, sl, cx)
            total += 2
        # description.txt
        lines = [f"IQ Rest — {loc.upper()} ad set", "",
                 "FACEBOOK / INSTAGRAM PRIMARY TEXT (fits preview, no truncation):",
                 d["primary"], "", "CREATIVES:"]
        for i, key in enumerate(ORDER, 1):
            h = " ".join(d[key][0].split("|"))
            s = " ".join(d[key][1].split("|"))
            lines.append(f"{i}) {LABELS[key]} — {FILE[key]}")
            lines.append(f"   {h}")
            lines.append(f"   {s}")
        with open(os.path.join(folder, "description.txt"), "w", encoding="utf-8") as f:
            f.write("\n".join(lines) + "\n")
    print(f"done: {len(DATA)} locales, {total} images -> {OUT_ROOT}")


if __name__ == "__main__":
    main()
