import { Check } from "lucide-react";
import { Section } from "@/app/_landing/components/section";

const BENEFITS = ["QR på hvert bord, scan-og-bestil, uden app", "Bestillinger i realtid på køkken- eller manager-tablet", "Eller i restaurantens WhatsApp — du vælger", "Modifiers, varianter og allergener kommer med på bonen", "Fri kommentar fra gæsten på hver bestilling", "Daglig nummerering til køkkenet", "Flersproget checkout i 35 sprog, efter gæstens telefon", "Nul provision pr. bestilling — fast månedligt abonnement"];
const HOW_STEPS = [
  { title: "Aktivér bestillinger for restauranten", desc: "Åbn restaurantens indstillinger, aktivér kontakten Bestillinger og vælg hvilke gæstefelter (navn, telefon, adresse) der skal indsamles." },
  { title: "Vælg leveringskanal", desc: "Intern tilstand sender nye bestillinger til fanen Køkken. WhatsApp-tilstand formaterer bestillingen som en besked i restaurantens WhatsApp. Eller begge parallelt." },
  { title: "Print og sæt QR op", desc: "Download QR (én pr. bord eller én pr. restaurant) i PDF eller PNG og sæt den på bordene. Gæsterne scanner med kameraet — uden App Store, uden friktion." },
  { title: "Kør vagten", desc: "Bestillinger lander i fanen Køkken med bordnummer, retter, varianter, allergener, kommentar og dagligt nummer. Skift ny → i gang → klar. Gæstens browser opdateres i realtid." },
];
const COMPARISON_ROWS = [["Provision pr. bestilling","20–30%","0%","0% (€6,90/md fast)"],["Hvor bestillingen lander","Aggregator-app","Din kasse","Din køkkentablet eller WhatsApp"],["Bordnummer på bon","Nej","Manuelt","Ja, automatisk"],["Modifiers / varianter","Begrænset","Ja","Ja, med allergener"],["Flersproget checkout","Deres app-sprog","Nej","35 sprog, automatisk"],["Krævet hardware","Aggregator-tablet","POS-terminal","Enhver tablet med browser"],["Opsætningstid","Onboarding-opkald","Dage-uger","5 minutter"]];

export function SeoContent() {
  return (<>
    <Section noContainer dataSection="seo-intro"><div className="w-full"><p className="text-xs font-medium uppercase tracking-widest text-primary mb-3 text-start">I dybden</p><h2 className="text-3xl sm:text-4xl lg:text-5xl font-medium tracking-tight mb-3 text-start">Hvad er et online bestillingssystem til restaurant <span className="text-muted-foreground">i virkeligheden</span></h2><p className="text-base sm:text-lg text-muted-foreground mb-10 text-start">Ingen marketplace. Ingen leveringsaggregator. En direkte linje fra gæstens telefon ved dit bord til køkkentabletten — eller WhatsApp.</p><div className="space-y-4 text-base sm:text-lg text-foreground/90 leading-relaxed"><p><strong>Online bestillingssystem til restaurant</strong> i IQ Rests forstand er software, der lader gæsten ved dit bord åbne menuen i telefonen, samle en kurv og sende bestillingen til køkkenet — uden Just Eat, Wolt, Bolt Food eller nogen anden marketplace. Gæsten forlader aldrig din QR-menu, du betaler ingen provision pr. bestilling, og bonen kommer med det rigtige bordnummer.</p><p>IQ Rest er bygget omkring to kanaler. Standard er <em>intern tilstand</em>: hver ny bestilling lander i fanen Køkken på panelet på en tablet, telefon eller laptop ved passet — med bordnummer, retter med varianter og allergener, fri kommentar fra gæsten og dagligt bestillingsnummer. Alternativet er <em>WhatsApp-tilstand</em>: samme bestilling formateres som en besked i restaurantens WhatsApp. Nyttigt for små teams, primært afhentning eller når manageren er væk fra salen. Begge tilstande kan køre samtidigt.</p></div></div></Section>
    <Section noContainer dataSection="seo-benefits"><div className="w-full"><h3 className="text-2xl sm:text-3xl font-medium tracking-tight mb-6 text-start">Hvad du reelt får</h3><div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-3 sm:gap-4">{BENEFITS.map((b) => (<div key={b} className="bg-muted/20 border border-border rounded-2xl p-4 sm:p-5 flex flex-row items-center gap-3"><div className="h-8 w-8 rounded-lg bg-primary/10 text-primary flex items-center justify-center shrink-0"><Check className="h-4 w-4" strokeWidth={2.5} /></div><p className="text-sm sm:text-base text-foreground/90 leading-snug">{b}</p></div>))}</div></div></Section>
    <Section noContainer dataSection="seo-how"><div className="w-full"><h3 className="text-2xl sm:text-3xl font-medium tracking-tight mb-6 text-start">Sådan virker IQ Rests bestillingsflow</h3><p className="text-base sm:text-lg text-foreground/90 leading-relaxed mb-6 text-start">Fire knapper i panelet — og du er live. Ingen installatør, ingen POS-hardware, intet integrationsprojekt.</p><div className="grid grid-cols-1 sm:grid-cols-2 gap-3 sm:gap-4">{HOW_STEPS.map((s, i) => (<div key={s.title} className="bg-muted/20 border border-border rounded-2xl p-5 flex flex-row items-start gap-4"><div className="h-10 w-10 rounded-lg bg-primary text-primary-foreground flex items-center justify-center shrink-0 font-semibold text-base">{i + 1}</div><div className="flex-1 min-w-0"><div className="text-base sm:text-lg font-semibold tracking-tight mb-1">{s.title}</div><p className="text-sm text-muted-foreground leading-relaxed">{s.desc}</p></div></div>))}</div></div></Section>
    <Section noContainer dataSection="seo-table"><div className="w-full"><h3 className="text-2xl sm:text-3xl font-medium tracking-tight mb-6 text-start">Aggregator, klassisk POS eller bestillingssystem</h3><div className="bg-muted/20 border border-border rounded-2xl p-4 sm:p-6 overflow-x-auto"><table className="w-full text-sm sm:text-base border-collapse"><thead><tr className="border-b border-border"><th className="text-left font-semibold py-3 pr-3 text-foreground">Egenskab</th><th className="text-left font-semibold py-3 pr-3 text-muted-foreground">Leveringsaggregator</th><th className="text-left font-semibold py-3 pr-3 text-muted-foreground">Klassisk POS</th><th className="text-left font-semibold py-3 text-primary">IQ Rest-bestillinger</th></tr></thead><tbody className="text-foreground/90">{COMPARISON_ROWS.map((row, i) => (<tr key={row[0]} className={i < COMPARISON_ROWS.length - 1 ? "border-b border-border/50" : ""}><td className="py-3 pr-3 font-medium">{row[0]}</td><td className="py-3 pr-3 text-muted-foreground">{row[1]}</td><td className="py-3 pr-3 text-muted-foreground">{row[2]}</td><td className="py-3 text-foreground">{row[3]}</td></tr>))}</tbody></table></div><p className="text-sm text-muted-foreground leading-relaxed mt-6 text-start">Et online bestillingssystem, som restauranten ejer selv, tjener sig hjem på den første weekend — hver krone gæsten bruger i din sal, bliver i din sal, og bonen ved passet er altid med rigtigt bordnummer.</p></div></Section>
  </>);
}
