import { QrCode, MessageCircle, ChefHat, Settings2, Languages, BarChart3 } from "lucide-react";
import type { LandingTexts } from "@/app/_landing/types";

export const TEXTS: LandingTexts = {
  htmlLang: "da",
  htmlDir: "ltr",
  meta: {
    title: "Online bestillingssystem til restaurant — QR og WhatsApp | IQ Rest",
    description: "Online bestillingssystem til restaurant: gæsten scanner QR ved bordet, samler bestillingen og den lander direkte på din køkkentablet eller WhatsApp. Nul provision, med bordnummer. 14 dage gratis.",
    canonical: "https://iq-rest.com/da/online-bestillingssystem-restaurant",
    ogLocale: "da_DK",
    ogTitle: "Online bestillingssystem til restaurant — Direkte til køkkenet",
    ogDescription: "Gæsten scanner QR ved bordet, samler bestillingen og den lander på din tablet eller WhatsApp — ingen aggregator, ingen provision, med bordnummer på hver bon.",
  },
  ctaText: "Aktivér bestillinger",
  demoText: "Live demo",
  microcopy: "Fra €6,90/md · 14 dage gratis · Stop når du vil",
  header: { navFeatures: "Funktioner", navHow: "Sådan virker det", navPricing: "Priser", navFaq: "FAQ", signIn: "Log ind", cta: "Prøv det" },
  hero: {
    verticals: ["Restauranter", "Caféer", "Bistroer", "Pizzeriaer", "Barer", "Ølbarer"],
    headline: "Online bestillingssystem til restaurant.",
    sub: "Gæsten scanner QR ved sit bord, samler bestillingen i telefonen — og bonen lander direkte på din køkkentablet eller restaurantens WhatsApp. Ingen aggregator, ingen provision, med bordnummer på hver bon.",
    dynamicHeadlines: ["Bestilling ved bordet.", "Direkte på køkkentabletten.", "Eller direkte i WhatsApp.", "Ingen provision.", "Med bordnummer."],
    painBullets: [
      "Online bestillingssystem som restauranten ejer selv — ingen mellemmænd, ingen provision.",
      "Bestillinger lander på køkkenets eller managerens tablet med bordnummer, modifiers, allergener og noter.",
      "Eller sendes direkte til restaurantens WhatsApp — ideelt til afhentning og små teams.",
      "QR til hvert bord (eller én til hele restauranten) genereres automatisk.",
    ],
    rating: "500+ restauranter i 30+ lande",
  },
  features: {
    heading: "Bestillingssystem,",
    headingAccent: "bygget til bordet.",
    sub: "Reel funktionalitet — ikke en klon af leveringsaggregatorer.",
    items: [
      { Icon: QrCode, title: "QR-menu med kurv til hvert bord", desc: "Gæsten scanner QR, gennemser menuen på sit eget sprog, tilføjer retter med modifiers, lægger en note til køkkenet og sender. Uden app.", tag: "QR-bestilling" },
      { Icon: ChefHat, title: "Bestillinger på køkkentabletten", desc: "Hver ny bestilling dukker op i fanen Køkken — på en tablet ved passet — med bordnummer, retter, varianter, allergener og kommentar. Ét tryk fra „i gang“ til „klar“.", tag: "Køkkenvisning" },
      { Icon: MessageCircle, title: "Eller i WhatsApp", desc: "Sæt restauranten i WhatsApp-tilstand (eller begge samtidig) — hver bestilling lander i WhatsApp som en formateret besked. Ideelt til afhentning eller små teams.", tag: "WhatsApp-tilstand" },
      { Icon: Settings2, title: "Modifiers, varianter og allergener", desc: "Hver ret har variantgrupper (størrelse, stegning, ekstra) med prisforskel, allergen-tags og fri beskrivelse. Kurven holder styr på det hele — bonen på tabletten er uden tvivl.", tag: "Rigtig kurv" },
      { Icon: Languages, title: "Flersproget checkout", desc: "Hele bestillingsflowet — kurv, modifiers, kommentar, bekræftelse — er oversat til 35 sprog og tilpasser sig automatisk sproget på gæstens telefon.", tag: "35 sprog" },
      { Icon: BarChart3, title: "Daglig nummerering og log", desc: "Hver bestilling får et dagligt nummer til køkkenet, ryger i loggen med beløb og tidsstempler, fodrer analyser. Annulleringer er soft-delete, rapporter forbliver rene.", tag: "Bestillingslog" },
    ],
  },
  founder: {
    eyebrow: "Lavet af en caféejer, ikke en levering-startup",
    quoteStart: "Min kone og jeg åbnede en café og brugte uger på at lede efter en måde at tage imod bordbestillinger på, som ikke skulle give 30% til en aggregator eller kræve en kasse til 1500 €. Alt vi prøvede var klodset, dyrt eller manglede det basale —",
    quoteAccent: "så vi byggede det bestillingssystem, vi selv ville have.",
    sign: "Bogdan Sokolov · grundlægger, eks-caféejer",
    photoAlt: "Bogdan, grundlægger af IQ Rest",
  },
  how: {
    heading: "Tænd for bestillingssystemet",
    headingAccent: "på 4 trin",
    sub: "Ingen installation, ingen integrator, intet opkald til IT. Bare en telefon og 5 minutter.",
    steps: [
      { n: "1", t: "Opret restauranten", d: "Tilmelding med e-mail eller Google — 30 sekunder." },
      { n: "2", t: "Tilføj menuen", d: "Drag-and-drop eller AI-scan af en papirmenu." },
      { n: "3", t: "Vælg kanal", d: "Køkkentablet, WhatsApp eller begge." },
      { n: "4", t: "Print QR", d: "Én QR pr. bord — gæsterne bestiller med det samme." },
    ],
  },
  pricing: {
    badge: "Ubegrænsede bestillinger · Nul provision",
    heading: "Én plan.",
    headingAccent: "Intet gebyr pr. bestilling.",
    sub: "Onlinebestilling, QR-menu, WhatsApp-tilstand, flersproget checkout og analyser — alt i ét abonnement. Ingen procent af transaktionen.",
    monthlyLabel: "Månedligt",
    yearlyLabel: "Årligt",
    saveBadge: "Spar 25%",
    perMonth: "om måneden",
    billedAnnually: "Faktureres én gang om året {total}",
    youSave: "Du sparer {amount}",
    trust: { secure: "Abonnement via Stripe", noCommitment: "Ingen binding", quick: "Aktiv på minutter", restaurants: "+500 restauranter" },
  },
  faq: {
    eyebrow: "Bestillingssystem — ofte stillede spørgsmål",
    heading: "Om bestillings-",
    headingAccent: "systemet.",
    sub: "Det restauratører spørger om, før de tænder for online bestillinger i IQ Rest. Mangler dit spørgsmål? Skriv på WhatsApp — rigtige mennesker svarer.",
    whatsappCta: "Spørg på WhatsApp",
    whatsappPrefill: "Hej, jeg har et spørgsmål om IQ Rest-bestillinger",
    items: [
      { q: "Er det en leveringsplatform som Just Eat eller Wolt?", a: "Nej, det er hele pointen. IQ Rest er restaurantens egen bestillingskanal: gæsten bestiller fra din QR, bestillingen lander på din tablet eller WhatsApp, du serverer. Ingen marketplace, intet aggregator-katalog — og vi tager aldrig en del af regningen." },
      { q: "Hvor dukker bestillingerne op præcis?", a: "I fanen Køkken i IQ Rest-panelet på enhver tablet eller telefon ved passet eller baren. Hver bestilling viser bordnummer, retter med varianter og allergener, gæstens kommentar og daglige nummer. Skiftet „ny → i gang → klar“ med ét tryk." },
      { q: "Kan bestillinger komme i WhatsApp i stedet?", a: "Ja. Hver restaurant har tre tilstande: intern (kun køkkentablet), WhatsApp (bestillingen kommer som besked i restaurantens WhatsApp) eller begge samtidig. Tilstanden er én knap i panelet, kan ændres når som helst." },
      { q: "Hvad er der i bestillingen?", a: "Retter med varianter og ekstra (med prisforskel), allergener, bordnummer, fri kommentar fra gæsten og — hvis du tænder felterne — navn, telefon og adresse. Nok til at sende en kurer eller ringe tilbage til bordet om en allergen." },
      { q: "Kan gæsterne betale online i menuen?", a: "Som standard — nej. IQ Rest er sat op til betaling ved bordet: gæsten bestiller, du bringer regningen, der betales som sædvanligt. Hvis du har brug for online kortbetaling (typisk til afhentning), er Stripe Connect-integration mulig efter anmodning — skriv på WhatsApp." },
      { q: "Skal jeg bruge en særlig tablet, printer eller POS-hardware?", a: "Nej. Enhver tablet, laptop eller telefon med browser — åbn panelet, log ind, lad fanen Køkken stå. Hvis du allerede har et POS — IQ Rest kører ved siden af, erstatter ikke kassen." },
      { q: "Hvad sker der efter 14 gratis dage?", a: "Uden betalingsmetode pauses kontoen — vi trækker aldrig automatisk. Menu, bestillinger og indstillinger bevares; tilføj et kort når du vil for at genaktivere. Stop med ét klik, ingen binding." },
    ],
  },
  finalCta: {
    heading: "Tænd for bestillingssystemet.",
    headingAccent: "Klar på 5 minutter.",
    sub: "14 dage gratis, intet kort. Stop når du vil. Vær med blandt 500+ restauranter, der styrer deres bestillinger gennem IQ Rest.",
  },
  scan: {
    heading: "Fra papirmenu til bestillingssystem",
    headingAccent: "på 60 sekunder",
    sub: "Upload et foto af menuen — AI henter kategorier, retter og priser direkte ind i editoren. Så kurv og QR — med ét klik.",
    cta: "Scan menuen →",
  },
  footer: {
    featureLinks: [
      { href: "/da/ai-translation", label: "AI-oversættelse" },
      { href: "/da/reservations", label: "Reservationer" },
      { href: "/da/mobile-management", label: "Mobilstyring" },
      { href: "/da/easy-menu", label: "Menu-editor" },
      { href: "/da/custom-design", label: "Video- og fotobaggrunde" },
      { href: "/da/color-scheme", label: "Brandfarver" },
      { href: "/da/multilingual", label: "Flersproget menu" },
      { href: "/da/ai-images", label: "AI-billedoptimering" },
      { href: "/da/analytics", label: "Analyser" },
      { href: "/da/instant-setup", label: "Øjeblikkelig opsætning" },
      { href: "/da/personal-support", label: "Personlig support" },
    ],
    navLinks: [
      { href: "#pricing", label: "Priser" },
      { href: "#faq", label: "Spørgsmål" },
      { href: "/da/changelog", label: "Nyt" },
      { href: "/da/languages", label: "Skift sprog" },
    ],
    copyrightTemplate: "© {year} IQ Rest. Alle rettigheder forbeholdes.",
  },
};
