import { Check } from "lucide-react";
import { Section } from "@/app/_landing/components/section";

const BENEFITS = ["QR ar gach bord, scan-agus-ordaigh, gan app", "Orduithe i bhfíor-am ar thaibléad cistine nó bainisteora", "Nó ar WhatsApp na bialainne — roghnaíonn tú", "Modhnóirí, malairtí agus ailléirginí téann ar an ticéad", "Nóta saor an aoi ar gach ordú", "Uimhriú laethúil don chistin", "Seic-amach ilteangach i 35 teanga, de réir ghuthán an aoi", "Gan choimisiún in aghaidh ordaithe — síntiús míosúil socair"];
const HOW_STEPS = [
  { title: "Cuir orduithe ar siúl don bhialann", desc: "Oscail socruithe na bialainne, gníomhachtaigh an lasc Orduithe agus roghnaigh cén réimsí aoi (ainm, fón, seoladh) le bailiú." },
  { title: "Roghnaigh cainéal seachadta", desc: "Seolann an mód inmheánach orduithe nua chuig an gcluaisín Cistin. Cuireann mód WhatsApp an t-ordú i bhformáid teachtaireachta chuig WhatsApp na bialainne. Nó an dá cheann go comhthreomhar." },
  { title: "Priontáil agus greamaigh QR", desc: "Íoslódáil QR (ceann in aghaidh an bhoird nó ceann in aghaidh na bialainne) i PDF nó PNG agus greamaigh ar na boird. Scanann aíonna leis an gceamara féin — gan App Store, gan frithchuimilt." },
  { title: "Oibrigh an seal", desc: "Tagann orduithe sa chluaisín Cistin le huimhir an bhoird, miasa, malairtí, ailléirginí, nóta agus uimhir laethúil. Aistriú nua → ar siúl → réidh. Nuashonraíonn brabhsálaí an aoi i bhfíor-am." },
];
const COMPARISON_ROWS = [["Coimisiún in aghaidh ordaithe","20–30%","0%","0% (€6.90/mí socair)"],["Cá dtéann an t-ordú","App an chomhbhailitheora","Do chiste","Do thaibléad cistine nó WhatsApp"],["Uimhir bhoird ar an ticéad","Níl","Le láimh","Tá, go huathoibríoch"],["Modhnóirí / malairtí","Teoranta","Tá","Tá, le hailléirginí"],["Seic-amach ilteangach","Teanga a n-app","Níl","35 teanga, go huathoibríoch"],["Crua-earraí riachtanach","Taibléad an chomhbhailitheora","Críochfort POS","Aon taibléad le brabhsálaí"],["Am socraithe","Glao onboarding","Laethanta-seachtainí","5 nóiméad"]];

export function SeoContent() {
  return (<>
    <Section dataSection="seo-intro"><div className="max-w-4xl mx-auto"><p className="text-xs font-medium uppercase tracking-widest text-primary mb-3 text-center">Sonraí</p><h2 className="text-3xl sm:text-4xl lg:text-5xl font-medium tracking-tight mb-3 text-center">Cad é córas orduithe ar líne do bhialann <span className="text-muted-foreground">i ndáiríre</span></h2><p className="text-base sm:text-lg text-muted-foreground mb-10 text-center">Gan margadh. Gan comhbhailitheoir seachadta. Líne dhíreach ó ghuthán an aoi ag do bhord chuig taibléad cistine — nó WhatsApp.</p><div className="space-y-4 text-base sm:text-lg text-foreground/90 leading-relaxed"><p><strong>Córas orduithe ar líne do bhialann</strong> i gciall IQ Rest is bogearra é a ligeann don aoi ag do bhord an biachlár a oscailt ar an ngutháin, ciseán a líonadh agus ordú a sheoladh chuig an gcistin — gan Deliveroo, Just Eat, Bolt Food ná aon mhargadh eile. Ní fhágann an t-aoi do bhiachlár QR, ní íocann tú coimisiún in aghaidh ordaithe, agus tagann an ticéad le fíor-uimhir an bhoird.</p><p>Tá IQ Rest tógtha thart ar dhá chainéal. De réir réamhshocraithe an <em>mód inmheánach</em>: tagann gach ordú nua chuig an gcluaisín Cistin sa phainéal ar thaibléad, guthán nó ríomhaire glúine in aice an pas — le huimhir an bhoird, miasa le malairtí agus ailléirginí, nóta saor an aoi agus uimhir laethúil an ordaithe. Mar mhalairt is é an <em>mód WhatsApp</em>: cuirtear an t-ordú céanna i bhformáid teachtaireachta chuig WhatsApp na bialainne. Úsáideach d'fhoirne beaga, do bhailiú go príomha nó nuair atá an bainisteoir lasmuigh den halla. Is féidir leis an dá mhód oibriú ag an am céanna.</p></div></div></Section>
    <Section dataSection="seo-benefits"><div className="max-w-4xl mx-auto"><h3 className="text-2xl sm:text-3xl font-medium tracking-tight mb-6 text-center">Cad a fhaigheann tú dáiríre</h3><div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-3 sm:gap-4">{BENEFITS.map((b) => (<div key={b} className="bg-muted/20 border border-border rounded-2xl p-4 sm:p-5 flex flex-row items-center gap-3"><div className="h-8 w-8 rounded-lg bg-primary/10 text-primary flex items-center justify-center shrink-0"><Check className="h-4 w-4" strokeWidth={2.5} /></div><p className="text-sm sm:text-base text-foreground/90 leading-snug">{b}</p></div>))}</div></div></Section>
    <Section dataSection="seo-how"><div className="max-w-4xl mx-auto"><h3 className="text-2xl sm:text-3xl font-medium tracking-tight mb-6 text-center">Conas a oibríonn sruth orduithe IQ Rest</h3><p className="text-base sm:text-lg text-foreground/90 leading-relaxed mb-6 text-center">Ceithre lasc sa phainéal — agus tá tú beo. Gan suiteoir, gan crua-earraí POS, gan tionscadal comhtháite.</p><div className="grid grid-cols-1 sm:grid-cols-2 gap-3 sm:gap-4">{HOW_STEPS.map((s, i) => (<div key={s.title} className="bg-muted/20 border border-border rounded-2xl p-5 flex flex-row items-start gap-4"><div className="h-10 w-10 rounded-lg bg-primary text-primary-foreground flex items-center justify-center shrink-0 font-semibold text-base">{i + 1}</div><div className="flex-1 min-w-0"><div className="text-base sm:text-lg font-semibold tracking-tight mb-1">{s.title}</div><p className="text-sm text-muted-foreground leading-relaxed">{s.desc}</p></div></div>))}</div></div></Section>
    <Section dataSection="seo-table"><div className="max-w-4xl mx-auto"><h3 className="text-2xl sm:text-3xl font-medium tracking-tight mb-6 text-center">Comhbhailitheoir, POS clasaiceach nó córas orduithe</h3><div className="bg-muted/20 border border-border rounded-2xl p-4 sm:p-6 overflow-x-auto"><table className="w-full text-sm sm:text-base border-collapse"><thead><tr className="border-b border-border"><th className="text-left font-semibold py-3 pr-3 text-foreground">Tréith</th><th className="text-left font-semibold py-3 pr-3 text-muted-foreground">Comhbhailitheoir seachadta</th><th className="text-left font-semibold py-3 pr-3 text-muted-foreground">POS clasaiceach</th><th className="text-left font-semibold py-3 text-primary">Orduithe IQ Rest</th></tr></thead><tbody className="text-foreground/90">{COMPARISON_ROWS.map((row, i) => (<tr key={row[0]} className={i < COMPARISON_ROWS.length - 1 ? "border-b border-border/50" : ""}><td className="py-3 pr-3 font-medium">{row[0]}</td><td className="py-3 pr-3 text-muted-foreground">{row[1]}</td><td className="py-3 pr-3 text-muted-foreground">{row[2]}</td><td className="py-3 text-foreground">{row[3]}</td></tr>))}</tbody></table></div><p className="text-sm text-muted-foreground leading-relaxed mt-6 text-center">Íocann córas orduithe ar líne a bhfuil úinéireacht ag an mbialann féin air as féin sa chéad deireadh seachtaine — fanann gach euro a chaitheann an t-aoi i do halla i do halla, agus bíonn fíor-uimhir an bhoird i gcónaí ar an ticéad in aice an pas.</p></div></Section>
  </>);
}
