import { QrCode, MessageCircle, ChefHat, Settings2, Languages, BarChart3 } from "lucide-react";
import type { LandingTexts } from "@/app/_landing/types";

export const TEXTS: LandingTexts = {
  htmlLang: "ga",
  htmlDir: "ltr",
  meta: {
    title: "Córas orduithe ar líne do bhialann — QR agus WhatsApp | IQ Rest",
    description: "Córas orduithe ar líne do bhialann: scanann an t-aoi an QR ag an mbord, déanann ordú agus tagann sé go díreach chuig do thaibléad cistine nó WhatsApp. Gan choimisiún, le huimhir an bhoird. 14 lá saor in aisce.",
    canonical: "https://iq-rest.com/ga/coras-orduithe-ar-line-bialann",
    ogLocale: "ga_IE",
    ogTitle: "Córas orduithe ar líne do bhialann — Díreach chuig an gcistin",
    ogDescription: "Scanann an t-aoi an QR ag an mbord, déanann ordú agus tagann sé chuig do thaibléad nó WhatsApp — gan idirghabhálaí, gan choimisiún, le huimhir an bhoird ar gach ticéad.",
  },
  ctaText: "Cuir orduithe ar siúl",
  demoText: "Taispeántas beo",
  microcopy: "Ó €6.90/mí · 14 lá saor in aisce · Cealaigh am ar bith",
  header: { navFeatures: "Gnéithe", navHow: "Conas a oibríonn sé", navPricing: "Praghsanna", navFaq: "FAQ", signIn: "Logáil isteach", cta: "Bain triail as" },
  hero: {
    verticals: ["Bialanna", "Caiféanna", "Bistros", "Pizzerias", "Beáir", "Beáir leanna"],
    headline: "Córas orduithe ar líne do bhialann.",
    sub: "Scanann an t-aoi QR a bhoird, déanann ordú ar a ghuthán — agus tagann an ticéad go díreach chuig do thaibléad cistine nó WhatsApp na bialainne. Gan idirghabhálaí, gan choimisiún, le huimhir an bhoird ar gach ticéad.",
    dynamicHeadlines: ["Ordú ag an mbord.", "Díreach chuig taibléad cistine.", "Nó díreach chuig WhatsApp.", "Gan choimisiún.", "Le huimhir an bhoird."],
    painBullets: [
      "Córas orduithe ar líne a bhfuil úinéireacht ag an mbialann féin air — gan idirghabhálaithe, gan choimisiún.",
      "Tagann orduithe chuig taibléad na cistine nó an bhainisteora le huimhir an bhoird, modhnóirí, ailléirginí agus nótaí.",
      "Nó seoltar iad go díreach chuig WhatsApp na bialainne — idéalach do bhailiú agus d'fhoirne beaga.",
      "Cruthaítear QR do gach bord (nó ceann amháin don halla iomlán) go huathoibríoch.",
    ],
    rating: "500+ bialann i 30+ tír",
  },
  features: {
    heading: "Córas orduithe,",
    headingAccent: "déanta don bhord.",
    sub: "Fíor-fheidhmiúlacht — ní macasamhail de chomhbhailitheoirí seachadta.",
    items: [
      { Icon: QrCode, title: "Biachlár QR le ciseán do gach bord", desc: "Scanann an t-aoi an QR, brabhsálann an biachlár ina theanga féin, cuireann miasa le modhnóirí, fágann nóta don chistin agus seolann. Gan app.", tag: "Orduithe QR" },
      { Icon: ChefHat, title: "Orduithe ar thaibléad cistine", desc: "Léiríonn gach ordú nua sa chluaisín Cistin — ar thaibléad in aice an pas — le huimhir an bhoird, miasa, malairtí, ailléirginí agus nóta. Tap amháin ó „ar siúl“ go „réidh“.", tag: "Radharc cistine" },
      { Icon: MessageCircle, title: "Nó chuig WhatsApp", desc: "Cuir an bhialann i mód WhatsApp (nó an dá cheann le chéile) — tagann gach ordú chuig WhatsApp mar theachtaireacht formáidithe. Idéalach do bhailiú nó d'fhoirne beaga.", tag: "Mód WhatsApp" },
      { Icon: Settings2, title: "Modhnóirí, malairtí agus ailléirginí", desc: "Tá grúpaí malairtí (méid, róstadh, breiseanna) ag gach mias le difríocht praghais, clibeanna ailléirginí agus cur síos saor in aisce. Comhairíonn an ciseán an t-iomlán — bíonn an ticéad ar an taibléad gan débhríocht.", tag: "Fíor-chiseán" },
      { Icon: Languages, title: "Seic-amach ilteangach", desc: "Tá an sruth orduithe iomlán — ciseán, modhnóirí, nóta, deimhniú — aistrithe go 35 teanga agus oiriúnaíonn sé go huathoibríoch do theanga ghuthán an aoi.", tag: "35 teanga" },
      { Icon: BarChart3, title: "Uimhriú laethúil agus loga", desc: "Faigheann gach ordú uimhir laethúil don chistin, téann sa loga le suimeanna agus stampaí ama, cothaíonn an anailísíocht. Cealuithe soft-delete, fanann tuarascálacha glan.", tag: "Loga orduithe" },
    ],
  },
  founder: {
    eyebrow: "Tógtha ag úinéir caifé, ní startup seachadta",
    quoteStart: "D'oscail mé féin agus mo bhean caifé agus chaitheamar seachtainí ag lorg slí orduithe boird a ghlacadh nach dtabharfadh 30% do chomhbhailitheoir agus nach mbeadh meaisín díola €1500 ag teastáil ann. Bhí gach rud a thrialaíomar trom, daor nó ar iarraidh leis na buntáistí —",
    quoteAccent: "mar sin thógamar an córas orduithe a theastaigh uainn féin.",
    sign: "Bogdan Sokolov · bunaitheoir, iar-úinéir caifé",
    photoAlt: "Bogdan, bunaitheoir IQ Rest",
  },
  how: {
    heading: "Cuir an córas orduithe ar siúl",
    headingAccent: "i 4 chéim",
    sub: "Gan suiteáil, gan comhtháthóir, gan glao chuig an TF. Guthán amháin agus 5 nóiméad.",
    steps: [
      { n: "1", t: "Cruthaigh bialann", d: "Cláraigh le ríomhphost nó Google — 30 soicind." },
      { n: "2", t: "Cuir biachlár leis", d: "Drag-and-drop nó scanadh AI ar bhiachlár páipéir." },
      { n: "3", t: "Roghnaigh cainéal", d: "Taibléad cistine, WhatsApp nó an dá cheann." },
      { n: "4", t: "Priontáil QR", d: "QR amháin in aghaidh an bhoird — déanann aíonna orduithe láithreach." },
    ],
  },
  pricing: {
    badge: "Orduithe gan teorainn · Gan choimisiún",
    heading: "Plean amháin.",
    headingAccent: "Gan táille in aghaidh an ordaithe.",
    sub: "Orduithe ar líne, biachlár QR, mód WhatsApp, seic-amach ilteangach agus anailísíocht — gach rud in aon síntiús amháin. Gan céatadán den idirbheart.",
    monthlyLabel: "Míosúil",
    yearlyLabel: "Bliantúil",
    saveBadge: "Sábháil 25%",
    perMonth: "in aghaidh na míosa",
    billedAnnually: "Billáilte uair sa bhliain {total}",
    youSave: "Sábhálann tú {amount}",
    trust: { secure: "Síntiús trí Stripe", noCommitment: "Gan tiomantas", quick: "Gníomhach i nóiméid", restaurants: "+500 bialann" },
  },
  faq: {
    eyebrow: "Córas orduithe — ceisteanna coitianta",
    heading: "Faoin gcóras",
    headingAccent: "orduithe.",
    sub: "Cad a fhiafraíonn úinéirí bialainne sula gcuireann siad orduithe ar líne ar siúl in IQ Rest. Nach bhfeiceann tú do cheist? Scríobh ar WhatsApp — freagraíonn fíordhaoine.",
    whatsappCta: "Cuir ceist ar WhatsApp",
    whatsappPrefill: "Dia duit, tá ceist agam faoi orduithe IQ Rest",
    items: [
      { q: "An ardán seachadta atá ann mar Deliveroo nó Just Eat?", a: "Ní hea, sin é an pointe go díreach. Is é IQ Rest cainéal orduithe na bialainne féin: ordaíonn an t-aoi ó do QR, tagann an t-ordú chuig do thaibléad nó WhatsApp, freastalaíonn tú. Gan margadh, gan chatalóg comhbhailitheora — agus ní ghlacann muid sciar den bhille riamh." },
      { q: "Cá feictear na horduithe go díreach?", a: "Sa chluaisín Cistin de phainéal IQ Rest ar aon taibléad nó guthán in aice an pas nó an bheár. Léiríonn gach ordú uimhir an bhoird, miasa le malairtí agus ailléirginí, nóta an aoi agus uimhir laethúil. Aistriú „nua → ar siúl → réidh“ le tap amháin." },
      { q: "An féidir le horduithe teacht chuig WhatsApp ina ionad?", a: "Is féidir. Tá trí mhód ag gach bialann: inmheánach (taibléad cistine amháin), WhatsApp (tagann an t-ordú mar theachtaireacht chuig WhatsApp na bialainne) nó an dá cheann le chéile. Is lasc amháin é an mód sa phainéal, athraíonn sé am ar bith." },
      { q: "Cad atá san ordú?", a: "Miasa le malairtí agus breiseanna (le difríocht praghais), ailléirginí, uimhir bhoird, nóta saor an aoi agus — má chuireann tú na réimsí ar siúl — ainm, fón agus seoladh. Go leor chun cúiréir a sheoladh nó glaoch ar ais chuig an mbord faoi ailléirgin." },
      { q: "An féidir le haíonna íoc ar líne sa bhiachlár?", a: "De réir réamhshocraithe — ní féidir. Tá IQ Rest socraithe d'íocaíocht ag an mbord: ordaíonn an t-aoi, tugann tú an bille, íoctar mar is gnách. Más gá íocaíocht chárta ar líne (tipiciúil do bhailiú), tá comhtháthú Stripe Connect indéanta ar iarratas — scríobh ar WhatsApp." },
      { q: "An bhfuil taibléad, printéir nó crua-earraí POS speisialta de dhíth?", a: "Níl. Aon taibléad, ríomhaire glúine nó guthán le brabhsálaí — oscail an painéal, sínigh isteach, fág an cluaisín Cistin ar oscailt. Má tá POS agat cheana — oibríonn IQ Rest taobh leis, ní ionadach é ar an gciste." },
      { q: "Cad a tharlaíonn tar éis 14 lá saor in aisce?", a: "Gan modh íocaíochta, sosann an cuntas — ní ghearrann muid go huathoibríoch riamh. Coinnítear an biachlár, na horduithe agus na socruithe; cuir cárta leis am ar bith chun athghníomhachtú a dhéanamh. Cealaigh le cliceáil amháin, gan tiomantas." },
    ],
  },
  finalCta: {
    heading: "Cuir an córas orduithe ar siúl.",
    headingAccent: "Réidh i 5 nóiméad.",
    sub: "14 lá saor in aisce, gan chárta. Cealaigh am ar bith. Bí leis na 500+ bialann atá ag bainistiú a n-orduithe trí IQ Rest.",
  },
  scan: {
    heading: "Ó bhiachlár páipéir go córas orduithe",
    headingAccent: "i 60 soicind",
    sub: "Uaslódáil grianghraf den bhiachlár — baineann an AI catagóirí, miasa agus praghsanna go díreach isteach san eagarthóir. Ansin ciseán agus QR — le cliceáil amháin.",
    cta: "Scan an biachlár →",
  },
  footer: {
    featureLinks: [
      { href: "/ga/ai-translation", label: "Aistriúchán AI" },
      { href: "/ga/reservations", label: "Áirithintí" },
      { href: "/ga/mobile-management", label: "Bainistíocht ar fhón" },
      { href: "/ga/easy-menu", label: "Eagarthóir biachláir" },
      { href: "/ga/custom-design", label: "Cúlraí físe agus grianghraif" },
      { href: "/ga/color-scheme", label: "Dathanna brandála" },
      { href: "/ga/multilingual", label: "Biachlár ilteangach" },
      { href: "/ga/ai-images", label: "Optamú íomhá AI" },
      { href: "/ga/analytics", label: "Anailís" },
      { href: "/ga/instant-setup", label: "Socrú láithreach" },
      { href: "/ga/personal-support", label: "Tacaíocht phearsanta" },
    ],
    navLinks: [
      { href: "#pricing", label: "Praghsanna" },
      { href: "#faq", label: "Ceisteanna" },
      { href: "/ga/changelog", label: "Nuacht" },
      { href: "/ga/languages", label: "Athraigh teanga" },
    ],
    copyrightTemplate: "© {year} IQ Rest. Gach ceart ar cosaint.",
  },
};
