import { Check } from "lucide-react";
import { Section } from "@/app/_landing/components/section";

const BENEFITS = ["QR minden asztalon, olvasd-és-rendelj, alkalmazás nélkül", "Rendelések valós időben a konyha vagy a vezető tabletjén", "Vagy az étterem WhatsApp-ján — te választod", "Módosítók, opciók és allergének a bizonylatra kerülnek", "Vendég szabad megjegyzése minden rendelésen", "Napi számozás a konyhának", "Többnyelvű checkout 35 nyelven, a vendég telefonja szerint", "Nulla jutalék rendelésenként — fix havi előfizetés"];
const HOW_STEPS = [
  { title: "Kapcsold be a rendeléseket az étteremhez", desc: "Nyisd meg az étterem beállításait, aktiváld a Rendelések kapcsolót és válaszd ki, mely vendégmezőket (név, telefon, cím) gyűjtsd." },
  { title: "Válassz kiszállítási csatornát", desc: "A belső mód az új rendeléseket a Konyha lapra küldi. A WhatsApp mód üzenetként formázza a rendelést az étterem WhatsApp-jára. Vagy mindkettő párhuzamosan." },
  { title: "Nyomtass és ragassz QR-t", desc: "Tölts le QR-t (asztalonként egyet vagy étterenként egyet) PDF-ben vagy PNG-ben és ragaszd az asztalokra. A vendégek a saját kamerájukkal olvassák be — App Store nélkül, súrlódás nélkül." },
  { title: "Vidd a műszakot", desc: "A rendelések megjelennek a Konyha lapon asztalszámmal, ételekkel, opciókkal, allergénekkel, megjegyzéssel és napi számmal. Az új → folyamatban → kész átmenet. A vendég böngészője valós időben frissül." },
];
const COMPARISON_ROWS = [["Jutalék rendelésenként","20–30%","0%","0% (€6,90/hó fix)"],["Hová megy a rendelés","Aggregátor app","A te pénztárgéped","A te konyhai tableted vagy WhatsApp"],["Asztalszám a bizonylaton","Nincs","Kézzel","Igen, automatikusan"],["Módosítók / opciók","Korlátozott","Igen","Igen, allergénekkel"],["Többnyelvű checkout","Az ő app-juk nyelve","Nincs","35 nyelv, automatikusan"],["Szükséges hardver","Aggregátor tablet","POS terminál","Bármilyen tablet böngészővel"],["Beállítási idő","Onboarding hívás","Napok-hetek","5 perc"]];

export function SeoContent() {
  return (<>
    <Section dataSection="seo-intro"><div className="max-w-4xl mx-auto"><p className="text-xs font-medium uppercase tracking-widest text-primary mb-3 text-center">Részletesen</p><h2 className="text-3xl sm:text-4xl lg:text-5xl font-medium tracking-tight mb-3 text-center">Mi az az online rendelési rendszer étteremnek <span className="text-muted-foreground">valójában</span></h2><p className="text-base sm:text-lg text-muted-foreground mb-10 text-center">Nem marketplace. Nem kiszállító aggregátor. Közvetlen vonal a vendég telefonjától az asztalodtól a konyhai tabletig — vagy WhatsApp-ra.</p><div className="space-y-4 text-base sm:text-lg text-foreground/90 leading-relaxed"><p><strong>Online rendelési rendszer étteremnek</strong> az IQ Rest értelmében olyan szoftver, amely lehetővé teszi a vendég számára az asztalodnál, hogy megnyissa az étlapot a telefonján, összeállítson egy kosarat és elküldje a rendelést a konyhába — Wolt, Foodpanda, Bolt Food vagy bármilyen más marketplace nélkül. A vendég soha nem hagyja el a QR étlapodat, te nem fizetsz jutalékot rendelésenként, és a bizonylat valódi asztalszámmal érkezik.</p><p>Az IQ Rest két csatorna köré épült. Alapértelmezetten <em>belső mód</em>: minden új rendelés megérkezik a Konyha lapra a panelben, tableten, telefonon vagy laptopon a pass mellett — asztalszámmal, ételekkel opciókkal és allergénekkel, vendég szabad megjegyzésével és napi rendelési számmal. Alternatíva a <em>WhatsApp mód</em>: ugyanaz a rendelés üzenetként formázódik az étterem WhatsApp-jára. Hasznos kis csapatoknak, főként elvitelre vagy ha a vezető nincs a teremben. Mindkét mód egyszerre futhat.</p></div></div></Section>
    <Section dataSection="seo-benefits"><div className="max-w-4xl mx-auto"><h3 className="text-2xl sm:text-3xl font-medium tracking-tight mb-6 text-center">Mit kapsz valójában</h3><div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-3 sm:gap-4">{BENEFITS.map((b) => (<div key={b} className="bg-muted/20 border border-border rounded-2xl p-4 sm:p-5 flex flex-row items-center gap-3"><div className="h-8 w-8 rounded-lg bg-primary/10 text-primary flex items-center justify-center shrink-0"><Check className="h-4 w-4" strokeWidth={2.5} /></div><p className="text-sm sm:text-base text-foreground/90 leading-snug">{b}</p></div>))}</div></div></Section>
    <Section dataSection="seo-how"><div className="max-w-4xl mx-auto"><h3 className="text-2xl sm:text-3xl font-medium tracking-tight mb-6 text-center">Hogyan működik az IQ Rest rendelési folyam</h3><p className="text-base sm:text-lg text-foreground/90 leading-relaxed mb-6 text-center">Négy kapcsoló a panelben — és élőben vagy. Telepítő nélkül, POS hardver nélkül, integrációs projekt nélkül.</p><div className="grid grid-cols-1 sm:grid-cols-2 gap-3 sm:gap-4">{HOW_STEPS.map((s, i) => (<div key={s.title} className="bg-muted/20 border border-border rounded-2xl p-5 flex flex-row items-start gap-4"><div className="h-10 w-10 rounded-lg bg-primary text-primary-foreground flex items-center justify-center shrink-0 font-semibold text-base">{i + 1}</div><div className="flex-1 min-w-0"><div className="text-base sm:text-lg font-semibold tracking-tight mb-1">{s.title}</div><p className="text-sm text-muted-foreground leading-relaxed">{s.desc}</p></div></div>))}</div></div></Section>
    <Section dataSection="seo-table"><div className="max-w-4xl mx-auto"><h3 className="text-2xl sm:text-3xl font-medium tracking-tight mb-6 text-center">Aggregátor, klasszikus POS vagy rendelési rendszer</h3><div className="bg-muted/20 border border-border rounded-2xl p-4 sm:p-6 overflow-x-auto"><table className="w-full text-sm sm:text-base border-collapse"><thead><tr className="border-b border-border"><th className="text-left font-semibold py-3 pr-3 text-foreground">Tulajdonság</th><th className="text-left font-semibold py-3 pr-3 text-muted-foreground">Kiszállító aggregátor</th><th className="text-left font-semibold py-3 pr-3 text-muted-foreground">Klasszikus POS</th><th className="text-left font-semibold py-3 text-primary">IQ Rest rendelések</th></tr></thead><tbody className="text-foreground/90">{COMPARISON_ROWS.map((row, i) => (<tr key={row[0]} className={i < COMPARISON_ROWS.length - 1 ? "border-b border-border/50" : ""}><td className="py-3 pr-3 font-medium">{row[0]}</td><td className="py-3 pr-3 text-muted-foreground">{row[1]}</td><td className="py-3 pr-3 text-muted-foreground">{row[2]}</td><td className="py-3 text-foreground">{row[3]}</td></tr>))}</tbody></table></div><p className="text-sm text-muted-foreground leading-relaxed mt-6 text-center">Az online rendelési rendszer, amelyet maga az étterem birtokol, az első hétvégén megtérül — minden forint, amit a vendég a termedben elkölt, a termedben marad, és a bizonylat a pass mellett mindig valódi asztalszámmal.</p></div></Section>
  </>);
}
