import { QrCode, MessageCircle, ChefHat, Settings2, Languages, BarChart3 } from "lucide-react";
import type { LandingTexts } from "@/app/_landing/types";

export const TEXTS: LandingTexts = {
  htmlLang: "hu",
  htmlDir: "ltr",
  meta: {
    title: "Online rendelési rendszer étteremnek — QR és WhatsApp | IQ Rest",
    description: "Online rendelési rendszer étteremnek: a vendég beolvassa az asztal QR-kódját, leadja a rendelést és az közvetlenül a konyhai tabletre vagy WhatsAppra érkezik. Nulla jutalék, asztalszámmal. 14 nap ingyen.",
    canonical: "https://iq-rest.com/hu/online-rendelesi-rendszer-etterem",
    ogLocale: "hu_HU",
    ogTitle: "Online rendelési rendszer étteremnek — Egyenesen a konyhába",
    ogDescription: "A vendég beolvassa az asztal QR-kódját, leadja a rendelést és az a tabletre vagy WhatsApp-ra érkezik — közvetítő nélkül, jutalék nélkül, asztalszámmal minden bizonylaton.",
  },
  ctaText: "Rendelések bekapcsolása",
  demoText: "Élő demó",
  microcopy: "€6,90/hó-tól · 14 nap ingyen · Bármikor lemondod",
  header: { navFeatures: "Funkciók", navHow: "Hogy működik", navPricing: "Árak", navFaq: "GYIK", signIn: "Belépés", cta: "Próbáld ki" },
  hero: {
    verticals: ["Éttermek", "Kávézók", "Bisztrók", "Pizzériák", "Bárok", "Sörözők"],
    headline: "Online rendelési rendszer étteremnek.",
    sub: "A vendég beolvassa az asztalának QR-kódját, leadja a rendelést a telefonján — és a bizonylat egyenesen a konyhai tabletre vagy az étterem WhatsApp-jára érkezik. Közvetítő nélkül, jutalék nélkül, asztalszámmal minden bizonylaton.",
    dynamicHeadlines: ["Rendelés az asztalnál.", "Egyenesen a konyhai tabletre.", "Vagy egyenesen WhatsApp-ra.", "Nulla jutalék.", "Asztalszámmal."],
    painBullets: [
      "Online rendelési rendszer, amelyet maga az étterem birtokol — közvetítők nélkül, jutalék nélkül.",
      "A rendelések a konyha vagy a vezető tabletjére érkeznek asztalszámmal, módosítókkal, allergénekkel és jegyzetekkel.",
      "Vagy közvetlenül az étterem WhatsApp-jára mennek — ideális elvitelhez és kis csapatokhoz.",
      "QR minden asztalhoz (vagy egy az egész teremre) automatikusan generálódik.",
    ],
    rating: "500+ étterem 30+ országban",
  },
  features: {
    heading: "Rendelési rendszer,",
    headingAccent: "az asztalhoz építve.",
    sub: "Valódi funkcionalitás — nem a kiszállító aggregátorok klónja.",
    items: [
      { Icon: QrCode, title: "QR étlap kosárral minden asztalhoz", desc: "A vendég beolvassa a QR-t, böngészi az étlapot a saját nyelvén, ételeket ad hozzá módosítókkal, jegyzetet hagy a konyhának és küld. Alkalmazás nélkül.", tag: "QR rendelés" },
      { Icon: ChefHat, title: "Rendelések a konyhai tableten", desc: "Minden új rendelés megjelenik a Konyha lapon — a pass melletti tableten — asztalszámmal, ételekkel, opciókkal, allergénekkel és megjegyzéssel. Egy érintés „folyamatban“-ról „kész“-re.", tag: "Konyha nézet" },
      { Icon: MessageCircle, title: "Vagy WhatsApp-ra", desc: "Állítsd az éttermet WhatsApp módba (vagy mindkettőt egyszerre) — minden rendelés formázott üzenetként érkezik WhatsApp-ra. Ideális elvitelhez vagy kis csapatokhoz.", tag: "WhatsApp mód" },
      { Icon: Settings2, title: "Módosítók, opciók és allergének", desc: "Minden ételnek vannak opciócsoportjai (méret, sültség, extra) árkülönbséggel, allergén címkékkel és szabad leírással. A kosár mindent számol — a bizonylat a tableten egyértelmű.", tag: "Igazi kosár" },
      { Icon: Languages, title: "Többnyelvű checkout", desc: "A teljes rendelési folyamat — kosár, módosítók, megjegyzés, megerősítés — 35 nyelvre lefordítva, automatikusan a vendég telefonjának nyelvéhez igazodik.", tag: "35 nyelv" },
      { Icon: BarChart3, title: "Napi számozás és napló", desc: "Minden rendelés napi számot kap a konyha számára, naplóba kerül összegekkel és időbélyegekkel, táplálja az analitikát. A lemondások soft-delete, a riportok tiszták maradnak.", tag: "Rendelési napló" },
    ],
  },
  founder: {
    eyebrow: "Kávézó-tulajdonos építette, nem kiszállító startup",
    quoteStart: "A feleségemmel kávézót nyitottunk, és heteket töltöttünk azzal, hogy találjunk módot asztali rendelések fogadására, ami nem ad 30%-ot egy aggregátornak és nem igényel 1500 €-s pénztárgépet. Minden, amit kipróbáltunk, otromba, drága volt vagy hiányoztak az alapok —",
    quoteAccent: "így megépítettük a rendelési rendszert, amit mi magunk akartunk volna.",
    sign: "Bogdan Sokolov · alapító, ex-kávézó tulajdonos",
    photoAlt: "Bogdan, az IQ Rest alapítója",
  },
  how: {
    heading: "Kapcsold be a rendelési rendszert",
    headingAccent: "4 lépésben",
    sub: "Telepítés nélkül, integrátor nélkül, IT-hívás nélkül. Csak egy telefon és 5 perc.",
    steps: [
      { n: "1", t: "Hozz létre éttermet", d: "Regisztráció e-mailben vagy Google-lal — 30 másodperc." },
      { n: "2", t: "Adj hozzá étlapot", d: "Drag-and-drop vagy AI szkennelés papír étlapról." },
      { n: "3", t: "Válassz csatornát", d: "Konyhai tablet, WhatsApp vagy mindkettő." },
      { n: "4", t: "Nyomtass QR-t", d: "Egy QR asztalonként — a vendégek azonnal rendelnek." },
    ],
  },
  pricing: {
    badge: "Korlátlan rendelés · Nulla jutalék",
    heading: "Egy csomag.",
    headingAccent: "Nincs rendelési díj.",
    sub: "Online rendelés, QR étlap, WhatsApp mód, többnyelvű checkout és analitika — minden egy előfizetésben. Nincs tranzakciós százalék.",
    monthlyLabel: "Havi",
    yearlyLabel: "Éves",
    saveBadge: "Spórolj 25%",
    perMonth: "havonta",
    billedAnnually: "Évente egyszer számlázva {total}",
    youSave: "Megspórolsz {amount}",
    trust: { secure: "Előfizetés Stripe-on keresztül", noCommitment: "Nincs elköteleződés", quick: "Aktív percek alatt", restaurants: "+500 étterem" },
  },
  faq: {
    eyebrow: "Rendelési rendszer — gyakran ismételt kérdések",
    heading: "A rendelési",
    headingAccent: "rendszerről.",
    sub: "Amit éttermesek kérdeznek, mielőtt bekapcsolják az online rendelést IQ Rest-ben. Nem látod a kérdésed? Írj WhatsApp-on — igazi emberek válaszolnak.",
    whatsappCta: "Kérdezz WhatsApp-on",
    whatsappPrefill: "Szia, kérdésem van az IQ Rest rendelésekről",
    items: [
      { q: "Ez egy kiszállító platform, mint a Wolt vagy a Foodpanda?", a: "Nem, pont ez a lényeg. Az IQ Rest az étterem saját rendelési csatornája: a vendég a te QR-edről rendel, a rendelés a te tabletedre vagy WhatsApp-odra érkezik, te szolgálsz fel. Nincs marketplace, nincs aggregátor katalógus — és soha nem veszünk részt a számlából." },
      { q: "Hol jelennek meg pontosan a rendelések?", a: "Az IQ Rest panel Konyha lapján bármilyen tableten vagy telefonon a pass vagy a bár mellett. Minden rendelés mutatja az asztalszámot, ételeket opciókkal és allergénekkel, vendég megjegyzését és napi számot. Az „új → folyamatban → kész“ átmenet egy érintéssel." },
      { q: "Lehet a rendeléseket WhatsApp-ra kapni helyette?", a: "Igen. Minden étteremnek három módja van: belső (csak konyhai tablet), WhatsApp (a rendelés üzenetként érkezik az étterem WhatsApp-jára) vagy mindkettő egyszerre. A mód egy kapcsoló a panelben, bármikor változik." },
      { q: "Mi van a rendelésben?", a: "Ételek opciókkal és extrákkal (árkülönbséggel), allergének, asztalszám, vendég szabad megjegyzése és — ha bekapcsolod a mezőket — név, telefon és cím. Elég futár küldéséhez vagy az asztal visszahívásához allergén miatt." },
      { q: "A vendégek fizethetnek online az étlapon?", a: "Alapértelmezetten — nem. Az IQ Rest asztalnál fizetésre van beállítva: a vendég rendel, te hozod a számlát, fizetés mint mindig. Ha online kártyás fizetésre van szükség (tipikus elvitelhez), a Stripe Connect integráció igény szerint lehetséges — írj WhatsApp-on." },
      { q: "Kell speciális tablet, nyomtató vagy POS hardver?", a: "Nem. Bármelyik tablet, laptop vagy telefon böngészővel — nyisd meg a panelt, jelentkezz be, hagyd a Konyha lapot nyitva. Ha már van POS-od — az IQ Rest mellette fut, nem helyettesíti a pénztárgépet." },
      { q: "Mi történik 14 ingyenes nap után?", a: "Fizetési mód nélkül a fiók szünetel — soha nem terhelünk automatikusan. Az étlap, rendelések és beállítások megmaradnak; adj hozzá kártyát bármikor az újraaktiváláshoz. Egy kattintással lemondod, nincs elköteleződés." },
    ],
  },
  finalCta: {
    heading: "Kapcsold be a rendelési rendszert.",
    headingAccent: "5 perc alatt kész.",
    sub: "14 nap ingyen, kártya nélkül. Bármikor lemondod. Csatlakozz az 500+ étteremhez, ami az IQ Rest-en keresztül kezeli a rendeléseit.",
  },
  scan: {
    heading: "Papír étlapról rendelési rendszerre",
    headingAccent: "60 másodperc alatt",
    sub: "Tölts fel egy fotót az étlapról — az AI kivonatolja a kategóriákat, ételeket és árakat egyenesen a szerkesztőbe. Aztán kosár és QR — egy kattintással.",
    cta: "Étlap beolvasása →",
  },
  footer: {
    featureLinks: [
      { href: "/hu/ai-translation", label: "AI fordítás" },
      { href: "/hu/reservations", label: "Foglalások" },
      { href: "/hu/mobile-management", label: "Mobil kezelés" },
      { href: "/hu/easy-menu", label: "Étlap szerkesztő" },
      { href: "/hu/custom-design", label: "Videó és fotó hátterek" },
      { href: "/hu/color-scheme", label: "Márka színek" },
      { href: "/hu/multilingual", label: "Többnyelvű étlap" },
      { href: "/hu/ai-images", label: "AI fotó optimalizálás" },
      { href: "/hu/analytics", label: "Analitika" },
      { href: "/hu/instant-setup", label: "Azonnali telepítés" },
      { href: "/hu/personal-support", label: "Személyes támogatás" },
    ],
    navLinks: [
      { href: "#pricing", label: "Árak" },
      { href: "#faq", label: "Kérdések" },
      { href: "/hu/changelog", label: "Újdonságok" },
      { href: "/hu/languages", label: "Nyelvváltás" },
    ],
    copyrightTemplate: "© {year} IQ Rest. Minden jog fenntartva.",
  },
};
