/**
 * Country code (ISO 3166-1 alpha-2) → primary IANA timezone
 * Used to convert UTC dates to local time for analytics display.
 * For multi-timezone countries, the most populated timezone is used.
 */
export const countryToTimezone: Record<string, string> = {
  // Europe
  GB: "Europe/London",
  IE: "Europe/Dublin",
  IS: "Atlantic/Reykjavik",
  PT: "Europe/Lisbon",
  ES: "Europe/Madrid",
  FR: "Europe/Paris",
  BE: "Europe/Brussels",
  NL: "Europe/Amsterdam",
  LU: "Europe/Luxembourg",
  DE: "Europe/Berlin",
  AT: "Europe/Vienna",
  CH: "Europe/Zurich",
  IT: "Europe/Rome",
  MT: "Europe/Malta",
  SI: "Europe/Ljubljana",
  HR: "Europe/Zagreb",
  BA: "Europe/Sarajevo",
  RS: "Europe/Belgrade",
  ME: "Europe/Podgorica",
  MK: "Europe/Skopje",
  AL: "Europe/Tirane",
  GR: "Europe/Athens",
  CY: "Asia/Nicosia",
  BG: "Europe/Sofia",
  RO: "Europe/Bucharest",
  MD: "Europe/Chisinau",
  UA: "Europe/Kyiv",
  HU: "Europe/Budapest",
  SK: "Europe/Bratislava",
  CZ: "Europe/Prague",
  PL: "Europe/Warsaw",
  LT: "Europe/Vilnius",
  LV: "Europe/Riga",
  EE: "Europe/Tallinn",
  FI: "Europe/Helsinki",
  SE: "Europe/Stockholm",
  NO: "Europe/Oslo",
  DK: "Europe/Copenhagen",
  RU: "Europe/Moscow",
  BY: "Europe/Minsk",
  TR: "Europe/Istanbul",

  // Americas
  US: "America/New_York",
  CA: "America/Toronto",
  MX: "America/Mexico_City",
  GT: "America/Guatemala",
  HN: "America/Tegucigalpa",
  SV: "America/El_Salvador",
  NI: "America/Managua",
  CR: "America/Costa_Rica",
  PA: "America/Panama",
  CU: "America/Havana",
  JM: "America/Jamaica",
  DO: "America/Santo_Domingo",
  PR: "America/Puerto_Rico",
  CO: "America/Bogota",
  VE: "America/Caracas",
  EC: "America/Guayaquil",
  PE: "America/Lima",
  BO: "America/La_Paz",
  PY: "America/Asuncion",
  UY: "America/Montevideo",
  AR: "America/Argentina/Buenos_Aires",
  CL: "America/Santiago",
  BR: "America/Sao_Paulo",

  // Middle East
  IL: "Asia/Jerusalem",
  PS: "Asia/Hebron",
  LB: "Asia/Beirut",
  SY: "Asia/Damascus",
  JO: "Asia/Amman",
  IQ: "Asia/Baghdad",
  KW: "Asia/Kuwait",
  SA: "Asia/Riyadh",
  BH: "Asia/Bahrain",
  QA: "Asia/Qatar",
  AE: "Asia/Dubai",
  OM: "Asia/Muscat",
  YE: "Asia/Aden",
  IR: "Asia/Tehran",

  // Africa
  EG: "Africa/Cairo",
  LY: "Africa/Tripoli",
  TN: "Africa/Tunis",
  DZ: "Africa/Algiers",
  MA: "Africa/Casablanca",
  NG: "Africa/Lagos",
  GH: "Africa/Accra",
  KE: "Africa/Nairobi",
  ET: "Africa/Addis_Ababa",
  TZ: "Africa/Dar_es_Salaam",
  ZA: "Africa/Johannesburg",

  // Central & South Asia
  GE: "Asia/Tbilisi",
  AM: "Asia/Yerevan",
  AZ: "Asia/Baku",
  KZ: "Asia/Almaty",
  UZ: "Asia/Tashkent",
  TM: "Asia/Ashgabat",
  KG: "Asia/Bishkek",
  TJ: "Asia/Dushanbe",
  AF: "Asia/Kabul",
  PK: "Asia/Karachi",
  IN: "Asia/Kolkata",
  LK: "Asia/Colombo",
  NP: "Asia/Kathmandu",
  BD: "Asia/Dhaka",
  MM: "Asia/Yangon",

  // East & Southeast Asia
  TH: "Asia/Bangkok",
  VN: "Asia/Ho_Chi_Minh",
  KH: "Asia/Phnom_Penh",
  LA: "Asia/Vientiane",
  MY: "Asia/Kuala_Lumpur",
  SG: "Asia/Singapore",
  ID: "Asia/Jakarta",
  PH: "Asia/Manila",
  CN: "Asia/Shanghai",
  HK: "Asia/Hong_Kong",
  MO: "Asia/Macau",
  TW: "Asia/Taipei",
  JP: "Asia/Tokyo",
  KR: "Asia/Seoul",
  MN: "Asia/Ulaanbaatar",

  // Oceania
  AU: "Australia/Sydney",
  NZ: "Pacific/Auckland",
  FJ: "Pacific/Fiji",
};

/**
 * Get IANA timezone for a country code.
 * Falls back to UTC for unknown countries.
 */
export function getTimezoneForCountry(countryCode: string): string {
  return countryToTimezone[countryCode?.toUpperCase()] || "UTC";
}
