// Locale-stable analytics keys. Landing event names must NOT vary by language
// so funnels aggregate across locales. The per-locale `trackPrefix`
// (l_<locale>_<feature>, sometimes l_<feature>) and the per-locale feature
// slugs are collapsed here to a single feature token.

/** Feature page slug (folder name, any locale) → stable feature token.
 *  Generated from app/<locale>/<slug>/content.ts trackPrefix. */
export const FEATURE_BY_SLUG: Record<string, string> = {
  "asztalfoglalas": "bookings",
  "bestallningssystem-restaurang": "orders",
  "bestelsysteem-restaurant": "orders",
  "bestillingssystem-restaurant": "orders",
  "biachlar-digiteach-bialann": "digital",
  "biachlar-qr-coda-bialann": "qr",
  "bord-bokun": "bookings",
  "bordreservasjon": "bookings",
  "bordreservation": "bookings",
  "bordsbokning": "bookings",
  "bronirovanie-stolov": "bookings",
  "bronyuvannya-stoliv": "bookings",
  "carta-digital-restaurant": "digital",
  "chubo-disupurei": "kds",
  "chumon-shisutemu-resutoran": "orders",
  "codi-qr-restaurant": "qr",
  "codigo-qr-restaurante": "qr",
  "coras-orduithe-bialann": "orders",
  "curfha-bord": "bookings",
  "cyfrowe-menu-restauracja": "digital",
  "dejitaru-menyu-resutoran": "digital",
  "dian-can-xi-tong-can-ting": "orders",
  "digitaal-menu-restaurant": "digital",
  "digitaalinen-ruokalista-ravintola": "digital",
  "digitaalne-menuu-restoran": "digital",
  "digital-menu-for-restaurants": "digital",
  "digital-meny-restaurang": "digital",
  "digital-meny-restaurant": "digital",
  "digitala-edienkarte-restorans": "digital",
  "digitale-speisekarte-restaurant": "digital",
  "digitalis-etlap-etterem": "digital",
  "digitalne-menu-restauracia": "digital",
  "digitalni-jedilnik-restavracija": "digital",
  "digitalni-jelovnik-restoran": "digital",
  "digitalni-meni-restoran": "digital",
  "digitalni-menu-restaurace": "digital",
  "digitalno-menyu-restorant": "digital",
  "digitalt-menu-restaurant": "digital",
  "dijital-menu-restoran": "digital",
  "dijiteol-menyu-resutorang": "digital",
  "display-bucatarie": "kds",
  "display-cucina": "kds",
  "display-de-cozinha": "kds",
  "ecran-cuisine": "kds",
  "ekran-kuchenny": "kds",
  "eldhus-skjar": "kds",
  "galdu-rezervesana": "bookings",
  "hajz-tawilat": "bookings",
  "hou-chu-xian-shi-qi": "kds",
  "juhang-diseupeullei": "kds",
  "juneun-shiseutem-resutorang": "orders",
  "kds-kuhonnyy-displey": "kds",
  "keittion-naytto": "kds",
  "keukenscherm": "kds",
  "kitchen-display-system": "kds",
  "kjokken-skjerm": "kds",
  "kok-skarm": "kds",
  "kokken-skaerm": "kds",
  "konyhai-kijelzo": "kds",
  "kook-ekraan": "kds",
  "kratisi-trapezi-online": "bookings",
  "kuchynsky-displej": "kds",
  "kuechen-display": "kds",
  "kuhinjski-ekran": "kds",
  "kuhinjski-zaslon": "kds",
  "kukhnenski-displei": "kds",
  "kukhonnyy-displey": "kds",
  "laudade-broneerimine": "bookings",
  "masa-rezervasyonu": "bookings",
  "meniu-digital-restaurant": "digital",
  "meniu-qr-cod-restaurant": "qr",
  "menooye-dijital-restoran": "digital",
  "menooye-qr-restoran": "qr",
  "menu-digital-restaurantes": "digital",
  "menu-digital-restaurants": "digital",
  "menu-digitale-ristoranti": "digital",
  "menu-qr-code-restaurant": "qr",
  "menu-qr-code-ristoranti": "qr",
  "menu-qr-kod-restauracja": "qr",
  "mutfak-ekrani": "kds",
  "namayeshgar-ashpazkhane": "kds",
  "nizam-talabat-matam": "orders",
  "objednavkovy-system-restaurace": "orders",
  "objednavkovy-system-restauracia": "orders",
  "othoni-mageirio": "kds",
  "pantalla-de-cocina": "kds",
  "pantalla-de-cuina": "kds",
  "pasutijumu-sistema-restorans": "orders",
  "pontunarkerfi-veitingastaur": "orders",
  "poytavaraus": "bookings",
  "prenotazione-tavoli": "bookings",
  "priem-zakazov-restoran": "orders",
  "pryjom-zamovlen-restoran": "orders",
  "psifiako-menou-estiatoria": "digital",
  "qaimat-taam-raqmiya-matam": "digital",
  "qr-cai-dan-can-ting": "qr",
  "qr-code-menu-for-restaurants": "qr",
  "qr-code-menu-restaurantes": "qr",
  "qr-code-menukaart-restaurant": "qr",
  "qr-code-speisekarte-restaurant": "qr",
  "qr-kod-etlap-etterem": "qr",
  "qr-kod-menu-restoran": "qr",
  "qr-kod-meny-restaurang": "qr",
  "qr-koda-izvelne-restorans": "qr",
  "qr-kode-menukort-restaurant": "qr",
  "qr-kode-meny-restaurant": "qr",
  "qr-kodo-meniu-restoranas": "qr",
  "qr-kood-menuu-restoran": "qr",
  "qr-koodi-ruokalista-ravintola": "qr",
  "qr-matsedill-veitingastadur": "qr",
  "qr-meni-restavracija": "qr",
  "qr-meni-restoran": "qr",
  "qr-menou-estiatorio": "qr",
  "qr-menu-matam": "qr",
  "qr-menu-restaurace": "qr",
  "qr-menu-restauracia": "qr",
  "qr-menu-resutoran": "qr",
  "qr-menyu-restoran": "qr",
  "qr-menyu-restorant": "qr",
  "qr-menyu-resutorang": "qr",
  "rendelesi-rendszer-etterem": "orders",
  "reserva-de-mesas": "bookings",
  "reserva-de-taules": "bookings",
  "reservas-de-mesas": "bookings",
  "reservation-tables": "bookings",
  "restaurant-bestellsystem": "orders",
  "restaurant-ordering-system": "orders",
  "restoran-siparis-sistemi": "orders",
  "rezervace-stolu": "bookings",
  "rezervacia-stolov": "bookings",
  "rezervacija-miz": "bookings",
  "rezervacija-stolova": "bookings",
  "rezervare-mese": "bookings",
  "rezervatsiya-masi": "bookings",
  "rezerve-miz": "bookings",
  "rezerwacja-stolikow": "bookings",
  "scailean-cistine": "kds",
  "shashat-matbakh": "kds",
  "shu-zi-cai-dan-can-ting": "digital",
  "sistem-comenzi-restaurant": "orders",
  "sistem-narocanja-restavracija": "orders",
  "sistem-porudzbina-restoran": "orders",
  "sistem-sefaresh-restoran": "orders",
  "sistema-comandes-restaurant": "orders",
  "sistema-de-pedidos-restaurante": "orders",
  "sistema-ordinazioni-ristorante": "orders",
  "sistema-pedidos-restaurante": "orders",
  "sistema-porachki-restorant": "orders",
  "skaitmeninis-meniu-restoranas": "digital",
  "stafraen-matsedill-veitingastaur": "digital",
  "staliuku-rezervacija": "bookings",
  "sustav-narudzbi-restoran": "orders",
  "system-zamowien-restauracja": "orders",
  "systeme-commandes-restaurant": "orders",
  "systima-paragelion-estiatorio": "orders",
  "table-booking-system": "bookings",
  "tafel-reserveren": "bookings",
  "tebeul-yeyak": "bookings",
  "tellimissusteem-restoran": "orders",
  "tesuto-yoyaku": "bookings",
  "tilausjarjestelma-ravintola": "orders",
  "tisch-reservierung": "bookings",
  "tsifrovoe-menyu": "digital",
  "tsyfrove-menyu-restoran": "digital",
  "uzsakymu-sistema-restoranas": "orders",
  "virtuves-ekranas": "kds",
  "virtuves-ekrans": "kds",
  "yu-ding-zhuo-wei": "bookings",
};

/** Collapse a raw `trackPrefix` (l_, optionally l_<locale>_) to `l_<feature>`. */
export function stablePrefix(raw: string | undefined | null): string {
  const base = (raw || "l_feature").replace(/^l_/, "").replace(/^[a-z]{2}_/, "");
  return `l_${base}`;
}

/** Feature token without the `l_` prefix (e.g. "kds", "home", "pricing"). */
export function featureKey(raw: string | undefined | null): string {
  return stablePrefix(raw).slice(2);
}

/** Map a (possibly locale-prefixed) href to a stable feature token. */
export function featureKeyFromHref(href: string): string {
  const clean = href.split("?")[0].split("#")[0].replace(/^\/+/, "").replace(/\/+$/, "");
  if (!clean) return "home";
  let parts = clean.split("/");
  if (parts.length > 1 && /^[a-z]{2}$/.test(parts[0])) parts = parts.slice(1);
  const slug = parts[0] || "home";
  if (slug === "pricing") return "pricing";
  if (slug === "help") return "help";
  return FEATURE_BY_SLUG[slug] || slug.replace(/[^a-z0-9]+/gi, "_").toLowerCase();
}
