import { Check } from "lucide-react";
import { Section } from "@/app/_landing/components/section";

const BENEFITS = ["QR σε κάθε τραπέζι, σκάναρε-και-παράγγειλε, χωρίς εφαρμογή", "Παραγγελίες σε πραγματικό χρόνο στο tablet κουζίνας ή του manager", "Ή στο WhatsApp του εστιατορίου — εσύ διαλέγεις", "Modifiers, παραλλαγές και αλλεργιογόνα μπαίνουν στο δελτίο", "Ελεύθερο σχόλιο πελάτη σε κάθε παραγγελία", "Ημερήσια αρίθμηση για την κουζίνα", "Πολύγλωσσο checkout σε 35 γλώσσες, βάσει κινητού πελάτη", "Μηδέν προμήθεια ανά παραγγελία — σταθερή μηνιαία συνδρομή"];
const HOW_STEPS = [
  { title: "Ενεργοποίησε τις παραγγελίες για το εστιατόριο", desc: "Άνοιξε τις ρυθμίσεις του εστιατορίου, ενεργοποίησε τον διακόπτη Παραγγελίες και επίλεξε ποια πεδία πελάτη (όνομα, τηλέφωνο, διεύθυνση) να συλλέγονται." },
  { title: "Επίλεξε κανάλι παράδοσης", desc: "Η εσωτερική λειτουργία στέλνει τις νέες παραγγελίες στην καρτέλα Κουζίνα. Η λειτουργία WhatsApp μορφοποιεί την παραγγελία ως μήνυμα στο WhatsApp του εστιατορίου. Ή και τα δύο παράλληλα." },
  { title: "Τύπωσε και κόλλησε QR", desc: "Κατέβασε QR (ένα ανά τραπέζι ή ένα ανά εστιατόριο) σε PDF ή PNG και κόλλα στα τραπέζια. Οι πελάτες σκανάρουν με την κάμερά τους — χωρίς App Store, χωρίς τριβή." },
  { title: "Δούλεψε τη βάρδια", desc: "Οι παραγγελίες εμφανίζονται στην καρτέλα Κουζίνα με αριθμό τραπεζιού, πιάτα, παραλλαγές, αλλεργιογόνα, σχόλιο και ημερήσιο αριθμό. Μετάβαση νέα → σε εξέλιξη → έτοιμη. Ο browser του πελάτη ενημερώνεται σε πραγματικό χρόνο." },
];
const COMPARISON_ROWS = [["Προμήθεια ανά παραγγελία","20–30%","0%","0% (€6,90/μήνα σταθερά)"],["Πού πάει η παραγγελία","Εφαρμογή aggregator","Το ταμείο σου","Tablet κουζίνας ή WhatsApp"],["Αριθμός τραπεζιού στο δελτίο","Όχι","Χειροκίνητα","Ναι, αυτόματα"],["Modifiers / παραλλαγές","Περιορισμένα","Ναι","Ναι, με αλλεργιογόνα"],["Πολύγλωσσο checkout","Γλώσσα της εφαρμογής τους","Όχι","35 γλώσσες, αυτόματα"],["Απαιτούμενο hardware","Tablet aggregator","POS terminal","Οποιοδήποτε tablet με browser"],["Χρόνος ρύθμισης","Onboarding κλήση","Μέρες-εβδομάδες","5 λεπτά"]];

export function SeoContent() {
  return (<>
    <Section dataSection="seo-intro"><div className="max-w-4xl mx-auto"><p className="text-xs font-medium uppercase tracking-widest text-primary mb-3 text-center">Αναλυτικά</p><h2 className="text-3xl sm:text-4xl lg:text-5xl font-medium tracking-tight mb-3 text-center">Τι είναι ένα online σύστημα παραγγελιών για εστιατόριο <span className="text-muted-foreground">στην πραγματικότητα</span></h2><p className="text-base sm:text-lg text-muted-foreground mb-10 text-center">Όχι marketplace. Όχι aggregator delivery. Άμεση γραμμή από το κινητό του πελάτη στο τραπέζι σου, στο tablet κουζίνας — ή στο WhatsApp.</p><div className="space-y-4 text-base sm:text-lg text-foreground/90 leading-relaxed"><p><strong>Online σύστημα παραγγελιών για εστιατόριο</strong> με την έννοια του IQ Rest είναι λογισμικό που επιτρέπει στον πελάτη στο τραπέζι σου να ανοίξει το μενού στο κινητό, να φτιάξει καλάθι και να στείλει παραγγελία στην κουζίνα — χωρίς efood, Wolt, Bolt Food ή άλλο marketplace. Ο πελάτης δεν φεύγει από το QR μενού σου, εσύ δεν πληρώνεις προμήθεια, και το δελτίο φτάνει με τον πραγματικό αριθμό τραπεζιού.</p><p>Το IQ Rest στηρίζεται σε δύο κανάλια. Από προεπιλογή <em>εσωτερική λειτουργία</em>: κάθε νέα παραγγελία φτάνει στην καρτέλα Κουζίνα του πάνελ σε tablet, κινητό ή laptop στο πάσο — με αριθμό τραπεζιού, πιάτα με παραλλαγές και αλλεργιογόνα, ελεύθερο σχόλιο πελάτη και ημερήσιο αριθμό παραγγελίας. Εναλλακτικά, <em>λειτουργία WhatsApp</em>: η ίδια παραγγελία μορφοποιείται ως μήνυμα στο WhatsApp του εστιατορίου. Χρήσιμο για μικρές ομάδες, κυρίως takeaway ή όταν ο manager είναι εκτός χώρου. Και οι δύο λειτουργίες μπορούν να τρέχουν παράλληλα.</p></div></div></Section>
    <Section dataSection="seo-benefits"><div className="max-w-4xl mx-auto"><h3 className="text-2xl sm:text-3xl font-medium tracking-tight mb-6 text-center">Τι παίρνεις πραγματικά</h3><div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-3 sm:gap-4">{BENEFITS.map((b) => (<div key={b} className="bg-muted/20 border border-border rounded-2xl p-4 sm:p-5 flex flex-row items-center gap-3"><div className="h-8 w-8 rounded-lg bg-primary/10 text-primary flex items-center justify-center shrink-0"><Check className="h-4 w-4" strokeWidth={2.5} /></div><p className="text-sm sm:text-base text-foreground/90 leading-snug">{b}</p></div>))}</div></div></Section>
    <Section dataSection="seo-how"><div className="max-w-4xl mx-auto"><h3 className="text-2xl sm:text-3xl font-medium tracking-tight mb-6 text-center">Πώς δουλεύει η ροή παραγγελιών του IQ Rest</h3><p className="text-base sm:text-lg text-foreground/90 leading-relaxed mb-6 text-center">Τέσσερις διακόπτες στο πάνελ — και είσαι στον αέρα. Χωρίς εγκαταστάτη, χωρίς POS hardware, χωρίς έργο integration.</p><div className="grid grid-cols-1 sm:grid-cols-2 gap-3 sm:gap-4">{HOW_STEPS.map((s, i) => (<div key={s.title} className="bg-muted/20 border border-border rounded-2xl p-5 flex flex-row items-start gap-4"><div className="h-10 w-10 rounded-lg bg-primary text-primary-foreground flex items-center justify-center shrink-0 font-semibold text-base">{i + 1}</div><div className="flex-1 min-w-0"><div className="text-base sm:text-lg font-semibold tracking-tight mb-1">{s.title}</div><p className="text-sm text-muted-foreground leading-relaxed">{s.desc}</p></div></div>))}</div></div></Section>
    <Section dataSection="seo-table"><div className="max-w-4xl mx-auto"><h3 className="text-2xl sm:text-3xl font-medium tracking-tight mb-6 text-center">Aggregator, κλασικό POS ή σύστημα παραγγελιών</h3><div className="bg-muted/20 border border-border rounded-2xl p-4 sm:p-6 overflow-x-auto"><table className="w-full text-sm sm:text-base border-collapse"><thead><tr className="border-b border-border"><th className="text-left font-semibold py-3 pr-3 text-foreground">Χαρακτηριστικό</th><th className="text-left font-semibold py-3 pr-3 text-muted-foreground">Aggregator delivery</th><th className="text-left font-semibold py-3 pr-3 text-muted-foreground">Κλασικό POS</th><th className="text-left font-semibold py-3 text-primary">Παραγγελίες IQ Rest</th></tr></thead><tbody className="text-foreground/90">{COMPARISON_ROWS.map((row, i) => (<tr key={row[0]} className={i < COMPARISON_ROWS.length - 1 ? "border-b border-border/50" : ""}><td className="py-3 pr-3 font-medium">{row[0]}</td><td className="py-3 pr-3 text-muted-foreground">{row[1]}</td><td className="py-3 pr-3 text-muted-foreground">{row[2]}</td><td className="py-3 text-foreground">{row[3]}</td></tr>))}</tbody></table></div><p className="text-sm text-muted-foreground leading-relaxed mt-6 text-center">Ένα online σύστημα παραγγελιών που το εστιατόριο ορίζει μόνο του αποσβένεται το πρώτο σαββατοκύριακο — κάθε ευρώ που ξοδεύει ο πελάτης στον χώρο σου μένει στον χώρο σου, και το δελτίο στο πάσο έχει πάντα τον πραγματικό αριθμό τραπεζιού.</p></div></Section>
  </>);
}
