import { Check } from "lucide-react";
import { Section } from "@/app/_landing/components/section";

const BENEFITS = ["QR روی هر میز، اسکن کن و سفارش بده، بدون اپ", "سفارش آنی روی تبلت آشپزخانه یا مدیر", "یا در واتس‌اپ رستوران — تو انتخاب می‌کنی", "آپشن، انواع و آلرژن روی فیش می‌آید", "کامنت آزاد مهمان روی هر سفارش", "شماره‌گذاری روزانه برای آشپزخانه", "چک‌اوت چندزبانه به ۳۵ زبان، بر اساس گوشی مهمان", "صفر کمیسیون به‌ازای سفارش — اشتراک ماهانهٔ ثابت"];
const HOW_STEPS = [
  { title: "سفارش‌ها را برای رستوران فعال کن", desc: "تنظیمات رستوران را باز کن، کلید سفارش‌ها را روشن کن و انتخاب کن کدام فیلدهای مهمان (نام، تلفن، آدرس) جمع شود." },
  { title: "کانال تحویل را انتخاب کن", desc: "حالت داخلی سفارش‌های جدید را به زبانهٔ آشپزخانه می‌فرستد. حالت واتس‌اپ سفارش را به‌صورت پیام در واتس‌اپ رستوران فرمت می‌کند. یا هر دو موازی." },
  { title: "QR را چاپ و نصب کن", desc: "QR را (یکی برای هر میز یا یکی برای کل رستوران) به PDF یا PNG دانلود کن و روی میزها بچسبان. مهمان‌ها با دوربین گوشی اسکن می‌کنند — بدون App Store، بدون اصطکاک." },
  { title: "شیفت کار را پیش ببر", desc: "سفارش‌ها در زبانهٔ آشپزخانه با شمارهٔ میز، غذا، آپشن، آلرژن، کامنت و شمارهٔ روزانه ظاهر می‌شوند. مرحلهٔ جدید → در حال انجام → آماده. مرورگر مهمان لحظه‌ای به‌روز می‌شود." },
];
const COMPARISON_ROWS = [["کمیسیون به‌ازای سفارش","۲۰–۳۰٪","۰٪","۰٪ (۶٫۹۰ یورو در ماه ثابت)"],["مقصد سفارش","اپلیکیشن واسطه","صندوق شما","تبلت آشپزخانه یا واتس‌اپ شما"],["شمارهٔ میز روی فیش","ندارد","دستی","بله، خودکار"],["آپشن / انواع","محدود","بله","بله، با آلرژن"],["چک‌اوت چندزبانه","زبان اپ خودشان","ندارد","۳۵ زبان، خودکار"],["سخت‌افزار لازم","تبلت واسطه","پایانهٔ POS","هر تبلتی با مرورگر"],["زمان راه‌اندازی","تماس آنبوردینگ","روز-هفته","۵ دقیقه"]];

export function SeoContent() {
  return (<>
    <Section dataSection="seo-intro"><div className="max-w-4xl mx-auto"><p className="text-xs font-medium uppercase tracking-widest text-primary mb-3 text-center">با جزئیات</p><h2 className="text-3xl sm:text-4xl lg:text-5xl font-medium tracking-tight mb-3 text-center">سیستم سفارش آنلاین برای رستوران <span className="text-muted-foreground">واقعاً چیست</span></h2><p className="text-base sm:text-lg text-muted-foreground mb-10 text-center">نه مارکت‌پلیس. نه اپلیکیشن پیک. خط مستقیم از گوشی مهمان سر میز شما تا تبلت آشپزخانه — یا واتس‌اپ.</p><div className="space-y-4 text-base sm:text-lg text-foreground/90 leading-relaxed"><p><strong>سیستم سفارش آنلاین برای رستوران</strong> به معنای IQ Rest نرم‌افزاری است که به مهمان سر میز شما اجازه می‌دهد منو را در گوشی باز کند، سبد را بچیند و سفارش را به آشپزخانه بفرستد — بدون اسنپ‌فود، تپسی‌فود، Wolt یا هر مارکت‌پلیس دیگری. مهمان هرگز از منوی QR شما خارج نمی‌شود، شما کمیسیونی پرداخت نمی‌کنید و فیش با شمارهٔ میز واقعی می‌رسد.</p><p>IQ Rest حول دو کانال ساخته شده. به‌صورت پیش‌فرض <em>حالت داخلی</em>: هر سفارش جدید در زبانهٔ آشپزخانهٔ پنل روی تبلت، گوشی یا لپ‌تاپ کنار پاس می‌رسد — با شمارهٔ میز، غذا با آپشن و آلرژن، کامنت آزاد مهمان و شمارهٔ روزانهٔ سفارش. جایگزین <em>حالت واتس‌اپ</em> است: همان سفارش به‌عنوان پیام در واتس‌اپ رستوران فرمت می‌شود. مفید برای تیم‌های کوچک، عمدتاً تحویل یا وقتی مدیر در سالن نیست. هر دو حالت می‌توانند هم‌زمان کار کنند.</p></div></div></Section>
    <Section dataSection="seo-benefits"><div className="max-w-4xl mx-auto"><h3 className="text-2xl sm:text-3xl font-medium tracking-tight mb-6 text-center">چه چیزی واقعاً به دست می‌آوری</h3><div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-3 sm:gap-4">{BENEFITS.map((b) => (<div key={b} className="bg-muted/20 border border-border rounded-2xl p-4 sm:p-5 flex flex-row items-center gap-3"><div className="h-8 w-8 rounded-lg bg-primary/10 text-primary flex items-center justify-center shrink-0"><Check className="h-4 w-4" strokeWidth={2.5} /></div><p className="text-sm sm:text-base text-foreground/90 leading-snug">{b}</p></div>))}</div></div></Section>
    <Section dataSection="seo-how"><div className="max-w-4xl mx-auto"><h3 className="text-2xl sm:text-3xl font-medium tracking-tight mb-6 text-center">جریان سفارش IQ Rest چطور کار می‌کند</h3><p className="text-base sm:text-lg text-foreground/90 leading-relaxed mb-6 text-center">چهار کلید در پنل — و آنلاین هستی. بدون نصاب، بدون سخت‌افزار POS، بدون پروژهٔ یکپارچه‌سازی.</p><div className="grid grid-cols-1 sm:grid-cols-2 gap-3 sm:gap-4">{HOW_STEPS.map((s, i) => (<div key={s.title} className="bg-muted/20 border border-border rounded-2xl p-5 flex flex-row items-start gap-4"><div className="h-10 w-10 rounded-lg bg-primary text-primary-foreground flex items-center justify-center shrink-0 font-semibold text-base">{i + 1}</div><div className="flex-1 min-w-0"><div className="text-base sm:text-lg font-semibold tracking-tight mb-1">{s.title}</div><p className="text-sm text-muted-foreground leading-relaxed">{s.desc}</p></div></div>))}</div></div></Section>
    <Section dataSection="seo-table"><div className="max-w-4xl mx-auto"><h3 className="text-2xl sm:text-3xl font-medium tracking-tight mb-6 text-center">واسطه، POS کلاسیک یا سیستم سفارش</h3><div className="bg-muted/20 border border-border rounded-2xl p-4 sm:p-6 overflow-x-auto"><table className="w-full text-sm sm:text-base border-collapse"><thead><tr className="border-b border-border"><th className="text-right font-semibold py-3 pr-3 text-foreground">ویژگی</th><th className="text-right font-semibold py-3 pr-3 text-muted-foreground">اپلیکیشن پیک</th><th className="text-right font-semibold py-3 pr-3 text-muted-foreground">POS کلاسیک</th><th className="text-right font-semibold py-3 text-primary">سفارش‌های IQ Rest</th></tr></thead><tbody className="text-foreground/90">{COMPARISON_ROWS.map((row, i) => (<tr key={row[0]} className={i < COMPARISON_ROWS.length - 1 ? "border-b border-border/50" : ""}><td className="py-3 pr-3 font-medium">{row[0]}</td><td className="py-3 pr-3 text-muted-foreground">{row[1]}</td><td className="py-3 pr-3 text-muted-foreground">{row[2]}</td><td className="py-3 text-foreground">{row[3]}</td></tr>))}</tbody></table></div><p className="text-sm text-muted-foreground leading-relaxed mt-6 text-center">سیستم سفارش آنلاینی که خود رستوران مالک آن است در همان آخر هفتهٔ اول خود را پرداخت می‌کند — هر یورویی که مهمان در سالن شما خرج می‌کند در سالن شما می‌ماند، و فیش کنار پاس همیشه با شمارهٔ میز واقعی است.</p></div></Section>
  </>);
}
