import { Check } from "lucide-react";
import { Section } from "@/app/_landing/components/section";

const BENEFITS = ["QR na každém stole, naskenuj-a-objednej, bez aplikace", "Objednávky v reálném čase na tabletu kuchyně nebo manažera", "Nebo do WhatsAppu restaurace — vy si vybíráte", "Modifikátory, varianty a alergeny jdou do tiketu", "Volný komentář hosta v každé objednávce", "Denní číslování pro kuchyň", "Vícejazyčný checkout v 35 jazycích, podle telefonu hosta", "Nulová provize z objednávky — fixní měsíční předplatné"];
const HOW_STEPS = [
  { title: "Zapněte objednávky pro restauraci", desc: "Otevřete nastavení restaurace, aktivujte přepínač Objednávky a vyberte, která pole hosta (jméno, telefon, adresa) sbírat." },
  { title: "Vyberte kanál doručení", desc: "Interní režim posílá nové objednávky do záložky Kuchyň. Režim WhatsApp formátuje objednávku jako zprávu do WhatsAppu restaurace. Nebo oba paralelně." },
  { title: "Vytiskněte a nalepte QR", desc: "Stáhněte QR (jeden na stůl nebo jeden na restauraci) v PDF nebo PNG a nalepte na stoly. Hosté skenují vlastní kamerou — bez App Store, bez tření." },
  { title: "Odjeďte směnu", desc: "Objednávky se objevují v záložce Kuchyň s číslem stolu, jídly, variantami, alergeny, komentářem a denním číslem. Přechod nová → v práci → hotová. Prohlížeč hosta se aktualizuje v reálném čase." },
];
const COMPARISON_ROWS = [["Provize z objednávky","20–30%","0%","0% (€6,90/měs fix)"],["Kam jde objednávka","Aplikace agregátoru","Vaše pokladna","Váš kuchyňský tablet nebo WhatsApp"],["Číslo stolu na tiketu","Není","Ručně","Ano, automaticky"],["Modifikátory / varianty","Omezené","Ano","Ano, s alergeny"],["Vícejazyčný checkout","Jazyk jejich aplikace","Není","35 jazyků, automaticky"],["Potřebný hardware","Tablet agregátora","POS terminál","Jakýkoliv tablet s prohlížečem"],["Čas nastavení","Onboarding hovor","Dny-týdny","5 minut"]];

export function SeoContent() {
  return (<>
    <Section dataSection="seo-intro"><div className="max-w-4xl mx-auto"><p className="text-xs font-medium uppercase tracking-widest text-primary mb-3 text-center">Podrobně</p><h2 className="text-3xl sm:text-4xl lg:text-5xl font-medium tracking-tight mb-3 text-center">Co je online objednávkový systém pro restauraci <span className="text-muted-foreground">doopravdy</span></h2><p className="text-base sm:text-lg text-muted-foreground mb-10 text-center">Žádný marketplace. Žádný rozvozový agregátor. Přímá linka z telefonu hosta u vašeho stolu na kuchyňský tablet — nebo do WhatsAppu.</p><div className="space-y-4 text-base sm:text-lg text-foreground/90 leading-relaxed"><p><strong>Online objednávkový systém pro restauraci</strong> ve smyslu IQ Rest je software, který hostovi u vašeho stolu umožní otevřít menu v telefonu, sestavit košík a poslat objednávku do kuchyně — bez Uber Eats, Wolt, Bolt Food nebo jiného marketplace. Host nikdy neopouští vaše QR menu, vy neplatíte provizi z objednávky a tiket přijde se skutečným číslem stolu.</p><p>IQ Rest stojí na dvou kanálech. Výchozí je <em>interní režim</em>: každá nová objednávka přijde do záložky Kuchyň panelu na tabletu, telefonu nebo notebooku u výdeje — s číslem stolu, jídly s variantami a alergeny, volným komentářem hosta a denním číslem objednávky. Alternativa je <em>režim WhatsApp</em>: stejná objednávka se zformátuje jako zpráva do WhatsAppu restaurace. Užitečné pro malé týmy, převážně vyzvednutí nebo když je manažer mimo sál. Oba režimy mohou běžet současně.</p></div></div></Section>
    <Section dataSection="seo-benefits"><div className="max-w-4xl mx-auto"><h3 className="text-2xl sm:text-3xl font-medium tracking-tight mb-6 text-center">Co reálně dostanete</h3><div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-3 sm:gap-4">{BENEFITS.map((b) => (<div key={b} className="bg-muted/20 border border-border rounded-2xl p-4 sm:p-5 flex flex-row items-center gap-3"><div className="h-8 w-8 rounded-lg bg-primary/10 text-primary flex items-center justify-center shrink-0"><Check className="h-4 w-4" strokeWidth={2.5} /></div><p className="text-sm sm:text-base text-foreground/90 leading-snug">{b}</p></div>))}</div></div></Section>
    <Section dataSection="seo-how"><div className="max-w-4xl mx-auto"><h3 className="text-2xl sm:text-3xl font-medium tracking-tight mb-6 text-center">Jak funguje objednávkový tok IQ Rest</h3><p className="text-base sm:text-lg text-foreground/90 leading-relaxed mb-6 text-center">Čtyři přepínače v panelu — a jste v provozu. Bez instalátora, bez POS hardwaru, bez integračního projektu.</p><div className="grid grid-cols-1 sm:grid-cols-2 gap-3 sm:gap-4">{HOW_STEPS.map((s, i) => (<div key={s.title} className="bg-muted/20 border border-border rounded-2xl p-5 flex flex-row items-start gap-4"><div className="h-10 w-10 rounded-lg bg-primary text-primary-foreground flex items-center justify-center shrink-0 font-semibold text-base">{i + 1}</div><div className="flex-1 min-w-0"><div className="text-base sm:text-lg font-semibold tracking-tight mb-1">{s.title}</div><p className="text-sm text-muted-foreground leading-relaxed">{s.desc}</p></div></div>))}</div></div></Section>
    <Section dataSection="seo-table"><div className="max-w-4xl mx-auto"><h3 className="text-2xl sm:text-3xl font-medium tracking-tight mb-6 text-center">Agregátor, klasický POS nebo objednávkový systém</h3><div className="bg-muted/20 border border-border rounded-2xl p-4 sm:p-6 overflow-x-auto"><table className="w-full text-sm sm:text-base border-collapse"><thead><tr className="border-b border-border"><th className="text-left font-semibold py-3 pr-3 text-foreground">Vlastnost</th><th className="text-left font-semibold py-3 pr-3 text-muted-foreground">Rozvozový agregátor</th><th className="text-left font-semibold py-3 pr-3 text-muted-foreground">Klasický POS</th><th className="text-left font-semibold py-3 text-primary">Objednávky IQ Rest</th></tr></thead><tbody className="text-foreground/90">{COMPARISON_ROWS.map((row, i) => (<tr key={row[0]} className={i < COMPARISON_ROWS.length - 1 ? "border-b border-border/50" : ""}><td className="py-3 pr-3 font-medium">{row[0]}</td><td className="py-3 pr-3 text-muted-foreground">{row[1]}</td><td className="py-3 pr-3 text-muted-foreground">{row[2]}</td><td className="py-3 text-foreground">{row[3]}</td></tr>))}</tbody></table></div><p className="text-sm text-muted-foreground leading-relaxed mt-6 text-center">Online objednávkový systém, který restaurace vlastní sama, se zaplatí za první víkend — každá koruna, kterou host utratí ve vašem sále, zůstává ve vašem sále, a tiket u výdeje je vždy se skutečným číslem stolu.</p></div></Section>
  </>);
}
