import { QrCode, MessageCircle, ChefHat, Settings2, Languages, BarChart3 } from "lucide-react";
import type { LandingTexts } from "@/app/_landing/types";

export const TEXTS: LandingTexts = {
  htmlLang: "cs",
  htmlDir: "ltr",
  meta: {
    title: "Online objednávkový systém pro restauraci — QR a WhatsApp | IQ Rest",
    description: "Online objednávkový systém pro restauraci: host naskenuje QR u stolu, sestaví objednávku a ta dorazí přímo na váš kuchyňský tablet nebo WhatsApp. Bez provize, s číslem stolu. 14 dní zdarma.",
    canonical: "https://iq-rest.com/cs/online-objednavkovy-system-restaurace",
    ogLocale: "cs_CZ",
    ogTitle: "Online objednávkový systém pro restauraci — Přímo do kuchyně",
    ogDescription: "Host naskenuje QR u stolu, sestaví objednávku a ta dorazí na váš tablet nebo WhatsApp — bez agregátoru, bez provize, s číslem stolu na každém tiketu.",
  },
  ctaText: "Zapnout objednávky",
  demoText: "Živé demo",
  microcopy: "Od €6,90/měs · 14 dní zdarma · Zruš kdykoliv",
  header: { navFeatures: "Funkce", navHow: "Jak to funguje", navPricing: "Ceny", navFaq: "FAQ", signIn: "Přihlásit", cta: "Vyzkoušet" },
  hero: {
    verticals: ["Restaurace", "Kavárny", "Bistra", "Pizzerie", "Bary", "Pivnice"],
    headline: "Online objednávkový systém pro restauraci.",
    sub: "Host naskenuje QR svého stolu, sestaví objednávku v telefonu — a tiket dorazí přímo na váš kuchyňský tablet nebo WhatsApp restaurace. Bez agregátoru, bez provize, s číslem stolu na každém tiketu.",
    dynamicHeadlines: ["Objednávka u stolu.", "Přímo na kuchyňský tablet.", "Nebo přímo do WhatsAppu.", "Bez provize.", "S číslem stolu."],
    painBullets: [
      "Online objednávkový systém, který restaurace vlastní sama — bez prostředníků, bez provize.",
      "Objednávky chodí na tablet kuchyně nebo manažera s číslem stolu, modifikátory, alergeny a poznámkami.",
      "Nebo se posílají přímo do WhatsAppu restaurace — ideální pro vyzvednutí a malé týmy.",
      "QR na každý stůl (nebo jeden pro celý sál) se generuje automaticky.",
    ],
    rating: "500+ restaurací ve 30+ zemích",
  },
  features: {
    heading: "Objednávkový systém,",
    headingAccent: "vyrobený pro stůl.",
    sub: "Reálná funkcionalita — ne klon rozvozových agregátorů.",
    items: [
      { Icon: QrCode, title: "QR menu s košíkem na každý stůl", desc: "Host naskenuje QR, prohlíží menu ve svém jazyce, přidává jídla s modifikátory, nechá poznámku pro kuchyň a odešle. Bez aplikace.", tag: "QR objednávání" },
      { Icon: ChefHat, title: "Objednávky na kuchyňském tabletu", desc: "Každá nová objednávka se objeví v záložce Kuchyň — na tabletu u výdeje — s číslem stolu, jídly, variantami, alergeny a komentářem. Jedním klepnutím z „v práci“ na „hotovo“.", tag: "Pohled kuchyně" },
      { Icon: MessageCircle, title: "Nebo do WhatsAppu", desc: "Přepněte restauraci do režimu WhatsApp (nebo oba současně) — každá objednávka přijde do WhatsAppu jako formátovaná zpráva. Ideální pro vyzvednutí nebo malé týmy.", tag: "Režim WhatsApp" },
      { Icon: Settings2, title: "Modifikátory, varianty a alergeny", desc: "Každé jídlo má skupiny variant (velikost, propečení, přídavky) s rozdílem v ceně, štítky alergenů a volný popis. Košík všechno zaúčtuje — tiket na tabletu je bez nejasností.", tag: "Skutečný košík" },
      { Icon: Languages, title: "Vícejazyčný checkout", desc: "Celý průběh objednávky — košík, modifikátory, komentář, potvrzení — je přeložen do 35 jazyků a automaticky se přizpůsobuje jazyku telefonu hosta.", tag: "35 jazyků" },
      { Icon: BarChart3, title: "Denní číslování a deník", desc: "Každá objednávka dostane denní číslo pro kuchyň, jde do deníku se sumami a časovými značkami, krmí analytiku. Storna jsou soft-delete, reporty zůstávají čisté.", tag: "Deník objednávek" },
    ],
  },
  founder: {
    eyebrow: "Vyrobeno majitelem kavárny, ne rozvozovým startupem",
    quoteStart: "S manželkou jsme otevřeli kavárnu a týdny hledali způsob, jak přijímat objednávky od stolu, který by nedával 30 % agregátoru a nevyžadoval pokladnu za 1500 €. Vše, co jsme zkoušeli, bylo neohrabané, drahé nebo bez základních věcí —",
    quoteAccent: "tak jsme postavili objednávkový systém, který jsme sami chtěli mít.",
    sign: "Bogdan Sokolov · zakladatel, ex-majitel kavárny",
    photoAlt: "Bogdan, zakladatel IQ Rest",
  },
  how: {
    heading: "Zapněte objednávkový systém",
    headingAccent: "ve 4 krocích",
    sub: "Bez instalace, bez integrátora, bez volání ajťákovi. Jen telefon a 5 minut.",
    steps: [
      { n: "1", t: "Vytvořte restauraci", d: "Registrace e-mailem nebo Google — 30 sekund." },
      { n: "2", t: "Přidejte menu", d: "Drag-and-drop nebo AI skenování papírového menu." },
      { n: "3", t: "Vyberte kanál", d: "Tablet kuchyně, WhatsApp nebo oba." },
      { n: "4", t: "Vytiskněte QR", d: "Jeden QR na stůl — hosté objednávají hned." },
    ],
  },
  pricing: {
    badge: "Neomezené objednávky · Nulová provize",
    heading: "Jeden tarif.",
    headingAccent: "Bez poplatku za objednávku.",
    sub: "Online objednávky, QR menu, režim WhatsApp, vícejazyčný checkout a analytika — vše v jednom předplatném. Bez procenta z transakce.",
    monthlyLabel: "Měsíčně",
    yearlyLabel: "Ročně",
    saveBadge: "Sleva 25%",
    perMonth: "měsíčně",
    billedAnnually: "Účtováno jednou ročně {total}",
    youSave: "Ušetříte {amount}",
    trust: { secure: "Předplatné přes Stripe", noCommitment: "Bez závazků", quick: "Aktivní za minuty", restaurants: "+500 restaurací" },
  },
  faq: {
    eyebrow: "Objednávkový systém — časté otázky",
    heading: "O objednávkovém",
    headingAccent: "systému.",
    sub: "Co se majitelé restaurací ptají před zapnutím online objednávek v IQ Rest. Nevidíte svou otázku? Napište na WhatsApp — odpovídají skuteční lidé.",
    whatsappCta: "Zeptat se na WhatsApp",
    whatsappPrefill: "Dobrý den, mám otázku k objednávkám IQ Rest",
    items: [
      { q: "Je to rozvozová platforma jako Wolt nebo Bolt Food?", a: "Ne, to je celé pointa. IQ Rest je vlastní objednávkový kanál restaurace: host objedná z vašeho QR, objednávka přijde na váš tablet nebo WhatsApp, vy servírujete. Žádný marketplace, žádný katalog agregátora — a my si nikdy nebereme část účtu." },
      { q: "Kde přesně se objednávky objevují?", a: "V záložce Kuchyň panelu IQ Rest na libovolném tabletu nebo telefonu u výdeje či baru. Každá objednávka ukazuje číslo stolu, jídla s variantami a alergeny, komentář hosta a denní číslo. Přechod „nová → v práci → hotová“ jedním klepnutím." },
      { q: "Mohou objednávky chodit do WhatsAppu místo toho?", a: "Ano. Každá restaurace má tři režimy: interní (jen kuchyňský tablet), WhatsApp (objednávka přijde jako zpráva do WhatsAppu restaurace) nebo oba současně. Režim je jeden přepínač v panelu, mění se kdykoliv." },
      { q: "Co je v objednávce?", a: "Jídla s variantami a přídavky (s rozdílem ceny), alergeny, číslo stolu, volný komentář hosta a — pokud zapnete pole — jméno, telefon a adresa. Stačí to k odeslání kurýra nebo zavolání ke stolu kvůli alergenu." },
      { q: "Mohou hosté platit online v menu?", a: "Ve výchozím nastavení — ne. IQ Rest je nastaven na platbu u stolu: host objedná, vy přinesete účet, platí se jako obvykle. Pokud potřebujete online platbu kartou (typické pro vyzvednutí), integrace Stripe Connect je možná na vyžádání — napište na WhatsApp." },
      { q: "Potřebuji speciální tablet, tiskárnu nebo POS hardware?", a: "Ne. Jakýkoliv tablet, notebook nebo telefon s prohlížečem — otevřete panel, přihlásíte se, necháte záložku Kuchyň. Pokud už máte POS — IQ Rest jede vedle, nenahrazuje pokladnu." },
      { q: "Co po 14 dnech zdarma?", a: "Bez platební metody se účet pozastaví — nikdy nestrháváme automaticky. Menu, objednávky a nastavení zůstávají; přidáte kartu, kdykoliv chcete pro reaktivaci. Zrušení jedním klepnutím, bez závazků." },
    ],
  },
  finalCta: {
    heading: "Zapněte objednávkový systém.",
    headingAccent: "Hotovo za 5 minut.",
    sub: "14 dní zdarma, bez karty. Zruš kdykoliv. Připojte se k 500+ restauracím, které spravují své objednávky přes IQ Rest.",
  },
  scan: {
    heading: "Z papírového menu na objednávkový systém",
    headingAccent: "za 60 sekund",
    sub: "Nahrajte foto menu — AI vytáhne kategorie, jídla a ceny přímo do editoru. Pak košík a QR — jedním klepnutím.",
    cta: "Naskenovat menu →",
  },
  footer: {
    featureLinks: [
      { href: "/cs/ai-translation", label: "AI překlad" },
      { href: "/cs/reservations", label: "Rezervace" },
      { href: "/cs/mobile-management", label: "Správa z telefonu" },
      { href: "/cs/easy-menu", label: "Editor menu" },
      { href: "/cs/custom-design", label: "Video a foto pozadí" },
      { href: "/cs/color-scheme", label: "Barvy značky" },
      { href: "/cs/multilingual", label: "Vícejazyčné menu" },
      { href: "/cs/ai-images", label: "AI optimalizace foto" },
      { href: "/cs/analytics", label: "Analytika" },
      { href: "/cs/instant-setup", label: "Okamžité spuštění" },
      { href: "/cs/personal-support", label: "Osobní podpora" },
    ],
    navLinks: [
      { href: "#pricing", label: "Ceny" },
      { href: "#faq", label: "Otázky" },
      { href: "/cs/changelog", label: "Novinky" },
      { href: "/cs/languages", label: "Změnit jazyk" },
    ],
    copyrightTemplate: "© {year} IQ Rest. Všechna práva vyhrazena.",
  },
};
