import { Check } from "lucide-react";
import { Section } from "@/app/_landing/components/section";

const BENEFITS = ["QR a cada taula, escaneja-i-demana, sense app", "Comandes en temps real a la tauleta de cuina o del manager", "O al WhatsApp del restaurant — tu tries", "Modificadors, variants i al·lèrgens entren al tiquet", "Comentari lliure del client a cada comanda", "Numeració diària per a la cuina", "Checkout multilingüe en 35 idiomes, segons el mòbil del client", "Zero comissions per comanda — quota mensual fixa"];
const HOW_STEPS = [
  { title: "Activa les comandes per al restaurant", desc: "Obre la configuració del restaurant, activa l'interruptor Comandes i tria quins camps del client (nom, telèfon, adreça) recollir." },
  { title: "Tria el canal de lliurament", desc: "El mode intern envia les comandes noves a la pestanya Cuina. El mode WhatsApp formata la comanda com a missatge al WhatsApp del restaurant. O tots dos en paral·lel." },
  { title: "Imprimeix i enganxa el QR", desc: "Descarrega el QR (un per taula o un per restaurant) en PDF o PNG i enganxa'l a les taules. Els clients escanegen amb la càmera nativa — sense App Store, sense friccions." },
  { title: "Treballa el torn", desc: "Les comandes apareixen a la pestanya Cuina amb número de taula, plats, variants, al·lèrgens, comentari i número del dia. Pas nova → en preparació → llesta. El navegador del client s'actualitza en temps real." },
];
const COMPARISON_ROWS = [["Comissió per comanda","20–30%","0%","0% (€6,90/mes fix)"],["On va la comanda","App de l'agregador","La teva caixa","La teva tauleta de cuina o WhatsApp"],["Número de taula al tiquet","No","Manual","Sí, automàtic"],["Modificadors / variants","Limitats","Sí","Sí, amb al·lèrgens"],["Checkout multilingüe","Idioma de la seva app","No","35 idiomes, automàtic"],["Maquinari necessari","Tauleta de l'agregador","TPV","Qualsevol tauleta amb navegador"],["Temps de posada en marxa","Trucada d'onboarding","Dies-setmanes","5 minuts"]];

export function SeoContent() {
  return (<>
    <Section dataSection="seo-intro"><div className="max-w-4xl mx-auto"><p className="text-xs font-medium uppercase tracking-widest text-primary mb-3 text-center">A fons</p><h2 className="text-3xl sm:text-4xl lg:text-5xl font-medium tracking-tight mb-3 text-center">Què és un sistema de comandes online per a restaurant <span className="text-muted-foreground">de debò</span></h2><p className="text-base sm:text-lg text-muted-foreground mb-10 text-center">No és un marketplace. No és un agregador de delivery. Línia directa des del mòbil del client a la teva taula fins a la tauleta de cuina — o al WhatsApp.</p><div className="space-y-4 text-base sm:text-lg text-foreground/90 leading-relaxed"><p><strong>Sistema de comandes online per a restaurant</strong>, en el sentit d'IQ Rest, és un software que permet al client a la teva taula obrir la carta al mòbil, omplir la cistella i enviar la comanda a la cuina — sense Uber Eats, Glovo, Bolt Food ni cap altre marketplace. El client no surt mai del teu QR, tu no pagues comissió per comanda, i el tiquet arriba amb el número de taula real.</p><p>IQ Rest està construït al voltant de dos canals. Per defecte, el <em>mode intern</em>: cada nova comanda arriba a la pestanya Cuina del panell, en una tauleta, mòbil o portàtil al pas — amb número de taula, plats amb variants i al·lèrgens, comentari lliure del client i número diari de la comanda. L'alternativa és el <em>mode WhatsApp</em>: la mateixa comanda es formata com a missatge al WhatsApp del restaurant. Útil per a equips petits, recollida principalment o quan el manager és fora de sala. Tots dos modes poden funcionar alhora.</p></div></div></Section>
    <Section dataSection="seo-benefits"><div className="max-w-4xl mx-auto"><h3 className="text-2xl sm:text-3xl font-medium tracking-tight mb-6 text-center">Què t'emportes de debò</h3><div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-3 sm:gap-4">{BENEFITS.map((b) => (<div key={b} className="bg-muted/20 border border-border rounded-2xl p-4 sm:p-5 flex flex-row items-center gap-3"><div className="h-8 w-8 rounded-lg bg-primary/10 text-primary flex items-center justify-center shrink-0"><Check className="h-4 w-4" strokeWidth={2.5} /></div><p className="text-sm sm:text-base text-foreground/90 leading-snug">{b}</p></div>))}</div></div></Section>
    <Section dataSection="seo-how"><div className="max-w-4xl mx-auto"><h3 className="text-2xl sm:text-3xl font-medium tracking-tight mb-6 text-center">Com funciona el flux de comandes d'IQ Rest</h3><p className="text-base sm:text-lg text-foreground/90 leading-relaxed mb-6 text-center">Quatre interruptors al panell — i estàs en línia. Sense instal·lador, sense maquinari TPV, sense projecte d'integració.</p><div className="grid grid-cols-1 sm:grid-cols-2 gap-3 sm:gap-4">{HOW_STEPS.map((s, i) => (<div key={s.title} className="bg-muted/20 border border-border rounded-2xl p-5 flex flex-row items-start gap-4"><div className="h-10 w-10 rounded-lg bg-primary text-primary-foreground flex items-center justify-center shrink-0 font-semibold text-base">{i + 1}</div><div className="flex-1 min-w-0"><div className="text-base sm:text-lg font-semibold tracking-tight mb-1">{s.title}</div><p className="text-sm text-muted-foreground leading-relaxed">{s.desc}</p></div></div>))}</div></div></Section>
    <Section dataSection="seo-table"><div className="max-w-4xl mx-auto"><h3 className="text-2xl sm:text-3xl font-medium tracking-tight mb-6 text-center">Agregador, TPV clàssic o sistema de comandes</h3><div className="bg-muted/20 border border-border rounded-2xl p-4 sm:p-6 overflow-x-auto"><table className="w-full text-sm sm:text-base border-collapse"><thead><tr className="border-b border-border"><th className="text-left font-semibold py-3 pr-3 text-foreground">Característica</th><th className="text-left font-semibold py-3 pr-3 text-muted-foreground">Agregador de delivery</th><th className="text-left font-semibold py-3 pr-3 text-muted-foreground">TPV clàssic</th><th className="text-left font-semibold py-3 text-primary">Comandes IQ Rest</th></tr></thead><tbody className="text-foreground/90">{COMPARISON_ROWS.map((row, i) => (<tr key={row[0]} className={i < COMPARISON_ROWS.length - 1 ? "border-b border-border/50" : ""}><td className="py-3 pr-3 font-medium">{row[0]}</td><td className="py-3 pr-3 text-muted-foreground">{row[1]}</td><td className="py-3 pr-3 text-muted-foreground">{row[2]}</td><td className="py-3 text-foreground">{row[3]}</td></tr>))}</tbody></table></div><p className="text-sm text-muted-foreground leading-relaxed mt-6 text-center">Un sistema de comandes online que el restaurant posseeix es paga el primer cap de setmana — cada euro que el client gasta a la teva sala es queda a la teva sala, i el tiquet al pas porta sempre el número de taula real.</p></div></Section>
  </>);
}
