import { QrCode, MessageCircle, ChefHat, Settings2, Languages, BarChart3 } from "lucide-react";
import type { LandingTexts } from "@/app/_landing/types";

export const TEXTS: LandingTexts = {
  htmlLang: "ca",
  htmlDir: "ltr",
  meta: {
    title: "Sistema de comandes online per a restaurant — QR i WhatsApp | IQ Rest",
    description: "Sistema de comandes online per a restaurant: el client escaneja el QR de la taula, fa la comanda i arriba directe a la tauleta de cuina o al WhatsApp. Zero comissions, amb número de taula. 14 dies gratis.",
    canonical: "https://iq-rest.com/ca/sistema-de-comandes-online-restaurant",
    ogLocale: "ca_ES",
    ogTitle: "Sistema de comandes online per a restaurant — Directe a la cuina",
    ogDescription: "El client escaneja el QR de la taula, fa la comanda i arriba a la teva tauleta o WhatsApp — sense agregador, sense comissió, amb número de taula a cada tiquet.",
  },
  ctaText: "Activar comandes",
  demoText: "Demo en directe",
  microcopy: "Des de €6,90/mes · 14 dies gratis · Cancel·la quan vulguis",
  header: { navFeatures: "Funcions", navHow: "Com funciona", navPricing: "Preus", navFaq: "FAQ", signIn: "Entrar", cta: "Prova-ho" },
  hero: {
    verticals: ["Restaurants", "Cafeteries", "Bistrots", "Pizzeries", "Bars", "Cerveseries"],
    headline: "Sistema de comandes online per a restaurant.",
    sub: "El client escaneja el QR de la seva taula, fa la comanda al mòbil — i el tiquet arriba directe a la tauleta de cuina o al WhatsApp del restaurant. Sense agregador, sense comissions, amb número de taula a cada tiquet.",
    dynamicHeadlines: ["Comanda a taula.", "Directe a la tauleta de cuina.", "O directe al WhatsApp.", "Zero comissions.", "Amb número de taula."],
    painBullets: [
      "Sistema de comandes online que el restaurant posseeix — sense intermediaris, sense comissions.",
      "Les comandes arriben a la tauleta de cuina o del manager amb número de taula, modificadors, al·lèrgens i notes.",
      "O s'envien directament al WhatsApp del restaurant — ideal per a recollida i equips petits.",
      "QR per a cada taula (o un per a tota la sala) es genera automàticament.",
    ],
    rating: "500+ restaurants en 30+ països",
  },
  features: {
    heading: "Sistema de comandes,",
    headingAccent: "fet per a la taula.",
    sub: "Funcionalitat real — no un clon dels agregadors de delivery.",
    items: [
      { Icon: QrCode, title: "Carta QR amb cistella per taula", desc: "El client escaneja el QR, navega per la carta en el seu idioma, afegeix plats amb modificadors, deixa una nota a la cuina i envia. Sense app.", tag: "Comandes QR" },
      { Icon: ChefHat, title: "Comandes a la tauleta de cuina", desc: "Cada nova comanda apareix a la pestanya Cuina — en una tauleta al pas — amb número de taula, plats, variants, al·lèrgens i comentari. Un toc de «en preparació» a «llest».", tag: "Vista de cuina" },
      { Icon: MessageCircle, title: "O al WhatsApp", desc: "Posa el restaurant en mode WhatsApp (o tots dos alhora) — cada comanda arriba al WhatsApp com a missatge formatat. Ideal per a recollida o equips petits.", tag: "Mode WhatsApp" },
      { Icon: Settings2, title: "Modificadors, variants i al·lèrgens", desc: "Cada plat té grups de variants (mida, punt, extres) amb diferència de preu, etiquetes d'al·lèrgens i descripció lliure. La cistella ho té tot — el tiquet a la tauleta surt sense ambigüitats.", tag: "Cistella de debò" },
      { Icon: Languages, title: "Checkout multilingüe", desc: "Tot el flux de comanda — cistella, modificadors, comentari, confirmació — està traduït a 35 idiomes i s'adapta automàticament a l'idioma del mòbil del client.", tag: "35 idiomes" },
      { Icon: BarChart3, title: "Numeració diària i registre", desc: "Cada comanda rep un número diari per a la cuina, va al registre amb imports i marques de temps, alimenta l'analítica. Les cancel·lacions són soft-delete, els informes queden nets.", tag: "Registre de comandes" },
    ],
  },
  founder: {
    eyebrow: "Fet per un propietari de cafeteria, no per una startup de delivery",
    quoteStart: "La meva dona i jo vam obrir una cafeteria i vam passar setmanes buscant una manera d'acceptar comandes a taula que no donés un 30% a un agregador ni exigís un TPV de 1500 €. Tot el que vam provar era pesat, car o sense les funcions bàsiques —",
    quoteAccent: "així que vam construir el sistema de comandes que volíem tenir.",
    sign: "Bogdan Sokolov · fundador, ex propietari de cafeteria",
    photoAlt: "Bogdan, fundador d'IQ Rest",
  },
  how: {
    heading: "Activa el sistema de comandes",
    headingAccent: "en 4 passos",
    sub: "Sense instal·lació, sense integrador, sense trucada a l'informàtic. Només mòbil i 5 minuts.",
    steps: [
      { n: "1", t: "Crea el restaurant", d: "Registre amb email o Google — 30 segons." },
      { n: "2", t: "Afegeix la carta", d: "Drag-and-drop o escaneig IA d'una carta en paper." },
      { n: "3", t: "Tria el canal", d: "Tauleta de cuina, WhatsApp o tots dos." },
      { n: "4", t: "Imprimeix el QR", d: "Un QR per taula — els clients fan comanda a l'instant." },
    ],
  },
  pricing: {
    badge: "Comandes il·limitades · Zero comissions",
    heading: "Un sol pla.",
    headingAccent: "Sense quota per comanda.",
    sub: "Comandes online, carta QR, mode WhatsApp, checkout multilingüe i analítica — tot en una subscripció. Sense percentatge de la transacció.",
    monthlyLabel: "Mensual",
    yearlyLabel: "Anual",
    saveBadge: "Estalvia 25%",
    perMonth: "al mes",
    billedAnnually: "Facturat un cop l'any {total}",
    youSave: "Estalvies {amount}",
    trust: { secure: "Subscripció via Stripe", noCommitment: "Sense compromís", quick: "Actiu en minuts", restaurants: "+500 restaurants" },
  },
  faq: {
    eyebrow: "Sistema de comandes — preguntes freqüents",
    heading: "Sobre el sistema",
    headingAccent: "de comandes.",
    sub: "El que els propietaris de restaurants pregunten abans d'activar comandes online a IQ Rest. No hi és la teva pregunta? Escriu per WhatsApp — responen persones reals.",
    whatsappCta: "Pregunta per WhatsApp",
    whatsappPrefill: "Hola, tinc una pregunta sobre les comandes d'IQ Rest",
    items: [
      { q: "És una plataforma de delivery com Uber Eats o Glovo?", a: "No, aquesta és la idea. IQ Rest és el canal de comandes propi del restaurant: el client demana des del teu QR, la comanda arriba a la teva tauleta o WhatsApp, tu serveixes. Sense marketplace, sense catàleg d'agregador — i mai ens emportem cap part del compte." },
      { q: "On apareixen exactament les comandes?", a: "A la pestanya Cuina del panell IQ Rest, a qualsevol tauleta o mòbil al pas o a la barra. Cada comanda mostra número de taula, plats amb variants i al·lèrgens, comentari del client i número diari. Pas de «nova → en preparació → llesta» amb un toc." },
      { q: "Poden arribar les comandes al WhatsApp en comptes d'això?", a: "Sí. Cada restaurant té tres modes: intern (només tauleta de cuina), WhatsApp (la comanda arriba com a missatge al WhatsApp del restaurant) o tots dos alhora. El mode és un interruptor al panell i es canvia quan vulguis." },
      { q: "Què inclou la comanda?", a: "Plats amb variants i extres (amb diferència de preu), al·lèrgens, número de taula, comentari lliure del client i — si actives els camps — nom, telèfon i adreça. Suficient per enviar un repartidor o trucar a la taula per un al·lergen." },
      { q: "Poden pagar els clients online des de la carta?", a: "Per defecte, no. IQ Rest està pensat per pagar a taula: el client demana, tu portes el compte, es paga com sempre. Si necessites pagament amb targeta online (típic per a recollida), la integració amb Stripe Connect és possible sota petició — escriu per WhatsApp." },
      { q: "Cal una tauleta, impressora o maquinari de TPV especial?", a: "No. Qualsevol tauleta, portàtil o mòbil amb navegador — obres el panell, inicies sessió, deixes la pestanya Cuina oberta. Si ja tens TPV — IQ Rest funciona al costat, no el substitueix." },
      { q: "Què passa després dels 14 dies gratis?", a: "Sense mètode de pagament, el compte es pausa — mai cobrem automàticament. La carta, les comandes i la configuració es conserven; afegeixes targeta quan vulguis per reactivar. Cancel·les amb un clic, sense compromís." },
    ],
  },
  finalCta: {
    heading: "Activa el sistema de comandes.",
    headingAccent: "Llest en 5 minuts.",
    sub: "14 dies gratis, sense targeta. Cancel·la quan vulguis. Uneix-te a 500+ restaurants que gestionen les comandes amb IQ Rest.",
  },
  scan: {
    heading: "De la carta en paper al sistema de comandes",
    headingAccent: "en 60 segons",
    sub: "Puja una foto de la carta — la IA n'extreu categories, plats i preus directament a l'editor. Després cistella i QR — amb un clic.",
    cta: "Escanejar la carta →",
  },
  footer: {
    featureLinks: [
      { href: "/ca/ai-translation", label: "Traducció IA" },
      { href: "/ca/reservations", label: "Reserves" },
      { href: "/ca/mobile-management", label: "Gestió des del mòbil" },
      { href: "/ca/easy-menu", label: "Editor de carta" },
      { href: "/ca/custom-design", label: "Fons de vídeo i foto" },
      { href: "/ca/color-scheme", label: "Colors de marca" },
      { href: "/ca/multilingual", label: "Carta multilingüe" },
      { href: "/ca/ai-images", label: "Optimització de fotos amb IA" },
      { href: "/ca/analytics", label: "Analítica" },
      { href: "/ca/instant-setup", label: "Configuració instantània" },
      { href: "/ca/personal-support", label: "Suport personal" },
    ],
    navLinks: [
      { href: "#pricing", label: "Preus" },
      { href: "#faq", label: "Preguntes" },
      { href: "/ca/changelog", label: "Novetats" },
      { href: "/ca/languages", label: "Canvia d'idioma" },
    ],
    copyrightTemplate: "© {year} IQ Rest. Tots els drets reservats.",
  },
};
