import { Check } from "lucide-react";
import { Section } from "@/app/_landing/components/section";

const BENEFITS = ["테이블당 QR, 스캔-주문, 앱 불필요", "주방/매니저 태블릿에 실시간 주문", "또는 매장 WhatsApp으로 라우팅 — 선택은 귀하", "옵션, 변형, 알레르기가 영수증에 반영", "각 주문에 손님의 자유 코멘트", "주방용 일일 번호 매김", "35개 언어 다국어 결제, 손님 휴대폰에서 자동 감지", "주문당 수수료 0% — 정액제 월 구독"];
const HOW_STEPS = [
  { title: "레스토랑에서 주문 활성화", desc: "레스토랑 설정을 열고, 「주문」 스위치를 켜고, 수집할 손님 필드(이름, 전화, 주소)를 선택." },
  { title: "전달 채널 선택", desc: "내부 모드는 새 주문을 「주방」 탭으로 전송. WhatsApp 모드는 포맷된 메시지로 매장 WhatsApp에 전송. 또는 두 가지 동시." },
  { title: "QR 인쇄 및 부착", desc: "QR(테이블당 또는 매장 공용)을 PDF 또는 PNG로 다운로드하여 테이블에 부착. 손님이 기본 카메라로 스캔 — 앱스토어, 마찰 없음." },
  { title: "서비스 운영", desc: "주문이 「주방」 탭에 테이블 번호, 음식, 옵션, 알레르기, 코멘트, 일일 번호와 함께 표시. 신규 → 진행 중 → 완료로 이동. 손님 브라우저가 실시간으로 업데이트." },
];
const COMPARISON_ROWS = [["주문당 수수료","20–30%","0%","0% (€6.90/월 고정)"],["주문 목적지","집계 앱","자체 계산대","자체 주방 태블릿 또는 WhatsApp"],["영수증의 테이블 번호","없음","수동","있음, 자동"],["옵션 / 변형","제한적","있음","있음, 알레르기 포함"],["다국어 결제","그들의 앱 언어","없음","35개 언어, 자동"],["필요 하드웨어","집계자 태블릿","POS 단말기","브라우저가 있는 모든 태블릿"],["설정 시간","온보딩 통화","며칠~몇 주","5분"]];

export function SeoContent() {
  return (<>
    <Section noContainer dataSection="seo-intro"><div className="w-full"><p className="text-xs font-medium uppercase tracking-widest text-primary mb-3 text-start">자세히</p><h2 className="text-3xl sm:text-4xl lg:text-5xl font-medium tracking-tight mb-3 text-start">레스토랑 온라인 주문 시스템 <span className="text-muted-foreground">실제로 무엇인가</span></h2><p className="text-base sm:text-lg text-muted-foreground mb-10 text-start">마켓플레이스가 아닙니다. 배달 집계 플랫폼이 아닙니다. 귀하의 테이블에 앉은 손님의 휴대폰에서 주방 태블릿 — 또는 WhatsApp으로 가는 직접 라인.</p><div className="space-y-4 text-base sm:text-lg text-foreground/90 leading-relaxed"><p>IQ Rest 의미의 <strong>레스토랑 온라인 주문 시스템</strong>은 귀하의 테이블에 앉은 손님이 자신의 휴대폰으로 메뉴를 열고 장바구니를 구성하여 주문을 귀하의 주방으로 보낼 수 있게 하는 소프트웨어입니다 — Uber Eats, 배민, Wolt 또는 다른 마켓플레이스를 거치지 않고. 손님은 QR 메뉴를 떠나지 않으며, 주문당 수수료를 지불하지 않고, 영수증은 실제 테이블 번호와 함께 도착합니다.</p><p>IQ Rest는 두 가지 전달 채널을 중심으로 구축됩니다. 기본 <em>내부 모드</em>: 각 새 주문은 패스에 두는 태블릿, 휴대폰 또는 노트북의 대시보드 「주방」 탭에 도착합니다 — 테이블 번호, 옵션과 알레르기가 있는 음식, 손님의 자유 코멘트, 주방용 일일 주문 번호와 함께. 대안 <em>WhatsApp 모드</em>: 동일한 주문이 매장 WhatsApp 번호로 포맷된 메시지로 전송 — 소규모 팀, 주로 포장, 매니저가 자리에 없을 때 유용. 두 모드는 병렬로 실행 가능.</p></div></div></Section>
    <Section noContainer dataSection="seo-benefits"><div className="w-full"><h3 className="text-2xl sm:text-3xl font-medium tracking-tight mb-6 text-start">실제로 받는 것</h3><div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-3 sm:gap-4">{BENEFITS.map((b) => (<div key={b} className="bg-muted/20 border border-border rounded-2xl p-4 sm:p-5 flex flex-row items-center gap-3"><div className="h-8 w-8 rounded-lg bg-primary/10 text-primary flex items-center justify-center shrink-0"><Check className="h-4 w-4" strokeWidth={2.5} /></div><p className="text-sm sm:text-base text-foreground/90 leading-snug">{b}</p></div>))}</div></div></Section>
    <Section noContainer dataSection="seo-how"><div className="w-full"><h3 className="text-2xl sm:text-3xl font-medium tracking-tight mb-6 text-start">IQ Rest 주문 흐름이 어떻게 작동하는가</h3><p className="text-base sm:text-lg text-foreground/90 leading-relaxed mb-6 text-start">대시보드의 네 가지 스위치로 라이브. 설치자, POS 하드웨어, 통합 프로젝트 불필요.</p><div className="grid grid-cols-1 sm:grid-cols-2 gap-3 sm:gap-4">{HOW_STEPS.map((s, i) => (<div key={s.title} className="bg-muted/20 border border-border rounded-2xl p-5 flex flex-row items-start gap-4"><div className="h-10 w-10 rounded-lg bg-primary text-primary-foreground flex items-center justify-center shrink-0 font-semibold text-base">{i + 1}</div><div className="flex-1 min-w-0"><div className="text-base sm:text-lg font-semibold tracking-tight mb-1">{s.title}</div><p className="text-sm text-muted-foreground leading-relaxed">{s.desc}</p></div></div>))}</div></div></Section>
    <Section noContainer dataSection="seo-table"><div className="w-full"><h3 className="text-2xl sm:text-3xl font-medium tracking-tight mb-6 text-start">집계자, 고전 POS 또는 주문 시스템</h3><div className="bg-muted/20 border border-border rounded-2xl p-4 sm:p-6 overflow-x-auto"><table className="w-full text-sm sm:text-base border-collapse"><thead><tr className="border-b border-border"><th className="text-left font-semibold py-3 pr-3 text-foreground">특징</th><th className="text-left font-semibold py-3 pr-3 text-muted-foreground">배달 집계자</th><th className="text-left font-semibold py-3 pr-3 text-muted-foreground">고전 POS</th><th className="text-left font-semibold py-3 text-primary">IQ Rest 주문</th></tr></thead><tbody className="text-foreground/90">{COMPARISON_ROWS.map((row, i) => (<tr key={row[0]} className={i < COMPARISON_ROWS.length - 1 ? "border-b border-border/50" : ""}><td className="py-3 pr-3 font-medium">{row[0]}</td><td className="py-3 pr-3 text-muted-foreground">{row[1]}</td><td className="py-3 pr-3 text-muted-foreground">{row[2]}</td><td className="py-3 text-foreground">{row[3]}</td></tr>))}</tbody></table></div><p className="text-sm text-muted-foreground leading-relaxed mt-6 text-start">레스토랑이 진짜 소유하는 주문 시스템은 첫 주말에 본전을 회수합니다 — 손님이 귀하의 매장에서 쓰는 모든 원이 매장에 남고, 패스의 영수증은 항상 실제 테이블 번호를 포함합니다.</p></div></Section>
  </>);
}
