import { QrCode, MessageCircle, ChefHat, Settings2, Languages, BarChart3 } from "lucide-react";
import type { LandingTexts } from "@/app/_landing/types";

export const TEXTS: LandingTexts = {
  htmlLang: "ko",
  htmlDir: "ltr",
  meta: {
    title: "레스토랑 온라인 주문 시스템 — QR & WhatsApp | IQ Rest",
    description: "레스토랑 온라인 주문 시스템: 손님이 테이블 QR을 스캔하면 주문이 주방 태블릿이나 매장 WhatsApp으로 바로 도착합니다. 수수료 없음, 테이블 번호 포함. 14일 무료.",
    canonical: "https://iq-rest.com/ko/restaurant-online-order-system",
    ogLocale: "ko_KR",
    ogTitle: "레스토랑 온라인 주문 시스템 — 바로 주방으로",
    ogDescription: "테이블에서 QR 스캔, 주문 작성, 태블릿이나 WhatsApp으로 직배송 — 중개사 없음, 수수료 없음, 모든 영수증에 테이블 번호.",
  },
  ctaText: "주문 활성화",
  demoText: "라이브 데모 보기",
  microcopy: "월 €6.90부터 · 14일 무료 · 언제든 취소",
  header: { navFeatures: "기능", navHow: "작동 방식", navPricing: "요금", navFaq: "FAQ", signIn: "로그인", cta: "무료 체험" },
  hero: {
    verticals: ["레스토랑", "카페", "비스트로", "피자집", "바", "양조장"],
    headline: "레스토랑 온라인 주문 시스템",
    sub: "손님이 테이블 QR을 스캔, 휴대폰에서 주문을 작성하고, 영수증은 주방 태블릿 또는 매장 WhatsApp으로 직접 도착합니다. 중개사 없음, 수수료 없음, 모든 영수증에 테이블 번호.",
    dynamicHeadlines: ["테이블에서 주문.", "주방 태블릿으로 직배송.", "또는 WhatsApp으로 직접.", "수수료 0%.", "테이블 번호 포함."],
    painBullets: [
      "레스토랑이 진짜 소유하는 온라인 주문 시스템 — 중개사 없음, 수수료 없음.",
      "주문은 테이블 번호, 옵션, 알레르기, 메모와 함께 주방/매니저 태블릿에 도착.",
      "또는 매장 WhatsApp으로 직접 — 포장 주문이나 소규모 팀에 최적.",
      "테이블당 QR(또는 매장 공용) 자동 생성.",
    ],
    rating: "30개국 이상 500+개 레스토랑",
  },
  features: {
    heading: "테이블을 위해 만든",
    headingAccent: "주문 시스템.",
    sub: "진짜 기능 — 배달 집계 플랫폼의 복제품이 아닙니다.",
    items: [
      { Icon: QrCode, title: "모든 테이블에 장바구니가 있는 QR 메뉴", desc: "손님이 QR을 스캔하고, 자신의 언어로 메뉴를 탐색하며, 옵션으로 음식을 추가하고, 주방에 메모를 남기고 전송합니다. 앱 설치 불필요.", tag: "QR 주문" },
      { Icon: ChefHat, title: "주방 태블릿에서 주문 확인", desc: "새 주문이 관리자 패널의 「주방」 탭에 표시됩니다. 테이블 번호, 음식, 옵션, 알레르기, 손님 코멘트 포함. 한 번 탭으로 진행 중 → 완료.", tag: "주방 뷰" },
      { Icon: MessageCircle, title: "또는 WhatsApp으로 주문 전송", desc: "매장을 WhatsApp 모드(또는 두 모드 동시)로 전환하면 각 주문이 매장 WhatsApp 번호로 포맷된 메시지로 도착합니다. 포장 또는 소규모 팀에 이상적.", tag: "WhatsApp 모드" },
      { Icon: Settings2, title: "옵션, 변형, 알레르기", desc: "각 음식에 변형 그룹(크기, 굽기, 추가), 가격차, 알레르기 태그, 자유 설명. 장바구니가 모두 반영 — 태블릿 영수증은 모호하지 않습니다.", tag: "진짜 장바구니" },
      { Icon: Languages, title: "다국어 결제", desc: "주문 흐름 전체(장바구니, 옵션, 코멘트, 확인)가 35개 언어로 번역되어 손님 휴대폰 언어에 자동 맞춤.", tag: "35개 언어" },
      { Icon: BarChart3, title: "일별 번호 및 주문 로그", desc: "각 주문에 주방용 일일 번호 부여, 합계와 타임스탬프가 있는 로그에 기록, 분석에 반영. 취소는 소프트 삭제로 보고서 정리.", tag: "주문 로그" },
    ],
  },
  founder: {
    eyebrow: "배달 스타트업이 아닌 카페 사장이 구축",
    quoteStart: "아내와 카페를 열고 테이블 주문을 받을 방법을 몇 주 동안 찾았습니다. 집계 플랫폼에 30%를 주기도 싫고, 1500€짜리 POS도 필요 없었어요. 시도한 모든 것이 무겁거나 비싸거나 기본 기능이 없었습니다 —",
    quoteAccent: "그래서 우리가 갖고 싶었던 주문 시스템을 만들었습니다.",
    sign: "Bogdan Sokolov · 창립자, 전 카페 사장",
    photoAlt: "Bogdan, IQ Rest 창립자",
  },
  how: {
    heading: "주문 시스템 활성화",
    headingAccent: "4단계",
    sub: "설치 불필요, 통합자 불필요, IT 전화 불필요. 휴대폰과 5분이면 충분.",
    steps: [
      { n: "1", t: "레스토랑 생성", d: "이메일 또는 Google 등록 — 30초." },
      { n: "2", t: "메뉴 추가", d: "드래그 앤 드롭 또는 종이 메뉴 AI 스캔." },
      { n: "3", t: "채널 선택", d: "주방 태블릿, WhatsApp 또는 둘 다." },
      { n: "4", t: "QR 인쇄", d: "테이블당 QR 한 장 — 손님이 즉시 주문 가능." },
    ],
  },
  pricing: {
    badge: "무제한 주문 · 수수료 0%",
    heading: "단일 요금제.",
    headingAccent: "주문당 비용 없음.",
    sub: "온라인 주문, QR 메뉴, WhatsApp 모드, 다국어 결제, 분석 — 모두 하나의 구독에. 거래당 수수료 없음.",
    monthlyLabel: "월간",
    yearlyLabel: "연간",
    saveBadge: "25% 절약",
    perMonth: "월",
    billedAnnually: "연간 청구 {total}",
    youSave: "절약 {amount}",
    trust: { secure: "Stripe로 구독", noCommitment: "약정 없음", quick: "분 단위 활성", restaurants: "+500 레스토랑" },
  },
  faq: {
    eyebrow: "주문 시스템 — 자주 묻는 질문",
    heading: "주문 시스템에",
    headingAccent: "대하여.",
    sub: "사장님들이 IQ Rest로 온라인 주문을 활성화하기 전에 하는 질문들. 질문이 없으면? WhatsApp으로 문의 — 실제 사람이 답변합니다.",
    whatsappCta: "WhatsApp에 질문",
    whatsappPrefill: "안녕하세요, IQ Rest 주문에 대해 질문이 있습니다",
    items: [
      { q: "Uber Eats나 배민 같은 배달 플랫폼인가요?", a: "아니요, 그것이 핵심입니다. IQ Rest는 레스토랑 자체 주문 채널입니다 — 손님이 귀하의 QR에서 주문하고, 영수증이 귀하의 태블릿이나 WhatsApp에 도착하며, 귀하가 제공합니다. 마켓플레이스도 집계 카탈로그도 없고, 계산서의 일부를 절대 가져가지 않습니다." },
      { q: "주문은 정확히 어디에 표시되나요?", a: "IQ Rest 대시보드의 「주방」 탭 — 패스나 바에 두는 어떤 태블릿/휴대폰에서든 열 수 있습니다. 각 주문에 테이블 번호, 옵션과 알레르기가 있는 음식, 손님 코멘트, 일일 번호 표시. 한 번 탭으로 신규 → 진행 중 → 완료." },
      { q: "WhatsApp으로 주문을 받을 수 있나요?", a: "네. 각 레스토랑에는 세 가지 모드: 내부(주방 태블릿만), WhatsApp(주문을 포맷된 메시지로 매장 WhatsApp 번호에 전송), 또는 둘 다 동시. 모드는 대시보드의 한 스위치 — 언제든 전환." },
      { q: "주문에는 무엇이 포함되나요?", a: "옵션과 추가 항목이 있는 음식(가격차 포함), 알레르기, 테이블 번호, 손님의 자유 코멘트, 그리고 필드를 활성화하면 손님 이름, 전화, 주소. 포장 배달원 보내거나 알레르기 관련 테이블에 다시 전화하기에 충분." },
      { q: "손님이 메뉴에서 온라인 결제할 수 있나요?", a: "기본적으로는 안 됩니다. IQ Rest는 테이블 결제 기반으로 설계 — 손님 주문, 계산서 가져다 주기, 평소처럼 결제. 온라인 카드 결제(포장에 일반적)가 필요하면 요청에 따라 Stripe Connect 통합 가능 — WhatsApp에 메시지를." },
      { q: "특별한 태블릿, 프린터, POS 하드웨어가 필요한가요?", a: "아니요. 브라우저가 있는 모든 태블릿, 노트북, 휴대폰이 작동합니다 — 대시보드 열기, 로그인, 「주방」 탭 열어 두기. 이미 POS가 있다면 IQ Rest는 그 옆에서 동작 — 계산대를 교체하지 않습니다." },
      { q: "14일 무료 후에는 어떻게 되나요?", a: "결제 수단이 없으면 계정이 일시 중지됩니다 — 절대 자동 청구하지 않습니다. 메뉴, 주문, 설정은 저장됩니다; 재활성화하려면 언제든 카드를 추가하세요. 한 번 클릭으로 취소, 약정 없음." },
    ],
  },
  finalCta: {
    heading: "주문 시스템을 활성화하세요.",
    headingAccent: "5분 내 가동.",
    sub: "14일 무료, 카드 불필요. 언제든 취소. IQ Rest로 자체 온라인 주문을 운영하는 500+ 레스토랑에 합류하세요.",
  },
  scan: {
    heading: "종이 메뉴에서 주문 시스템까지",
    headingAccent: "60초",
    sub: "메뉴 사진 업로드 — AI가 카테고리, 음식, 가격을 에디터로 바로 추출. 거기서 장바구니와 QR은 한 번의 클릭.",
    cta: "내 메뉴 스캔 →",
  },
  footer: {
    featureLinks: [
      { href: "/ko/ai-translation", label: "AI 번역" },
      { href: "/ko/reservations", label: "예약" },
      { href: "/ko/mobile-management", label: "모바일 관리" },
      { href: "/ko/easy-menu", label: "메뉴 에디터" },
      { href: "/ko/custom-design", label: "비디오 및 사진 배경" },
      { href: "/ko/color-scheme", label: "브랜드 컬러" },
      { href: "/ko/multilingual", label: "다국어 메뉴" },
      { href: "/ko/ai-images", label: "AI 이미지 최적화" },
      { href: "/ko/analytics", label: "분석" },
      { href: "/ko/instant-setup", label: "즉시 설정" },
      { href: "/ko/personal-support", label: "개인 지원" },
    ],
    navLinks: [
      { href: "#pricing", label: "요금" },
      { href: "#faq", label: "질문" },
      { href: "/ko/changelog", label: "업데이트" },
      { href: "/ko/languages", label: "언어 변경" },
    ],
    copyrightTemplate: "© {year} IQ Rest. All rights reserved.",
  },
};
