import { ScanLine, Languages, CalendarCheck, Palette, Smartphone, ListPlus } from "lucide-react";
import type { LandingTexts } from "@/app/_landing/types";

export const TEXTS: LandingTexts = {
  htmlLang: "no", htmlDir: "ltr",
  meta: {
    title: "QR-meny for Restauranter — Direkte Bestillinger, Null Provisjon | IQ Rest",
    description: "Slutt med papirmenyer og leveringsapp-provisjoner. QR-meny, direkte bestillinger, reservasjoner og flerspråklig nettsted. 14 dager gratis, uten kort.",
    canonical: "https://iq-rest.com/no", ogLocale: "no_NO",
    ogTitle: "QR-meny for Restauranter — Direkte Bestillinger, Null Provisjon",
    ogDescription: "QR-meny, direkte bestillinger, reservasjoner og AI-oversettelse. Klart på 2 minutter. 14 dager gratis — uten kort.",
  },
  ctaText: "Start gratis →",
  demoText: "Se live-demo", microcopy: "14 dager gratis · Ingen kort · Avslutt når du vil",
  header: { navFeatures: "Funksjoner", navHow: "Slik virker det", navPricing: "Priser", navFaq: "FAQ", signIn: "Logg inn", cta: "Start gratis →" },
  hero: {
    verticals: ["Restauranter", "Kafeer", "Barer", "Hoteller", "Pizzeriaer"],
    variants: [
      { headline: "Slutt å trykke menyer.", headlineAccent: "Slutt å gi 30% til leveringsapper.", sub: "QR-meny, direkte bestillinger, reservasjoner og flerspråklig nettsted. Klart på 2 minutter — uten kort." },
      { headline: "Restauranten din fortjener mer enn", headlineAccent: "papirmenyer og tapte anrop.", sub: "Direkte bestillinger, øyeblikkelige meny-oppdateringer og reservasjoner 24/7. Satt opp på 2 minutter." },
      { headline: "Én QR-kode.", headlineAccent: "Null provisjon. Adjø papir.", sub: "QR-meny, online bestillinger og reservasjoner — alt på ett sted. 14 dager gratis, uten kort." },
      { headline: "Få direkte bestillinger.", headlineAccent: "Hopp over provisjonen.", sub: "Gjester skanner, bestiller og betaler — direkte til deg, uten Foodora-kutt. Klart på 2 minutter." },
      { headline: "Flere bestillinger. Flere reservasjoner.", headlineAccent: "Ingen papir, ingen apper.", sub: "QR-meny + reservasjoner + flerspråklig side på autopilot. 14 dagers gratis prøve." },
      { headline: "Turister forstår ikke menyen?", headlineAccent: "Løst på 2 minutter.", sub: "AI oversetter hele menyen til 35 språk. Pluss QR-bestillinger og reservasjoner inkludert." },
      { headline: "Fra papirmeny til QR-kode,", headlineAccent: "før espressoen blir kald.", sub: "QR-meny, direkte bestillinger og reservasjoner 24/7. Klart på 2 minutter — uten kort." },
      { headline: "Forfriskende enkel QR-meny.", headlineAccent: "Stille kraftig under.", sub: "Direkte bestillinger, AI-oversettelse, reservasjoner og nettsted — alt med ett trykk på telefonen." },
    ],
    painBullets: ["Ingen utskrifter — endre priser umiddelbart", "Null provisjon — bestillinger rett til deg", "Ingen tapte anrop — reservasjoner 24/7", "35 språk — mist aldri en turist"],
    rating: "4,9 · over 500 restauranter i 30+ land",
  },
  features: {
    heading: "Alt du trenger.", headingAccent: "Ingenting du ikke trenger.",
    sub: "Bygget for restauranter. Brukt ved bordet.",
    items: [
      { Icon: ScanLine, title: "Behold 100% av hver bestilling", desc: "Gjester skanner, bestiller og betaler — rett til deg. Ingen apper å laste ned, ingen 30%-leveringssnitt. Hver bestilling lander i sanntid med bordnummer i panelet." },
      { Icon: Languages, title: "Selg til turister på deres språk", desc: "Ett trykk oversetter hele menyen til 35 språk. AI fanger kulinarisk kontekst — gjester bestiller mer når de virkelig forstår retten." },
      { Icon: CalendarCheck, title: "Mist ingen reservasjoner mens du lager mat", desc: "Gjester reserverer 24/7, ingen anrop. Auto- eller manuell bekreftelse, e-postpåminnelser inkludert — færre no-shows, null stress." },
      { Icon: Palette, title: "Uforglemmelig på 1 sekund", desc: "Legg inn en kjøkkenvideo eller et heltebilde som menybakgrunn. Gjester slutter å scrolle. Merket ditt fester seg." },
      { Icon: Smartphone, title: "Oppdater på sekunder, ikke dager", desc: "Endre priser, bytt bilder, legg til dagens — fra telefonen, mellom bord. Live for gjester med en gang. Aldri mer trykk." },
      { Icon: ListPlus, title: "Kan du sende SMS, kan du dette", desc: "Trykk for å legge til en rett. Dra for å omsortere. Slå av det utsolgte. Ingen manualer, ingen tutorials, ingen læringskurve." },
    ],
  },
  founder: {
    eyebrow: "Bygget av en restauratør",
    quoteStart: "Min kone og jeg åpnet en kafé og brukte uker på å lete etter et system som håndterer onlinebestillinger, reservasjoner og samtidig ser moderne ut. Alt vi prøvde var klumpete, stygt eller manglet halvparten av funksjonene —",
    quoteAccent: "så vi bygget det vi selv ville hatt.",
    sign: "Bogdan Sokolov · grunnlegger, eks-kafeeier",
    photoAlt: "Bogdan, grunnlegger av IQ Rest",
  },
  how: {
    heading: "Live på under 2 minutter",
    sub: "Fire korte steg. Ingen installasjon, ingen teknisk oppsett.",
    steps: [
      { n: "1", t: "Registrer deg", d: "E-post eller Google. Ingen kort. Klart på 10 sekunder." },
      { n: "2", t: "Restaurantens navn", d: "Skriv navnet. Vises øverst på menyen." },
      { n: "3", t: "Legg til første rett", d: "Kategori, navn, pris, bilde. Det var det." },
      { n: "4", t: "Velg cover og skriv ut QR", d: "Velg bakgrunn. Hent QR. Lim på bordene." },
    ],
  },
  pricing: {
    badge: "Null provisjon · Ingen kontrakter",
    heading: "Én plan.", headingAccent: "Alt inkludert.",
    sub: "QR-meny, bestillinger, AI-oversettelse, restaurantnettsted og reservasjoner. Én enkel pris.",
    monthlyLabel: "Månedlig", yearlyLabel: "Årlig", saveBadge: "Spar 25%", perMonth: "per måned",
    billedAnnually: "Fakturert årlig {total}", youSave: "Du sparer {amount}",
    trust: { secure: "Sikker betaling med Stripe", noCommitment: "Ingen binding", quick: "Aktiv på minutter", restaurants: "500+ restauranter" },
  },
  faq: {
    eyebrow: "Spørsmål?", heading: "Vanlige", headingAccent: "spørsmål.",
    sub: "Det restauratører spør om før påmelding. Mangler ditt? Skriv på WhatsApp — ekte folk svarer.",
    whatsappCta: "Spør på WhatsApp", whatsappPrefill: "Hei, jeg har et spørsmål om IQ Rest",
    items: [
      { q: "Hva inkluderer prøveperioden og hva skjer etterpå?", a: "14 dager full tilgang, ingen kort. Etter 14 dager pauses kontoen hvis du ikke legger til betalingsmetode — vi trekker aldri automatisk. Legg til betaling senere for å reaktivere. Avslutt med ett klikk." },
      { q: "Tar dere provisjon på bestillinger?", a: "Null. Hver bestilling fra QR-menyen din går rett til deg — ingen del til oss, ingen Foodora / Wolt-gebyrer. Én fast månedspris, det er det." },
      { q: "Trenger gjestene en app? Trenger jeg tekniske kunnskaper?", a: "Ingen apper for gjester — de skanner QR med kameraet, menyen åpnes i nettleseren. Ingen tekniske kunnskaper for deg — hele panelet virker i mobilen, trykk for å legge til, dra for å omsortere, det er hele kurven." },
      { q: "Kan jeg drive flere restauranter fra én konto?", a: "Ja. Pro-planen lar deg drive flere restauranter i samme konto — separate menyer, separate QR-er, separat statistikk, én innlogging. Bytt mellom dem på to trykk." },
      { q: "Hvor raskt endrer jeg priser og legger til retter?", a: "Med en gang. Endre pris på telefonen, gjestene ser det på sekunder. Ny rett? Trykk, skriv, bilde, ferdig — ingen utskrifter, ingen designer å vente på." },
      { q: "Hvor mange språk støttes?", a: "35 språk med innebygd AI-oversettelse. Ett trykk oversetter hele menyen, AI forstår kulinarisk kontekst — navn og beskrivelser høres naturlig ut på hvert språk. Turister bestiller mer når de virkelig forstår." },
    ],
  },
  finalCta: { heading: "Klart på 2 minutter.", headingAccent: "Gratis i 14 dager.", sub: "Ingen kort. Avslutt når du vil. Bli med 500+ restauranter allerede på IQ Rest." },
  footer: {
    featureLinks: [
      { href: "/no/online-orders", label: "Onlinebestillinger" },
      { href: "/no/ai-translation", label: "AI-oversettelse" },
      { href: "/no/reservations", label: "Reservasjoner" },
      { href: "/no/mobile-management", label: "Mobilstyring" },
      { href: "/no/easy-menu", label: "Meny-editor" },
      { href: "/no/custom-design", label: "Video- og fotobakgrunner" },
      { href: "/no/color-scheme", label: "Merkefarger" },
      { href: "/no/multilingual", label: "Flerspråklig nettsted" },
      { href: "/no/ai-images", label: "AI-bildeoptimalisering" },
      { href: "/no/analytics", label: "Statistikk" },
      { href: "/no/instant-setup", label: "Øyeblikkelig oppsett" },
      { href: "/no/personal-support", label: "Personlig support" },
    ],
    navLinks: [
      { href: "#pricing", label: "Priser" }, { href: "#faq", label: "Spørsmål" },
      { href: "/no/languages", label: "Bytt språk" },
    ],
    legalLinks: [
      { href: "/no/terms", label: "Vilkår" }, { href: "/no/privacy", label: "Personvern" },
      { href: "/no/cookies", label: "Cookies" }, { href: "/sitemap.xml", label: "Sitemap" },
    ],
    copyrightTemplate: "© {year} IQ Rest. Alle rettigheter forbeholdt.",
  },
};
