import { Check } from "lucide-react";
import { Section } from "@/app/_landing/components/section";

const BENEFITS = ["QR na vsaki mizi, skeniraj-in-naroči, brez aplikacije", "Naročila v realnem času na kuhinjskem ali managerjevem tabletu", "Ali v WhatsApp restavracije — vi izberete", "Modifikatorji, različice in alergeni gredo na račun", "Prost komentar gosta na vsakem naročilu", "Dnevno številčenje za kuhinjo", "Večjezični checkout v 35 jezikih, po gostovem telefonu", "Brez provizije na naročilo — fiksna mesečna naročnina"];
const HOW_STEPS = [
  { title: "Vklopi naročila za restavracijo", desc: "Odpri nastavitve restavracije, aktiviraj preklop Naročila in izberi, katera polja gosta (ime, telefon, naslov) zbirati." },
  { title: "Izberi dostavni kanal", desc: "Notranji način pošilja nova naročila v zavihek Kuhinja. WhatsApp način formatira naročilo kot sporočilo v WhatsApp restavracije. Ali oba vzporedno." },
  { title: "Natisni in nalepi QR", desc: "Prenesi QR (enega na mizo ali enega na restavracijo) v PDF ali PNG in nalepi na mize. Gostje skenirajo z lastno kamero — brez App Store, brez trenja." },
  { title: "Odpelji izmeno", desc: "Naročila se pojavijo v zavihku Kuhinja s številko mize, jedmi, različicami, alergeni, komentarjem in dnevno številko. Prehod novo → v delu → pripravljeno. Brskalnik gosta se osveži v realnem času." },
];
const COMPARISON_ROWS = [["Provizija na naročilo","20–30%","0%","0% (€6,90/mes fiksno)"],["Kam gre naročilo","Aplikacija agregatorja","Vaša blagajna","Vaš kuhinjski tablet ali WhatsApp"],["Številka mize na računu","Ne","Ročno","Da, samodejno"],["Modifikatorji / različice","Omejeni","Da","Da, z alergeni"],["Večjezični checkout","Jezik njihove aplikacije","Ne","35 jezikov, samodejno"],["Potrebna strojna oprema","Tablet agregatorja","POS terminal","Katerikoli tablet z brskalnikom"],["Čas namestitve","Onboarding klic","Dnevi-tedni","5 minut"]];

export function SeoContent() {
  return (<>
    <Section noContainer dataSection="seo-intro"><div className="w-full"><p className="text-xs font-medium uppercase tracking-widest text-primary mb-3 text-start">Podrobno</p><h2 className="text-3xl sm:text-4xl lg:text-5xl font-medium tracking-tight mb-3 text-start">Kaj je spletni sistem naročanja za restavracijo <span className="text-muted-foreground">v resnici</span></h2><p className="text-base sm:text-lg text-muted-foreground mb-10 text-start">Ni marketplace. Ni dostavni agregator. Neposredna linija od gostovega telefona pri vaši mizi do kuhinjskega tableta — ali WhatsApp.</p><div className="space-y-4 text-base sm:text-lg text-foreground/90 leading-relaxed"><p><strong>Spletni sistem naročanja za restavracijo</strong> v smislu IQ Rest je programska oprema, ki omogoča gostu pri vaši mizi, da odpre meni na telefonu, sestavi košarico in pošlje naročilo v kuhinjo — brez Wolta, Glova, Bolt Fooda ali drugega marketplaca. Gost nikoli ne zapusti vašega QR menija, ne plačate provizije na naročilo, in račun pride z resnično številko mize.</p><p>IQ Rest je zgrajen okrog dveh kanalov. Privzeto je <em>notranji način</em>: vsako novo naročilo prispe v zavihek Kuhinja na panelu na tabletu, telefonu ali prenosniku ob izdaji — s številko mize, jedmi z različicami in alergeni, prostim komentarjem gosta in dnevno številko naročila. Alternativa je <em>WhatsApp način</em>: isto naročilo se formatira kot sporočilo v WhatsApp restavracije. Uporabno za majhne ekipe, predvsem prevzem ali ko je manager izven dvorane. Oba načina lahko tečeta hkrati.</p></div></div></Section>
    <Section noContainer dataSection="seo-benefits"><div className="w-full"><h3 className="text-2xl sm:text-3xl font-medium tracking-tight mb-6 text-start">Kaj resnično dobite</h3><div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-3 sm:gap-4">{BENEFITS.map((b) => (<div key={b} className="bg-muted/20 border border-border rounded-2xl p-4 sm:p-5 flex flex-row items-center gap-3"><div className="h-8 w-8 rounded-lg bg-primary/10 text-primary flex items-center justify-center shrink-0"><Check className="h-4 w-4" strokeWidth={2.5} /></div><p className="text-sm sm:text-base text-foreground/90 leading-snug">{b}</p></div>))}</div></div></Section>
    <Section noContainer dataSection="seo-how"><div className="w-full"><h3 className="text-2xl sm:text-3xl font-medium tracking-tight mb-6 text-start">Kako deluje tok naročil IQ Rest</h3><p className="text-base sm:text-lg text-foreground/90 leading-relaxed mb-6 text-start">Štirje preklopi v panelu — in ste v živo. Brez namestitelja, brez POS strojne opreme, brez integracijskega projekta.</p><div className="grid grid-cols-1 sm:grid-cols-2 gap-3 sm:gap-4">{HOW_STEPS.map((s, i) => (<div key={s.title} className="bg-muted/20 border border-border rounded-2xl p-5 flex flex-row items-start gap-4"><div className="h-10 w-10 rounded-lg bg-primary text-primary-foreground flex items-center justify-center shrink-0 font-semibold text-base">{i + 1}</div><div className="flex-1 min-w-0"><div className="text-base sm:text-lg font-semibold tracking-tight mb-1">{s.title}</div><p className="text-sm text-muted-foreground leading-relaxed">{s.desc}</p></div></div>))}</div></div></Section>
    <Section noContainer dataSection="seo-table"><div className="w-full"><h3 className="text-2xl sm:text-3xl font-medium tracking-tight mb-6 text-start">Agregator, klasični POS ali sistem naročanja</h3><div className="bg-muted/20 border border-border rounded-2xl p-4 sm:p-6 overflow-x-auto"><table className="w-full text-sm sm:text-base border-collapse"><thead><tr className="border-b border-border"><th className="text-left font-semibold py-3 pr-3 text-foreground">Lastnost</th><th className="text-left font-semibold py-3 pr-3 text-muted-foreground">Dostavni agregator</th><th className="text-left font-semibold py-3 pr-3 text-muted-foreground">Klasični POS</th><th className="text-left font-semibold py-3 text-primary">Naročila IQ Rest</th></tr></thead><tbody className="text-foreground/90">{COMPARISON_ROWS.map((row, i) => (<tr key={row[0]} className={i < COMPARISON_ROWS.length - 1 ? "border-b border-border/50" : ""}><td className="py-3 pr-3 font-medium">{row[0]}</td><td className="py-3 pr-3 text-muted-foreground">{row[1]}</td><td className="py-3 pr-3 text-muted-foreground">{row[2]}</td><td className="py-3 text-foreground">{row[3]}</td></tr>))}</tbody></table></div><p className="text-sm text-muted-foreground leading-relaxed mt-6 text-start">Spletni sistem naročanja, ki ga ima v lasti sama restavracija, se izplača že prvi vikend — vsak evro, ki ga gost porabi v vaši dvorani, ostane v vaši dvorani, in račun ob izdaji je vedno z resnično številko mize.</p></div></Section>
  </>);
}
