import { QrCode, MessageCircle, ChefHat, Settings2, Languages, BarChart3 } from "lucide-react";
import type { LandingTexts } from "@/app/_landing/types";

export const TEXTS: LandingTexts = {
  htmlLang: "sl",
  htmlDir: "ltr",
  meta: {
    title: "Spletni sistem naročanja za restavracijo — QR in WhatsApp | IQ Rest",
    description: "Spletni sistem naročanja za restavracijo: gost skenira QR pri mizi, sestavi naročilo in to prispe neposredno na kuhinjski tablet ali WhatsApp. Brez provizije, s številko mize. 14 dni brezplačno.",
    canonical: "https://iq-rest.com/sl/spletni-sistem-narocanja-restavracija",
    ogLocale: "sl_SI",
    ogTitle: "Spletni sistem naročanja za restavracijo — Neposredno v kuhinjo",
    ogDescription: "Gost skenira QR pri mizi, sestavi naročilo in prispe na tablet ali WhatsApp — brez posrednika, brez provizije, s številko mize na vsakem računu.",
  },
  ctaText: "Vključi naročila",
  demoText: "Demo v živo",
  microcopy: "Od €6,90/mes · 14 dni brezplačno · Prekliči kadar koli",
  header: { navFeatures: "Funkcije", navHow: "Kako deluje", navPricing: "Cene", navFaq: "FAQ", signIn: "Prijava", cta: "Poskusi" },
  hero: {
    verticals: ["Restavracije", "Kavarne", "Bistroji", "Picerije", "Bari", "Pivnice"],
    headline: "Spletni sistem naročanja za restavracijo.",
    sub: "Gost skenira QR svoje mize, sestavi naročilo na telefonu — in račun prispe neposredno na kuhinjski tablet ali WhatsApp restavracije. Brez posrednika, brez provizije, s številko mize na vsakem računu.",
    dynamicHeadlines: ["Naročilo pri mizi.", "Neposredno na kuhinjski tablet.", "Ali neposredno v WhatsApp.", "Brez provizije.", "S številko mize."],
    painBullets: [
      "Spletni sistem naročanja, ki ga ima v lasti sama restavracija — brez posrednikov, brez provizije.",
      "Naročila prispejo na kuhinjski ali managerjev tablet s številko mize, modifikatorji, alergeni in opombami.",
      "Ali so poslana neposredno na WhatsApp restavracije — idealno za prevzem in majhne ekipe.",
      "QR za vsako mizo (ali eden za celotno dvorano) se generira samodejno.",
    ],
    rating: "500+ restavracij v 30+ državah",
  },
  features: {
    heading: "Sistem naročanja,",
    headingAccent: "narejen za mizo.",
    sub: "Resnična funkcionalnost — ne klon dostavnih agregatorjev.",
    items: [
      { Icon: QrCode, title: "QR meni z košarico za vsako mizo", desc: "Gost skenira QR, pregleduje meni v svojem jeziku, dodaja jedi z modifikatorji, pusti opombo za kuhinjo in pošlje. Brez aplikacije.", tag: "QR naročila" },
      { Icon: ChefHat, title: "Naročila na kuhinjskem tabletu", desc: "Vsako novo naročilo se pojavi v zavihku Kuhinja — na tabletu ob izdaji — s številko mize, jedmi, različicami, alergeni in komentarjem. En dotik iz „v delu“ v „pripravljeno“.", tag: "Pogled kuhinje" },
      { Icon: MessageCircle, title: "Ali v WhatsApp", desc: "Postavi restavracijo v WhatsApp način (ali oba hkrati) — vsako naročilo prispe v WhatsApp kot formatirano sporočilo. Idealno za prevzem ali majhne ekipe.", tag: "WhatsApp način" },
      { Icon: Settings2, title: "Modifikatorji, različice in alergeni", desc: "Vsaka jed ima skupine različic (velikost, peka, dodatki) z razliko v ceni, oznake alergenov in prost opis. Košarica vse obračuna — račun na tabletu brez nejasnosti.", tag: "Prava košarica" },
      { Icon: Languages, title: "Večjezični checkout", desc: "Celoten tok naročila — košarica, modifikatorji, komentar, potrditev — je preveden v 35 jezikov in se samodejno prilagodi jeziku gostovega telefona.", tag: "35 jezikov" },
      { Icon: BarChart3, title: "Dnevno številčenje in dnevnik", desc: "Vsako naročilo dobi dnevno številko za kuhinjo, gre v dnevnik s vsotami in časovnimi žigi, hrani analitiko. Preklici so soft-delete, poročila ostanejo čista.", tag: "Dnevnik naročil" },
    ],
  },
  founder: {
    eyebrow: "Naredil lastnik kavarne, ne dostavni startup",
    quoteStart: "Z ženo sva odprla kavarno in tedne iskala način, kako sprejemati naročila pri mizi, ki ne bi dajal 30 % agregatorju in ne bi zahteval blagajne za 1500 €. Vse, kar sva preizkusila, je bilo okorno, drago ali brez osnov —",
    quoteAccent: "zato sva zgradila sistem naročanja, ki bi ga sama hotela imeti.",
    sign: "Bogdan Sokolov · ustanovitelj, nekdanji lastnik kavarne",
    photoAlt: "Bogdan, ustanovitelj IQ Rest",
  },
  how: {
    heading: "Vklopi sistem naročanja",
    headingAccent: "v 4 korakih",
    sub: "Brez namestitve, brez integratorja, brez klica IT-ju. Samo telefon in 5 minut.",
    steps: [
      { n: "1", t: "Ustvari restavracijo", d: "Registracija z e-pošto ali Googlom — 30 sekund." },
      { n: "2", t: "Dodaj meni", d: "Drag-and-drop ali AI skeniranje papirnatega menija." },
      { n: "3", t: "Izberi kanal", d: "Kuhinjski tablet, WhatsApp ali oba." },
      { n: "4", t: "Natisni QR", d: "En QR na mizo — gostje naročajo takoj." },
    ],
  },
  pricing: {
    badge: "Neomejena naročila · Brez provizije",
    heading: "En načrt.",
    headingAccent: "Brez pristojbine na naročilo.",
    sub: "Spletna naročila, QR meni, WhatsApp način, večjezični checkout in analitika — vse v eni naročnini. Brez odstotka od transakcije.",
    monthlyLabel: "Mesečno",
    yearlyLabel: "Letno",
    saveBadge: "Prihrani 25%",
    perMonth: "mesečno",
    billedAnnually: "Zaračunano enkrat letno {total}",
    youSave: "Prihraniš {amount}",
    trust: { secure: "Naročnina prek Stripe", noCommitment: "Brez obveznosti", quick: "Aktivno v minutah", restaurants: "+500 restavracij" },
  },
  faq: {
    eyebrow: "Sistem naročanja — pogosta vprašanja",
    heading: "O sistemu",
    headingAccent: "naročanja.",
    sub: "Kaj lastniki restavracij sprašujejo pred vklopom spletnih naročil v IQ Rest. Ne vidiš svojega vprašanja? Piši na WhatsApp — odgovarjajo pravi ljudje.",
    whatsappCta: "Vprašaj na WhatsApp",
    whatsappPrefill: "Pozdravljeni, imam vprašanje o naročilih IQ Rest",
    items: [
      { q: "Ali je to dostavna platforma kot Wolt ali Glovo?", a: "Ne, prav v tem je bistvo. IQ Rest je lasten naročilni kanal restavracije: gost naroči iz tvojega QR, naročilo pride na tvoj tablet ali WhatsApp, ti postrežeš. Brez marketplaca, brez kataloga agregatorja — in nikoli ne vzamemo deleža računa." },
      { q: "Kje točno se naročila pojavijo?", a: "V zavihku Kuhinja panela IQ Rest na katerem koli tabletu ali telefonu ob izdaji ali šanku. Vsako naročilo prikaže številko mize, jedi z različicami in alergeni, komentar gosta in dnevno številko. Prehod „novo → v delu → pripravljeno“ z enim dotikom." },
      { q: "Ali lahko naročila pridejo v WhatsApp namesto tega?", a: "Da. Vsaka restavracija ima tri načine: notranji (samo kuhinjski tablet), WhatsApp (naročilo pride kot sporočilo v WhatsApp restavracije) ali oba hkrati. Način je en preklop v panelu, spremeni se kadar koli." },
      { q: "Kaj je v naročilu?", a: "Jedi z različicami in dodatki (z razliko v ceni), alergeni, številka mize, prost komentar gosta in — če vklopiš polja — ime, telefon in naslov. Dovolj za pošiljanje kurirja ali klic nazaj k mizi zaradi alergena." },
      { q: "Ali lahko gostje plačajo spletno v meniju?", a: "Privzeto — ne. IQ Rest je nastavljen za plačilo pri mizi: gost naroči, ti prineseš račun, plača se kot običajno. Če potrebuješ spletno plačilo s kartico (tipično za prevzem), je integracija Stripe Connect mogoča na zahtevo — piši na WhatsApp." },
      { q: "Ali potrebujem poseben tablet, tiskalnik ali POS strojno opremo?", a: "Ne. Katerikoli tablet, prenosnik ali telefon z brskalnikom — odpri panel, prijavi se, pusti zavihek Kuhinja odprt. Če že imaš POS — IQ Rest teče ob njem, ne nadomešča blagajne." },
      { q: "Kaj po 14 brezplačnih dneh?", a: "Brez plačilne metode se račun pavzira — nikoli ne zaračunamo samodejno. Meni, naročila in nastavitve se ohranijo; dodaš kartico kadar koli za reaktivacijo. Preklic z enim klikom, brez obveznosti." },
    ],
  },
  finalCta: {
    heading: "Vklopi sistem naročanja.",
    headingAccent: "Pripravljeno v 5 minutah.",
    sub: "14 dni brezplačno, brez kartice. Prekliči kadar koli. Pridruži se 500+ restavracijam, ki svoja naročila upravljajo prek IQ Rest.",
  },
  scan: {
    heading: "Iz papirnatega menija v sistem naročanja",
    headingAccent: "v 60 sekundah",
    sub: "Naloži fotografijo menija — AI izvleče kategorije, jedi in cene neposredno v urejevalnik. Nato košarica in QR — z enim klikom.",
    cta: "Skeniraj meni →",
  },
  footer: {
    featureLinks: [
      { href: "/sl/ai-translation", label: "AI prevod" },
      { href: "/sl/reservations", label: "Rezervacije" },
      { href: "/sl/mobile-management", label: "Mobilno upravljanje" },
      { href: "/sl/easy-menu", label: "Urejevalnik jedilnika" },
      { href: "/sl/custom-design", label: "Video in foto ozadja" },
      { href: "/sl/color-scheme", label: "Barve znamke" },
      { href: "/sl/multilingual", label: "Večjezični meni" },
      { href: "/sl/ai-images", label: "AI optimizacija fotografij" },
      { href: "/sl/analytics", label: "Analitika" },
      { href: "/sl/instant-setup", label: "Takojšnja namestitev" },
      { href: "/sl/personal-support", label: "Osebna podpora" },
    ],
    navLinks: [
      { href: "#pricing", label: "Cene" },
      { href: "#faq", label: "Vprašanja" },
      { href: "/sl/changelog", label: "Novice" },
      { href: "/sl/languages", label: "Spremeni jezik" },
    ],
    copyrightTemplate: "© {year} IQ Rest. Vse pravice pridržane.",
  },
};
