import { Check } from "lucide-react";
import { Section } from "@/app/_landing/components/section";

const BENEFITS = ["QR på hvert bord, skann-og-bestill, uten app", "Bestillinger i sanntid på kjøkken- eller manager-nettbrett", "Eller i restaurantens WhatsApp — du velger", "Modifiers, varianter og allergener kommer med på kvitteringen", "Fri kommentar fra gjest på hver bestilling", "Daglig nummerering til kjøkkenet", "Flerspråklig checkout på 35 språk, etter gjestens telefon", "Null provisjon per bestilling — fast månedlig abonnement"];
const HOW_STEPS = [
  { title: "Slå på bestillinger for restauranten", desc: "Åpne restaurantinnstillingene, aktiver bryteren Bestillinger og velg hvilke gjestefelt (navn, telefon, adresse) som skal samles inn." },
  { title: "Velg leveringskanal", desc: "Intern modus sender nye bestillinger til fanen Kjøkken. WhatsApp-modus formaterer bestillingen som melding i restaurantens WhatsApp. Eller begge parallelt." },
  { title: "Skriv ut og fest QR", desc: "Last ned QR (én per bord eller én per restaurant) i PDF eller PNG og fest på bordene. Gjestene skanner med eget kamera — uten App Store, uten friksjon." },
  { title: "Kjør vakten", desc: "Bestillinger dukker opp i fanen Kjøkken med bordnummer, retter, varianter, allergener, kommentar og daglig nummer. Overgang ny → pågår → ferdig. Gjestens nettleser oppdateres i sanntid." },
];
const COMPARISON_ROWS = [["Provisjon per bestilling","20–30%","0%","0% (€6,90/mnd fast)"],["Hvor bestillingen havner","Aggregator-app","Din kasse","Ditt kjøkkennettbrett eller WhatsApp"],["Bordnummer på kvittering","Nei","Manuelt","Ja, automatisk"],["Modifiers / varianter","Begrenset","Ja","Ja, med allergener"],["Flerspråklig checkout","Deres app-språk","Nei","35 språk, automatisk"],["Nødvendig maskinvare","Aggregator-nettbrett","POS-terminal","Et hvilket som helst nettbrett med nettleser"],["Oppsettstid","Onboarding-samtale","Dager-uker","5 minutter"]];

export function SeoContent() {
  return (<>
    <Section noContainer dataSection="seo-intro"><div className="w-full"><p className="text-xs font-medium uppercase tracking-widest text-primary mb-3 text-start">Detaljert</p><h2 className="text-3xl sm:text-4xl lg:text-5xl font-medium tracking-tight mb-3 text-start">Hva et online bestillingssystem for restaurant <span className="text-muted-foreground">egentlig er</span></h2><p className="text-base sm:text-lg text-muted-foreground mb-10 text-start">Ingen marketplace. Ingen leveringsaggregator. En direkte linje fra gjestens telefon ved bordet ditt til kjøkkennettbrettet — eller WhatsApp.</p><div className="space-y-4 text-base sm:text-lg text-foreground/90 leading-relaxed"><p><strong>Online bestillingssystem for restaurant</strong> i IQ Rest sin forstand er programvare som lar gjesten ved bordet ditt åpne menyen på telefonen, lage en kurv og sende bestillingen til kjøkkenet — uten Foodora, Wolt, Bolt Food eller en annen marketplace. Gjesten forlater aldri din QR-meny, du betaler ingen provisjon per bestilling, og kvitteringen kommer med det reelle bordnummeret.</p><p>IQ Rest er bygget rundt to kanaler. Som standard er <em>intern modus</em>: hver nye bestilling havner i fanen Kjøkken i panelet på et nettbrett, telefon eller bærbar PC ved passet — med bordnummer, retter med varianter og allergener, fri kommentar fra gjest og daglig bestillingsnummer. Alternativet er <em>WhatsApp-modus</em>: samme bestilling formateres som melding i restaurantens WhatsApp. Nyttig for små team, hovedsakelig take away eller når manageren er ute av salen. Begge moduser kan kjøre samtidig.</p></div></div></Section>
    <Section noContainer dataSection="seo-benefits"><div className="w-full"><h3 className="text-2xl sm:text-3xl font-medium tracking-tight mb-6 text-start">Hva du faktisk får</h3><div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-3 sm:gap-4">{BENEFITS.map((b) => (<div key={b} className="bg-muted/20 border border-border rounded-2xl p-4 sm:p-5 flex flex-row items-center gap-3"><div className="h-8 w-8 rounded-lg bg-primary/10 text-primary flex items-center justify-center shrink-0"><Check className="h-4 w-4" strokeWidth={2.5} /></div><p className="text-sm sm:text-base text-foreground/90 leading-snug">{b}</p></div>))}</div></div></Section>
    <Section noContainer dataSection="seo-how"><div className="w-full"><h3 className="text-2xl sm:text-3xl font-medium tracking-tight mb-6 text-start">Slik virker IQ Rest sin bestillingsflyt</h3><p className="text-base sm:text-lg text-foreground/90 leading-relaxed mb-6 text-start">Fire brytere i panelet — og du er live. Ingen installatør, ingen POS-maskinvare, intet integrasjonsprosjekt.</p><div className="grid grid-cols-1 sm:grid-cols-2 gap-3 sm:gap-4">{HOW_STEPS.map((s, i) => (<div key={s.title} className="bg-muted/20 border border-border rounded-2xl p-5 flex flex-row items-start gap-4"><div className="h-10 w-10 rounded-lg bg-primary text-primary-foreground flex items-center justify-center shrink-0 font-semibold text-base">{i + 1}</div><div className="flex-1 min-w-0"><div className="text-base sm:text-lg font-semibold tracking-tight mb-1">{s.title}</div><p className="text-sm text-muted-foreground leading-relaxed">{s.desc}</p></div></div>))}</div></div></Section>
    <Section noContainer dataSection="seo-table"><div className="w-full"><h3 className="text-2xl sm:text-3xl font-medium tracking-tight mb-6 text-start">Aggregator, klassisk POS eller bestillingssystem</h3><div className="bg-muted/20 border border-border rounded-2xl p-4 sm:p-6 overflow-x-auto"><table className="w-full text-sm sm:text-base border-collapse"><thead><tr className="border-b border-border"><th className="text-left font-semibold py-3 pr-3 text-foreground">Egenskap</th><th className="text-left font-semibold py-3 pr-3 text-muted-foreground">Leveringsaggregator</th><th className="text-left font-semibold py-3 pr-3 text-muted-foreground">Klassisk POS</th><th className="text-left font-semibold py-3 text-primary">IQ Rest-bestillinger</th></tr></thead><tbody className="text-foreground/90">{COMPARISON_ROWS.map((row, i) => (<tr key={row[0]} className={i < COMPARISON_ROWS.length - 1 ? "border-b border-border/50" : ""}><td className="py-3 pr-3 font-medium">{row[0]}</td><td className="py-3 pr-3 text-muted-foreground">{row[1]}</td><td className="py-3 pr-3 text-muted-foreground">{row[2]}</td><td className="py-3 text-foreground">{row[3]}</td></tr>))}</tbody></table></div><p className="text-sm text-muted-foreground leading-relaxed mt-6 text-start">Et online bestillingssystem som restauranten eier selv tjener seg inn første helg — hver krone gjesten bruker i salen din blir i salen din, og kvitteringen ved passet er alltid med ekte bordnummer.</p></div></Section>
  </>);
}
