import { QrCode, MessageCircle, ChefHat, Settings2, Languages, BarChart3 } from "lucide-react";
import type { LandingTexts } from "@/app/_landing/types";

export const TEXTS: LandingTexts = {
  htmlLang: "no",
  htmlDir: "ltr",
  meta: {
    title: "Online bestillingssystem for restaurant — QR og WhatsApp | IQ Rest",
    description: "Online bestillingssystem for restaurant: gjesten skanner QR ved bordet, lager bestilling og den havner rett på kjøkkennettbrettet eller WhatsApp. Null provisjon, med bordnummer. 14 dager gratis.",
    canonical: "https://iq-rest.com/no/online-bestillingssystem-restaurant",
    ogLocale: "no_NO",
    ogTitle: "Online bestillingssystem for restaurant — Rett til kjøkkenet",
    ogDescription: "Gjesten skanner QR ved bordet, lager bestilling og den havner på nettbrettet eller WhatsApp — uten mellomledd, uten provisjon, med bordnummer på hver kvittering.",
  },
  ctaText: "Slå på bestillinger",
  demoText: "Live demo",
  microcopy: "Fra €6,90/mnd · 14 dager gratis · Avslutt når du vil",
  header: { navFeatures: "Funksjoner", navHow: "Slik virker det", navPricing: "Priser", navFaq: "FAQ", signIn: "Logg inn", cta: "Prøv det" },
  hero: {
    verticals: ["Restauranter", "Kafeer", "Bistroer", "Pizzeriaer", "Barer", "Ølbarer"],
    headline: "Online bestillingssystem for restaurant.",
    sub: "Gjesten skanner QR-en på bordet sitt, lager bestilling på telefonen — og kvitteringen havner rett på kjøkkennettbrettet eller restaurantens WhatsApp. Uten mellomledd, uten provisjon, med bordnummer på hver kvittering.",
    dynamicHeadlines: ["Bestilling ved bordet.", "Rett til kjøkkennettbrettet.", "Eller rett til WhatsApp.", "Null provisjon.", "Med bordnummer."],
    painBullets: [
      "Online bestillingssystem som restauranten eier selv — ingen mellomledd, ingen provisjon.",
      "Bestillinger havner på kjøkkenets eller managerens nettbrett med bordnummer, modifiers, allergener og notater.",
      "Eller sendes rett til restaurantens WhatsApp — ideelt for take away og små team.",
      "QR til hvert bord (eller én til hele restauranten) genereres automatisk.",
    ],
    rating: "500+ restauranter i 30+ land",
  },
  features: {
    heading: "Bestillingssystem,",
    headingAccent: "bygget for bordet.",
    sub: "Reell funksjonalitet — ikke en klone av leveringsaggregatorer.",
    items: [
      { Icon: QrCode, title: "QR-meny med kurv for hvert bord", desc: "Gjesten skanner QR, blar i menyen på sitt eget språk, legger til retter med modifiers, etterlater notat til kjøkkenet og sender. Uten app.", tag: "QR-bestilling" },
      { Icon: ChefHat, title: "Bestillinger på kjøkkennettbrettet", desc: "Hver ny bestilling dukker opp i fanen Kjøkken — på et nettbrett ved passet — med bordnummer, retter, varianter, allergener og kommentar. Ett trykk fra „pågår“ til „ferdig“.", tag: "Kjøkkenvisning" },
      { Icon: MessageCircle, title: "Eller til WhatsApp", desc: "Sett restauranten i WhatsApp-modus (eller begge samtidig) — hver bestilling havner i WhatsApp som formatert melding. Ideelt for take away eller små team.", tag: "WhatsApp-modus" },
      { Icon: Settings2, title: "Modifiers, varianter og allergener", desc: "Hver rett har variantgrupper (størrelse, steking, ekstra) med prisforskjell, allergen-tagger og fri beskrivelse. Kurven regner ut alt — kvitteringen på nettbrettet er uten tvil.", tag: "Ekte kurv" },
      { Icon: Languages, title: "Flerspråklig checkout", desc: "Hele bestillingsflyten — kurv, modifiers, kommentar, bekreftelse — er oversatt til 35 språk og tilpasser seg automatisk språket på gjestens telefon.", tag: "35 språk" },
      { Icon: BarChart3, title: "Daglig nummerering og logg", desc: "Hver bestilling får et daglig nummer for kjøkkenet, går i loggen med beløp og tidsstempler, mater analyser. Kanselleringer er soft-delete, rapporter forblir rene.", tag: "Bestillingslogg" },
    ],
  },
  founder: {
    eyebrow: "Laget av en kafé-eier, ikke en leverings-startup",
    quoteStart: "Min kone og jeg åpnet en kafé og brukte uker på å lete etter en måte å ta imot bordbestillinger på som ikke skulle gi 30% til en aggregator eller kreve en kasse til 1500 €. Alt vi prøvde var klumpete, dyrt eller manglet det basale —",
    quoteAccent: "så vi bygget bestillingssystemet vi selv ville hatt.",
    sign: "Bogdan Sokolov · grunnlegger, eks-kafeeier",
    photoAlt: "Bogdan, grunnlegger av IQ Rest",
  },
  how: {
    heading: "Slå på bestillingssystemet",
    headingAccent: "på 4 steg",
    sub: "Ingen installasjon, ingen integrator, ingen IT-telefon. Bare en telefon og 5 minutter.",
    steps: [
      { n: "1", t: "Lag restaurant", d: "Registrering med e-post eller Google — 30 sekunder." },
      { n: "2", t: "Legg til meny", d: "Drag-and-drop eller AI-skanning av papirmeny." },
      { n: "3", t: "Velg kanal", d: "Kjøkkennettbrett, WhatsApp eller begge." },
      { n: "4", t: "Skriv ut QR", d: "Én QR per bord — gjestene bestiller med en gang." },
    ],
  },
  pricing: {
    badge: "Ubegrensede bestillinger · Null provisjon",
    heading: "Én plan.",
    headingAccent: "Ingen gebyr per bestilling.",
    sub: "Online bestilling, QR-meny, WhatsApp-modus, flerspråklig checkout og analyser — alt i ett abonnement. Ingen prosent av transaksjonen.",
    monthlyLabel: "Månedlig",
    yearlyLabel: "Årlig",
    saveBadge: "Spar 25%",
    perMonth: "per måned",
    billedAnnually: "Fakturert én gang i året {total}",
    youSave: "Du sparer {amount}",
    trust: { secure: "Abonnement via Stripe", noCommitment: "Ingen binding", quick: "Aktiv på minutter", restaurants: "+500 restauranter" },
  },
  faq: {
    eyebrow: "Bestillingssystem — vanlige spørsmål",
    heading: "Om bestillings-",
    headingAccent: "systemet.",
    sub: "Det restauratører spør om før de slår på online-bestillinger i IQ Rest. Mangler ditt spørsmål? Skriv på WhatsApp — ekte folk svarer.",
    whatsappCta: "Spør på WhatsApp",
    whatsappPrefill: "Hei, jeg har et spørsmål om IQ Rest-bestillinger",
    items: [
      { q: "Er det en leveringsplattform som Foodora eller Wolt?", a: "Nei, det er hele poenget. IQ Rest er restaurantens egen bestillingskanal: gjesten bestiller fra din QR, bestillingen havner på nettbrettet eller WhatsApp, du serverer. Ingen marketplace, ingen aggregator-katalog — og vi tar aldri en del av regningen." },
      { q: "Hvor dukker bestillingene opp nøyaktig?", a: "I fanen Kjøkken i IQ Rest-panelet på et hvilket som helst nettbrett eller telefon ved passet eller baren. Hver bestilling viser bordnummer, retter med varianter og allergener, gjestens kommentar og daglig nummer. Overgang „ny → pågår → ferdig“ med ett trykk." },
      { q: "Kan bestillinger komme til WhatsApp i stedet?", a: "Ja. Hver restaurant har tre moduser: intern (kun kjøkkennettbrett), WhatsApp (bestillingen kommer som melding i restaurantens WhatsApp) eller begge samtidig. Modus er én bryter i panelet, endres når du vil." },
      { q: "Hva er i bestillingen?", a: "Retter med varianter og ekstra (med prisforskjell), allergener, bordnummer, fri kommentar fra gjest og — hvis du slår på feltene — navn, telefon og adresse. Nok til å sende bud eller ringe tilbake til bordet om en allergen." },
      { q: "Kan gjestene betale online i menyen?", a: "Som standard — nei. IQ Rest er satt opp for betaling ved bordet: gjesten bestiller, du bringer regningen, det betales som vanlig. Hvis du trenger online kortbetaling (typisk for take away), er Stripe Connect-integrasjon mulig på forespørsel — skriv på WhatsApp." },
      { q: "Trenger jeg en spesiell nettbrett, skriver eller POS-maskinvare?", a: "Nei. Et hvilket som helst nettbrett, bærbar PC eller telefon med nettleser — åpne panelet, logg inn, la fanen Kjøkken stå åpen. Hvis du allerede har et POS — IQ Rest kjører ved siden av, erstatter ikke kassen." },
      { q: "Hva skjer etter 14 gratis dager?", a: "Uten betalingsmetode pauses kontoen — vi trekker aldri automatisk. Meny, bestillinger og innstillinger bevares; legg til kort når du vil for å reaktivere. Avslutt med ett klikk, ingen binding." },
    ],
  },
  finalCta: {
    heading: "Slå på bestillingssystemet.",
    headingAccent: "Klart på 5 minutter.",
    sub: "14 dager gratis, ingen kort. Avslutt når du vil. Bli med blant 500+ restauranter som styrer bestillingene sine gjennom IQ Rest.",
  },
  scan: {
    heading: "Fra papirmeny til bestillingssystem",
    headingAccent: "på 60 sekunder",
    sub: "Last opp et bilde av menyen — AI henter kategorier, retter og priser rett inn i redigereren. Så kurv og QR — med ett klikk.",
    cta: "Skann menyen →",
  },
  footer: {
    featureLinks: [
      { href: "/no/ai-translation", label: "AI-oversettelse" },
      { href: "/no/reservations", label: "Reservasjoner" },
      { href: "/no/mobile-management", label: "Mobilstyring" },
      { href: "/no/easy-menu", label: "Meny-editor" },
      { href: "/no/custom-design", label: "Video- og fotobakgrunner" },
      { href: "/no/color-scheme", label: "Merkefarger" },
      { href: "/no/multilingual", label: "Flerspråklig meny" },
      { href: "/no/ai-images", label: "AI-bildeoptimalisering" },
      { href: "/no/analytics", label: "Analyser" },
      { href: "/no/instant-setup", label: "Øyeblikkelig oppsett" },
      { href: "/no/personal-support", label: "Personlig support" },
    ],
    navLinks: [
      { href: "#pricing", label: "Priser" },
      { href: "#faq", label: "Spørsmål" },
      { href: "/no/changelog", label: "Nyheter" },
      { href: "/no/languages", label: "Bytt språk" },
    ],
    copyrightTemplate: "© {year} IQ Rest. Alle rettigheter forbeholdt.",
  },
};
