// Generate per-locale PPC LP /lp/<qr-menu-slug> for all 35 locales. Mirrors
// the existing /lp/digital-menu-* matrix but hammers "QR menu" instead of
// "digital menu" so Google Ads can run a separate ad group / keyword
// (qr menu) with strong landing page relevance.
//
// Each LP overrides the minimum that matters for QS: H1 + accent word +
// hero sub, founder quote, two FAQ items, finalCta, and meta. Everything
// else inherits from the locale's main TEXTS so we don't drift copy that
// isn't keyword-bearing.

import { writeFileSync, mkdirSync, existsSync } from "fs";
import * as path from "path";

interface LocaleSpec {
  code: string;          // e.g. "en"
  slug: string;          // path under /<locale>/lp/, e.g. "qr-menu-for-restaurants"
  ogLocale: string;      // e.g. "en_US"
  // Keyword + adjacent phrasing in the locale's language. The H1 is built as
  // `headlinePrefix + accentWord + headlineSuffix` so the accent rotator can
  // still cycle venue types.
  headlinePrefix: string;
  accentWord: string;
  headlineSuffix: string;
  // Full noun phrase ("QR menu for restaurants") used in FAQ + finalCta.
  fullPhrase: string;
  // Free-form copy slots.
  heroSub: string;
  founderQuoteStart: string;
  founderQuoteAccent: string;
  faqQ1: string; faqA1: string;
  faqQ2: string; faqA2: string;
  finalCtaHeading: string; finalCtaAccent: string; finalCtaSub: string;
  metaTitle: string; metaDescription: string; ogTitle: string; ogDescription: string;
}

const SPECS: LocaleSpec[] = [
  {
    code: "en", slug: "qr-menu-for-restaurants", ogLocale: "en_US",
    headlinePrefix: "QR menu for ", accentWord: "restaurants", headlineSuffix: "",
    fullPhrase: "QR menu for restaurants",
    heroSub: "500+ restaurants in 30+ countries replace printed menus with a QR menu, sell more to tourists, and cut delivery commissions to zero. Live in 5 minutes — 14 days free.",
    founderQuoteStart: "My wife and I opened a café and spent weeks looking for a QR menu for restaurants that also handled table ordering and reservations without being clunky or ugly —",
    founderQuoteAccent: "so we built the QR menu we wanted ourselves.",
    faqQ1: "What is a QR menu for restaurants?",
    faqA1: "A QR menu for restaurants is the printable QR code at the table that guests scan with their phone camera to open the menu in the browser — no app to install. With IQ Rest the QR menu also includes direct table ordering, 24/7 reservations, and AI translation into 35 languages, all updated from your phone in real time.",
    faqQ2: "How much does a QR menu for restaurants cost?",
    faqA2: "€6.90/month, all included. Unlimited QR codes for every table, full menu editor, direct ordering with zero commissions, AI translation into 35 languages, reservations, and analytics. 14-day free trial, no card required.",
    finalCtaHeading: "QR menu for restaurants.", finalCtaAccent: "Ready in 5 minutes.",
    finalCtaSub: "14 days free. No card required. Join 500+ restaurants running their QR menu on IQ Rest.",
    metaTitle: "QR Menu for Restaurants — Ready in 5 Min | IQ Rest",
    metaDescription: "QR menu for restaurants: printable QR code at every table, direct orders with zero commissions, AI translation in 35 languages. Live in 5 minutes, 14 days free.",
    ogTitle: "QR Menu for Restaurants — Ready in 5 Minutes",
    ogDescription: "QR menu for restaurants with direct orders, 35 AI languages and table reservations. Live in 5 minutes — 14 days free.",
  },
  {
    code: "es", slug: "menu-qr-para-restaurantes", ogLocale: "es_ES",
    headlinePrefix: "Menú QR para ", accentWord: "restaurantes", headlineSuffix: "",
    fullPhrase: "Menú QR para restaurantes",
    heroSub: "Más de 500 restaurantes en 30+ países usan un menú QR en lugar de cartas impresas, venden más a los turistas y eliminan las comisiones de delivery. Listo en 5 minutos — 14 días gratis.",
    founderQuoteStart: "Mi mujer y yo abrimos un café y pasamos semanas buscando un menú QR para restaurantes que también hiciera pedidos en mesa y reservas sin ser feo o complicado —",
    founderQuoteAccent: "así que construimos el menú QR que queríamos nosotros mismos.",
    faqQ1: "¿Qué es un menú QR para restaurantes?",
    faqA1: "Un menú QR para restaurantes es el código QR imprimible en la mesa que los clientes escanean con la cámara del móvil para abrir la carta en el navegador — sin app que instalar. Con IQ Rest el menú QR incluye pedidos en mesa, reservas 24/7 y traducción IA a 35 idiomas, todo actualizado desde el móvil.",
    faqQ2: "¿Cuánto cuesta un menú QR para restaurantes?",
    faqA2: "6,90 €/mes, todo incluido. QR ilimitados para cada mesa, editor completo, pedidos directos sin comisión, traducción IA a 35 idiomas, reservas y analítica. 14 días gratis, sin tarjeta.",
    finalCtaHeading: "Menú QR para restaurantes.", finalCtaAccent: "Listo en 5 minutos.",
    finalCtaSub: "14 días gratis. Sin tarjeta. Más de 500 restaurantes ya usan su menú QR en IQ Rest.",
    metaTitle: "Menú QR para Restaurantes — Listo en 5 Min | IQ Rest",
    metaDescription: "Menú QR para restaurantes: código QR en cada mesa, pedidos directos sin comisión, traducción IA a 35 idiomas. Listo en 5 minutos, 14 días gratis.",
    ogTitle: "Menú QR para Restaurantes — Listo en 5 Minutos",
    ogDescription: "Menú QR con pedidos directos, 35 idiomas IA y reservas. Listo en 5 minutos — 14 días gratis.",
  },
  {
    code: "it", slug: "menu-qr-per-ristoranti", ogLocale: "it_IT",
    headlinePrefix: "Menu QR per ", accentWord: "ristoranti", headlineSuffix: "",
    fullPhrase: "Menu QR per ristoranti",
    heroSub: "Oltre 500 ristoranti in 30+ paesi sostituiscono il menu cartaceo con un menu QR, vendono di più ai turisti e azzerano le commissioni del delivery. Online in 5 minuti — 14 giorni gratis.",
    founderQuoteStart: "Io e mia moglie abbiamo aperto un bar e passato settimane a cercare un menu QR per ristoranti che gestisse anche ordini al tavolo e prenotazioni senza essere brutto o complicato —",
    founderQuoteAccent: "così abbiamo costruito il menu QR che volevamo noi stessi.",
    faqQ1: "Cos'è un menu QR per ristoranti?",
    faqA1: "Un menu QR per ristoranti è il QR code stampabile sul tavolo che il cliente inquadra con il telefono per aprire il menu nel browser — nessuna app da installare. Con IQ Rest il menu QR include ordini al tavolo, prenotazioni 24/7 e traduzione AI in 35 lingue, tutto aggiornabile dal telefono.",
    faqQ2: "Quanto costa un menu QR per ristoranti?",
    faqA2: "6,90 €/mese, tutto incluso. QR illimitati per ogni tavolo, editor completo, ordini diretti senza commissioni, traduzione AI in 35 lingue, prenotazioni e analytics. 14 giorni gratis, senza carta.",
    finalCtaHeading: "Menu QR per ristoranti.", finalCtaAccent: "Pronto in 5 minuti.",
    finalCtaSub: "14 giorni gratis. Senza carta. Oltre 500 ristoranti usano già il menu QR su IQ Rest.",
    metaTitle: "Menu QR per Ristoranti — Pronto in 5 Min | IQ Rest",
    metaDescription: "Menu QR per ristoranti: QR code su ogni tavolo, ordini diretti senza commissioni, traduzione AI in 35 lingue. Online in 5 minuti, 14 giorni gratis.",
    ogTitle: "Menu QR per Ristoranti — Pronto in 5 Minuti",
    ogDescription: "Menu QR con ordini diretti, 35 lingue AI e prenotazioni. Online in 5 minuti — 14 giorni gratis.",
  },
  {
    code: "fr", slug: "menu-qr-pour-restaurants", ogLocale: "fr_FR",
    headlinePrefix: "Menu QR pour ", accentWord: "restaurants", headlineSuffix: "",
    fullPhrase: "Menu QR pour restaurants",
    heroSub: "Plus de 500 restaurants dans 30+ pays remplacent leur menu papier par un menu QR, vendent plus aux touristes et suppriment les commissions de livraison. En ligne en 5 minutes — 14 jours gratuits.",
    founderQuoteStart: "Ma femme et moi avons ouvert un café et passé des semaines à chercher un menu QR pour restaurants qui gère aussi commandes à table et réservations sans être moche ou compliqué —",
    founderQuoteAccent: "alors nous avons construit le menu QR que nous voulions.",
    faqQ1: "Qu'est-ce qu'un menu QR pour restaurants ?",
    faqA1: "Un menu QR pour restaurants est le code QR imprimable sur la table que les clients scannent avec l'appareil photo de leur téléphone pour ouvrir la carte dans le navigateur — sans app. Avec IQ Rest le menu QR inclut commandes à table, réservations 24/7 et traduction IA en 35 langues, tout mis à jour depuis le mobile.",
    faqQ2: "Combien coûte un menu QR pour restaurants ?",
    faqA2: "6,90 €/mois, tout inclus. QR illimités pour chaque table, éditeur complet, commandes directes sans commission, traduction IA en 35 langues, réservations et analytics. 14 jours gratuits, sans carte.",
    finalCtaHeading: "Menu QR pour restaurants.", finalCtaAccent: "Prêt en 5 minutes.",
    finalCtaSub: "14 jours gratuits. Sans carte. Plus de 500 restaurants utilisent déjà leur menu QR sur IQ Rest.",
    metaTitle: "Menu QR pour Restaurants — Prêt en 5 Min | IQ Rest",
    metaDescription: "Menu QR pour restaurants : QR code sur chaque table, commandes directes sans commission, traduction IA en 35 langues. En ligne en 5 minutes, 14 jours gratuits.",
    ogTitle: "Menu QR pour Restaurants — Prêt en 5 Minutes",
    ogDescription: "Menu QR avec commandes directes, 35 langues IA et réservations. En ligne en 5 minutes — 14 jours gratuits.",
  },
  {
    code: "de", slug: "qr-speisekarte-fuer-restaurants", ogLocale: "de_DE",
    headlinePrefix: "QR-Speisekarte für ", accentWord: "Restaurants", headlineSuffix: "",
    fullPhrase: "QR-Speisekarte für Restaurants",
    heroSub: "Über 500 Restaurants in 30+ Ländern ersetzen die Papierspeisekarte durch eine QR-Speisekarte, verkaufen mehr an Touristen und sparen Lieferprovisionen. Live in 5 Minuten — 14 Tage kostenlos.",
    founderQuoteStart: "Meine Frau und ich haben ein Café eröffnet und wochenlang nach einer QR-Speisekarte für Restaurants gesucht, die auch Tischbestellungen und Reservierungen kann ohne klobig zu sein —",
    founderQuoteAccent: "also haben wir die QR-Speisekarte selbst gebaut.",
    faqQ1: "Was ist eine QR-Speisekarte für Restaurants?",
    faqA1: "Eine QR-Speisekarte für Restaurants ist der druckbare QR-Code am Tisch, den Gäste mit der Handykamera scannen, um die Karte im Browser zu öffnen — keine App nötig. Mit IQ Rest enthält die QR-Speisekarte Tischbestellungen, Reservierungen rund um die Uhr und KI-Übersetzung in 35 Sprachen, alles per Mobile aktualisierbar.",
    faqQ2: "Was kostet eine QR-Speisekarte für Restaurants?",
    faqA2: "6,90 €/Monat, alles inklusive. Unbegrenzte QR-Codes für jeden Tisch, voller Editor, Direktbestellung ohne Provisionen, KI-Übersetzung in 35 Sprachen, Reservierungen und Analytics. 14 Tage gratis, ohne Karte.",
    finalCtaHeading: "QR-Speisekarte für Restaurants.", finalCtaAccent: "Bereit in 5 Minuten.",
    finalCtaSub: "14 Tage kostenlos. Ohne Karte. Über 500 Restaurants nutzen ihre QR-Speisekarte auf IQ Rest.",
    metaTitle: "QR-Speisekarte für Restaurants — In 5 Min Bereit | IQ Rest",
    metaDescription: "QR-Speisekarte für Restaurants: QR-Code an jedem Tisch, Direktbestellungen ohne Provision, KI-Übersetzung in 35 Sprachen. Live in 5 Minuten, 14 Tage gratis.",
    ogTitle: "QR-Speisekarte für Restaurants — In 5 Minuten Bereit",
    ogDescription: "QR-Speisekarte mit Direktbestellung, 35 KI-Sprachen und Reservierungen. Live in 5 Minuten — 14 Tage gratis.",
  },
  {
    code: "pt", slug: "menu-qr-para-restaurantes", ogLocale: "pt_PT",
    headlinePrefix: "Menu QR para ", accentWord: "restaurantes", headlineSuffix: "",
    fullPhrase: "Menu QR para restaurantes",
    heroSub: "Mais de 500 restaurantes em 30+ países substituem o menu impresso por um menu QR, vendem mais a turistas e eliminam comissões de delivery. Online em 5 minutos — 14 dias grátis.",
    founderQuoteStart: "Eu e a minha mulher abrimos um café e passámos semanas à procura de um menu QR para restaurantes que tratasse também pedidos à mesa e reservas sem ser feio —",
    founderQuoteAccent: "por isso construímos o menu QR que queríamos.",
    faqQ1: "O que é um menu QR para restaurantes?",
    faqA1: "Um menu QR para restaurantes é o código QR imprimível na mesa que os clientes lêem com a câmara do telemóvel para abrir a carta no browser — sem app. Com a IQ Rest o menu QR inclui pedidos à mesa, reservas 24/7 e tradução IA em 35 idiomas, tudo atualizado do telemóvel.",
    faqQ2: "Quanto custa um menu QR para restaurantes?",
    faqA2: "6,90 €/mês, tudo incluído. QR ilimitados para cada mesa, editor completo, pedidos diretos sem comissões, tradução IA em 35 idiomas, reservas e analytics. 14 dias grátis, sem cartão.",
    finalCtaHeading: "Menu QR para restaurantes.", finalCtaAccent: "Pronto em 5 minutos.",
    finalCtaSub: "14 dias grátis. Sem cartão. Mais de 500 restaurantes já usam o menu QR na IQ Rest.",
    metaTitle: "Menu QR para Restaurantes — Pronto em 5 Min | IQ Rest",
    metaDescription: "Menu QR para restaurantes: QR code em cada mesa, pedidos diretos sem comissões, tradução IA em 35 idiomas. Online em 5 minutos, 14 dias grátis.",
    ogTitle: "Menu QR para Restaurantes — Pronto em 5 Minutos",
    ogDescription: "Menu QR com pedidos diretos, 35 idiomas IA e reservas. Online em 5 minutos — 14 dias grátis.",
  },
  {
    code: "ru", slug: "qr-menyu-dlya-restoranov", ogLocale: "ru_RU",
    headlinePrefix: "QR-меню для ", accentWord: "ресторанов", headlineSuffix: "",
    fullPhrase: "QR-меню для ресторанов",
    heroSub: "Более 500 ресторанов в 30+ странах заменили бумажное меню на QR-меню, больше продают туристам и убрали комиссии доставок. Готово за 5 минут — 14 дней бесплатно.",
    founderQuoteStart: "Мы с женой открыли кафе и долго искали QR-меню для ресторанов с заказами за столом и бронями без уродливого интерфейса —",
    founderQuoteAccent: "поэтому сделали QR-меню сами.",
    faqQ1: "Что такое QR-меню для ресторанов?",
    faqA1: "QR-меню для ресторанов — это QR-код на столе, который гость сканирует камерой телефона и открывает меню в браузере — без приложения. В IQ Rest QR-меню включает заказы за столом, брони 24/7 и AI-перевод на 35 языков, всё обновляется со смартфона.",
    faqQ2: "Сколько стоит QR-меню для ресторанов?",
    faqA2: "6,90 €/мес, всё включено. Безлимит QR-кодов на каждый стол, полный редактор, прямые заказы без комиссии, AI-перевод на 35 языков, брони и аналитика. 14 дней бесплатно, без карты.",
    finalCtaHeading: "QR-меню для ресторанов.", finalCtaAccent: "Готово за 5 минут.",
    finalCtaSub: "14 дней бесплатно. Без карты. 500+ ресторанов уже используют QR-меню в IQ Rest.",
    metaTitle: "QR-меню для Ресторанов — За 5 Мин | IQ Rest",
    metaDescription: "QR-меню для ресторанов: QR-код на каждом столе, прямые заказы без комиссии, AI-перевод на 35 языков. Готово за 5 минут, 14 дней бесплатно.",
    ogTitle: "QR-меню для Ресторанов — Готово за 5 Минут",
    ogDescription: "QR-меню с прямыми заказами, 35 языков AI и бронями. Готово за 5 минут — 14 дней бесплатно.",
  },
  {
    code: "pl", slug: "menu-qr-dla-restauracji", ogLocale: "pl_PL",
    headlinePrefix: "Menu QR dla ", accentWord: "restauracji", headlineSuffix: "",
    fullPhrase: "Menu QR dla restauracji",
    heroSub: "Ponad 500 restauracji w 30+ krajach zastępuje drukowane menu menu QR, więcej sprzedaje turystom i eliminuje prowizje dostaw. Gotowe w 5 minut — 14 dni za darmo.",
    founderQuoteStart: "Z żoną otworzyliśmy kawiarnię i przez tygodnie szukaliśmy menu QR dla restauracji z zamówieniami przy stoliku i rezerwacjami bez brzydkiego interfejsu —",
    founderQuoteAccent: "więc sami stworzyliśmy menu QR, którego chcieliśmy.",
    faqQ1: "Czym jest menu QR dla restauracji?",
    faqA1: "Menu QR dla restauracji to drukowany kod QR przy stoliku, który gość skanuje aparatem telefonu i otwiera kartę w przeglądarce — bez aplikacji. Z IQ Rest menu QR zawiera zamówienia przy stoliku, rezerwacje 24/7 i tłumaczenie AI na 35 języków, wszystko aktualizowane z telefonu.",
    faqQ2: "Ile kosztuje menu QR dla restauracji?",
    faqA2: "6,90 €/mies, wszystko w cenie. Nielimitowane kody QR na każdy stolik, pełny edytor, bezpośrednie zamówienia bez prowizji, tłumaczenie AI na 35 języków, rezerwacje i analityka. 14 dni za darmo, bez karty.",
    finalCtaHeading: "Menu QR dla restauracji.", finalCtaAccent: "Gotowe w 5 minut.",
    finalCtaSub: "14 dni za darmo. Bez karty. Ponad 500 restauracji już używa menu QR na IQ Rest.",
    metaTitle: "Menu QR dla Restauracji — Gotowe w 5 Min | IQ Rest",
    metaDescription: "Menu QR dla restauracji: kod QR na każdym stoliku, bezpośrednie zamówienia bez prowizji, tłumaczenie AI na 35 języków. Gotowe w 5 minut, 14 dni za darmo.",
    ogTitle: "Menu QR dla Restauracji — Gotowe w 5 Minut",
    ogDescription: "Menu QR z bezpośrednimi zamówieniami, 35 językami AI i rezerwacjami. Gotowe w 5 minut — 14 dni za darmo.",
  },
  {
    code: "nl", slug: "qr-menu-voor-restaurants", ogLocale: "nl_NL",
    headlinePrefix: "QR-menu voor ", accentWord: "restaurants", headlineSuffix: "",
    fullPhrase: "QR-menu voor restaurants",
    heroSub: "Meer dan 500 restaurants in 30+ landen vervangen hun papieren menu door een QR-menu, verkopen meer aan toeristen en schrappen bezorg-commissies. Live in 5 minuten — 14 dagen gratis.",
    founderQuoteStart: "Mijn vrouw en ik openden een café en zochten weken naar een QR-menu voor restaurants dat ook tafelbestellingen en reserveringen aankan zonder lelijk te zijn —",
    founderQuoteAccent: "dus bouwden we het QR-menu dat we zelf wilden.",
    faqQ1: "Wat is een QR-menu voor restaurants?",
    faqA1: "Een QR-menu voor restaurants is de printbare QR-code op tafel die gasten met hun telefooncamera scannen om de kaart in de browser te openen — geen app nodig. Met IQ Rest bevat het QR-menu tafelbestellingen, reserveringen 24/7 en AI-vertaling naar 35 talen, alles vanaf de telefoon bij te werken.",
    faqQ2: "Wat kost een QR-menu voor restaurants?",
    faqA2: "€ 6,90/maand, alles inbegrepen. Onbeperkte QR-codes voor elke tafel, volledige editor, directe bestellingen zonder commissie, AI-vertaling naar 35 talen, reserveringen en analytics. 14 dagen gratis, geen kaart nodig.",
    finalCtaHeading: "QR-menu voor restaurants.", finalCtaAccent: "Klaar in 5 minuten.",
    finalCtaSub: "14 dagen gratis. Geen kaart. Meer dan 500 restaurants gebruiken al hun QR-menu op IQ Rest.",
    metaTitle: "QR-menu voor Restaurants — Klaar in 5 Min | IQ Rest",
    metaDescription: "QR-menu voor restaurants: QR-code op elke tafel, directe bestellingen zonder commissie, AI-vertaling naar 35 talen. Live in 5 minuten, 14 dagen gratis.",
    ogTitle: "QR-menu voor Restaurants — Klaar in 5 Minuten",
    ogDescription: "QR-menu met directe bestellingen, 35 AI-talen en reserveringen. Live in 5 minuten — 14 dagen gratis.",
  },
  {
    code: "tr", slug: "restoranlar-icin-qr-menu", ogLocale: "tr_TR",
    headlinePrefix: "Restoranlar için ", accentWord: "QR menü", headlineSuffix: "",
    fullPhrase: "Restoranlar için QR menü",
    heroSub: "30+ ülkedeki 500+ restoran basılı menüyü QR menü ile değiştiriyor, turistlere daha çok satıyor ve teslimat komisyonlarını sıfırlıyor. 5 dakikada hazır — 14 gün ücretsiz.",
    founderQuoteStart: "Eşimle bir kafe açtık ve restoranlar için masa siparişi ve rezervasyon yapabilen, çirkin olmayan bir QR menü ararken haftalar geçirdik —",
    founderQuoteAccent: "bu yüzden istediğimiz QR menüyü kendimiz yaptık.",
    faqQ1: "Restoranlar için QR menü nedir?",
    faqA1: "Restoranlar için QR menü, müşterilerin telefon kamerasıyla masadaki QR kodu okutarak menüyü tarayıcıda açtığı sistemdir — uygulama gerekmez. IQ Rest ile QR menü masa siparişi, 24/7 rezervasyon ve 35 dile AI çeviri içerir, hepsi telefondan güncellenir.",
    faqQ2: "Restoranlar için QR menü ne kadar?",
    faqA2: "Ayda 6,90 €, her şey dahil. Her masaya sınırsız QR kod, tam editör, komisyonsuz direkt sipariş, 35 dile AI çeviri, rezervasyon ve analitik. 14 gün ücretsiz, kart gerekmez.",
    finalCtaHeading: "Restoranlar için QR menü.", finalCtaAccent: "5 dakikada hazır.",
    finalCtaSub: "14 gün ücretsiz. Kart gerekmez. 500+ restoran QR menüsünü IQ Rest'te kullanıyor.",
    metaTitle: "Restoranlar için QR Menü — 5 Dakikada Hazır | IQ Rest",
    metaDescription: "Restoranlar için QR menü: her masada QR kod, komisyonsuz direkt sipariş, 35 dile AI çeviri. 5 dakikada hazır, 14 gün ücretsiz.",
    ogTitle: "Restoranlar için QR Menü — 5 Dakikada Hazır",
    ogDescription: "QR menü ile direkt sipariş, 35 dil AI ve rezervasyon. 5 dakikada hazır — 14 gün ücretsiz.",
  },
  {
    code: "ar", slug: "qaimat-qr-lilmataem", ogLocale: "ar_SA",
    headlinePrefix: "قائمة QR لـ ", accentWord: "المطاعم", headlineSuffix: "",
    fullPhrase: "قائمة QR للمطاعم",
    heroSub: "أكثر من 500 مطعم في 30+ دولة يستبدلون القائمة الورقية بقائمة QR ويبيعون أكثر للسياح وبدون عمولات توصيل. جاهزة خلال 5 دقائق — 14 يومًا مجانًا.",
    founderQuoteStart: "أنا وزوجتي افتتحنا مقهى وقضينا أسابيع نبحث عن قائمة QR للمطاعم تدعم الطلبات على الطاولة والحجوزات بدون تصميم سيئ —",
    founderQuoteAccent: "فبنينا قائمة QR التي أردناها بأنفسنا.",
    faqQ1: "ما هي قائمة QR للمطاعم؟",
    faqA1: "قائمة QR للمطاعم هي رمز QR قابل للطباعة على الطاولة يمسحه الضيف بكاميرا الهاتف ليفتح القائمة في المتصفح — بدون تطبيق. مع IQ Rest تتضمن قائمة QR الطلبات على الطاولة، الحجوزات 24/7 وترجمة AI لـ 35 لغة، كل ذلك من الهاتف.",
    faqQ2: "كم تكلفة قائمة QR للمطاعم؟",
    faqA2: "6.90 يورو/شهر، شامل كل شيء. رموز QR غير محدودة لكل طاولة، محرر كامل، طلبات مباشرة بدون عمولة، ترجمة AI لـ 35 لغة، حجوزات وتحليلات. 14 يومًا مجانًا، بدون بطاقة.",
    finalCtaHeading: "قائمة QR للمطاعم.", finalCtaAccent: "جاهزة في 5 دقائق.",
    finalCtaSub: "14 يومًا مجانًا. بدون بطاقة. أكثر من 500 مطعم يستخدمون قائمة QR على IQ Rest.",
    metaTitle: "قائمة QR للمطاعم — جاهزة في 5 دقائق | IQ Rest",
    metaDescription: "قائمة QR للمطاعم: رمز QR على كل طاولة، طلبات مباشرة بدون عمولة، ترجمة AI لـ 35 لغة. جاهزة في 5 دقائق، 14 يومًا مجانًا.",
    ogTitle: "قائمة QR للمطاعم — جاهزة في 5 دقائق",
    ogDescription: "قائمة QR مع طلبات مباشرة و35 لغة AI وحجوزات. جاهزة في 5 دقائق — 14 يومًا مجانًا.",
  },
  {
    code: "ja", slug: "restoran-qr-menu", ogLocale: "ja_JP",
    headlinePrefix: "レストラン向け ", accentWord: "QRメニュー", headlineSuffix: "",
    fullPhrase: "レストラン向けQRメニュー",
    heroSub: "30か国以上の500軒以上のレストランが紙のメニューをQRメニューに切り替え、観光客への販売を伸ばし、配達手数料をゼロにしています。5分で公開 — 14日間無料。",
    founderQuoteStart: "妻と私はカフェを開き、テーブル注文と予約も使えるレストラン向けQRメニューを何週間も探していました —",
    founderQuoteAccent: "そこで欲しかったQRメニューを自分たちで作りました。",
    faqQ1: "レストラン向けQRメニューとは？",
    faqA1: "レストラン向けQRメニューは、テーブルに置く印刷可能なQRコードで、お客様がスマートフォンのカメラで読み取るとブラウザでメニューが開きます。アプリ不要。IQ Restならテーブル注文、24時間予約、35言語AI翻訳もすべてスマホから更新可能です。",
    faqQ2: "レストラン向けQRメニューの料金は？",
    faqA2: "月額6.90ユーロですべて込み。各テーブル無制限QRコード、フルエディター、手数料ゼロの直接注文、35言語AI翻訳、予約、分析。14日間無料、カード不要。",
    finalCtaHeading: "レストラン向けQRメニュー。", finalCtaAccent: "5分で準備完了。",
    finalCtaSub: "14日間無料。カード不要。500軒以上のレストランがIQ RestでQRメニューを利用中。",
    metaTitle: "レストラン向けQRメニュー — 5分で完成 | IQ Rest",
    metaDescription: "レストラン向けQRメニュー：各テーブルにQRコード、手数料ゼロの直接注文、35言語AI翻訳。5分で公開、14日間無料。",
    ogTitle: "レストラン向けQRメニュー — 5分で完成",
    ogDescription: "QRメニューと直接注文、35言語AI、予約。5分で公開 — 14日間無料。",
  },
  {
    code: "zh", slug: "restaurant-qr-menu-chinese", ogLocale: "zh_CN",
    headlinePrefix: "餐厅 ", accentWord: "QR菜单", headlineSuffix: "",
    fullPhrase: "餐厅QR菜单",
    heroSub: "30多个国家的500多家餐厅用QR菜单取代纸质菜单，提高对游客的销售并取消外卖佣金。5分钟内上线 — 14天免费。",
    founderQuoteStart: "我和妻子开了一家咖啡馆，花了几周寻找能同时支持桌面点单和预订的餐厅QR菜单，但都不够好用 —",
    founderQuoteAccent: "于是我们自己做了想要的QR菜单。",
    faqQ1: "餐厅QR菜单是什么？",
    faqA1: "餐厅QR菜单是桌面上可打印的QR码，顾客用手机相机扫描即可在浏览器中打开菜单 — 无需安装应用。使用IQ Rest，QR菜单包含桌面点单、24/7预订和35种语言AI翻译，全部通过手机更新。",
    faqQ2: "餐厅QR菜单多少钱？",
    faqA2: "每月6.90欧元，全部包含。每张桌子无限QR码、完整编辑器、零佣金直接点单、35种语言AI翻译、预订和分析。14天免费试用，无需信用卡。",
    finalCtaHeading: "餐厅QR菜单。", finalCtaAccent: "5分钟内准备好。",
    finalCtaSub: "14天免费。无需信用卡。500多家餐厅已在IQ Rest使用QR菜单。",
    metaTitle: "餐厅QR菜单 — 5分钟即可使用 | IQ Rest",
    metaDescription: "餐厅QR菜单：每张桌子上的QR码、零佣金直接点单、35种语言AI翻译。5分钟内上线，14天免费。",
    ogTitle: "餐厅QR菜单 — 5分钟即可使用",
    ogDescription: "QR菜单提供直接点单、35种AI语言和预订。5分钟内上线 — 14天免费。",
  },
  {
    code: "ko", slug: "restaurant-qr-menu-korean", ogLocale: "ko_KR",
    headlinePrefix: "레스토랑 ", accentWord: "QR 메뉴", headlineSuffix: "",
    fullPhrase: "레스토랑 QR 메뉴",
    heroSub: "30개국 이상의 500개 이상의 레스토랑이 종이 메뉴를 QR 메뉴로 대체하고, 관광객에 더 많이 판매하며 배달 수수료를 없애고 있습니다. 5분 만에 시작 — 14일 무료.",
    founderQuoteStart: "아내와 저는 카페를 열고 테이블 주문과 예약도 지원하는 레스토랑 QR 메뉴를 몇 주 동안 찾았지만 마음에 드는 것이 없었습니다 —",
    founderQuoteAccent: "그래서 우리가 원하는 QR 메뉴를 직접 만들었습니다.",
    faqQ1: "레스토랑 QR 메뉴란?",
    faqA1: "레스토랑 QR 메뉴는 테이블에 인쇄된 QR 코드로, 손님이 스마트폰 카메라로 스캔하면 브라우저에서 메뉴가 열립니다 — 앱 설치 불필요. IQ Rest의 QR 메뉴는 테이블 주문, 24/7 예약, 35개 언어 AI 번역을 포함하며 모두 모바일에서 업데이트됩니다.",
    faqQ2: "레스토랑 QR 메뉴 가격은?",
    faqA2: "월 6.90유로, 모두 포함. 테이블당 무제한 QR 코드, 전체 편집기, 수수료 없는 직접 주문, 35개 언어 AI 번역, 예약 및 분석. 14일 무료 체험, 카드 불필요.",
    finalCtaHeading: "레스토랑 QR 메뉴.", finalCtaAccent: "5분 만에 준비.",
    finalCtaSub: "14일 무료. 카드 불필요. 500개 이상의 레스토랑이 IQ Rest에서 QR 메뉴를 사용 중.",
    metaTitle: "레스토랑 QR 메뉴 — 5분 만에 준비 | IQ Rest",
    metaDescription: "레스토랑 QR 메뉴: 각 테이블의 QR 코드, 수수료 없는 직접 주문, 35개 언어 AI 번역. 5분 만에 시작, 14일 무료.",
    ogTitle: "레스토랑 QR 메뉴 — 5분 만에 준비",
    ogDescription: "QR 메뉴와 직접 주문, 35개 AI 언어, 예약. 5분 만에 시작 — 14일 무료.",
  },
  {
    code: "uk", slug: "qr-menyu-dlya-restoraniv", ogLocale: "uk_UA",
    headlinePrefix: "QR-меню для ", accentWord: "ресторанів", headlineSuffix: "",
    fullPhrase: "QR-меню для ресторанів",
    heroSub: "Понад 500 ресторанів у 30+ країнах замінили паперове меню QR-меню, більше продають туристам і скасували комісії доставок. Готово за 5 хвилин — 14 днів безкоштовно.",
    founderQuoteStart: "Ми з дружиною відкрили кафе й кілька тижнів шукали QR-меню для ресторанів із замовленнями за столом та бронюваннями без потворного інтерфейсу —",
    founderQuoteAccent: "тож зробили QR-меню самі.",
    faqQ1: "Що таке QR-меню для ресторанів?",
    faqA1: "QR-меню для ресторанів — це QR-код на столі, який гість сканує камерою телефону, щоб відкрити меню в браузері — без застосунку. У IQ Rest QR-меню включає замовлення за столом, бронювання 24/7 та AI-переклад на 35 мов, усе оновлюється зі смартфону.",
    faqQ2: "Скільки коштує QR-меню для ресторанів?",
    faqA2: "6,90 €/міс, усе включено. Безлімітні QR-коди на кожен стіл, повний редактор, прямі замовлення без комісії, AI-переклад на 35 мов, бронювання та аналітика. 14 днів безкоштовно, без картки.",
    finalCtaHeading: "QR-меню для ресторанів.", finalCtaAccent: "Готово за 5 хвилин.",
    finalCtaSub: "14 днів безкоштовно. Без картки. 500+ ресторанів уже користуються QR-меню в IQ Rest.",
    metaTitle: "QR-меню для Ресторанів — За 5 Хв | IQ Rest",
    metaDescription: "QR-меню для ресторанів: QR-код на кожному столі, прямі замовлення без комісії, AI-переклад на 35 мов. Готово за 5 хвилин, 14 днів безкоштовно.",
    ogTitle: "QR-меню для Ресторанів — Готово за 5 Хвилин",
    ogDescription: "QR-меню з прямими замовленнями, 35 мов AI та бронюваннями. Готово за 5 хвилин — 14 днів безкоштовно.",
  },
  {
    code: "bg", slug: "qr-menyu-za-restoranti", ogLocale: "bg_BG",
    headlinePrefix: "QR меню за ", accentWord: "ресторанти", headlineSuffix: "",
    fullPhrase: "QR меню за ресторанти",
    heroSub: "Над 500 ресторанта в 30+ страни заменят хартиеното меню с QR меню, продават повече на туристите и премахват комисионите за доставка. Готово за 5 минути — 14 дни безплатно.",
    founderQuoteStart: "Със съпругата ми отворихме кафене и седмици търсихме QR меню за ресторанти с поръчки на масата и резервации без грозен интерфейс —",
    founderQuoteAccent: "затова направихме QR менюто сами.",
    faqQ1: "Какво е QR меню за ресторанти?",
    faqA1: "QR меню за ресторанти е принтиращ се QR код на масата, който гостът сканира с камерата на телефона и отваря менюто в браузъра — без приложение. С IQ Rest QR менюто включва поръчки на масата, резервации 24/7 и AI превод на 35 езика, всичко се обновява от телефона.",
    faqQ2: "Колко струва QR меню за ресторанти?",
    faqA2: "6,90 €/месец, всичко включено. Неограничени QR кодове за всяка маса, пълен редактор, директни поръчки без комисиона, AI превод на 35 езика, резервации и анализи. 14 дни безплатно, без карта.",
    finalCtaHeading: "QR меню за ресторанти.", finalCtaAccent: "Готово за 5 минути.",
    finalCtaSub: "14 дни безплатно. Без карта. 500+ ресторанта вече използват QR меню в IQ Rest.",
    metaTitle: "QR Меню за Ресторанти — Готово за 5 Мин | IQ Rest",
    metaDescription: "QR меню за ресторанти: QR код на всяка маса, директни поръчки без комисиона, AI превод на 35 езика. Готово за 5 минути, 14 дни безплатно.",
    ogTitle: "QR Меню за Ресторанти — Готово за 5 Минути",
    ogDescription: "QR меню с директни поръчки, 35 езика AI и резервации. Готово за 5 минути — 14 дни безплатно.",
  },
  {
    code: "ca", slug: "menu-qr-per-restaurants", ogLocale: "ca_ES",
    headlinePrefix: "Menú QR per a ", accentWord: "restaurants", headlineSuffix: "",
    fullPhrase: "Menú QR per a restaurants",
    heroSub: "Més de 500 restaurants a 30+ països substitueixen la carta impresa per un menú QR, venen més als turistes i eliminen comissions de delivery. Llest en 5 minuts — 14 dies gratis.",
    founderQuoteStart: "Amb la meva dona vam obrir una cafeteria i vam passar setmanes buscant un menú QR per a restaurants amb comandes a taula i reserves sense ser lleig —",
    founderQuoteAccent: "així que vam fer el menú QR nosaltres mateixos.",
    faqQ1: "Què és un menú QR per a restaurants?",
    faqA1: "Un menú QR per a restaurants és el codi QR imprimible a la taula que el client escaneja amb la càmera del mòbil per obrir la carta al navegador — sense aplicació. Amb IQ Rest el menú QR inclou comandes a taula, reserves 24/7 i traducció IA a 35 idiomes, tot actualitzat des del mòbil.",
    faqQ2: "Quant costa un menú QR per a restaurants?",
    faqA2: "6,90 €/mes, tot inclòs. QR il·limitats per a cada taula, editor complet, comandes directes sense comissió, traducció IA a 35 idiomes, reserves i analítica. 14 dies gratis, sense targeta.",
    finalCtaHeading: "Menú QR per a restaurants.", finalCtaAccent: "Llest en 5 minuts.",
    finalCtaSub: "14 dies gratis. Sense targeta. Més de 500 restaurants ja usen el menú QR a IQ Rest.",
    metaTitle: "Menú QR per a Restaurants — Llest en 5 Min | IQ Rest",
    metaDescription: "Menú QR per a restaurants: codi QR a cada taula, comandes directes sense comissió, traducció IA a 35 idiomes. Llest en 5 minuts, 14 dies gratis.",
    ogTitle: "Menú QR per a Restaurants — Llest en 5 Minuts",
    ogDescription: "Menú QR amb comandes directes, 35 idiomes IA i reserves. Llest en 5 minuts — 14 dies gratis.",
  },
  {
    code: "cs", slug: "qr-menu-pro-restaurace", ogLocale: "cs_CZ",
    headlinePrefix: "QR menu pro ", accentWord: "restaurace", headlineSuffix: "",
    fullPhrase: "QR menu pro restaurace",
    heroSub: "Více než 500 restaurací ve 30+ zemích nahrazuje tištěné menu QR menu, prodává více turistům a ruší provize doručovacích služeb. Hotovo za 5 minut — 14 dní zdarma.",
    founderQuoteStart: "S manželkou jsme otevřeli kavárnu a týdny hledali QR menu pro restaurace s objednávkami u stolu a rezervacemi bez ošklivého rozhraní —",
    founderQuoteAccent: "tak jsme QR menu udělali sami.",
    faqQ1: "Co je QR menu pro restaurace?",
    faqA1: "QR menu pro restaurace je tisknutelný QR kód u stolu, který host naskenuje fotoaparátem telefonu a otevře jídelní lístek v prohlížeči — bez aplikace. S IQ Rest QR menu obsahuje objednávky u stolu, rezervace 24/7 a AI překlad do 35 jazyků, vše aktualizované z mobilu.",
    faqQ2: "Kolik stojí QR menu pro restaurace?",
    faqA2: "6,90 €/měsíc, vše v ceně. Neomezené QR kódy pro každý stůl, kompletní editor, přímé objednávky bez provize, AI překlad do 35 jazyků, rezervace a analytika. 14 dní zdarma, bez karty.",
    finalCtaHeading: "QR menu pro restaurace.", finalCtaAccent: "Hotovo za 5 minut.",
    finalCtaSub: "14 dní zdarma. Bez karty. Více než 500 restaurací používá QR menu na IQ Rest.",
    metaTitle: "QR Menu pro Restaurace — Hotovo za 5 Min | IQ Rest",
    metaDescription: "QR menu pro restaurace: QR kód u každého stolu, přímé objednávky bez provize, AI překlad do 35 jazyků. Hotovo za 5 minut, 14 dní zdarma.",
    ogTitle: "QR Menu pro Restaurace — Hotovo za 5 Minut",
    ogDescription: "QR menu s přímými objednávkami, 35 AI jazyky a rezervacemi. Hotovo za 5 minut — 14 dní zdarma.",
  },
  {
    code: "da", slug: "qr-menu-til-restauranter", ogLocale: "da_DK",
    headlinePrefix: "QR-menu til ", accentWord: "restauranter", headlineSuffix: "",
    fullPhrase: "QR-menu til restauranter",
    heroSub: "Over 500 restauranter i 30+ lande udskifter den trykte menu med en QR-menu, sælger mere til turister og fjerner leveringsprovision. Klar på 5 minutter — 14 dage gratis.",
    founderQuoteStart: "Min kone og jeg åbnede en café og brugte uger på at lede efter en QR-menu til restauranter med bordbestilling og reservationer uden grim brugerflade —",
    founderQuoteAccent: "så vi byggede selv den QR-menu, vi ville have.",
    faqQ1: "Hvad er en QR-menu til restauranter?",
    faqA1: "En QR-menu til restauranter er den printbare QR-kode på bordet, som gæsten scanner med telefonens kamera for at åbne menukortet i browseren — uden app. Med IQ Rest indeholder QR-menuen bordbestillinger, reservationer 24/7 og AI-oversættelse til 35 sprog, alt opdateres fra mobilen.",
    faqQ2: "Hvad koster en QR-menu til restauranter?",
    faqA2: "6,90 €/måned, alt inkluderet. Ubegrænsede QR-koder til hvert bord, fuld editor, direkte bestillinger uden provision, AI-oversættelse til 35 sprog, reservationer og analytics. 14 dage gratis, intet kort.",
    finalCtaHeading: "QR-menu til restauranter.", finalCtaAccent: "Klar på 5 minutter.",
    finalCtaSub: "14 dage gratis. Intet kort. Over 500 restauranter bruger allerede QR-menu på IQ Rest.",
    metaTitle: "QR-menu til Restauranter — Klar på 5 Min | IQ Rest",
    metaDescription: "QR-menu til restauranter: QR-kode ved hvert bord, direkte bestillinger uden provision, AI-oversættelse til 35 sprog. Klar på 5 minutter, 14 dage gratis.",
    ogTitle: "QR-menu til Restauranter — Klar på 5 Minutter",
    ogDescription: "QR-menu med direkte bestillinger, 35 AI-sprog og reservationer. Klar på 5 minutter — 14 dage gratis.",
  },
  {
    code: "el", slug: "qr-menu-gia-estiatoria", ogLocale: "el_GR",
    headlinePrefix: "QR μενού για ", accentWord: "εστιατόρια", headlineSuffix: "",
    fullPhrase: "QR μενού για εστιατόρια",
    heroSub: "Πάνω από 500 εστιατόρια σε 30+ χώρες αντικαθιστούν το έντυπο μενού με QR μενού, πουλούν περισσότερο στους τουρίστες και μηδενίζουν τις προμήθειες delivery. Έτοιμο σε 5 λεπτά — 14 ημέρες δωρεάν.",
    founderQuoteStart: "Με τη γυναίκα μου ανοίξαμε καφέ και ψάχναμε για εβδομάδες ένα QR μενού για εστιατόρια με παραγγελίες στο τραπέζι και κρατήσεις χωρίς άσχημο σχεδιασμό —",
    founderQuoteAccent: "οπότε φτιάξαμε εμείς το QR μενού που θέλαμε.",
    faqQ1: "Τι είναι ένα QR μενού για εστιατόρια;",
    faqA1: "Ένα QR μενού για εστιατόρια είναι ο εκτυπώσιμος κωδικός QR στο τραπέζι που οι πελάτες σκανάρουν με την κάμερα του κινητού για να ανοίξουν τον κατάλογο στον περιηγητή — χωρίς εφαρμογή. Με την IQ Rest το QR μενού περιλαμβάνει παραγγελίες στο τραπέζι, κρατήσεις 24/7 και AI μετάφραση σε 35 γλώσσες, όλα ενημερώνονται από το κινητό.",
    faqQ2: "Πόσο κοστίζει ένα QR μενού για εστιατόρια;",
    faqA2: "6,90 €/μήνα, όλα μέσα. Απεριόριστοι κωδικοί QR σε κάθε τραπέζι, πλήρης editor, απευθείας παραγγελίες χωρίς προμήθεια, AI μετάφραση σε 35 γλώσσες, κρατήσεις και analytics. 14 ημέρες δωρεάν, χωρίς κάρτα.",
    finalCtaHeading: "QR μενού για εστιατόρια.", finalCtaAccent: "Έτοιμο σε 5 λεπτά.",
    finalCtaSub: "14 ημέρες δωρεάν. Χωρίς κάρτα. Πάνω από 500 εστιατόρια χρησιμοποιούν QR μενού στην IQ Rest.",
    metaTitle: "QR Μενού για Εστιατόρια — Έτοιμο σε 5 Λεπτά | IQ Rest",
    metaDescription: "QR μενού για εστιατόρια: κωδικός QR σε κάθε τραπέζι, απευθείας παραγγελίες χωρίς προμήθεια, AI μετάφραση σε 35 γλώσσες. Έτοιμο σε 5 λεπτά, 14 ημέρες δωρεάν.",
    ogTitle: "QR Μενού για Εστιατόρια — Έτοιμο σε 5 Λεπτά",
    ogDescription: "QR μενού με απευθείας παραγγελίες, 35 γλώσσες AI και κρατήσεις. Έτοιμο σε 5 λεπτά — 14 ημέρες δωρεάν.",
  },
  {
    code: "et", slug: "qr-menuu-restoranidele", ogLocale: "et_EE",
    headlinePrefix: "QR-menüü ", accentWord: "restoranidele", headlineSuffix: "",
    fullPhrase: "QR-menüü restoranidele",
    heroSub: "Üle 500 restorani 30+ riigis on asendanud paberi QR-menüüga, müüvad rohkem turistidele ja kaotanud tarnekomisjonid. Valmis 5 minutiga — 14 päeva tasuta.",
    founderQuoteStart: "Avasime abikaasaga kohviku ja otsisime nädalaid QR-menüüd restoranidele lauatellimuste ja broneeringutega ilma koleda kujunduseta —",
    founderQuoteAccent: "nii et tegime QR-menüü ise.",
    faqQ1: "Mis on QR-menüü restoranidele?",
    faqA1: "QR-menüü restoranidele on lauas olev trükitav QR-kood, mille külaline skannib telefoni kaameraga ja avab menüü brauseris — rakendus pole vajalik. IQ Restiga sisaldab QR-menüü lauatellimusi, broneeringuid 24/7 ja AI tõlget 35 keelde, kõik värskendatav telefonist.",
    faqQ2: "Kui palju maksab QR-menüü restoranidele?",
    faqA2: "6,90 €/kuus, kõik sees. Piiramatud QR-koodid igale lauale, täielik redaktor, otsetellimused ilma komisjonita, AI tõlge 35 keelde, broneeringud ja analüütika. 14 päeva tasuta, ilma kaardita.",
    finalCtaHeading: "QR-menüü restoranidele.", finalCtaAccent: "Valmis 5 minutiga.",
    finalCtaSub: "14 päeva tasuta. Ilma kaardita. Üle 500 restorani kasutab juba QR-menüüd IQ Restis.",
    metaTitle: "QR-menüü Restoranidele — Valmis 5 Min | IQ Rest",
    metaDescription: "QR-menüü restoranidele: QR-kood igal laual, otsetellimused ilma komisjonita, AI tõlge 35 keelde. Valmis 5 minutiga, 14 päeva tasuta.",
    ogTitle: "QR-menüü Restoranidele — Valmis 5 Minutiga",
    ogDescription: "QR-menüü otsetellimustega, 35 AI keelt ja broneeringud. Valmis 5 minutiga — 14 päeva tasuta.",
  },
  {
    code: "fa", slug: "menooye-qr-baraye-restoranha", ogLocale: "fa_IR",
    headlinePrefix: "منوی QR برای ", accentWord: "رستوران‌ها", headlineSuffix: "",
    fullPhrase: "منوی QR برای رستوران‌ها",
    heroSub: "بیش از 500 رستوران در 30+ کشور منوی کاغذی را با منوی QR جایگزین کرده‌اند، فروش بیشتری به گردشگران دارند و کارمزد تحویل را صفر کرده‌اند. در 5 دقیقه آماده — 14 روز رایگان.",
    founderQuoteStart: "من و همسرم یک کافه باز کردیم و هفته‌ها دنبال منوی QR برای رستوران‌ها با سفارش روی میز و رزرو بدون رابط زشت گشتیم —",
    founderQuoteAccent: "پس منوی QR را خودمان ساختیم.",
    faqQ1: "منوی QR برای رستوران‌ها چیست؟",
    faqA1: "منوی QR برای رستوران‌ها کد QR قابل چاپی است که روی میز قرار می‌گیرد و مشتری با دوربین گوشی آن را اسکن می‌کند تا منو در مرورگر باز شود — بدون نیاز به اپلیکیشن. با IQ Rest منوی QR شامل سفارش روی میز، رزرو 24/7 و ترجمه AI به 35 زبان است که همگی از موبایل به‌روز می‌شوند.",
    faqQ2: "هزینه منوی QR برای رستوران‌ها چقدر است؟",
    faqA2: "ماهی 6.90 یورو، همه چیز شامل. کد QR نامحدود برای هر میز، ویرایشگر کامل، سفارش مستقیم بدون کارمزد، ترجمه AI به 35 زبان، رزرو و تحلیل. 14 روز رایگان، بدون کارت.",
    finalCtaHeading: "منوی QR برای رستوران‌ها.", finalCtaAccent: "در 5 دقیقه آماده.",
    finalCtaSub: "14 روز رایگان. بدون کارت. بیش از 500 رستوران از منوی QR در IQ Rest استفاده می‌کنند.",
    metaTitle: "منوی QR برای رستوران‌ها — در 5 دقیقه | IQ Rest",
    metaDescription: "منوی QR برای رستوران‌ها: کد QR روی هر میز، سفارش مستقیم بدون کارمزد، ترجمه AI به 35 زبان. در 5 دقیقه آماده، 14 روز رایگان.",
    ogTitle: "منوی QR برای رستوران‌ها — در 5 دقیقه آماده",
    ogDescription: "منوی QR با سفارش مستقیم، 35 زبان AI و رزرو. در 5 دقیقه آماده — 14 روز رایگان.",
  },
  {
    code: "fi", slug: "qr-ruokalista-ravintoloille", ogLocale: "fi_FI",
    headlinePrefix: "QR-ruokalista ", accentWord: "ravintoloille", headlineSuffix: "",
    fullPhrase: "QR-ruokalista ravintoloille",
    heroSub: "Yli 500 ravintolaa 30+ maassa korvaa painetun ruokalistan QR-ruokalistalla, myy enemmän turisteille ja poistaa toimituspalkkiot. Valmis 5 minuutissa — 14 päivää ilmaiseksi.",
    founderQuoteStart: "Vaimoni kanssa avasimme kahvilan ja vietimme viikkoja etsien QR-ruokalistaa ravintoloille pöytätilauksilla ja varauksilla ilman rumaa käyttöliittymää —",
    founderQuoteAccent: "joten rakensimme haluamamme QR-ruokalistan itse.",
    faqQ1: "Mikä on QR-ruokalista ravintoloille?",
    faqA1: "QR-ruokalista ravintoloille on pöydässä oleva tulostettava QR-koodi, jonka asiakas skannaa puhelimen kameralla avatakseen ruokalistan selaimessa — ei sovellusta. IQ Restin QR-ruokalista sisältää pöytätilaukset, varaukset 24/7 ja AI-käännökset 35 kielelle, kaikki päivitettävissä puhelimesta.",
    faqQ2: "Kuinka paljon QR-ruokalista ravintoloille maksaa?",
    faqA2: "6,90 €/kk, kaikki sisältyy. Rajattomat QR-koodit jokaiseen pöytään, täysi editori, suorat tilaukset ilman provisiota, AI-käännökset 35 kielelle, varaukset ja analytiikka. 14 päivää ilmaiseksi, ei korttia.",
    finalCtaHeading: "QR-ruokalista ravintoloille.", finalCtaAccent: "Valmis 5 minuutissa.",
    finalCtaSub: "14 päivää ilmaiseksi. Ei korttia. Yli 500 ravintolaa käyttää jo QR-ruokalistaa IQ Restissä.",
    metaTitle: "QR-ruokalista Ravintoloille — Valmis 5 Min | IQ Rest",
    metaDescription: "QR-ruokalista ravintoloille: QR-koodi jokaiseen pöytään, suorat tilaukset ilman provisiota, AI-käännökset 35 kielelle. Valmis 5 minuutissa, 14 päivää ilmaiseksi.",
    ogTitle: "QR-ruokalista Ravintoloille — Valmis 5 Minuutissa",
    ogDescription: "QR-ruokalista suorilla tilauksilla, 35 AI-kielellä ja varauksilla. Valmis 5 minuutissa — 14 päivää ilmaiseksi.",
  },
  {
    code: "ga", slug: "biachlar-qr-do-bhialanna", ogLocale: "ga_IE",
    headlinePrefix: "Biachlár QR do ", accentWord: "bhialanna", headlineSuffix: "",
    fullPhrase: "Biachlár QR do bhialanna",
    heroSub: "Tá níos mó ná 500 bialann i 30+ tír ag malartú an bhiachláir phriontáilte le biachlár QR, ag díol níos mó le turasóirí agus ag baint coimisiún seachadta. Réidh i 5 nóiméad — 14 lá saor in aisce.",
    founderQuoteStart: "D'oscail mé féin agus mo bhean caife agus chaitheamar seachtainí ag cuardach biachlár QR do bhialanna le horduithe ag an mbord agus áirithintí gan comhéadan gránna —",
    founderQuoteAccent: "mar sin thógamar an biachlár QR a theastaigh uainn féin.",
    faqQ1: "Cad is biachlár QR do bhialanna ann?",
    faqA1: "Is é biachlár QR do bhialanna an cód QR inphriontáilte ag an mbord a scananálann an custaiméir lena cheamara fóin chun an biachlár a oscailt sa bhrabhsálaí — gan aip. Le IQ Rest cuimsíonn an biachlár QR orduithe boird, áirithintí 24/7 agus aistriúchán AI go 35 teanga, gach rud nuashonraithe ón bhfón.",
    faqQ2: "Cé mhéad a chosnaíonn biachlár QR do bhialanna?",
    faqA2: "€6.90 sa mhí, gach rud san áireamh. Cóid QR gan teorainn do gach bord, eagarthóir iomlán, orduithe díreach gan choimisiún, aistriúchán AI go 35 teanga, áirithintí agus anailísíocht. 14 lá saor in aisce, gan cárta.",
    finalCtaHeading: "Biachlár QR do bhialanna.", finalCtaAccent: "Réidh i 5 nóiméad.",
    finalCtaSub: "14 lá saor in aisce. Gan cárta. Tá níos mó ná 500 bialann ag baint úsáide as biachlár QR ar IQ Rest.",
    metaTitle: "Biachlár QR do Bhialanna — Réidh i 5 Nóim | IQ Rest",
    metaDescription: "Biachlár QR do bhialanna: cód QR ag gach bord, orduithe díreach gan choimisiún, aistriúchán AI go 35 teanga. Réidh i 5 nóiméad, 14 lá saor.",
    ogTitle: "Biachlár QR do Bhialanna — Réidh i 5 Nóiméad",
    ogDescription: "Biachlár QR le horduithe díreacha, 35 teanga AI agus áirithintí. Réidh i 5 nóiméad — 14 lá saor.",
  },
  {
    code: "hr", slug: "qr-jelovnik-za-restorane", ogLocale: "hr_HR",
    headlinePrefix: "QR jelovnik za ", accentWord: "restorane", headlineSuffix: "",
    fullPhrase: "QR jelovnik za restorane",
    heroSub: "Više od 500 restorana u 30+ zemalja zamjenjuje tiskani jelovnik QR jelovnikom, više prodaje turistima i ukida provizije dostave. Spreman za 5 minuta — 14 dana besplatno.",
    founderQuoteStart: "Sa ženom sam otvorio kafić i tjednima tražio QR jelovnik za restorane s narudžbama za stolom i rezervacijama bez ružnog sučelja —",
    founderQuoteAccent: "pa smo sami napravili QR jelovnik kakav smo željeli.",
    faqQ1: "Što je QR jelovnik za restorane?",
    faqA1: "QR jelovnik za restorane je printabilan QR kod na stolu koji gost skenira kamerom mobitela kako bi otvorio jelovnik u pregledniku — bez aplikacije. S IQ Rest QR jelovnik uključuje narudžbe za stolom, rezervacije 24/7 i AI prijevod na 35 jezika, sve ažurirano s mobitela.",
    faqQ2: "Koliko košta QR jelovnik za restorane?",
    faqA2: "6,90 €/mjesec, sve uključeno. Neograničeni QR kodovi za svaki stol, potpuni urednik, direktne narudžbe bez provizije, AI prijevod na 35 jezika, rezervacije i analitika. 14 dana besplatno, bez kartice.",
    finalCtaHeading: "QR jelovnik za restorane.", finalCtaAccent: "Spreman za 5 minuta.",
    finalCtaSub: "14 dana besplatno. Bez kartice. Više od 500 restorana koristi QR jelovnik na IQ Rest.",
    metaTitle: "QR Jelovnik za Restorane — Spreman za 5 Min | IQ Rest",
    metaDescription: "QR jelovnik za restorane: QR kod na svakom stolu, direktne narudžbe bez provizije, AI prijevod na 35 jezika. Spreman za 5 minuta, 14 dana besplatno.",
    ogTitle: "QR Jelovnik za Restorane — Spreman za 5 Minuta",
    ogDescription: "QR jelovnik s direktnim narudžbama, 35 AI jezika i rezervacijama. Spreman za 5 minuta — 14 dana besplatno.",
  },
  {
    code: "hu", slug: "qr-etlap-ettermeknek", ogLocale: "hu_HU",
    headlinePrefix: "QR étlap ", accentWord: "éttermeknek", headlineSuffix: "",
    fullPhrase: "QR étlap éttermeknek",
    heroSub: "Több mint 500 étterem 30+ országban cseréli a nyomtatott étlapot QR étlapra, többet ad el a turistáknak és nullára csökkenti a kiszállítási jutalékot. Kész 5 perc alatt — 14 nap ingyenes.",
    founderQuoteStart: "A feleségemmel kávézót nyitottunk és hetekig kerestünk QR étlapot éttermeknek asztali rendeléssel és foglalással, de a megoldások csúnyák voltak —",
    founderQuoteAccent: "így mi magunk építettük meg a QR étlapot, amit szerettünk volna.",
    faqQ1: "Mi az a QR étlap éttermeknek?",
    faqA1: "A QR étlap éttermeknek az asztalon lévő nyomtatható QR kód, amelyet a vendég a telefonja kamerájával beolvas, hogy megnyissa az étlapot a böngészőben — alkalmazás nélkül. Az IQ Rest QR étlap tartalmazza az asztali rendeléseket, 24/7 foglalásokat és AI fordítást 35 nyelvre, mindent telefonról frissíthet.",
    faqQ2: "Mennyibe kerül egy QR étlap éttermeknek?",
    faqA2: "Havi 6,90 €, minden benne. Korlátlan QR kódok minden asztalra, teljes szerkesztő, közvetlen rendelések jutalék nélkül, AI fordítás 35 nyelvre, foglalások és analitika. 14 nap ingyenes, kártya nélkül.",
    finalCtaHeading: "QR étlap éttermeknek.", finalCtaAccent: "Kész 5 perc alatt.",
    finalCtaSub: "14 nap ingyenes. Kártya nélkül. Több mint 500 étterem használja a QR étlapot az IQ Rest-en.",
    metaTitle: "QR Étlap Éttermeknek — Kész 5 Perc Alatt | IQ Rest",
    metaDescription: "QR étlap éttermeknek: QR kód minden asztalon, közvetlen rendelések jutalék nélkül, AI fordítás 35 nyelvre. Kész 5 perc alatt, 14 nap ingyenes.",
    ogTitle: "QR Étlap Éttermeknek — Kész 5 Perc Alatt",
    ogDescription: "QR étlap közvetlen rendelésekkel, 35 AI nyelvvel és foglalásokkal. Kész 5 perc alatt — 14 nap ingyenes.",
  },
  {
    code: "is", slug: "qr-matsedill-fyrir-veitingastadi", ogLocale: "is_IS",
    headlinePrefix: "QR matseðill fyrir ", accentWord: "veitingastaði", headlineSuffix: "",
    fullPhrase: "QR matseðill fyrir veitingastaði",
    heroSub: "Yfir 500 veitingastaðir í 30+ löndum skipta út prentuðum matseðli fyrir QR matseðil, selja meira til ferðamanna og fjarlægja afhendingargjöld. Tilbúinn á 5 mínútum — 14 dagar ókeypis.",
    founderQuoteStart: "Konan mín og ég opnuðum kaffihús og eyddum vikum í að leita að QR matseðli fyrir veitingastaði með borðpöntunum og bókunum án ljóts viðmóts —",
    founderQuoteAccent: "svo við smíðuðum sjálf QR matseðilinn sem við vildum.",
    faqQ1: "Hvað er QR matseðill fyrir veitingastaði?",
    faqA1: "QR matseðill fyrir veitingastaði er prentanlegur QR kóði á borðinu sem gestur skannar með myndavél símans til að opna matseðilinn í vafranum — ekkert app. Með IQ Rest inniheldur QR matseðillinn borðpantanir, bókanir 24/7 og AI þýðingu á 35 tungumál, allt uppfært úr símanum.",
    faqQ2: "Hvað kostar QR matseðill fyrir veitingastaði?",
    faqA2: "6,90 €/mánuði, allt innifalið. Ótakmarkaðir QR kóðar á hvert borð, fullkomin ritstýring, beinar pantanir án umboðslauna, AI þýðing á 35 tungumál, bókanir og greiningar. 14 dagar ókeypis, ekkert kort.",
    finalCtaHeading: "QR matseðill fyrir veitingastaði.", finalCtaAccent: "Tilbúinn á 5 mínútum.",
    finalCtaSub: "14 dagar ókeypis. Ekkert kort. Yfir 500 veitingastaðir nota QR matseðil á IQ Rest.",
    metaTitle: "QR Matseðill fyrir Veitingastaði — 5 Mín | IQ Rest",
    metaDescription: "QR matseðill fyrir veitingastaði: QR kóði á hverju borði, beinar pantanir án umboðslauna, AI þýðing á 35 tungumál. Tilbúinn á 5 mínútum, 14 dagar ókeypis.",
    ogTitle: "QR Matseðill fyrir Veitingastaði — 5 Mínútur",
    ogDescription: "QR matseðill með beinum pöntunum, 35 AI tungumálum og bókunum. Tilbúinn á 5 mínútum — 14 dagar ókeypis.",
  },
  {
    code: "lt", slug: "qr-meniu-restoranams", ogLocale: "lt_LT",
    headlinePrefix: "QR meniu ", accentWord: "restoranams", headlineSuffix: "",
    fullPhrase: "QR meniu restoranams",
    heroSub: "Daugiau nei 500 restoranų 30+ šalių keičia spausdintą meniu QR meniu, daugiau parduoda turistams ir naikina pristatymo komisinius. Paruošta per 5 minutes — 14 dienų nemokamai.",
    founderQuoteStart: "Su žmona atidarėme kavinę ir savaites ieškojome QR meniu restoranams su užsakymais prie staliuko ir rezervacijomis be bjauraus dizaino —",
    founderQuoteAccent: "todėl QR meniu pasidarėme patys.",
    faqQ1: "Kas yra QR meniu restoranams?",
    faqA1: "QR meniu restoranams yra spausdinamas QR kodas ant stalo, kurį svečias nuskaito telefono kamera ir atveria meniu naršyklėje — be programėlės. Su IQ Rest QR meniu apima užsakymus prie staliuko, rezervacijas 24/7 ir AI vertimą į 35 kalbas, viskas atnaujinama iš telefono.",
    faqQ2: "Kiek kainuoja QR meniu restoranams?",
    faqA2: "6,90 €/mėn, viskas įskaičiuota. Neriboti QR kodai kiekvienam stalui, visas redaktorius, tiesioginiai užsakymai be komisinių, AI vertimas į 35 kalbas, rezervacijos ir analitika. 14 dienų nemokamai, be kortelės.",
    finalCtaHeading: "QR meniu restoranams.", finalCtaAccent: "Paruošta per 5 minutes.",
    finalCtaSub: "14 dienų nemokamai. Be kortelės. Daugiau nei 500 restoranų naudoja QR meniu IQ Rest.",
    metaTitle: "QR Meniu Restoranams — Per 5 Min | IQ Rest",
    metaDescription: "QR meniu restoranams: QR kodas ant kiekvieno stalo, tiesioginiai užsakymai be komisinių, AI vertimas į 35 kalbas. Paruošta per 5 minutes, 14 dienų nemokamai.",
    ogTitle: "QR Meniu Restoranams — Paruošta per 5 Minutes",
    ogDescription: "QR meniu su tiesioginiais užsakymais, 35 AI kalbomis ir rezervacijomis. Paruošta per 5 minutes — 14 dienų nemokamai.",
  },
  {
    code: "lv", slug: "qr-edienkarte-restoraniem", ogLocale: "lv_LV",
    headlinePrefix: "QR ēdienkarte ", accentWord: "restorāniem", headlineSuffix: "",
    fullPhrase: "QR ēdienkarte restorāniem",
    heroSub: "Vairāk nekā 500 restorānu 30+ valstīs nomaina drukāto ēdienkarti ar QR ēdienkarti, vairāk pārdod tūristiem un atceļ piegādes komisijas. Gatava 5 minūtēs — 14 dienas bez maksas.",
    founderQuoteStart: "Mēs ar sievu atvērām kafejnīcu un nedēļām meklējām QR ēdienkarti restorāniem ar pasūtījumiem pie galda un rezervācijām bez neglīta dizaina —",
    founderQuoteAccent: "tāpēc paši uztaisījām QR ēdienkarti, kādu gribējām.",
    faqQ1: "Kas ir QR ēdienkarte restorāniem?",
    faqA1: "QR ēdienkarte restorāniem ir uz galda izdrukājams QR kods, ko viesis noskannē ar telefona kameru, lai atvērtu ēdienkarti pārlūkprogrammā — bez lietotnes. Ar IQ Rest QR ēdienkarte ietver pasūtījumus pie galda, rezervācijas 24/7 un AI tulkojumu 35 valodās, viss atjaunināms no telefona.",
    faqQ2: "Cik maksā QR ēdienkarte restorāniem?",
    faqA2: "6,90 €/mēnesī, viss iekļauts. Neierobežoti QR kodi katram galdam, pilns redaktors, tieši pasūtījumi bez komisijas, AI tulkojums 35 valodās, rezervācijas un analītika. 14 dienas bez maksas, bez kartes.",
    finalCtaHeading: "QR ēdienkarte restorāniem.", finalCtaAccent: "Gatava 5 minūtēs.",
    finalCtaSub: "14 dienas bez maksas. Bez kartes. Vairāk nekā 500 restorānu izmanto QR ēdienkarti uz IQ Rest.",
    metaTitle: "QR Ēdienkarte Restorāniem — 5 Min | IQ Rest",
    metaDescription: "QR ēdienkarte restorāniem: QR kods uz katra galda, tieši pasūtījumi bez komisijas, AI tulkojums 35 valodās. Gatava 5 minūtēs, 14 dienas bez maksas.",
    ogTitle: "QR Ēdienkarte Restorāniem — Gatava 5 Minūtēs",
    ogDescription: "QR ēdienkarte ar tiešiem pasūtījumiem, 35 AI valodām un rezervācijām. Gatava 5 minūtēs — 14 dienas bez maksas.",
  },
  {
    code: "no", slug: "qr-meny-for-restauranter", ogLocale: "nb_NO",
    headlinePrefix: "QR-meny for ", accentWord: "restauranter", headlineSuffix: "",
    fullPhrase: "QR-meny for restauranter",
    heroSub: "Over 500 restauranter i 30+ land erstatter den trykte menyen med en QR-meny, selger mer til turister og fjerner leveringsprovisjoner. Klar på 5 minutter — 14 dager gratis.",
    founderQuoteStart: "Min kone og jeg åpnet en kafé og brukte uker på å lete etter en QR-meny for restauranter med bordbestilling og reservasjoner uten stygt grensesnitt —",
    founderQuoteAccent: "så vi bygde QR-menyen vi selv ville ha.",
    faqQ1: "Hva er en QR-meny for restauranter?",
    faqA1: "En QR-meny for restauranter er den printbare QR-koden på bordet som gjester skanner med telefonkameraet for å åpne menyen i nettleseren — ingen app. Med IQ Rest inkluderer QR-menyen bordbestillinger, reservasjoner 24/7 og AI-oversettelse til 35 språk, alt oppdatert fra mobilen.",
    faqQ2: "Hva koster en QR-meny for restauranter?",
    faqA2: "6,90 €/måned, alt inkludert. Ubegrensede QR-koder for hvert bord, full editor, direkte bestillinger uten provisjon, AI-oversettelse til 35 språk, reservasjoner og analytics. 14 dager gratis, uten kort.",
    finalCtaHeading: "QR-meny for restauranter.", finalCtaAccent: "Klar på 5 minutter.",
    finalCtaSub: "14 dager gratis. Uten kort. Over 500 restauranter bruker allerede QR-meny på IQ Rest.",
    metaTitle: "QR-meny for Restauranter — Klar på 5 Min | IQ Rest",
    metaDescription: "QR-meny for restauranter: QR-kode ved hvert bord, direkte bestillinger uten provisjon, AI-oversettelse til 35 språk. Klar på 5 minutter, 14 dager gratis.",
    ogTitle: "QR-meny for Restauranter — Klar på 5 Minutter",
    ogDescription: "QR-meny med direkte bestillinger, 35 AI-språk og reservasjoner. Klar på 5 minutter — 14 dager gratis.",
  },
  {
    code: "ro", slug: "meniu-qr-pentru-restaurante", ogLocale: "ro_RO",
    headlinePrefix: "Meniu QR pentru ", accentWord: "restaurante", headlineSuffix: "",
    fullPhrase: "Meniu QR pentru restaurante",
    heroSub: "Peste 500 de restaurante din 30+ țări înlocuiesc meniul tipărit cu un meniu QR, vând mai mult turiștilor și elimină comisioanele de livrare. Gata în 5 minute — 14 zile gratis.",
    founderQuoteStart: "Eu și soția am deschis o cafenea și am căutat săptămâni un meniu QR pentru restaurante cu comenzi la masă și rezervări fără interfață urâtă —",
    founderQuoteAccent: "așa că am construit meniul QR pe care îl voiam.",
    faqQ1: "Ce este un meniu QR pentru restaurante?",
    faqA1: "Un meniu QR pentru restaurante este codul QR imprimabil pe masă pe care clienții îl scanează cu camera telefonului pentru a deschide meniul în browser — fără aplicație. Cu IQ Rest meniul QR include comenzi la masă, rezervări 24/7 și traducere AI în 35 de limbi, totul actualizat de pe telefon.",
    faqQ2: "Cât costă un meniu QR pentru restaurante?",
    faqA2: "6,90 €/lună, totul inclus. Coduri QR nelimitate pe fiecare masă, editor complet, comenzi directe fără comision, traducere AI în 35 de limbi, rezervări și analitică. 14 zile gratis, fără card.",
    finalCtaHeading: "Meniu QR pentru restaurante.", finalCtaAccent: "Gata în 5 minute.",
    finalCtaSub: "14 zile gratis. Fără card. Peste 500 de restaurante folosesc meniul QR pe IQ Rest.",
    metaTitle: "Meniu QR pentru Restaurante — Gata în 5 Min | IQ Rest",
    metaDescription: "Meniu QR pentru restaurante: cod QR pe fiecare masă, comenzi directe fără comision, traducere AI în 35 de limbi. Gata în 5 minute, 14 zile gratis.",
    ogTitle: "Meniu QR pentru Restaurante — Gata în 5 Minute",
    ogDescription: "Meniu QR cu comenzi directe, 35 de limbi AI și rezervări. Gata în 5 minute — 14 zile gratis.",
  },
  {
    code: "sk", slug: "qr-menu-pre-restauracie", ogLocale: "sk_SK",
    headlinePrefix: "QR menu pre ", accentWord: "reštaurácie", headlineSuffix: "",
    fullPhrase: "QR menu pre reštaurácie",
    heroSub: "Viac ako 500 reštaurácií v 30+ krajinách nahrádza tlačené menu QR menu, predáva viac turistom a ruší provízie za rozvoz. Hotovo za 5 minút — 14 dní zadarmo.",
    founderQuoteStart: "S manželkou sme otvorili kaviareň a týždne sme hľadali QR menu pre reštaurácie s objednávkami pri stole a rezerváciami bez škaredého rozhrania —",
    founderQuoteAccent: "tak sme si QR menu vyrobili sami.",
    faqQ1: "Čo je QR menu pre reštaurácie?",
    faqA1: "QR menu pre reštaurácie je tlačiteľný QR kód pri stole, ktorý hosť naskenuje kamerou telefónu a otvorí jedálny lístok v prehliadači — bez aplikácie. S IQ Rest QR menu obsahuje objednávky pri stole, rezervácie 24/7 a AI preklad do 35 jazykov, všetko aktualizované z mobilu.",
    faqQ2: "Koľko stojí QR menu pre reštaurácie?",
    faqA2: "6,90 €/mesiac, všetko v cene. Neobmedzené QR kódy pre každý stôl, kompletný editor, priame objednávky bez provízie, AI preklad do 35 jazykov, rezervácie a analytika. 14 dní zadarmo, bez karty.",
    finalCtaHeading: "QR menu pre reštaurácie.", finalCtaAccent: "Hotovo za 5 minút.",
    finalCtaSub: "14 dní zadarmo. Bez karty. Viac ako 500 reštaurácií používa QR menu na IQ Rest.",
    metaTitle: "QR Menu pre Reštaurácie — Hotovo za 5 Min | IQ Rest",
    metaDescription: "QR menu pre reštaurácie: QR kód pri každom stole, priame objednávky bez provízie, AI preklad do 35 jazykov. Hotovo za 5 minút, 14 dní zadarmo.",
    ogTitle: "QR Menu pre Reštaurácie — Hotovo za 5 Minút",
    ogDescription: "QR menu s priamymi objednávkami, 35 AI jazykmi a rezerváciami. Hotovo za 5 minút — 14 dní zadarmo.",
  },
  {
    code: "sl", slug: "qr-jedilnik-za-restavracije", ogLocale: "sl_SI",
    headlinePrefix: "QR jedilnik za ", accentWord: "restavracije", headlineSuffix: "",
    fullPhrase: "QR jedilnik za restavracije",
    heroSub: "Več kot 500 restavracij v 30+ državah nadomešča tiskan jedilnik z QR jedilnikom, več prodaja turistom in odpravlja provizije za dostavo. Pripravljen v 5 minutah — 14 dni brezplačno.",
    founderQuoteStart: "Z ženo sva odprla kavarno in tedne iskala QR jedilnik za restavracije z naročili za mizo in rezervacijami brez grdega vmesnika —",
    founderQuoteAccent: "zato sva QR jedilnik naredila sama.",
    faqQ1: "Kaj je QR jedilnik za restavracije?",
    faqA1: "QR jedilnik za restavracije je natisljiva QR koda na mizi, ki jo gost skenira s kamero telefona, da odpre jedilnik v brskalniku — brez aplikacije. Z IQ Rest QR jedilnik vključuje naročila za mizo, rezervacije 24/7 in AI prevod v 35 jezikov, vse posodobljeno iz telefona.",
    faqQ2: "Koliko stane QR jedilnik za restavracije?",
    faqA2: "6,90 €/mesec, vse vključeno. Neomejene QR kode za vsako mizo, popoln urejevalnik, neposredna naročila brez provizije, AI prevod v 35 jezikov, rezervacije in analitika. 14 dni brezplačno, brez kartice.",
    finalCtaHeading: "QR jedilnik za restavracije.", finalCtaAccent: "Pripravljen v 5 minutah.",
    finalCtaSub: "14 dni brezplačno. Brez kartice. Več kot 500 restavracij uporablja QR jedilnik na IQ Rest.",
    metaTitle: "QR Jedilnik za Restavracije — 5 Min | IQ Rest",
    metaDescription: "QR jedilnik za restavracije: QR koda na vsaki mizi, neposredna naročila brez provizije, AI prevod v 35 jezikov. Pripravljen v 5 minutah, 14 dni brezplačno.",
    ogTitle: "QR Jedilnik za Restavracije — Pripravljen v 5 Minutah",
    ogDescription: "QR jedilnik z neposrednimi naročili, 35 AI jeziki in rezervacijami. Pripravljen v 5 minutah — 14 dni brezplačno.",
  },
  {
    code: "sr", slug: "qr-meni-za-restorane", ogLocale: "sr_RS",
    headlinePrefix: "QR meni za ", accentWord: "restorane", headlineSuffix: "",
    fullPhrase: "QR meni za restorane",
    heroSub: "Više od 500 restorana u 30+ zemalja zamenjuje štampani meni QR menijem, više prodaje turistima i ukida provizije dostave. Spreman za 5 minuta — 14 dana besplatno.",
    founderQuoteStart: "Sa ženom sam otvorio kafić i nedeljama tražio QR meni za restorane sa porudžbinama za stolom i rezervacijama bez ružnog dizajna —",
    founderQuoteAccent: "pa smo QR meni napravili sami.",
    faqQ1: "Šta je QR meni za restorane?",
    faqA1: "QR meni za restorane je štampani QR kod na stolu koji gost skenira kamerom telefona da otvori meni u pregledaču — bez aplikacije. Sa IQ Rest QR meni uključuje porudžbine za stolom, rezervacije 24/7 i AI prevod na 35 jezika, sve ažurirano sa telefona.",
    faqQ2: "Koliko košta QR meni za restorane?",
    faqA2: "6,90 €/mesec, sve uključeno. Neograničeni QR kodovi za svaki sto, kompletan editor, direktne porudžbine bez provizije, AI prevod na 35 jezika, rezervacije i analitika. 14 dana besplatno, bez kartice.",
    finalCtaHeading: "QR meni za restorane.", finalCtaAccent: "Spreman za 5 minuta.",
    finalCtaSub: "14 dana besplatno. Bez kartice. Više od 500 restorana koristi QR meni na IQ Rest.",
    metaTitle: "QR Meni za Restorane — Spreman za 5 Min | IQ Rest",
    metaDescription: "QR meni za restorane: QR kod na svakom stolu, direktne porudžbine bez provizije, AI prevod na 35 jezika. Spreman za 5 minuta, 14 dana besplatno.",
    ogTitle: "QR Meni za Restorane — Spreman za 5 Minuta",
    ogDescription: "QR meni sa direktnim porudžbinama, 35 AI jezika i rezervacijama. Spreman za 5 minuta — 14 dana besplatno.",
  },
  {
    code: "sv", slug: "qr-meny-for-restauranger", ogLocale: "sv_SE",
    headlinePrefix: "QR-meny för ", accentWord: "restauranger", headlineSuffix: "",
    fullPhrase: "QR-meny för restauranger",
    heroSub: "Över 500 restauranger i 30+ länder ersätter den tryckta menyn med en QR-meny, säljer mer till turister och tar bort leveransprovisioner. Klar på 5 minuter — 14 dagar gratis.",
    founderQuoteStart: "Min fru och jag öppnade ett café och letade i veckor efter en QR-meny för restauranger med bordsbeställning och bokningar utan fult gränssnitt —",
    founderQuoteAccent: "så vi byggde QR-menyn vi själva ville ha.",
    faqQ1: "Vad är en QR-meny för restauranger?",
    faqA1: "En QR-meny för restauranger är den utskrivbara QR-koden på bordet som gäster skannar med telefonkameran för att öppna menyn i webbläsaren — ingen app. Med IQ Rest inkluderar QR-menyn bordsbeställningar, bokningar 24/7 och AI-översättning till 35 språk, allt uppdateras från mobilen.",
    faqQ2: "Vad kostar en QR-meny för restauranger?",
    faqA2: "6,90 €/månad, allt inkluderat. Obegränsade QR-koder för varje bord, full editor, direkta beställningar utan provision, AI-översättning till 35 språk, bokningar och analytics. 14 dagar gratis, inget kort.",
    finalCtaHeading: "QR-meny för restauranger.", finalCtaAccent: "Klar på 5 minuter.",
    finalCtaSub: "14 dagar gratis. Inget kort. Över 500 restauranger använder QR-meny på IQ Rest.",
    metaTitle: "QR-meny för Restauranger — Klar på 5 Min | IQ Rest",
    metaDescription: "QR-meny för restauranger: QR-kod vid varje bord, direkta beställningar utan provision, AI-översättning till 35 språk. Klar på 5 minuter, 14 dagar gratis.",
    ogTitle: "QR-meny för Restauranger — Klar på 5 Minuter",
    ogDescription: "QR-meny med direkta beställningar, 35 AI-språk och bokningar. Klar på 5 minuter — 14 dagar gratis.",
  },
];

function textsTs(s: LocaleSpec): string {
  return `import type { LandingTexts } from "@/app/_landing/types";
import { TEXTS as DEFAULT } from "../../texts";

// PPC variant of /${s.code}, tuned for the BROAD-MATCH keyword "qr menu
// for restaurants". Inherits content from the indexed /${s.code} page and only
// overrides what should differ for the Google Ads landing: meta
// (canonical + og), microcopy with entry price, and hero/founder/faq/
// finalCta copy that hammers the exact phrase for ad relevance scoring.
export const TEXTS: LandingTexts = {
  ...DEFAULT,

  microcopy: DEFAULT.microcopy,

  hero: {
    ...DEFAULT.hero,
    headline: ${JSON.stringify(s.fullPhrase)},
    sub: ${JSON.stringify(s.heroSub)},
    dynamicHeadlines: [],
    headlinePrefix: ${JSON.stringify(s.headlinePrefix)},
    accentWord: ${JSON.stringify(s.accentWord)},
    accentWordRotation: DEFAULT.hero.accentWordRotation ?? [],
    headlineSuffix: ${JSON.stringify(s.headlineSuffix)},
  },

  founder: {
    ...DEFAULT.founder,
    quoteStart: ${JSON.stringify(s.founderQuoteStart)},
    quoteAccent: ${JSON.stringify(s.founderQuoteAccent)},
  },

  footer: {
    ...DEFAULT.footer,
    featureLinks: [],
    navLinks: [],
  },

  faq: {
    ...DEFAULT.faq,
    items: [
      {
        q: ${JSON.stringify(s.faqQ1)},
        a: ${JSON.stringify(s.faqA1)},
      },
      {
        q: ${JSON.stringify(s.faqQ2)},
        a: ${JSON.stringify(s.faqA2)},
      },
      ...DEFAULT.faq.items,
    ],
  },

  finalCta: {
    ...DEFAULT.finalCta,
    heading: ${JSON.stringify(s.finalCtaHeading)},
    headingAccent: ${JSON.stringify(s.finalCtaAccent)},
    sub: ${JSON.stringify(s.finalCtaSub)},
  },

  meta: {
    title: ${JSON.stringify(s.metaTitle)},
    description: ${JSON.stringify(s.metaDescription)},
    canonical: ${JSON.stringify(`https://iq-rest.com/${s.code}/lp/${s.slug}`)},
    ogLocale: ${JSON.stringify(s.ogLocale)},
    ogTitle: ${JSON.stringify(s.ogTitle)},
    ogDescription: ${JSON.stringify(s.ogDescription)},
  },
};
`;
}

function pageTsx(s: LocaleSpec): string {
  return `import type { Metadata } from "next";
import { LandingPageBody } from "@/app/_landing/components/landing-page-body";
import { TEXTS } from "./texts";
import { JSON_LD_HTML } from "./jsonld";

const LOCALE = "${s.code}";

export const metadata: Metadata = {
  metadataBase: new URL("https://iq-rest.com"),
  title: TEXTS.meta.title,
  description: TEXTS.meta.description,
  alternates: { canonical: TEXTS.meta.canonical },
  robots: { index: false, follow: false },
  openGraph: {
    title: TEXTS.meta.ogTitle,
    description: TEXTS.meta.ogDescription,
    url: TEXTS.meta.canonical,
    siteName: "IQ Rest",
    locale: TEXTS.meta.ogLocale,
    type: "website",
    images: [{ url: "/og-image.png", width: 1200, height: 630, alt: "IQ Rest — QR Menu for Restaurants" }],
  },
  twitter: {
    card: "summary_large_image",
    title: TEXTS.meta.ogTitle,
    description: TEXTS.meta.ogDescription,
    images: ["/og-image.png"],
  },
};

export default function Page() {
  return <LandingPageBody locale={LOCALE} texts={TEXTS} jsonLdHtml={JSON_LD_HTML} />;
}
`;
}

function jsonldTs(s: LocaleSpec): string {
  return `import { TEXTS } from "./texts";

const data = {
  "@context": "https://schema.org",
  "@graph": [
    {
      "@type": "SoftwareApplication",
      name: \`IQ Rest — ${s.fullPhrase}\`,
      applicationCategory: "BusinessApplication",
      operatingSystem: "Web",
      description: TEXTS.meta.description,
      inLanguage: "${s.code}",
      offers: { "@type": "Offer", price: "6.90", priceCurrency: "EUR" },
    },
    {
      "@type": "FAQPage",
      mainEntity: TEXTS.faq.items.map((it) => ({
        "@type": "Question",
        name: it.q,
        acceptedAnswer: { "@type": "Answer", text: it.a },
      })),
    },
  ],
};

export const JSON_LD_HTML = JSON.stringify(data).replace(/</g, "\\\\u003c");
`;
}

function main() {
  const root = path.join(process.cwd(), "app");
  let created = 0;
  for (const s of SPECS) {
    const dir = path.join(root, s.code, "lp", s.slug);
    if (existsSync(dir)) {
      console.log(`skip (exists): ${dir}`);
      continue;
    }
    mkdirSync(dir, { recursive: true });
    writeFileSync(path.join(dir, "texts.ts"), textsTs(s));
    writeFileSync(path.join(dir, "page.tsx"), pageTsx(s));
    writeFileSync(path.join(dir, "jsonld.ts"), jsonldTs(s));
    created++;
    console.log(`+ ${s.code}/lp/${s.slug}`);
  }
  console.log(`\nDone. Created ${created} LPs.`);
}

main();
