/**
 * Rebuild the `dashboard` namespace in messages/en.json with the new content
 * referenced by the _v2 dashboard code. Legacy `dashboard.*` keys are
 * discarded — they were for the old (pre-rewrite) dashboard and are no longer
 * referenced.
 *
 * Other top-level namespaces in en.json (header, home, faq, sublandings, etc)
 * are left untouched.
 *
 * Usage:
 *   npx tsx scripts/rebuild-dashboard-namespace.ts
 */

import * as fs from "fs";
import * as path from "path";

const EN_PATH = path.join(process.cwd(), "messages/en.json");

const dashboard = {
  nav: {
    menu: "Menu",
    reservations: "Bookings",
    orders: "Orders",
    kitchen: "Kitchen",
    analytics: "Analytics",
    settings: "Settings",
    untitledRestaurant: "Untitled restaurant",
  },
  common: {
    save: "Save",
    saving: "Saving...",
    cancel: "Cancel",
    delete: "Delete",
    deleting: "Deleting...",
    close: "Close",
    confirm: "Confirm",
    back: "Back",
    edit: "Edit",
    add: "Add",
    ok: "OK",
    yes: "Yes",
    no: "No",
    loading: "Loading…",
    untitled: "Untitled",
    noName: "No name",
    moveUp: "Move up",
    moveDown: "Move down",
    translate: "Translate",
    translating: "Translating...",
    translateWithAi: "Translate with AI",
    translateAll: "Translate all",
    replace: "Replace",
    copy: "Copy",
    copied: "Copied",
    download: "Download",
    open: "Open",
    openMenu: "Open menu",
    downloadQr: "Download QR",
    menuLink: "Menu link",
    tableLink: "Table link",
    selected: "selected",
    qrCode: "QR code",
    noResults: "No results",
    willUse: "Will use",
  },
  subscriptionChip: {
    plan: "Plan",
    free: "Free",
    trialDays: "Trial · {days}d",
    trialExpired: "Trial expired",
  },
  preview: {
    preview: "Preview",
    share: "Share",
    shareTitle: "Share {name}",
    shareYourMenu: "your menu",
    tip: "Print and place on tables, or share online.",
    tableTip: "Print and place on this table. Scanning opens the menu with this table preselected.",
  },
  ai: {
    translateReplaceTitle: "Replace existing translation?",
    translateReplaceMessage: "This will overwrite what you've already typed in this field.",
    generate: "Generate",
    generating: "Generating...",
    tryAgain: "Try again",
    useThisPhoto: "Use this photo",
    describe: "Describe",
    describeTip: "Describe what you want, then tap Generate.",
    promptTip: "Tip: mention angle, lighting, or background.",
    noImage: "No image returned.",
    errorGenerate: "Couldn't generate. Try again.",
    promptPlaceholder: "e.g. Margherita pizza on a wooden board, top-down view",
  },
  photo: {
    label: "Photo",
    addPhoto: "Add photo",
    removePhoto: "Remove photo",
  },
  menu: {
    title: "Menu",
    subtitle: "Manage your categories and dishes.",
    expand: "Expand",
    collapse: "Collapse",
    noCategories: "No categories yet",
    noCategoriesSub: "Add your first category to start building the menu.",
    addCategory: "Add category",
    addDish: "Add dish",
    noDishes: "No dishes yet.",
    expandCategory: "Expand category",
    collapseCategory: "Collapse category",
    moveCategoryUp: "Move category up",
    moveCategoryDown: "Move category down",
    editCategory: "Edit category",
    editDish: "Edit dish",
    hideDish: "Hide dish",
    showDish: "Show dish",
  },
  categoryForm: {
    newTitle: "New category",
    breadcrumb: "Menu",
    nameLabel: "Name",
    namePlaceholder: "e.g. Antipasti",
    deleteButton: "Delete category",
    deleteTitle: "Delete category?",
    deleteMessage: "This will also delete all dishes inside it. This cannot be undone.",
    nameRequiredTitle: "Name is required",
    nameRequiredMessage: "Enter a category name in the default language before saving.",
  },
  dishForm: {
    newTitle: "New dish",
    breadcrumb: "Menu",
    nameLabel: "Name",
    namePlaceholder: "e.g. Spaghetti carbonara",
    descLabel: "Description",
    descPlaceholder: "Short description for guests...",
    priceLabel: "Price",
    pricePlaceholder: "12.50",
    allergensLabel: "Allergens",
    allergensTip: "Tap to toggle.",
    optionsLabel: "Options",
    optionsTip: "Variants like sizes, extras, or add-ons.",
    addOption: "Add option",
    visibleLabel: "Visible to guests",
    visibleTip: "Hidden dishes don't appear in the menu.",
    deleteButton: "Delete dish",
    deleteTitle: "Delete dish?",
    deleteMessage: "This dish will be removed from the menu.",
    aiTitle: "Generate dish photo",
    nameRequiredTitle: "Name is required",
    nameRequiredMessage: "Enter a dish name in the default language before saving.",
    priceRequiredTitle: "Price is required",
    priceRequiredMessage: "Enter a valid price (e.g. 12.50) before saving.",
    missingTitle: "Missing fields",
    missingMessage: "Enter a name and a valid price before saving.",
  },
  optionForm: {
    newTitle: "New option",
    untitledOption: "Untitled option",
    breadcrumb: "Menu",
    nameLabel: "Name",
    namePlaceholder: "e.g. Size, Toppings, Crust",
    multiLabel: "Allow multiple choices",
    multiTip: "Off — guest picks one. On — guest picks any number.",
    requiredLabel: "Required",
    requiredTip: "Guest can't add to cart without choosing.",
    variantsLabel: "Variants",
    variantsTip: "Each variant has a name and an optional price modifier.",
    addVariant: "Add variant",
    removeVariant: "Remove variant",
    variantNamePlaceholder: "Variant name",
    priceModifier: "Price modifier",
    deleteButton: "Delete option",
    deleteTitle: "Delete option?",
    deleteMessage: "This option will be removed from the dish.",
    missingTitle: "Missing fields",
    missingMessage: "Enter an option name and at least one variant before saving.",
    nameRequiredTitle: "Name is required",
    nameRequiredMessage: "Enter an option name in the default language before saving.",
    variantRequiredTitle: "Variant required",
    variantRequiredMessage: "Add at least one variant with a name in the default language before saving.",
    typeMulti: "Multiple choice",
    typeSingle: "Single choice",
    required: "Required",
    optional: "Optional",
    variantOne: "variant",
    variantOther: "variants",
  },
  allergens: {
    gluten: "Gluten",
    lactose: "Lactose",
    eggs: "Eggs",
    nuts: "Tree nuts",
    peanuts: "Peanuts",
    fish: "Fish",
    shellfish: "Shellfish",
    soy: "Soy",
    sesame: "Sesame",
    celery: "Celery",
    mustard: "Mustard",
    sulfites: "Sulfites",
    lupin: "Lupin",
    molluscs: "Molluscs",
  },
  orders: {
    title: "Orders",
    subtitleOne: "You have {count} active order.",
    subtitleOther: "You have {count} active orders.",
    noActive: "No active orders",
    noActiveSub: "Tap a free table on the map to start an order, or wait for guests to place one via the QR menu.",
    tapTable: "Tap a table on the map to see or start an order.",
    tableLabel: "Table {number}",
    noActiveShort: "No active orders",
    activeOrderOne: "{count} active order",
    activeOrderOther: "{count} active orders",
    startOrder: "Start order",
    newOrder: "New order",
    allReady: "All ready",
    cooking: "Cooking",
    itemOne: "{count} item",
    itemOther: "{count} items",
    completeOrder: "Complete order",
    deleteOrderTitle: "Delete order?",
    deleteOrderMessage: "This will permanently remove the order and all its items. This action cannot be undone.",
    ordersBreadcrumb: "Orders",
    startedAt: "Started at {time} · {minutes} min ago",
    noItems: "No items yet.",
    addItem: "Add item",
    total: "Total",
    allServed: "All items served. Ready to complete.",
    deleteOrder: "Delete order",
    tapToChangeStatus: "Tap to change status",
    removeItem: "Remove item",
    addItemBreadcrumb: "Add item",
    noDishesInCategory: "No dishes in this category.",
    continue: "Continue",
    addPrice: "Add · {price}",
    addExtras: "Add extras",
    multiPickHint: "Pick one or more, then Continue.",
    decrease: "Decrease",
    increase: "Increase",
    perEach: "+{amount} each",
    notesLabel: "Notes",
    notesPlaceholder: "e.g. no onions, well done",
    statusPending: "Pending",
    statusCooking: "Cooking",
    statusReady: "Ready",
    statusServed: "Served",
    kitchenClear: "Kitchen is clear",
    kitchenClearSub: "Items will appear here as guests place orders.",
    elapsed: "{time} · {minutes} min",
  },
  reservations: {
    title: "Bookings",
    subtitleOne: "You have {count} upcoming booking.",
    subtitleOther: "You have {count} upcoming bookings.",
    noBookings: "No bookings yet",
    noBookingsSub: "Once guests book a table, you'll see them here.",
    today: "Today",
    noToday: "No bookings for today.",
    bookingOne: "{count} booking",
    bookingOther: "{count} bookings",
    guestOne: "{count} guest",
    guestOther: "{count} guests",
    tableLabel: "Table {number}",
    notAssigned: "Not assigned",
    reject: "Reject",
    confirm: "Confirm",
    statusPending: "Pending",
    statusConfirmed: "Confirmed",
    statusCancelled: "Cancelled",
    statusCompleted: "Completed",
    statusNoShow: "No-show",
  },
  tables: {
    table: "Table",
    settingsBreadcrumb: "Settings",
    title: "Tables",
    showQr: "Show QR code",
    deleteTable: "Delete table",
    tapTable: "Tap a table on the map to edit it.",
    positionX: "Position X",
    positionY: "Position Y",
    name: "Name",
    namePlaceholder: "e.g. Window, Bar, Patio",
    number: "Number",
    seats: "Seats",
    photo: "Photo",
    qrModalTitle: "Table {number}{label}",
    qrForTable: "QR for table {number}",
    tableLabelAria: "Table {number}",
    cantDeleteTitle: "Can't delete this table",
    cantDeleteMessage: "Table {number} has active orders or upcoming bookings. Resolve them first, then try again.",
    deleteTitle: "Delete table?",
    deleteMessage: "Table {number}{label} will be removed from the floor plan.",
  },
  settings: {
    breadcrumb: "Settings",
    about: {
      title: "About",
      titleLabel: "Title",
      titlePlaceholder: "Love Eatery",
      subtitleLabel: "Subtitle",
      subtitlePlaceholder: "Love at the first bite",
      showTitleLabel: "Show title on homepage",
      showTitleTip: "Displayed on the homepage of your public website.",
    },
    contacts: {
      title: "Contacts & location",
      contactsHeader: "Contacts",
      contactsTip: "Shown on the contacts page of your public menu.",
      phoneLabel: "Phone",
      phonePlaceholder: "+34 612 345 678",
      instagramLabel: "Instagram",
      instagramPlaceholder: "latrattoria",
      whatsappLabel: "WhatsApp",
      locationHeader: "Location",
      locationTip: "Address and map shown on your public contacts page. Search or tap the map to set the pin.",
    },
    branding: {
      title: "Branding",
      accentLabel: "Accent color",
      accentTip: "Main color for buttons and highlights.",
      colorAria: "Color {hex}",
      customColor: "Custom color",
      backgroundLabel: "Background",
      generateAi: "Generate with AI",
      removeBackground: "Remove background",
      video: "VIDEO",
      uploadHint: "Upload image or video",
      backgroundTip: "Shown as the homepage background of your public website.",
      aiTitle: "Generate background",
      aiPlaceholder: "e.g. Cozy candlelit table with rustic plates and warm wood",
    },
    general: {
      title: "General",
      menuLinkLabel: "Menu link",
      slugPlaceholder: "your-slug",
      copyUrl: "Copy URL",
      menuLinkTip: "Your unique URL where customers can view your menu.",
      slugError: "Use 2–40 lowercase letters, digits, or hyphens.",
      currencyLabel: "Currency",
      currencyTip: "Used for prices in your menu.",
    },
    orders: {
      title: "Orders",
      acceptLabel: "Accept orders",
      acceptTip: "When off, guests can browse the menu but can't place orders.",
      modeLabel: "Order mode",
      modeTip: "Internal orders are saved in the dashboard. WhatsApp orders are sent directly to your WhatsApp. You can enable both.",
      internal: "Internal",
      whatsapp: "WhatsApp",
      modeError: "Enable at least one mode.",
      requiredFieldsLabel: "Required fields",
      requiredFieldsTip: "Enabled fields will be required for the customer to fill in when placing an order.",
      fieldName: "Name",
      fieldPhone: "Phone",
      fieldAddress: "Address",
    },
    bookings: {
      title: "Bookings",
      enableLabel: "Enable bookings",
      enableTip: "When off, guests can browse the menu but can't reserve a table.",
      modeLabel: "Confirmation mode",
      modeAutoTip: "Reservations are confirmed automatically.",
      modeManualTip: "You will need to manually confirm each reservation.",
      modeAuto: "Automatic",
      modeManual: "Manual",
      durationLabel: "Reservation duration",
      durationTip: "How long a table is held per booking.",
      durationMin: "{min} min",
      hoursLabel: "Working hours",
      hoursTip: "Reservations can be made within these hours.",
      hoursError: "\"From\" must be earlier than \"to\".",
    },
    languages: {
      title: "Languages",
      availableLabel: "Available languages",
      availableTip: "Pick the languages you want for your menu. Tap to add or remove.",
      noneError: "Pick at least one language.",
      defaultLabel: "Default language",
      defaultTip: "The language you write your menu in first. Other languages are translations of this one.",
    },
    billing: {
      title: "Billing",
      menuUnavailable: "Menu unavailable for scanning",
      menuUnavailableTip: "Your trial has expired and there is no active subscription. Customers cannot scan and view your menu until you choose a plan.",
      trialActive: "Trial active",
      trialEnds: "Trial ends on {date}. Choose a plan to keep your menu available.",
      active: "Active",
      renewsOn: "Renews on {date}",
      manage: "Manage",
      yearly: "Yearly",
      monthly: "Monthly",
      billedYearly: "billed yearly",
      billedMonthly: "billed monthly",
      save30: "Save 30%",
      current: "Current",
      perMo: "/mo",
      currentPlan: "Current plan",
      switch: "Switch",
      subscribe: "Subscribe",
      cancelTip: "Cancel anytime via the customer portal. Yearly plans renew once per year.",
    },
    support: {
      title: "Support",
      noMessages: "No messages yet. Say hi!",
      placeholder: "Type a message...",
      send: "Send message",
    },
  },
  settingsHub: {
    title: "Settings",
    subtitle: "Manage your restaurant, team, and account.",
    logout: "Log out",
    loggingOut: "Logging out...",
    logoutDesc: "Sign out of this account.",
    rows: {
      about: "About",
      aboutDesc: "Title, subtitle, visibility",
      contacts: "Contacts & location",
      contactsDesc: "Phone, social, address",
      branding: "Branding",
      brandingDesc: "Background, accent color",
      general: "General",
      generalDesc: "Menu link, currency",
      tables: "Tables",
      tablesDesc: "Floor plan and capacity",
      orders: "Orders",
      ordersDesc: "Accept orders, modes, required fields",
      bookings: "Bookings",
      bookingsDesc: "Confirmation mode, duration, hours",
      languages: "Languages",
      languagesDesc: "Menu translation languages",
      billing: "Billing",
      billingDesc: "Subscription and invoices",
      support: "Support",
      supportDesc: "Chat with our team",
      companies: "Companies",
      companiesDesc: "All companies, plans, and chats.",
      sessions: "Sessions",
      sessionsDesc: "User sessions, events, and conversions.",
    },
  },
  impersonation: {
    loggedInAs: "Logged in as {email}",
    exit: "Exit",
    exiting: "Exiting…",
  },
  analyticsDashboard: {
    title: "Analytics",
    subtitle: "Menu views and performance.",
    loading: "Loading analytics…",
    noData: "No data yet",
    noDataSub: "Once guests start scanning your menu, you'll see stats here.",
    todayLabel: "Today",
    dayLabel: "Day",
    weekLabel: "Week",
    monthLabel: "Month",
    totalScans: "Total scans",
    uniqueScans: "Unique sessions",
    totalViews: "Page views",
    avgViews: "Avg pages/scan",
    byDay: "By day",
    byLanguage: "By language",
    byPage: "By page",
    noBreakdownData: "No data for this period.",
    limit: "Monthly limit",
    limitUsed: "{used} of {limit}",
    limitOver: "Over limit",
    limitInfinite: "Unlimited",
    periodToday: "Today",
    period7d: "7 days",
    period30d: "30 days",
    period90d: "90 days",
    noDataLong: "Once guests scan your menu, traffic and engagement metrics will appear here.",
    scans: "Scans",
    pageViews: "Page views",
    pagesPerScan: "Pages / scan",
    returning: "Returning",
    scansPerDay: "Scans per day",
    languages: "Languages",
    pages: "Pages",
    freePlanUsage: "Free plan usage",
    scansThisMonth: "Scans this calendar month",
    pageHome: "Home",
    pageLanguage: "Language picker",
    pageContacts: "Contacts",
    pageMenu: "Menu",
    dayTooltip: "{day} · {scans} scans · {views} views",
  },
  auth: {
    title: "Sign in to",
    titleAccent: "IQ Rest",
    subtitle: "Manage your menu, take orders, and grow your business.",
    emailLabel: "Email",
    emailPlaceholder: "you@restaurant.com",
    continueEmail: "Continue with email",
    or: "or",
    continueGoogle: "Continue with Google",
    consent: {
      text: "By continuing you agree to our",
      terms: "Terms",
      and: "and",
      privacy: "Privacy Policy",
    },
    verifyTitle: "Check your email",
    verifySubtitle: "We sent a 6-digit code to {email}.",
    verifyCodeLabel: "Verification code",
    checkSpam: "Don't see it? Check your spam folder.",
    verifyButton: "Verify and continue",
    resendCode: "Resend code",
    resendSent: "Code sent",
    changeEmail: "Use a different email",
    errors: {
      emailInvalid: "Please enter a valid email address.",
      sendFailed: "Couldn't send the code. Try again.",
      verifyFailed: "Couldn't verify the code. Try again.",
      codeExpired: "This code expired. Request a new one.",
      noCode: "No code on file. Request a new one.",
      invalidCode: "Wrong code. Try again.",
      tooManyAttempts: "Too many attempts. Wait and try again later.",
    },
  },
  admin: {
    all: "All",
    activeToday: "Active today",
    companiesTitle: "Companies",
    noCompanies: "No companies",
    noName: "No name",
    sessionsTitle: "Sessions",
    today: "Today",
    yesterday: "Yesterday",
    sevenDays: "7 days",
    refresh: "Refresh",
    noSessions: "No sessions",
    events: "{count} ev.",
    loading: "Loading…",
    settingsBreadcrumb: "Settings",
  },
};

const en = JSON.parse(fs.readFileSync(EN_PATH, "utf-8"));
en.dashboard = dashboard;
fs.writeFileSync(EN_PATH, JSON.stringify(en, null, 2) + "\n", "utf-8");
console.log(`Replaced messages/en.json#dashboard with ${Object.keys(dashboard).length} sub-namespaces`);
