import { Check } from "lucide-react";
import { Section } from "@/app/_landing/components/section";

const BENEFITS = ["QR لكل طاولة، امسح-واطلب، بدون تطبيق", "طلبات في الوقت الفعلي على لوحي المطبخ أو المدير", "أو موجّهة إلى WhatsApp المطعم — اختيارك", "المعدّلات والمتغيرات والحساسيات تصل إلى الفاتورة", "تعليق حر من الزبون على كل طلب", "ترقيم يومي للمطبخ", "إتمام طلب متعدد اللغات بـ 35 لغة، يكشَف من هاتف الزبون", "صفر عمولة لكل طلب — اشتراك شهري ثابت"];
const HOW_STEPS = [
  { title: "فعّل الطلبات في المطعم", desc: "افتح إعدادات المطعم، فعّل مفتاح الطلبات واختر حقول الزبون (الاسم، الهاتف، العنوان) المراد جمعها." },
  { title: "اختر قناة التسليم", desc: "الوضع الداخلي يرسل الطلبات الجديدة إلى تبويب المطبخ. وضع WhatsApp يرسلها كرسالة منسّقة إلى WhatsApp المطعم. أو الاثنين معاً." },
  { title: "اطبع QR والصقه", desc: "حمّل QR (واحد لكل طاولة أو واحد للمطعم بأكمله) بصيغة PDF أو PNG والصقه على الطاولات. يمسح الضيوف بكاميرا الجهاز الأصلية — بدون متجر تطبيقات، بدون احتكاك." },
  { title: "أدر الخدمة", desc: "تظهر الطلبات في تبويب المطبخ برقم الطاولة، الأطباق، المتغيرات، الحساسيات، التعليق والرقم اليومي. تنتقل بين جديد → قيد المعالجة → مكتمل. متصفح الزبون يُحدَّث في الوقت الفعلي." },
];
const COMPARISON_ROWS = [["عمولة لكل طلب","20–30%","0%","0% (€6.90/شهر ثابت)"],["وجهة الطلب","تطبيق المجمع","الكاشير الخاص بك","لوحي المطبخ أو WhatsApp"],["رقم الطاولة في الفاتورة","لا","يدوي","نعم، تلقائي"],["المعدّلات / المتغيرات","محدودة","نعم","نعم، مع الحساسيات"],["إتمام طلب متعدد اللغات","لغة تطبيقهم","لا","35 لغة، تلقائي"],["العتاد المطلوب","لوحي المجمع","نقطة بيع","أي لوحي بمتصفح"],["وقت الإعداد","مكالمة إعداد","أيام-أسابيع","5 دقائق"]];

export function SeoContent() {
  return (<>
    <Section noContainer dataSection="seo-intro"><div className="w-full"><p className="text-xs font-medium uppercase tracking-widest text-primary mb-3 text-start">بالتفصيل</p><h2 className="text-3xl sm:text-4xl lg:text-5xl font-medium tracking-tight mb-3 text-start">ما هو نظام طلبات أونلاين للمطاعم <span className="text-muted-foreground">حقاً</span></h2><p className="text-base sm:text-lg text-muted-foreground mb-10 text-start">ليس سوقاً. ليس مجمع توصيل. خط مباشر من هاتف الزبون على طاولتك إلى لوحي المطبخ — أو WhatsApp الخاص بك.</p><div className="space-y-4 text-base sm:text-lg text-foreground/90 leading-relaxed"><p><strong>نظام طلبات أونلاين للمطاعم</strong> بمفهوم IQ Rest هو البرنامج الذي يتيح للزبون الجالس على طاولتك أن يفتح القائمة في هاتفه، يبني سلة، ويرسل الطلب إلى مطبخك — دون المرور بـ Uber Eats أو طلبات أو Wolt أو أي سوق آخر. لا يغادر الزبون قائمة QR، لا تدفع عمولة لكل طلب، وتصل الفاتورة برقم الطاولة الحقيقي.</p><p>IQ Rest مبني حول قناتي تسليم. افتراضياً <em>الوضع الداخلي</em>: يصل كل طلب جديد إلى تبويب المطبخ في اللوحة على اللوحي أو الهاتف أو اللابتوب عند منفذ التقديم — برقم الطاولة، الأطباق مع المتغيرات والحساسيات، تعليق الزبون الحر ورقم يومي للمطبخ. البديل <em>وضع WhatsApp</em>: نفس الطلب كرسالة منسّقة إلى رقم WhatsApp المطعم — مفيد للفرق الصغيرة، الطلبات الخارجية الغالبة أو غياب المدير. يمكن أن يعمل الوضعان بالتوازي.</p></div></div></Section>
    <Section noContainer dataSection="seo-benefits"><div className="w-full"><h3 className="text-2xl sm:text-3xl font-medium tracking-tight mb-6 text-start">ما تحصل عليه فعلاً</h3><div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-3 sm:gap-4">{BENEFITS.map((b) => (<div key={b} className="bg-muted/20 border border-border rounded-2xl p-4 sm:p-5 flex flex-row items-center gap-3"><div className="h-8 w-8 rounded-lg bg-primary/10 text-primary flex items-center justify-center shrink-0"><Check className="h-4 w-4" strokeWidth={2.5} /></div><p className="text-sm sm:text-base text-foreground/90 leading-snug">{b}</p></div>))}</div></div></Section>
    <Section noContainer dataSection="seo-how"><div className="w-full"><h3 className="text-2xl sm:text-3xl font-medium tracking-tight mb-6 text-start">كيف يعمل تدفق طلبات IQ Rest</h3><p className="text-base sm:text-lg text-foreground/90 leading-relaxed mb-6 text-start">أربعة مفاتيح في اللوحة وأنت تعمل. بدون مثبّت، بدون عتاد نقطة بيع، بدون مشروع دمج.</p><div className="grid grid-cols-1 sm:grid-cols-2 gap-3 sm:gap-4">{HOW_STEPS.map((s, i) => (<div key={s.title} className="bg-muted/20 border border-border rounded-2xl p-5 flex flex-row items-start gap-4"><div className="h-10 w-10 rounded-lg bg-primary text-primary-foreground flex items-center justify-center shrink-0 font-semibold text-base">{i + 1}</div><div className="flex-1 min-w-0"><div className="text-base sm:text-lg font-semibold tracking-tight mb-1">{s.title}</div><p className="text-sm text-muted-foreground leading-relaxed">{s.desc}</p></div></div>))}</div></div></Section>
    <Section noContainer dataSection="seo-table"><div className="w-full"><h3 className="text-2xl sm:text-3xl font-medium tracking-tight mb-6 text-start">مجمع، نقطة بيع كلاسيكية أو نظام طلبات</h3><div className="bg-muted/20 border border-border rounded-2xl p-4 sm:p-6 overflow-x-auto"><table className="w-full text-sm sm:text-base border-collapse"><thead><tr className="border-b border-border"><th className="text-left font-semibold py-3 pr-3 text-foreground">الخاصية</th><th className="text-left font-semibold py-3 pr-3 text-muted-foreground">مجمع توصيل</th><th className="text-left font-semibold py-3 pr-3 text-muted-foreground">نقطة بيع كلاسيكية</th><th className="text-left font-semibold py-3 text-primary">طلبات IQ Rest</th></tr></thead><tbody className="text-foreground/90">{COMPARISON_ROWS.map((row, i) => (<tr key={row[0]} className={i < COMPARISON_ROWS.length - 1 ? "border-b border-border/50" : ""}><td className="py-3 pr-3 font-medium">{row[0]}</td><td className="py-3 pr-3 text-muted-foreground">{row[1]}</td><td className="py-3 pr-3 text-muted-foreground">{row[2]}</td><td className="py-3 text-foreground">{row[3]}</td></tr>))}</tbody></table></div><p className="text-sm text-muted-foreground leading-relaxed mt-6 text-start">نظام طلبات يملكه المطعم فعلاً يسدّد تكلفته في عطلة الأسبوع الأولى — كل يورو ينفقه الزبون في مكانك يبقى في مكانك، وفاتورة منفذ التقديم تحمل دائماً رقم الطاولة الحقيقي.</p></div></Section>
  </>);
}
