import { QrCode, MessageCircle, ChefHat, Settings2, Languages, BarChart3 } from "lucide-react";
import type { LandingTexts } from "@/app/_landing/types";

export const TEXTS: LandingTexts = {
  htmlLang: "nl",
  htmlDir: "ltr",
  meta: {
    title: "Online Bestelsysteem voor Restaurants — QR & WhatsApp | IQ Rest",
    description: "Online bestelsysteem voor restaurants: gast scant de QR, bestelt, en de bestelling komt direct op je keuken-tablet of WhatsApp. Geen commissie, tafelnummer inbegrepen. 14 dagen gratis.",
    canonical: "https://iq-rest.com/nl/online-bestelsysteem-voor-restaurants",
    ogLocale: "nl_NL",
    ogTitle: "Online Bestelsysteem voor Restaurants — Direct naar de Keuken",
    ogDescription: "De gast scant de QR aan tafel, bouwt de bestelling, en die landt op je tablet of WhatsApp — zonder aggregator, zonder commissie, met tafelnummer op elke bon.",
  },
  ctaText: "Activeer mijn bestellingen",
  demoText: "Bekijk live demo",
  microcopy: "Vanaf €6,90/maand · 14 dagen gratis · Wanneer dan ook opzegbaar",
  header: { navFeatures: "Functies", navHow: "Hoe het werkt", navPricing: "Prijzen", navFaq: "FAQ", signIn: "Inloggen", cta: "Gratis proberen" },
  hero: {
    verticals: ["Restaurants", "Cafés", "Bistro's", "Pizzeria's", "Bars", "Brouwerijen"],
    headline: "Online Bestelsysteem voor Restaurants.",
    sub: "De gast scant de QR aan de tafel, bouwt de bestelling op zijn telefoon en de bon landt direct op je keuken-tablet of WhatsApp van het restaurant. Geen aggregator, geen commissie, tafelnummer op elke ticket.",
    dynamicHeadlines: ["Bestellen aan tafel.", "Direct naar de keuken-tablet.", "Of direct naar WhatsApp.", "Nul commissie.", "Met tafelnummer."],
    painBullets: [
      "Online bestelsysteem dat het restaurant écht bezit — geen tussenpartij, geen commissie.",
      "Bestellingen komen op de keuken- of manager-tablet met tafelnummer, modifiers, allergenen en notities.",
      "Of direct naar de WhatsApp van het restaurant — perfect voor afhaal en kleine teams.",
      "QR per tafel (of één voor de hele zaak) automatisch gegenereerd.",
    ],
    rating: "+500 restaurants in 30+ landen",
  },
  features: {
    heading: "Een bestelsysteem",
    headingAccent: "gebouwd voor de tafel.",
    sub: "Echte functionaliteit — geen kloon van bezorgaggregators.",
    items: [
      { Icon: QrCode, title: "QR-menu met winkelmandje aan elke tafel", desc: "De gast scant de QR, bladert door het menu in zijn taal, voegt gerechten met modifiers toe, laat een notitie voor de keuken achter en verstuurt. Geen app nodig.", tag: "QR-bestellingen" },
      { Icon: ChefHat, title: "Bestellingen op je keuken-tablet", desc: "Elke nieuwe bestelling verschijnt in het Keuken-tabblad — op de tablet bij de doorgeefluik — met tafelnummer, gerechten, varianten, allergenen en gastopmerking. Met één tap van in behandeling naar voltooid.", tag: "Keukenweergave" },
      { Icon: MessageCircle, title: "Of stuur bestellingen naar WhatsApp", desc: "Zet het restaurant in WhatsApp-modus (of beide tegelijk) — elke bestelling komt als geformatteerd bericht op WhatsApp van de zaak. Ideaal voor afhaal of kleine teams.", tag: "WhatsApp-modus" },
      { Icon: Settings2, title: "Modifiers, varianten en allergenen", desc: "Elk gerecht heeft variantgroepen (maat, gaarheid, toppings) met prijsverschil, allergeen-tags en vrije beschrijving. Het winkelmandje respecteert alles — de bon op de tablet is eenduidig.", tag: "Echt winkelmandje" },
      { Icon: Languages, title: "Meertalige checkout", desc: "Heel het bestelproces — winkelmandje, modifiers, opmerking, bevestiging — vertaald in 35 talen en past zich automatisch aan de telefoontaal van de gast aan.", tag: "35 talen" },
      { Icon: BarChart3, title: "Dagelijkse nummering en logboek", desc: "Elke bestelling krijgt een dagnummer voor de keuken, landt in een log met totalen en tijdstempels, voedt de analytics. Annuleringen zijn soft-deleted — rapporten blijven schoon.", tag: "Bestellog" },
    ],
  },
  founder: {
    eyebrow: "Gebouwd door een café-eigenaar, niet door een bezorgstartup",
    quoteStart: "Met mijn vrouw openden we een café en zochten weken naar een manier om bestellingen aan tafel op te nemen die geen 30% aan een aggregator gaf of een kassa van €1500 vereiste. Alles wat we probeerden was zwaar, duur of miste het basics —",
    quoteAccent: "dus bouwden we het bestelsysteem dat we wilden hebben.",
    sign: "Bogdan Sokolov · oprichter, voormalig café-eigenaar",
    photoAlt: "Bogdan, oprichter van IQ Rest",
  },
  how: {
    heading: "Activeer je bestelsysteem",
    headingAccent: "in 4 stappen",
    sub: "Geen installatie, geen integrator, geen IT-telefoontje. Alleen je telefoon en 5 minuten.",
    steps: [
      { n: "1", t: "Maak het restaurant aan", d: "Aanmelden via email of Google — 30 seconden." },
      { n: "2", t: "Voeg het menu toe", d: "Drag-and-drop of AI-scan van een papieren menu." },
      { n: "3", t: "Kies het kanaal", d: "Keuken-tablet, WhatsApp of beide." },
      { n: "4", t: "Druk de QR", d: "Eén QR per tafel — gasten beginnen meteen te bestellen." },
    ],
  },
  pricing: {
    badge: "Onbeperkt bestellen · Nul commissie",
    heading: "Eén plan.",
    headingAccent: "Geen kosten per bestelling.",
    sub: "Online bestellen, QR-menu, WhatsApp-modus, meertalige checkout en analytics — alles in één abonnement. Geen percentage per transactie.",
    monthlyLabel: "Maandelijks",
    yearlyLabel: "Jaarlijks",
    saveBadge: "Bespaar 25%",
    perMonth: "per maand",
    billedAnnually: "Jaarlijks gefactureerd {total}",
    youSave: "Je bespaart {amount}",
    trust: { secure: "Abonnement via Stripe", noCommitment: "Geen verplichting", quick: "Live in minuten", restaurants: "+500 restaurants" },
  },
  faq: {
    eyebrow: "Bestelsysteem — veelgestelde vragen",
    heading: "Over het",
    headingAccent: "bestelsysteem.",
    sub: "Wat eigenaren vragen voordat ze online bestellen met IQ Rest activeren. Vraag niet beantwoord? Stuur ons een berichtje op WhatsApp — echte mensen antwoorden.",
    whatsappCta: "Vraag op WhatsApp",
    whatsappPrefill: "Hoi, ik heb een vraag over IQ Rest bestellingen",
    items: [
      { q: "Is dit een bezorgplatform zoals Thuisbezorgd of Uber Eats?", a: "Nee, en dat is precies het punt. IQ Rest is het eigen bestelkanaal van het restaurant — de gast bestelt vanaf je QR, de bon landt op je tablet of WhatsApp, jij serveert. Geen marktplaats, geen aggregator-catalogus — en we nemen nooit een deel van de rekening." },
      { q: "Waar verschijnen de bestellingen precies?", a: "In het Keuken-tabblad van het IQ Rest dashboard, op elke tablet of telefoon bij de doorgeefluik of bar. Elke bestelling toont tafelnummer, gerechten met varianten en allergenen, gastopmerking en het dagnummer. Met één tap door nieuw → in behandeling → voltooid." },
      { q: "Kan ik de bestelling in plaats daarvan op WhatsApp ontvangen?", a: "Ja. Elk restaurant heeft drie modi: intern (alleen keuken-tablet), WhatsApp (de bestelling komt als geformatteerd bericht op het WhatsApp-nummer van de zaak) of beide tegelijk. De modus is één schakelaar in het dashboard — wissel wanneer je wilt." },
      { q: "Wat zit er in een bestelling?", a: "Gerechten met varianten en toppings (inclusief prijsverschil), allergenen, tafelnummer, vrije opmerking van de gast en — als je de velden inschakelt — naam, telefoon en adres. Genoeg om een afhaalkoerier te sturen of de tafel terug te bellen over een allergie." },
      { q: "Kunnen gasten online betalen vanaf het menu?", a: "Niet standaard. IQ Rest is gebouwd rond pay-at-the-table — de gast bestelt, jij brengt de rekening, hij betaalt zoals altijd. Online kaartbetaling (typisch voor afhaal) kan op verzoek met Stripe Connect worden geïntegreerd — stuur een WhatsApp-bericht." },
      { q: "Heb ik een speciale tablet, printer of POS-hardware nodig?", a: "Nee. Elke tablet, laptop of telefoon met browser werkt — open het dashboard, log in, laat het Keuken-tabblad open. Heb je al een POS, dan leeft IQ Rest ernaast; we vervangen je kassa niet." },
      { q: "Wat gebeurt er na de 14 gratis dagen?", a: "Zonder betaalmethode pauzeert het account — we incasseren nooit automatisch. Menu, bestellingen en instellingen blijven bewaard; voeg een kaart toe wanneer je wilt reactiveren. Eén klik om op te zeggen, geen verplichting." },
    ],
  },
  finalCta: {
    heading: "Activeer je bestelsysteem.",
    headingAccent: "Live in 5 minuten.",
    sub: "14 dagen gratis, zonder kaart. Wanneer dan ook opzegbaar. Sluit aan bij 500+ restaurants die hun eigen online bestelsysteem draaien met IQ Rest.",
  },
  scan: {
    heading: "Van papieren menu naar bestelsysteem",
    headingAccent: "in 60 seconden",
    sub: "Upload een foto van het menu — AI haalt categorieën, gerechten en prijzen rechtstreeks in de editor. Vanaf daar zijn winkelmandje en QR één klik weg.",
    cta: "Scan mijn menu →",
  },
  footer: {
    featureLinks: [
      { href: "/nl/ai-translation", label: "AI-vertaling" },
      { href: "/nl/reservations", label: "Reserveringen" },
      { href: "/nl/mobile-management", label: "Mobiel beheer" },
      { href: "/nl/easy-menu", label: "Menu-editor" },
      { href: "/nl/custom-design", label: "Video- en fotoachtergronden" },
      { href: "/nl/color-scheme", label: "Merkkleuren" },
      { href: "/nl/multilingual", label: "Meertalig menu" },
      { href: "/nl/ai-images", label: "AI-foto-optimalisatie" },
      { href: "/nl/analytics", label: "Analytics" },
      { href: "/nl/instant-setup", label: "Direct opzetten" },
      { href: "/nl/personal-support", label: "Persoonlijke support" },
    ],
    navLinks: [
      { href: "#pricing", label: "Prijzen" },
      { href: "#faq", label: "Vragen" },
      { href: "/nl/changelog", label: "Nieuws" },
      { href: "/nl/languages", label: "Taal wijzigen" },
    ],
    copyrightTemplate: "© {year} IQ Rest. Alle rechten voorbehouden.",
  },
};
