import { Check } from "lucide-react";
import { Section } from "@/app/_landing/components/section";

const BENEFITS = ["QR á hverju borði, skannaðu-og-pantaðu, án forrits", "Pantanir í rauntíma á eldhús- eða stjórnandaspjaldtölvu", "Eða í WhatsApp veitingastaðarins — þú velur", "Breytur, valmöguleikar og ofnæmisvakar fara á kvittunina", "Frjáls athugasemd gestsins á hverri pöntun", "Dagleg númering fyrir eldhúsið", "Fjöltyngd útgreiðsla á 35 tungumálum, eftir síma gestsins", "Núll þóknun á pöntun — föst mánaðarleg áskrift"];
const HOW_STEPS = [
  { title: "Kveiktu á pöntunum fyrir veitingastaðinn", desc: "Opnaðu stillingar veitingastaðarins, virkjaðu rofann Pantanir og veldu hvaða gestareiti (nafn, sími, heimilisfang) eigi að safna." },
  { title: "Veldu afhendingarrás", desc: "Innri hamurinn sendir nýjar pantanir á flipann Eldhús. WhatsApp-hamurinn sniðmótar pöntunina sem skilaboð í WhatsApp veitingastaðarins. Eða báðar samhliða." },
  { title: "Prentaðu og límdu QR", desc: "Sæktu QR (eitt á borð eða eitt á veitingastað) í PDF eða PNG og límdu á borðin. Gestir skanna með eigin myndavél — án App Store, án núnings." },
  { title: "Vinnðu vaktina", desc: "Pantanir birtast á flipanum Eldhús með borðnúmeri, réttum, valmöguleikum, ofnæmisvökum, athugasemd og daglegu númeri. Skipti ný → í vinnslu → tilbúin. Vafri gestsins uppfærist í rauntíma." },
];
const COMPARISON_ROWS = [["Þóknun á pöntun","20–30%","0%","0% (€6,90/mán fast)"],["Hvert pöntunin fer","Forrit aggregatora","Þinn kassi","Þín eldhússpjaldtölva eða WhatsApp"],["Borðnúmer á kvittun","Ekki","Handvirkt","Já, sjálfvirkt"],["Breytur / valmöguleikar","Takmarkað","Já","Já, með ofnæmisvökum"],["Fjöltyngd útgreiðsla","Tungumál þeirra forrits","Ekki","35 tungumál, sjálfvirkt"],["Nauðsynlegur vélbúnaður","Aggregator-spjaldtölva","POS skautstöð","Sérhver spjaldtölva með vafra"],["Uppsetningartími","Þjálfunarsamtal","Dagar-vikur","5 mínútur"]];

export function SeoContent() {
  return (<>
    <Section dataSection="seo-intro"><div className="max-w-4xl mx-auto"><p className="text-xs font-medium uppercase tracking-widest text-primary mb-3 text-center">Nánar</p><h2 className="text-3xl sm:text-4xl lg:text-5xl font-medium tracking-tight mb-3 text-center">Hvað er netpöntunarkerfi fyrir veitingastað <span className="text-muted-foreground">í raun</span></h2><p className="text-base sm:text-lg text-muted-foreground mb-10 text-center">Engin markaðstorg. Enginn afhendingaraggregator. Bein lína frá síma gestsins við borðið þitt í eldhússpjaldtölvuna — eða WhatsApp.</p><div className="space-y-4 text-base sm:text-lg text-foreground/90 leading-relaxed"><p><strong>Netpöntunarkerfi fyrir veitingastað</strong> í skilningi IQ Rest er hugbúnaður sem leyfir gesti við borðið þitt að opna matseðilinn í símanum, fylla körfu og senda pöntun í eldhúsið — án Wolt, Deliveroo, Bolt Food eða annarra markaðstorga. Gesturinn fer aldrei úr QR matseðlinum þínum, þú greiðir enga þóknun á pöntun, og kvittunin kemur með raunverulegu borðnúmeri.</p><p>IQ Rest er smíðað í kringum tvær rásir. Sjálfgefið er <em>innri hamur</em>: hver ný pöntun berst á flipann Eldhús í mælaborðinu á spjaldtölvu, síma eða fartölvu við passið — með borðnúmeri, réttum með breytum og ofnæmisvökum, frjálsri athugasemd gestsins og daglegu pöntunarnúmeri. Valkostur er <em>WhatsApp-hamur</em>: sama pöntunin er sniðmótuð sem skilaboð í WhatsApp veitingastaðarins. Gagnlegt fyrir lítil teymi, aðallega sækjapantanir eða þegar stjórnandinn er fjarri salnum. Báðir hamir geta keyrt samtímis.</p></div></div></Section>
    <Section dataSection="seo-benefits"><div className="max-w-4xl mx-auto"><h3 className="text-2xl sm:text-3xl font-medium tracking-tight mb-6 text-center">Hvað þú færð í raun</h3><div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-3 sm:gap-4">{BENEFITS.map((b) => (<div key={b} className="bg-muted/20 border border-border rounded-2xl p-4 sm:p-5 flex flex-row items-center gap-3"><div className="h-8 w-8 rounded-lg bg-primary/10 text-primary flex items-center justify-center shrink-0"><Check className="h-4 w-4" strokeWidth={2.5} /></div><p className="text-sm sm:text-base text-foreground/90 leading-snug">{b}</p></div>))}</div></div></Section>
    <Section dataSection="seo-how"><div className="max-w-4xl mx-auto"><h3 className="text-2xl sm:text-3xl font-medium tracking-tight mb-6 text-center">Hvernig pöntunarflæði IQ Rest virkar</h3><p className="text-base sm:text-lg text-foreground/90 leading-relaxed mb-6 text-center">Fjórir rofar í mælaborðinu — og þú ert á lofti. Enginn uppsetningarmaður, enginn POS vélbúnaður, ekkert samþættingarverkefni.</p><div className="grid grid-cols-1 sm:grid-cols-2 gap-3 sm:gap-4">{HOW_STEPS.map((s, i) => (<div key={s.title} className="bg-muted/20 border border-border rounded-2xl p-5 flex flex-row items-start gap-4"><div className="h-10 w-10 rounded-lg bg-primary text-primary-foreground flex items-center justify-center shrink-0 font-semibold text-base">{i + 1}</div><div className="flex-1 min-w-0"><div className="text-base sm:text-lg font-semibold tracking-tight mb-1">{s.title}</div><p className="text-sm text-muted-foreground leading-relaxed">{s.desc}</p></div></div>))}</div></div></Section>
    <Section dataSection="seo-table"><div className="max-w-4xl mx-auto"><h3 className="text-2xl sm:text-3xl font-medium tracking-tight mb-6 text-center">Aggregator, klassískt POS eða pöntunarkerfi</h3><div className="bg-muted/20 border border-border rounded-2xl p-4 sm:p-6 overflow-x-auto"><table className="w-full text-sm sm:text-base border-collapse"><thead><tr className="border-b border-border"><th className="text-left font-semibold py-3 pr-3 text-foreground">Eiginleiki</th><th className="text-left font-semibold py-3 pr-3 text-muted-foreground">Afhendingaraggregator</th><th className="text-left font-semibold py-3 pr-3 text-muted-foreground">Klassískt POS</th><th className="text-left font-semibold py-3 text-primary">IQ Rest pantanir</th></tr></thead><tbody className="text-foreground/90">{COMPARISON_ROWS.map((row, i) => (<tr key={row[0]} className={i < COMPARISON_ROWS.length - 1 ? "border-b border-border/50" : ""}><td className="py-3 pr-3 font-medium">{row[0]}</td><td className="py-3 pr-3 text-muted-foreground">{row[1]}</td><td className="py-3 pr-3 text-muted-foreground">{row[2]}</td><td className="py-3 text-foreground">{row[3]}</td></tr>))}</tbody></table></div><p className="text-sm text-muted-foreground leading-relaxed mt-6 text-center">Netpöntunarkerfi sem veitingastaðurinn á sjálfur borgar sig upp fyrstu helgina — hver króna sem gesturinn eyðir í salnum þínum verður eftir í salnum þínum, og kvittunin við passið er alltaf með raunverulegu borðnúmeri.</p></div></Section>
  </>);
}
