import { QrCode, MessageCircle, ChefHat, Settings2, Languages, BarChart3 } from "lucide-react";
import type { LandingTexts } from "@/app/_landing/types";

export const TEXTS: LandingTexts = {
  htmlLang: "is",
  htmlDir: "ltr",
  meta: {
    title: "Netpöntunarkerfi fyrir veitingastað — QR og WhatsApp | IQ Rest",
    description: "Netpöntunarkerfi fyrir veitingastað: gesturinn skannar QR við borðið, setur saman pöntun og hún berst beint á eldhússpjaldtölvuna eða WhatsApp. Núll þóknun, með borðnúmeri. 14 dagar ókeypis.",
    canonical: "https://iq-rest.com/is/netpontunarkerfi-veitingastadar",
    ogLocale: "is_IS",
    ogTitle: "Netpöntunarkerfi fyrir veitingastað — Beint í eldhúsið",
    ogDescription: "Gesturinn skannar QR við borðið, setur saman pöntun og hún berst á spjaldtölvuna eða WhatsApp — engin milliliður, engin þóknun, með borðnúmeri á hverri kvittun.",
  },
  ctaText: "Kveikja á pöntunum",
  demoText: "Bein kynning",
  microcopy: "Frá €6,90/mán · 14 dagar ókeypis · Hættu hvenær sem er",
  header: { navFeatures: "Eiginleikar", navHow: "Hvernig það virkar", navPricing: "Verð", navFaq: "FAQ", signIn: "Innskráning", cta: "Prófaðu" },
  hero: {
    verticals: ["Veitingastaðir", "Kaffihús", "Bistros", "Pizzustaðir", "Barir", "Bjórstofur"],
    headline: "Netpöntunarkerfi fyrir veitingastað.",
    sub: "Gesturinn skannar QR við borðið sitt, setur saman pöntun í símanum — og kvittunin berst beint á eldhússpjaldtölvuna eða WhatsApp veitingastaðarins. Engin milliliður, engin þóknun, með borðnúmeri á hverri kvittun.",
    dynamicHeadlines: ["Pöntun við borðið.", "Beint á eldhússpjaldtölvuna.", "Eða beint í WhatsApp.", "Núll þóknun.", "Með borðnúmeri."],
    painBullets: [
      "Netpöntunarkerfi sem veitingastaðurinn á sjálfur — engar milliliðir, engin þóknun.",
      "Pantanir berast á spjaldtölvu eldhúss eða stjórnanda með borðnúmeri, breytum, ofnæmisvökum og athugasemdum.",
      "Eða sendar beint í WhatsApp veitingastaðarins — fullkomið fyrir sækjapantanir og lítil teymi.",
      "QR fyrir hvert borð (eða eitt fyrir allan salinn) er búið til sjálfkrafa.",
    ],
    rating: "500+ veitingastaðir í 30+ löndum",
  },
  features: {
    heading: "Pöntunarkerfi,",
    headingAccent: "smíðað fyrir borðið.",
    sub: "Raunveruleg virkni — ekki klónun afhendingaraggregatora.",
    items: [
      { Icon: QrCode, title: "QR matseðill með körfu fyrir hvert borð", desc: "Gesturinn skannar QR, vafrar um matseðilinn á sínu tungumáli, bætir réttum með breytum, skilur eftir athugasemd fyrir eldhúsið og sendir. Án forrits.", tag: "QR pöntun" },
      { Icon: ChefHat, title: "Pantanir á eldhússpjaldtölvunni", desc: "Hver ný pöntun birtist á flipanum Eldhús — á spjaldtölvu við passið — með borðnúmeri, réttum, valmöguleikum, ofnæmisvökum og athugasemd. Einn smellur frá „í vinnslu“ í „tilbúið“.", tag: "Eldhússýn" },
      { Icon: MessageCircle, title: "Eða í WhatsApp", desc: "Settu veitingastaðinn í WhatsApp-ham (eða báða samtímis) — hver pöntun berst í WhatsApp sem snyrtileg skilaboð. Fullkomið fyrir sækjapantanir eða lítil teymi.", tag: "WhatsApp-hamur" },
      { Icon: Settings2, title: "Breytur, valmöguleikar og ofnæmisvakar", desc: "Hver réttur hefur valhópa (stærð, steiking, viðbætur) með verðmun, ofnæmismerkjum og frjálsri lýsingu. Karfan reiknar allt — kvittunin á spjaldtölvunni er án vafa.", tag: "Alvöru karfa" },
      { Icon: Languages, title: "Fjöltyngd útgreiðsla", desc: "Allt pöntunarferlið — karfa, breytur, athugasemd, staðfesting — er þýtt á 35 tungumál og aðlagast sjálfkrafa tungumáli síma gestsins.", tag: "35 tungumál" },
      { Icon: BarChart3, title: "Dagleg númering og dagbók", desc: "Hver pöntun fær daglegt númer fyrir eldhúsið, fer í dagbók með upphæðum og tímamerkjum, fæðir tölfræði. Afpantanir eru soft-delete, skýrslur halda sér hreinar.", tag: "Pöntunardagbók" },
    ],
  },
  founder: {
    eyebrow: "Smíðað af kaffihúsareiganda, ekki afhendingar-startup",
    quoteStart: "Konan mín og ég opnuðum kaffihús og eyddum vikum í að leita að leið til að taka við pöntunum við borðið sem gæfi ekki 30% til aggregatora og þyrfti ekki 1500 € kassa. Allt sem við reyndum var klúbbalegt, dýrt eða vantaði grunnatriðin —",
    quoteAccent: "svo við smíðuðum pöntunarkerfið sem við sjálf vildum hafa.",
    sign: "Bogdan Sokolov · stofnandi, fyrrverandi kaffihúsareigandi",
    photoAlt: "Bogdan, stofnandi IQ Rest",
  },
  how: {
    heading: "Kveiktu á pöntunarkerfinu",
    headingAccent: "á 4 skrefum",
    sub: "Engin uppsetning, enginn samþættari, ekkert símtal til UT. Bara sími og 5 mínútur.",
    steps: [
      { n: "1", t: "Búðu til veitingastað", d: "Skráning með tölvupósti eða Google — 30 sekúndur." },
      { n: "2", t: "Bættu við matseðli", d: "Drag-and-drop eða AI skönnun af pappírsmatseðli." },
      { n: "3", t: "Veldu rás", d: "Eldhússpjaldtölva, WhatsApp eða báðar." },
      { n: "4", t: "Prentaðu QR", d: "Eitt QR á borð — gestir panta strax." },
    ],
  },
  pricing: {
    badge: "Ótakmarkaðar pantanir · Núll þóknun",
    heading: "Ein áskrift.",
    headingAccent: "Engin gjald á pöntun.",
    sub: "Netpantanir, QR matseðill, WhatsApp-hamur, fjöltyngd útgreiðsla og tölfræði — allt í einni áskrift. Engin prósenta af færslu.",
    monthlyLabel: "Mánaðarlega",
    yearlyLabel: "Árlega",
    saveBadge: "Sparaðu 25%",
    perMonth: "á mánuði",
    billedAnnually: "Rukkað einu sinni á ári {total}",
    youSave: "Þú sparar {amount}",
    trust: { secure: "Áskrift í gegnum Stripe", noCommitment: "Engin skuldbinding", quick: "Virkt á mínútum", restaurants: "+500 veitingastaðir" },
  },
  faq: {
    eyebrow: "Pöntunarkerfi — algengar spurningar",
    heading: "Um pöntunar-",
    headingAccent: "kerfið.",
    sub: "Hvað veitingastaðareigendur spyrja áður en þeir kveikja á netpöntunum í IQ Rest. Sérðu ekki þína spurningu? Skrifaðu á WhatsApp — alvöru fólk svarar.",
    whatsappCta: "Spurðu á WhatsApp",
    whatsappPrefill: "Hæ, ég er með spurningu um IQ Rest pantanir",
    items: [
      { q: "Er þetta afhendingarvettvangur eins og Wolt eða Deliveroo?", a: "Nei, einmitt það er punkturinn. IQ Rest er eigin pöntunarrás veitingastaðarins: gesturinn pantar af þínu QR, pöntunin berst á spjaldtölvuna þína eða WhatsApp, þú framreiðir. Engin markaðstorg, enginn aggregator-skrá — og við tökum aldrei hluta af reikningnum." },
      { q: "Hvar birtast pantanir nákvæmlega?", a: "Á flipanum Eldhús í IQ Rest mælaborði á hvaða spjaldtölvu eða síma sem er við passið eða barinn. Hver pöntun sýnir borðnúmer, rétti með breytum og ofnæmisvökum, athugasemd gestsins og daglegt númer. Skipti „ný → í vinnslu → tilbúin“ með einum smelli." },
      { q: "Geta pantanir komið í WhatsApp í staðinn?", a: "Já. Hver veitingastaður er með þrjá hami: innri (aðeins eldhússpjaldtölva), WhatsApp (pöntunin kemur sem skilaboð í WhatsApp veitingastaðarins) eða báða samtímis. Hamurinn er einn rofi í mælaborðinu, breytist hvenær sem er." },
      { q: "Hvað er í pöntuninni?", a: "Réttir með breytum og viðbótum (með verðmun), ofnæmisvakar, borðnúmer, frjáls athugasemd gestsins og — ef þú kveikir á reitunum — nafn, sími og heimilisfang. Nóg til að senda kúrir eða hringja aftur í borðið vegna ofnæmisvaka." },
      { q: "Geta gestir greitt á netinu á matseðlinum?", a: "Sjálfgefið — nei. IQ Rest er sett upp fyrir greiðslu við borðið: gesturinn pantar, þú kemur með reikninginn, greitt sem venjulega. Ef þú þarft greiðslu á netinu með korti (dæmigert fyrir sækjapantanir), er Stripe Connect samþætting möguleg eftir beiðni — skrifaðu á WhatsApp." },
      { q: "Þarf ég sérstaka spjaldtölvu, prentara eða POS vélbúnað?", a: "Nei. Sérhver spjaldtölva, fartölva eða sími með vafra — opnaðu mælaborðið, skráðu þig inn, hafðu flipann Eldhús opinn. Ef þú ert þegar með POS — IQ Rest virkar við hliðina, kemur ekki í stað kassans." },
      { q: "Hvað gerist eftir 14 ókeypis daga?", a: "Án greiðslumáta tekur reikningurinn hlé — við rukkum aldrei sjálfvirkt. Matseðill, pantanir og stillingar eru varðveittar; bættu við korti hvenær sem er til að virkja aftur. Hættu með einum smelli, engin skuldbinding." },
    ],
  },
  finalCta: {
    heading: "Kveiktu á pöntunarkerfinu.",
    headingAccent: "Tilbúið á 5 mínútum.",
    sub: "14 dagar ókeypis, ekkert kort. Hættu hvenær sem er. Vertu með 500+ veitingastöðum sem stýra pöntunum sínum í gegnum IQ Rest.",
  },
  scan: {
    heading: "Frá pappírsmatseðli í pöntunarkerfi",
    headingAccent: "á 60 sekúndum",
    sub: "Hladdu upp mynd af matseðlinum — AI dregur út flokka, rétti og verð beint í ritilinn. Síðan karfa og QR — með einum smelli.",
    cta: "Skanna matseðilinn →",
  },
  footer: {
    featureLinks: [
      { href: "/is/ai-translation", label: "AI þýðing" },
      { href: "/is/reservations", label: "Bókanir" },
      { href: "/is/mobile-management", label: "Stjórn úr síma" },
      { href: "/is/easy-menu", label: "Matseðilritstjóri" },
      { href: "/is/custom-design", label: "Mynd- og myndbandsbakgrunnar" },
      { href: "/is/color-scheme", label: "Vörumerkjalitir" },
      { href: "/is/multilingual", label: "Fjöltyngdur matseðill" },
      { href: "/is/ai-images", label: "AI myndbestun" },
      { href: "/is/analytics", label: "Tölfræði" },
      { href: "/is/instant-setup", label: "Stundaruppsetning" },
      { href: "/is/personal-support", label: "Persónuleg aðstoð" },
    ],
    navLinks: [
      { href: "#pricing", label: "Verð" },
      { href: "#faq", label: "Spurningar" },
      { href: "/is/changelog", label: "Fréttir" },
      { href: "/is/languages", label: "Skipta um tungumál" },
    ],
    copyrightTemplate: "© {year} IQ Rest. Allur réttur áskilinn.",
  },
};
