import { Check } from "lucide-react";
import { Section } from "@/app/_landing/components/section";

const BENEFITS = ["QR na svakom stolu, skeniraj-i-naruči, bez aplikacije", "Porudžbine u realnom vremenu na tabletu kuhinje ili menadžera", "Ili na WhatsAppu restorana — vi birate", "Modifikatori, varijante i alergeni idu na račun", "Slobodan komentar gosta na svakoj porudžbini", "Dnevno numerisanje za kuhinju", "Višejezični checkout na 35 jezika, prema gostovom telefonu", "Nula provizije po porudžbini — fiksna mesečna pretplata"];
const HOW_STEPS = [
  { title: "Uključi porudžbine za restoran", desc: "Otvori podešavanja restorana, aktiviraj prekidač Porudžbine i izaberi koja polja gosta (ime, telefon, adresu) prikupljati." },
  { title: "Izaberi kanal isporuke", desc: "Interni režim šalje nove porudžbine u karticu Kuhinja. WhatsApp režim formatira porudžbinu kao poruku na WhatsAppu restorana. Ili oba paralelno." },
  { title: "Odštampaj i zalepi QR", desc: "Preuzmi QR (jedan po stolu ili jedan po restoranu) u PDF ili PNG i zalepi na stolove. Gosti skeniraju sopstvenom kamerom — bez App Storea, bez trenja." },
  { title: "Odradi smenu", desc: "Porudžbine se pojavljuju u kartici Kuhinja sa brojem stola, jelima, varijantama, alergenima, komentarom i dnevnim brojem. Prelaz nova → u toku → gotova. Pretraživač gosta osvežava se u realnom vremenu." },
];
const COMPARISON_ROWS = [["Provizija po porudžbini","20–30%","0%","0% (€6,90/mes fiksno)"],["Gde porudžbina ide","Aplikacija agregatora","Vaša kasa","Vaš kuhinjski tablet ili WhatsApp"],["Broj stola na računu","Nema","Ručno","Da, automatski"],["Modifikatori / varijante","Ograničeno","Da","Da, sa alergenima"],["Višejezični checkout","Jezik njihove aplikacije","Nema","35 jezika, automatski"],["Potreban hardver","Tablet agregatora","POS terminal","Bilo koji tablet sa pretraživačem"],["Vreme podešavanja","Onboarding poziv","Dani-nedelje","5 minuta"]];

export function SeoContent() {
  return (<>
    <Section noContainer dataSection="seo-intro"><div className="w-full"><p className="text-xs font-medium uppercase tracking-widest text-primary mb-3 text-start">Detaljno</p><h2 className="text-3xl sm:text-4xl lg:text-5xl font-medium tracking-tight mb-3 text-start">Šta je online sistem porudžbina za restoran <span className="text-muted-foreground">stvarno</span></h2><p className="text-base sm:text-lg text-muted-foreground mb-10 text-start">Nije marketplace. Nije agregator dostave. Direktna linija od telefona gosta za vašim stolom do kuhinjskog tableta — ili WhatsAppa.</p><div className="space-y-4 text-base sm:text-lg text-foreground/90 leading-relaxed"><p><strong>Online sistem porudžbina za restoran</strong> u smislu IQ Resta je softver koji omogućava gostu za vašim stolom da otvori meni u telefonu, sastavi korpu i pošalje porudžbinu u kuhinju — bez Wolta, Glova, Bolt Fooda ili bilo kog drugog marketplacea. Gost nikada ne napušta vaš QR meni, vi ne plaćate proviziju po porudžbini, i račun stiže sa pravim brojem stola.</p><p>IQ Rest je izgrađen oko dva kanala. Po podrazumevanim podešavanjima je <em>interni režim</em>: svaka nova porudžbina stiže u karticu Kuhinja u panelu na tabletu, telefonu ili laptopu uz pas — sa brojem stola, jelima sa varijantama i alergenima, slobodnim komentarom gosta i dnevnim brojem porudžbine. Alternativa je <em>WhatsApp režim</em>: ista porudžbina formatira se kao poruka na WhatsAppu restorana. Korisno za male timove, uglavnom preuzimanje ili kada je menadžer van sale. Oba režima mogu raditi istovremeno.</p></div></div></Section>
    <Section noContainer dataSection="seo-benefits"><div className="w-full"><h3 className="text-2xl sm:text-3xl font-medium tracking-tight mb-6 text-start">Šta zaista dobijate</h3><div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-3 sm:gap-4">{BENEFITS.map((b) => (<div key={b} className="bg-muted/20 border border-border rounded-2xl p-4 sm:p-5 flex flex-row items-center gap-3"><div className="h-8 w-8 rounded-lg bg-primary/10 text-primary flex items-center justify-center shrink-0"><Check className="h-4 w-4" strokeWidth={2.5} /></div><p className="text-sm sm:text-base text-foreground/90 leading-snug">{b}</p></div>))}</div></div></Section>
    <Section noContainer dataSection="seo-how"><div className="w-full"><h3 className="text-2xl sm:text-3xl font-medium tracking-tight mb-6 text-start">Kako radi tok porudžbina IQ Resta</h3><p className="text-base sm:text-lg text-foreground/90 leading-relaxed mb-6 text-start">Četiri prekidača u panelu — i u eteru ste. Bez instalatera, bez POS hardvera, bez integracijskog projekta.</p><div className="grid grid-cols-1 sm:grid-cols-2 gap-3 sm:gap-4">{HOW_STEPS.map((s, i) => (<div key={s.title} className="bg-muted/20 border border-border rounded-2xl p-5 flex flex-row items-start gap-4"><div className="h-10 w-10 rounded-lg bg-primary text-primary-foreground flex items-center justify-center shrink-0 font-semibold text-base">{i + 1}</div><div className="flex-1 min-w-0"><div className="text-base sm:text-lg font-semibold tracking-tight mb-1">{s.title}</div><p className="text-sm text-muted-foreground leading-relaxed">{s.desc}</p></div></div>))}</div></div></Section>
    <Section noContainer dataSection="seo-table"><div className="w-full"><h3 className="text-2xl sm:text-3xl font-medium tracking-tight mb-6 text-start">Agregator, klasični POS ili sistem porudžbina</h3><div className="bg-muted/20 border border-border rounded-2xl p-4 sm:p-6 overflow-x-auto"><table className="w-full text-sm sm:text-base border-collapse"><thead><tr className="border-b border-border"><th className="text-left font-semibold py-3 pr-3 text-foreground">Karakteristika</th><th className="text-left font-semibold py-3 pr-3 text-muted-foreground">Agregator dostave</th><th className="text-left font-semibold py-3 pr-3 text-muted-foreground">Klasični POS</th><th className="text-left font-semibold py-3 text-primary">Porudžbine IQ Rest</th></tr></thead><tbody className="text-foreground/90">{COMPARISON_ROWS.map((row, i) => (<tr key={row[0]} className={i < COMPARISON_ROWS.length - 1 ? "border-b border-border/50" : ""}><td className="py-3 pr-3 font-medium">{row[0]}</td><td className="py-3 pr-3 text-muted-foreground">{row[1]}</td><td className="py-3 pr-3 text-muted-foreground">{row[2]}</td><td className="py-3 text-foreground">{row[3]}</td></tr>))}</tbody></table></div><p className="text-sm text-muted-foreground leading-relaxed mt-6 text-start">Online sistem porudžbina koji restoran poseduje sam isplati se već prvog vikenda — svaki dinar koji gost potroši u vašoj sali ostaje u vašoj sali, a račun uz pas uvek je sa pravim brojem stola.</p></div></Section>
  </>);
}
