import { QrCode, MessageCircle, ChefHat, Settings2, Languages, BarChart3 } from "lucide-react";
import type { LandingTexts } from "@/app/_landing/types";

export const TEXTS: LandingTexts = {
  htmlLang: "sr",
  htmlDir: "ltr",
  meta: {
    title: "Online sistem porudžbina za restoran — QR i WhatsApp | IQ Rest",
    description: "Online sistem porudžbina za restoran: gost skenira QR za stolom, sastavi porudžbinu i ona stiže direktno na kuhinjski tablet ili WhatsApp. Nula provizije, sa brojem stola. 14 dana besplatno.",
    canonical: "https://iq-rest.com/sr/online-sistem-porudzbina-restoran",
    ogLocale: "sr_RS",
    ogTitle: "Online sistem porudžbina za restoran — Direktno u kuhinju",
    ogDescription: "Gost skenira QR za stolom, sastavi porudžbinu i ona stiže na tablet ili WhatsApp — bez posrednika, bez provizije, sa brojem stola na svakom računu.",
  },
  ctaText: "Uključi porudžbine",
  demoText: "Demo uživo",
  microcopy: "Od €6,90/mes · 14 dana besplatno · Otkaži kad god želiš",
  header: { navFeatures: "Funkcije", navHow: "Kako radi", navPricing: "Cene", navFaq: "FAQ", signIn: "Prijava", cta: "Probaj" },
  hero: {
    verticals: ["Restorani", "Kafići", "Bistroi", "Picerije", "Barovi", "Pivnice"],
    headline: "Online sistem porudžbina za restoran.",
    sub: "Gost skenira QR svog stola, sastavi porudžbinu u telefonu — i račun stiže direktno na vaš kuhinjski tablet ili WhatsApp restorana. Bez posrednika, bez provizije, sa brojem stola na svakom računu.",
    dynamicHeadlines: ["Porudžbina za stolom.", "Direktno na kuhinjski tablet.", "Ili direktno na WhatsApp.", "Nula provizije.", "Sa brojem stola."],
    painBullets: [
      "Online sistem porudžbina koji restoran poseduje sam — bez posrednika, bez provizije.",
      "Porudžbine stižu na tablet kuhinje ili menadžera sa brojem stola, modifikatorima, alergenima i napomenama.",
      "Ili se šalju direktno na WhatsApp restorana — idealno za preuzimanje i male timove.",
      "QR za svaki sto (ili jedan za celu salu) generiše se automatski.",
    ],
    rating: "500+ restorana u 30+ zemalja",
  },
  features: {
    heading: "Sistem porudžbina,",
    headingAccent: "napravljen za sto.",
    sub: "Stvarna funkcionalnost — nije klon agregatora za dostavu.",
    items: [
      { Icon: QrCode, title: "QR meni sa korpom za svaki sto", desc: "Gost skenira QR, pregleda meni na svom jeziku, dodaje jela sa modifikatorima, ostavlja napomenu za kuhinju i šalje. Bez aplikacije.", tag: "QR porudžbine" },
      { Icon: ChefHat, title: "Porudžbine na kuhinjskom tabletu", desc: "Svaka nova porudžbina pojavljuje se u kartici Kuhinja — na tabletu uz pas — sa brojem stola, jelima, varijantama, alergenima i komentarom. Jednim dodirom od „u toku“ do „gotovo“.", tag: "Pogled kuhinje" },
      { Icon: MessageCircle, title: "Ili na WhatsApp", desc: "Stavi restoran u WhatsApp režim (ili oba istovremeno) — svaka porudžbina stiže na WhatsApp kao formatirana poruka. Idealno za preuzimanje ili male timove.", tag: "WhatsApp režim" },
      { Icon: Settings2, title: "Modifikatori, varijante i alergeni", desc: "Svako jelo ima grupe varijanti (veličina, prženje, dodaci) sa razlikom u ceni, oznake alergena i slobodan opis. Korpa sve obračunava — račun na tabletu bez nejasnoća.", tag: "Prava korpa" },
      { Icon: Languages, title: "Višejezični checkout", desc: "Ceo tok porudžbine — korpa, modifikatori, komentar, potvrda — preveden je na 35 jezika i automatski se prilagođava jeziku gostovog telefona.", tag: "35 jezika" },
      { Icon: BarChart3, title: "Dnevno numerisanje i dnevnik", desc: "Svaka porudžbina dobija dnevni broj za kuhinju, ide u dnevnik sa iznosima i vremenskim oznakama, hrani analitiku. Otkazi su soft-delete, izveštaji ostaju čisti.", tag: "Dnevnik porudžbina" },
    ],
  },
  founder: {
    eyebrow: "Napravio vlasnik kafića, ne dostavni startup",
    quoteStart: "Žena i ja smo otvorili kafić i nedeljama tražili način da primamo porudžbine za stolom koji ne bi davao 30% agregatoru i ne bi tražio kasu od 1500 €. Sve što smo isprobali bilo je nezgrapno, skupo ili bez osnovnih stvari —",
    quoteAccent: "pa smo izgradili sistem porudžbina koji smo sami želeli da imamo.",
    sign: "Bogdan Sokolov · osnivač, bivši vlasnik kafića",
    photoAlt: "Bogdan, osnivač IQ Rest",
  },
  how: {
    heading: "Uključi sistem porudžbina",
    headingAccent: "u 4 koraka",
    sub: "Bez instalacije, bez integratora, bez poziva IT-u. Samo telefon i 5 minuta.",
    steps: [
      { n: "1", t: "Napravi restoran", d: "Registracija emailom ili Google — 30 sekundi." },
      { n: "2", t: "Dodaj meni", d: "Drag-and-drop ili AI skeniranje papirnog menija." },
      { n: "3", t: "Izaberi kanal", d: "Kuhinjski tablet, WhatsApp ili oba." },
      { n: "4", t: "Odštampaj QR", d: "Jedan QR po stolu — gosti naručuju odmah." },
    ],
  },
  pricing: {
    badge: "Neograničene porudžbine · Nula provizije",
    heading: "Jedan plan.",
    headingAccent: "Bez naknade po porudžbini.",
    sub: "Online porudžbine, QR meni, WhatsApp režim, višejezični checkout i analitika — sve u jednoj pretplati. Bez procenta od transakcije.",
    monthlyLabel: "Mesečno",
    yearlyLabel: "Godišnje",
    saveBadge: "Ušteda 25%",
    perMonth: "mesečno",
    billedAnnually: "Naplata jednom godišnje {total}",
    youSave: "Štediš {amount}",
    trust: { secure: "Pretplata preko Stripe", noCommitment: "Bez obaveze", quick: "Aktivno za minute", restaurants: "+500 restorana" },
  },
  faq: {
    eyebrow: "Sistem porudžbina — često postavljana pitanja",
    heading: "O sistemu",
    headingAccent: "porudžbina.",
    sub: "Šta vlasnici restorana pitaju pre uključivanja online porudžbina u IQ Restu. Ne vidiš svoje pitanje? Piši na WhatsApp — odgovaraju pravi ljudi.",
    whatsappCta: "Pitaj na WhatsApp",
    whatsappPrefill: "Zdravo, imam pitanje o porudžbinama IQ Rest",
    items: [
      { q: "Da li je ovo dostavna platforma kao Wolt ili Glovo?", a: "Ne, baš u tome je poenta. IQ Rest je sopstveni kanal porudžbina restorana: gost naručuje sa tvog QR-a, porudžbina stiže na tvoj tablet ili WhatsApp, ti služiš. Bez marketplacea, bez kataloga agregatora — i nikada ne uzimamo deo računa." },
      { q: "Gde se tačno pojavljuju porudžbine?", a: "U kartici Kuhinja panela IQ Rest na bilo kom tabletu ili telefonu uz pas ili šank. Svaka porudžbina prikazuje broj stola, jela sa varijantama i alergenima, komentar gosta i dnevni broj. Prelaz „nova → u toku → gotova“ jednim dodirom." },
      { q: "Mogu li porudžbine da dolaze na WhatsApp umesto toga?", a: "Da. Svaki restoran ima tri režima: interni (samo kuhinjski tablet), WhatsApp (porudžbina dolazi kao poruka na WhatsApp restorana) ili oba istovremeno. Režim je jedan prekidač u panelu, menja se kad god želiš." },
      { q: "Šta sadrži porudžbina?", a: "Jela sa varijantama i dodacima (sa razlikom u ceni), alergeni, broj stola, slobodan komentar gosta i — ako uključiš polja — ime, telefon i adresu. Dovoljno za slanje kurira ili pozivanje stola nazad zbog alergena." },
      { q: "Mogu li gosti da plate online u meniju?", a: "Po podrazumevanim podešavanjima — ne. IQ Rest je podešen za plaćanje za stolom: gost naručuje, ti donosiš račun, plaća se kao i obično. Ako trebaš online plaćanje karticom (tipično za preuzimanje), Stripe Connect integracija je moguća na zahtev — piši na WhatsApp." },
      { q: "Treba li mi poseban tablet, štampač ili POS hardver?", a: "Ne. Bilo koji tablet, laptop ili telefon sa pretraživačem — otvori panel, prijavi se, ostavi karticu Kuhinja otvorenu. Ako već imaš POS — IQ Rest radi pored njega, ne zamenjuje kasu." },
      { q: "Šta se dešava posle 14 besplatnih dana?", a: "Bez načina plaćanja nalog se pauzira — nikad ne naplaćujemo automatski. Meni, porudžbine i podešavanja se čuvaju; dodaj karticu kad god želiš za reaktivaciju. Otkaz jednim klikom, bez obaveze." },
    ],
  },
  finalCta: {
    heading: "Uključi sistem porudžbina.",
    headingAccent: "Spremno za 5 minuta.",
    sub: "14 dana besplatno, bez kartice. Otkaži kad god želiš. Pridruži se 500+ restorana koji upravljaju svojim porudžbinama preko IQ Resta.",
  },
  scan: {
    heading: "Od papirnog menija do sistema porudžbina",
    headingAccent: "za 60 sekundi",
    sub: "Otpremi fotografiju menija — AI izvlači kategorije, jela i cene direktno u urednik. Zatim korpa i QR — jednim klikom.",
    cta: "Skeniraj meni →",
  },
  footer: {
    featureLinks: [
      { href: "/sr/ai-translation", label: "AI prevod" },
      { href: "/sr/reservations", label: "Rezervacije" },
      { href: "/sr/mobile-management", label: "Mobilno upravljanje" },
      { href: "/sr/easy-menu", label: "Editor menija" },
      { href: "/sr/custom-design", label: "Video i foto pozadine" },
      { href: "/sr/color-scheme", label: "Boje brenda" },
      { href: "/sr/multilingual", label: "Višejezični meni" },
      { href: "/sr/ai-images", label: "AI optimizacija slika" },
      { href: "/sr/analytics", label: "Analitika" },
      { href: "/sr/instant-setup", label: "Trenutna postavka" },
      { href: "/sr/personal-support", label: "Lična podrška" },
    ],
    navLinks: [
      { href: "#pricing", label: "Cene" },
      { href: "#faq", label: "Pitanja" },
      { href: "/sr/changelog", label: "Novosti" },
      { href: "/sr/languages", label: "Promeni jezik" },
    ],
    copyrightTemplate: "© {year} IQ Rest. Sva prava zadržana.",
  },
};
