import { QrCode, MessageCircle, ChefHat, Settings2, Languages, BarChart3 } from "lucide-react";
import type { LandingTexts } from "@/app/_landing/types";

export const TEXTS: LandingTexts = {
  htmlLang: "zh",
  htmlDir: "ltr",
  meta: {
    title: "餐厅在线点餐系统 — 二维码与 WhatsApp | IQ Rest",
    description: "餐厅在线点餐系统：客人扫描桌面二维码下单，订单直接发送到您的厨房平板或 WhatsApp。零佣金、含桌号。14 天免费试用。",
    canonical: "https://iq-rest.com/zh/qr-ordering-system-restaurant",
    ogLocale: "zh_CN",
    ogTitle: "餐厅在线点餐系统 — 直达厨房",
    ogDescription: "客人扫码下单，订单直达您的平板或 WhatsApp — 无聚合平台、无佣金、每张单据含桌号。",
  },
  ctaText: "启用我的点餐",
  demoText: "查看在线演示",
  microcopy: "每月仅 €6.90 起 · 14 天免费 · 随时取消",
  header: { navFeatures: "功能", navHow: "如何运作", navPricing: "价格", navFaq: "常见问题", signIn: "登录", cta: "免费试用" },
  hero: {
    verticals: ["餐厅", "咖啡馆", "小酒馆", "披萨店", "酒吧", "酿酒坊"],
    headline: "餐厅在线点餐系统",
    sub: "客人扫描桌面二维码，在手机上组建订单，订单直接发送到您的厨房平板或餐厅 WhatsApp。无聚合平台、无佣金、每张单据都带真实桌号。",
    dynamicHeadlines: ["桌上点餐", "直达厨房平板", "或直达 WhatsApp", "零佣金", "含桌号"],
    painBullets: [
      "真正归餐厅所有的在线点餐系统 — 无中间商、无佣金。",
      "订单送达厨房或经理平板，含桌号、修饰符、过敏原和备注。",
      "或直接发送到餐厅 WhatsApp — 非常适合外带和小团队。",
      "每桌一个二维码（或全店共用一个），自动生成。",
    ],
    rating: "30 多个国家 500+ 家餐厅",
  },
  features: {
    heading: "为餐桌打造的",
    headingAccent: "点餐系统",
    sub: "真实功能 — 不是配送聚合平台的克隆。",
    items: [
      { Icon: QrCode, title: "每桌带购物车的二维码菜单", desc: "客人扫描桌面二维码，使用自己的语言浏览菜单，添加菜品和修饰符，给厨房留言，然后发送。无需安装应用。", tag: "二维码点餐" },
      { Icon: ChefHat, title: "厨房平板查看订单", desc: "每个新订单在管理面板的「厨房」标签出现 — 显示桌号、菜品、变体、过敏原和客人备注。一键从「进行中」改为「完成」。", tag: "厨房视图" },
      { Icon: MessageCircle, title: "或发送到 WhatsApp", desc: "将餐厅切换到 WhatsApp 模式（或同时使用两种模式），每个订单都会作为格式化消息发送到餐厅 WhatsApp — 适合外带或小团队。", tag: "WhatsApp 模式" },
      { Icon: Settings2, title: "修饰符、变体和过敏原", desc: "每道菜都有变体组（尺寸、熟度、配料）、价差、过敏原标签和自由描述。购物车尊重所有设置 — 平板上的单据毫不含糊。", tag: "真正的购物车" },
      { Icon: Languages, title: "多语言结账", desc: "整个下单流程 — 购物车、修饰符、备注、确认 — 已翻译成 35 种语言，自动适配客人手机语言。", tag: "35 种语言" },
      { Icon: BarChart3, title: "每日编号和订单日志", desc: "每个订单获得厨房用的日编号，进入含总额和时间戳的日志，喂入分析。取消采用软删除 — 报告保持干净。", tag: "订单日志" },
    ],
  },
  founder: {
    eyebrow: "由咖啡馆老板而非外卖创业公司打造",
    quoteStart: "我和妻子开了一家咖啡馆，花了数周寻找能在桌上接单的方法，既不想给聚合平台 30%，也不想要 €1500 的 POS。试过的都太重、太贵或缺少基础功能 —",
    quoteAccent: "于是我们打造了自己想要的点餐系统。",
    sign: "Bogdan Sokolov · 创始人，前咖啡馆老板",
    photoAlt: "Bogdan，IQ Rest 创始人",
  },
  how: {
    heading: "启用您的点餐系统",
    headingAccent: "仅需 4 步",
    sub: "无需安装、无需集成商、无需电话技术支持。只需手机和 5 分钟。",
    steps: [
      { n: "1", t: "创建餐厅", d: "邮箱或 Google 注册 — 30 秒。" },
      { n: "2", t: "添加菜单", d: "拖放或 AI 扫描纸质菜单。" },
      { n: "3", t: "选择渠道", d: "厨房平板、WhatsApp 或两者。" },
      { n: "4", t: "打印二维码", d: "每桌一个 — 客人立即开始下单。" },
    ],
  },
  pricing: {
    badge: "无限订单 · 零佣金",
    heading: "一个计划。",
    headingAccent: "无每单费用。",
    sub: "在线点餐、二维码菜单、WhatsApp 模式、多语言结账和分析 — 全部包含在一个订阅中。无交易百分比。",
    monthlyLabel: "月付",
    yearlyLabel: "年付",
    saveBadge: "省 25%",
    perMonth: "每月",
    billedAnnually: "按年结算 {total}",
    youSave: "节省 {amount}",
    trust: { secure: "通过 Stripe 订阅", noCommitment: "无承诺", quick: "几分钟启动", restaurants: "500+ 餐厅" },
  },
  faq: {
    eyebrow: "点餐系统 — 常见问题",
    heading: "关于",
    headingAccent: "点餐系统",
    sub: "餐厅老板在用 IQ Rest 启用在线点餐前的问题。没看到您的问题？在 WhatsApp 上联系我们 — 真人回复。",
    whatsappCta: "在 WhatsApp 提问",
    whatsappPrefill: "您好，我对 IQ Rest 点餐有疑问",
    items: [
      { q: "这是像 Uber Eats 或美团那样的外卖平台吗？", a: "不是，这正是要点。IQ Rest 是餐厅自己的点餐渠道 — 客人从您的二维码下单，订单进入您的平板或 WhatsApp，您来出餐。无市场、无聚合目录 — 我们从不抽走账单的任何部分。" },
      { q: "订单具体出现在哪里？", a: "在 IQ Rest 仪表板的「厨房」标签 — 在您放在备餐台或吧台的任何平板或手机上。每个订单显示桌号、含变体和过敏原的菜品、客人备注和每日订单号。一键切换：新 → 进行中 → 完成。" },
      { q: "我可以改在 WhatsApp 接单吗？", a: "可以。每个餐厅有三种模式：内部（仅厨房平板）、WhatsApp（订单作为格式化消息发送到餐厅 WhatsApp）或同时启用两者。模式是仪表板的一个开关 — 随时切换。" },
      { q: "订单包含什么？", a: "菜品及其变体和加料（含价差）、过敏原、桌号、客人自由备注，以及 — 启用相关字段后 — 客人姓名、电话和地址。足以派送外带或就过敏原回拨客人。" },
      { q: "客人可以从菜单在线支付吗？", a: "默认不可以。IQ Rest 围绕桌边支付设计 — 客人下单，您送账单，照常付款。如需在线刷卡（典型外带场景），可按需通过 Stripe Connect 集成 — 请在 WhatsApp 联系。" },
      { q: "需要特殊的平板、打印机或 POS 硬件吗？", a: "不需要。任何带浏览器的平板、笔记本或手机均可 — 打开仪表板、登录、保持「厨房」标签打开。如已有 POS，IQ Rest 共存 — 不替换收银机。" },
      { q: "14 天免费后会怎样？", a: "如果未添加支付方式，账户暂停 — 我们从不自动扣款。菜单、订单和设置均保留；想重新激活时添加银行卡。一键取消，无承诺。" },
    ],
  },
  finalCta: {
    heading: "启用您的点餐系统",
    headingAccent: "5 分钟上线",
    sub: "14 天免费、无需银行卡、随时取消。加入用 IQ Rest 运营自己在线点餐的 500+ 餐厅。",
  },
  scan: {
    heading: "纸质菜单到点餐系统",
    headingAccent: "60 秒",
    sub: "上传菜单照片 — AI 把分类、菜品和价格直接提取到编辑器。从那开始，购物车和二维码只在一键之外。",
    cta: "扫描我的菜单 →",
  },
  footer: {
    featureLinks: [
      { href: "/zh/ai-translation", label: "AI 翻译" },
      { href: "/zh/reservations", label: "预订" },
      { href: "/zh/mobile-management", label: "移动管理" },
      { href: "/zh/easy-menu", label: "菜单编辑器" },
      { href: "/zh/custom-design", label: "视频和图片背景" },
      { href: "/zh/color-scheme", label: "品牌颜色" },
      { href: "/zh/multilingual", label: "多语言菜单" },
      { href: "/zh/ai-images", label: "AI 图片优化" },
      { href: "/zh/analytics", label: "分析" },
      { href: "/zh/instant-setup", label: "即时设置" },
      { href: "/zh/personal-support", label: "个人支持" },
    ],
    navLinks: [
      { href: "#pricing", label: "价格" },
      { href: "#faq", label: "问题" },
      { href: "/zh/changelog", label: "更新日志" },
      { href: "/zh/languages", label: "切换语言" },
    ],
    copyrightTemplate: "© {year} IQ Rest. 版权所有。",
  },
};
